iTwin/itwinjs-core

common/changes/@bentley/imodeljs-common/fix-key-color-equals_2020-10-29-15-24.json, core/common/src/Gradient.ts
Equality function for two KeyColor objects needs to use && instead of ||.
=> Fix KeyColor equality function

common/changes/@bentley/ui-components/updateEditorContainerTests_2020-10-29-18-57.json, ui/components/src/test/editors/EditorContainer.test.tsx
rush cover would randomly failure on EditorContainer test.  Cleaned up to explicitly unmount test components and wait for change before testing expected result.
=> Update EditorContainer tests to avoid sporadic test failures.

.github/CODEOWNERS, .github/workflows/sanity.yaml
Due to a few of the current users in the CODEOWNERS file not having write access yet, removing them temporarily from the file.
Also, added a GitHub Workflow that helps validate changes to the CODEOWNERS file to avoid syntax errors in the future.
=> Cleanup the codeowners file

common/api/imodeljs-backend.api.md, common/api/summary/imodeljs-backend.exports.csv, common/changes/@bentley/imodel-bridge/master_2020-10-29-23-53.json, common/changes/@bentley/imodeljs-backend/master_2020-10-29-23-53.json, common/changes/@bentley/imodeljs-frontend/master_2020-10-29-23-53.json, core/backend/src/IModelDb.ts, core/backend/src/IModelHost.ts, core/frontend/src/IModelApp.ts, core/imodel-bridge/src/BridgeRunner.ts
Disable Bentley usage tracking for iModelBank cases
Avoid waiting on usage tracking to succeed/fail in backend and bridge
=> Disable Bentley usage tracking when using iModelBank

README.md, common/config/azure-pipelines/ci.yaml, common/config/azure-pipelines/jobs/regression-testing.yaml
The current build status link goes to the incorrect build.  Update it and fix the trigger for that build to run nightly on the correct release branches.
Also update the trigger for the regression testing.
=> Update build status in README. Add triggers to regression testing build

test-apps/display-performance-test-app/src/backend/CsvWriter.ts, test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts
Add capability to modify hilite and emphasis settings changes in display-performance-test-app so that they can be tested on a regular basis with the image compare tests.
If the settings are not the default settings then filenames for output images have a +hXXXXXXXXX and/or +eXXXXXXXXX added to them to indicate the changes made to the hilite and/or emphasis settings (where XXXXXXXXX is a base36 number representing the changes).
A new column is added to the CVS output for "Other Props" (only if at leastr one test exists which modified the default hilite or emphasis settings) which will contain an entry if the hilite or emphasis settings were modified from the defaults with entries like those added to the output file names of images.
=> Hilite emphasis in dpta

common/api/geometry-core.api.md, common/changes/@bentley/geometry-core/EDLCurveCollectionClosestPoint_2020-11-02-16-01.json, core/geometry/src/curve/CurveCollection.ts, core/geometry/src/curve/CurveLocationDetail.ts, core/geometry/src/test/curve/CurveCollection.test.ts
New method to search a curve collection and return the curvePrimitive, fraction, and xyz of point closest to a spacePoint
```
in class CurveCollection
/** Return the closest point on the contained curves */
public closestPoint(spacePoint: Point3d): CurveLocationDetail | undefined ...
```
=> Add closestPoint method to CurveCollection (peer of maxGap, sumLengths)

common/config/azure-pipelines/jobs/version-bump.yaml
Converted the current Designer Version of the Version bump job to a yaml-based one and made a few enhancements along the way.
The main changes I made were to convert (almost) everything to bash and simplify the conditions on all of the jobs. Previously we had a matrix of variables needed in order to queue each bump but now it's distilled down to 4 options.
I'll need to cherry-pick this change back to the `release/2.8.0` branch in order to make the patch release today.
I've tested each of the four options in a fork and I'll link to the results of each of them for review;
- `nightly`
- Run on [master](https://github.com/calebmshafer/imodeljs/commit/a480cf2c8f5ab8102de8cc7bc19782eb5af6a71f)
- Run on [release branch](https://github.com/calebmshafer/imodeljs/commit/1506836452fcf64ab990d29821ab8 …
=> Add version bump yaml

common/config/azure-pipelines/templates/core-build.yaml
ADOps Pipelines handled the `System.PullRequest.TargetBranch` variable differently between GitHub and ADOps repos.  In the latter, the resulting string would always include `refs/heads` whereas the former it includes only the branch name after the `refs/heads`. 
Updated the script to correctly check for the release branch and in addition append `origin/` to avoid ambiguity between a branch and git tag.
=> Fix rush change for release branches

common/config/azure-pipelines/ci.yaml, common/config/azure-pipelines/integration-pr-validation.yaml, common/config/azure-pipelines/jobs/fast-ci.yaml, common/config/azure-pipelines/jobs/regression-testing.yaml, common/config/azure-pipelines/jobs/version-bump.yaml
Clean up various build triggers and schedules.
- Switch from `0 0 * * *` to `0 5 * * *` for cron jobs to run them at midnight Eastern instead of 7pm.
- Do not build draft PRs automatically
- Add explicit PR triggers. Previously were being overridden directly in the build.
=> Fix formatting of triggers. Do not build draft PRs

common/api/imodeljs-backend.api.md, common/api/summary/imodeljs-backend.exports.csv, common/changes/@bentley/imodeljs-backend/check-entity-class_2020-11-03-20-56.json, core/backend/src/Entity.ts, core/backend/src/IModelDb.ts, core/backend/src/test/standalone/IModel.test.ts
getElement, getModel, and getSubModel can now optionally validate the expected entity class.
=> Check entity class

common/config/rush/common-versions.json, package.json
The root package.json shouldn't have any packages defined in it.  Moving the flat buffer requirement to the common-versions to always force that version.
@EarlinLutz the `@types/flatbuffers` package is currently the latest version so there isn't anything to update there.
=> Move flatbuffers from the root package.json to common-versions

clients/imodelhub/src/imodelhub/Briefcases.ts, common/changes/@bentley/imodelhub-client-tests/briefcase-delete-fix_2020-11-03-16-06.json, common/changes/@bentley/imodelhub-client/briefcase-delete-fix_2020-11-03-16-06.json, full-stack-tests/imodelhub-client/src/imodelhub/Briefcases.test.ts
- Added a check before abandoning briefcase if it owns any locks. This prevents users without appropriate permissions from attempting to release briefcase locks.
- Added tests to ensure correct behavior
=> Briefcase abandon fix

common/changes/@bentley/imodeljs-backend/fix-project-extents-test_2020-11-05-13-52.json, core/backend/src/test/standalone/IModel.test.ts
Simply switch the "seed" element to one in a regular model.
=> computeProjectExtents test was mistakenly inserting into a template model

common/config/azure-pipelines/ci.yaml
This fixes the issue we're running into in #186. The PR triggers are preventing the pipeline from being triggered by a comment.  According to this [GitHub issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/4206), when the PR triggers do not match the PR you're trying to trigger it on the comment triggers won't work correctly.
I still need to write-up the steps for reviewing fork-based PRs, I'll do that shortly, but did add some comments to the ci.yaml itself about when it's used and why.
=> Remove the file requirement for the slow ci pr triggers

common/changes/@bentley/imodeljs-backend/vc-top-parents_2020-11-09-18-37.json, common/changes/@bentley/imodeljs-common/vc-top-parents_2020-11-09-18-37.json, core/backend/src/test/integration/ChangedElements.test.ts, core/common/src/ChangedElements.ts
Handle the new data coming from the addon processing that includes top parent data for the changed elements. Updated test.
=> feat: #472753: top parents adjustment

common/api/imodeljs-backend.api.md, common/changes/@bentley/imodeljs-backend/IModelImporter-computeProjectExtents_2020-11-06-21-50.json, core/backend/src/IModelImporter.ts, core/backend/src/IModelTransformer.ts
- Compute the projectExtents at the end rather than checking during import of each element
- Add option for *outliers* to be excluded from the projectExtents computation
- Log warnings if certain projectExtents issues are detected
=> Improve IModelTransformer's projectExtents handling

common/api/presentation-backend.api.md, common/changes/@bentley/presentation-backend/presentation-separate-asset-path-overrides-for-common-and-backend_2020-11-12-09-23.json, common/config/rush/browser-approved-packages.json, presentation/backend/package.json, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/index.test.ts
Allow overriding asset path directories for 'presentation-backend' and 'presentation-common' separately for cases when consumers want to use non-default paths, but don't want to merge assets into a single directory
=> Presentation: Allow specifying asset path overrides separately for 'common' and 'backend'

ui/scripts/setup-tests.js
We used Windows-like file path separator for setting up snapshot location which didn't work on Unix systems. This resulted to snapshots being located in output rather than source directory on Unix. Which resulted in none of the snapshots being compared.
Now we're using file-system specific path separator.
=> UI: Fix snapshot tests on unix file systems

common/changes/@bentley/ui-ninezone/ui-cancel-raf_2020-11-13-16-05.json, ui/ninezone/src/test/Utils.ts, ui/ninezone/src/ui-ninezone/widget-panels/Panel.tsx
Fix issue in Panel component where requested animation frame is not canceled, causing RAF callback (with setState) to execute after the component is unmounted.
Related warning in test environment: 
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
=> Cancel requested animation frame in Panel component

.github/CODEOWNERS
Moved the imodeljs/display team under the imodeljs/core team to remove the additional notifications.
Added a few people that have just been added to the Org.
=> Update CODEOWNERS to reflect changes in GitHub Teams

common/changes/@bentley/ui-components/fixDatePickerForDaylightSavings_2020-11-17-19-08.json, ui/components/src/ui-components/datepicker/DatePicker.tsx
Fix calendar logic to avoid duplicate day numbers when day light saving ends, producing a 25hr day.
=> Fix bug in date picker seen when daylight savings ends

full-stack-tests/core/src/frontend/hub/PlanProjection.test.ts, full-stack-tests/core/src/frontend/standalone/BackgroundMap.test.ts
Specifically, tests that want to test the color of a single (CSS) pixel will fail when run in contexts when 1 CSS pixel != 1 device pixel.
=> Ignore device pixel ratio in tests

common/api/imodeljs-common.api.md, core/common/src/tile/IModelTileIO.ts
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/127669).
=> Tile format version 18.0

common/changes/@bentley/ui-components/fixEnumEditorInGridLayout_2020-11-18-01-45.json, common/changes/@bentley/ui-framework/fixEnumEditorInGridLayout_2020-11-18-01-45.json, ui/components/src/ui-components/editors/EnumEditor.scss, ui/framework/src/ui-framework/uiprovider/DefaultDialogGridContainer.scss
* Revert change to EnumEditor style and fix a more specific way for horizontal tool settings.
=> Backport: Fix enum editor in grid layout - DR issue. (#252)

common/changes/@bentley/ui-components/fixDatePickerForDaylightSavings_2020-11-17-19-08.json, ui/components/src/ui-components/datepicker/DatePicker.tsx
* Fix calender logic to avoid duplicate day numbers when day light saving ends, producing a 25hr day.
* fix lint issue
* rush change
=> Backport: Fix bug in date picker seen when daylight savings ends (#248)

full-stack-tests/presentation/package.json, full-stack-tests/presentation/src/frontend/FavoriteProperties.test.ts
We use specific namespace+settingId for storing favorites in user settings service. Problem is that there was a race condition when multiple presentation-full-stack-tests were run in parallel - one test could overwrite settings that were set up by another. This PR stops us from using the settings service completely.
=> Presentation: Stop using settings service in full stack tests

common/api/presentation-backend.api.md, common/changes/@bentley/presentation-backend/presentation-fix-test-failing-on-unix_2020-11-23-09-10.json, full-stack-tests/presentation/package.json, full-stack-tests/presentation/src/IntegrationTests.ts, full-stack-tests/presentation/src/frontend/Content.test.ts, presentation/backend/src/presentation-backend/BackendLoggerCategory.ts
We use active locale as 'en-PSEUDO' and the directory containing pseudo-localized strings is 'en-pseudo'. That's not an issue on Windows and Mac, but on Linux we need casing to match exactly for paths. The addon now tries ['en-pseudo', 'en-PSEUDO', 'EN-pseudo', 'EN-PSEUDO'].
=> Presentation: Unskip a test that was failing due to localization files not being found (fixed in addon)

common/changes/@bentley/ui-components/ui-fix-test-failure_2020-11-11-17-52.json, common/changes/@bentley/ui-core/ui-fix-test-failure_2020-11-11-17-52.json, ui/components/src/test/editors/EditorContainer.test.tsx, ui/core/src/ui-core/focustrap/FocusTrap.tsx
* Use sinon assertions for better failure logging.
* Clear FocusTrap timeout.
* Rush change.
Co-authored-by: Caleb Shafer <31107829+calebmshafer@users.noreply.github.com>
Co-authored-by: bsteinbk <65047615+bsteinbk@users.noreply.github.com>
=> Cherry pick: Fix random ui-components test failure (#216)

common/changes/@bentley/imodeljs-frontend/fix-blanking-regions-for-non-logarithmic-depth_2020-11-24-13-39.json, core/frontend/src/render/webgl/Mesh.ts
Second attempt as [original PR](https://github.com/imodeljs/imodeljs/pull/302) appears to be hosed; cannot get it to recognize new build attempts after flaky integration test failure.
=> Fix text z-fighting with background when log Z is disabled

common/api/presentation-common.api.md, common/changes/@bentley/presentation-common/presentation-include-actual-primary-class-ids-for-nested-content-fields_2020-12-02-11-49.json, full-stack-tests/presentation/src/frontend/Content.test.ts, presentation/backend/src/test/PresentationManager.test.snap, presentation/common/src/presentation-common/PresentationRpcInterface.ts, presentation/common/src/presentation-common/content/Fields.ts, presentation/common/src/test/_helpers/random/Content.ts, presentation/common/src/test/content/Descriptor.test.snap, presentation/common/src/test/content/Fields.test.snap
The descriptor now tells what actual source classes the related content fields are related to. This allows requesting descriptor for a base class and then determine properties for any of its base classes without having to request another descriptor.
In the future we might want to provide some utilities similar to what's in the added test.
Addon PR: 130264
=> Presentation: Include actual primary class ids for related content fields

common/config/azure-pipelines/jobs/ci-core.yaml, common/config/azure-pipelines/templates/publish.yaml
The conditional insertion is not working as intended so switching it to use a different set of conditions.  Introduced the regression in #251 that has lead to nightly releases to not be correctly published...
=> Fix package publishing trigger

common/api/ui-ninezone.api.md, common/changes/@bentley/ui-ninezone/ui-footer-popup-props_2020-12-09-11-00.json, ui/ninezone/src/ui-ninezone/footer/Popup.tsx
This PR exposes all `Popup` props in a `FooterPopup` component allowing advanced `FooterPopup` configuration.
Related to #199
=> Allow all PopupProps to be passed in to FooterPopup

core/frontend/src/QuantityFormatter.ts, core/frontend/src/test/QuantityFormatter.test.ts
Keep a member variable for the different promises when loading FormatterSpec or ParserSpec. This will prevent subsequent calls to "load" to issue more than one promise.
=> Return the same promise for subsequent loads.

common/changes/@bentley/frontend-devtools/inspect-element-copy-to-clipboard_2020-12-10-19-17.json, core/frontend-devtools/src/tools/InspectElementTool.ts
We already had a "copy" argument but we never hooked it up. Very annoying when output is verbose and you want to copy-paste it elsewhere.
=> InspectElementTool optionally copies to clipboard.

common/changes/@bentley/imodeljs-frontend/fix-polyline-hilite_2020-12-10-22-06.json, core/frontend/src/render/webgl/glsl/FeatureSymbology.ts, core/frontend/src/render/webgl/glsl/Polyline.ts
It would always draw the silhouette using the element's weight even when the symbology overrides specified a different weight.
Shader was checking the wrong flags.
=> Fix hilite silhouette ignoring line weight override

full-stack-tests/core/src/frontend/hub/HyperModeling.test.ts, full-stack-tests/core/src/frontend/hub/IModelConnection.test.ts, full-stack-tests/core/src/frontend/hub/InteractiveEditingSession.test.ts
This does the minimum to get these tests passing again so we can avoid further regressions by enabling them again in the iModel.js Integration CI job.
- Skip failing usage logging test.
- Disable interactive editing tests in browser - interactive editing is currently unsupported using the Web RPC protocol.
- In electron, skip a test that requires the hypermodeling package's keyins to be parsed from JSON - for whatever reason, the test framework fails to find them (only in electron). Real electron apps have no such problem.
=> Get core-full-stack-tests (#integration) passing

full-stack-tests/core/src/frontend/standalone/ExtensionAdmin.test.ts, full-stack-tests/core/webpack.config.js
The tests were originally turned off due to the memory issues we were having on master.  We later figured out that they were due to the coverage reporting when webpack-ing.  That issue has been "fixed" by just disabling the instrumented bundle for the test suites, having nothing to do with this test.
=> re-enable the ExtensionAdmin tests

common/changes/@bentley/imodeljs-frontend/exaggerated-view-decorations_2020-12-15-16-13.json, core/frontend/src/AccuDraw.ts, core/frontend/src/Viewport.ts, core/frontend/src/tools/ViewTool.ts
Surface normal decoration from locate HitDetail, view tool depth point indicator, and AccuDraw compass now check for an exaggerated view.
=> Account for aspect ratio skew in core decorations.

common/api/imodeljs-common.api.md, common/changes/@bentley/imodeljs-common/fix-planar-uv-params_2020-12-16-15-09.json, core/common/src/tile/IModelTileIO.ts
Just a tile format version bump.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/133452).
=> Fix planar uv params

full-stack-tests/core/src/frontend/standalone/tile/TileIO.test.ts
Appears to crash between the first and second TileAdmin test, in Linux Electron tests.
Have not reproduced locally. Skipping while I investigate so as not to impact PRs.
=> Temporarily skip sporadically failing test.

common/api/geometry-core.api.md, common/changes/@bentley/geometry-core/EDLLineStringDrapeContext_2020-12-09-15-19.json, core/geometry/src/polyface/IndexedPolyfaceVisitor.ts, core/geometry/src/polyface/PolyfaceQuery.ts, core/geometry/src/polyface/multiclip/SweepLineStringToFacetContext.ts, core/geometry/src/test/polyface/DrapeLinestring.test.ts
New static method
```
PolyfaceQuery.asyncSweepLinestringToFacetsXYReturnChains(
linestringPoints: GrowableXYZArray, polyface: Polyface): Promise<LineString3d[]>
```
to drape a linestring to a mesh, operating as an async.
=> New method: async version of sweeping a linestring to a mesh. (bp #388)

common/config/azure-pipelines/templates/core-build.yaml
While looking at trying to speed up our builds overall I noticed I accidentally merged this last week.  I'm going to override @wgoehrig and @ColinKerr review once this is approved and builds.
=> Fix accidentally committed --to flag in build

common/api/presentation-common.api.md, common/api/summary/presentation-common.exports.csv, common/api/ui-abstract.api.md, common/api/ui-components.api.md, common/changes/@bentley/presentation-common/presentation-navigation-instancekey_2020-12-22-08-51.json, common/changes/@bentley/presentation-components/presentation-navigation-instancekey_2020-12-22-08-51.json, common/changes/@bentley/ui-abstract/presentation-navigation-instancekey_2020-12-22-08-51.json, common/changes/@bentley/ui-components/presentation-navigation-instancekey_2020-12-22-08-51.json, full-stack-tests/presentation/src/frontend/providers/PropertyPaneDataProvider.test.snap, full-stack-tests/presentation/src/frontend/providers/TableDataProvider.test.snap, presentation/common/src/presentation-common/RulesetsFactory.ts, presentation/common/src/test/RulesetsFactory.test.ts, presentation/components/src/presentation-components/DataProvidersFactory.ts, ui/abstract/src/ui-abstract/properties/PrimitiveTypes.ts, ui/components/src/test/TestUtils.ts, ui/components/src/test/converters/NavigationPropertyTypeConverter.test.ts, ui/components/src/test/properties/renderers/value/NavigationPropertyValueRenderer.test.tsx, ui/components/src/ui-components/converters/NavigationPropertyTypeConverter.ts
In addition to instance id, navigation properties now also have information of related instance's class id. This greatly increases navigation property value usefulness as it can now be treated as an instance key.
This is a **breaking change**, however only uncommon Presentation use cases are affected.
=> Presentation: Make navigation property values be instance keys

common/api/imodeljs-common.api.md, common/changes/@bentley/imodeljs-common/allow-part-linestyles_2020-12-31-20-46.json, common/changes/@bentley/imodeljs-frontend/allow-part-linestyles_2020-12-31-20-46.json, common/changes/@bentley/ui-framework/allow-part-linestyles_2020-12-31-20-46.json, core/common/src/tile/IModelTileIO.ts
This PR simply bumps the tile format major version to match native.
[Corresponding native PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/135196).
=> Allow stroked line styles in geometry parts

common/changes/@bentley/imodeljs-frontend/geo-wmtscapabilities_xmljs_2021-01-07-13-47.json, common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, core/frontend/package.json, core/frontend/src/tile/map/WmtsCapabilities.ts
* WmtsCapabilities now using 'xml-js' instead of 'fast-xml-parser'.
* Added change log.
* Removed useless optional chaining. Fixed lint error.
=> WmtsCapabilities now using 'xml-js' instead of 'fast-xml-parser'. (bp #529)

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/match-global-building-height-to-non-geodetic-terrain_2020-12-04-19-50.json, core/frontend/src/DisplayStyleState.ts, core/frontend/src/tile/RealityModelTileTree.ts
* Bias global reality models to match background map.
* extract-api and changes
* Calculate isContentUnbounded once for reality model tile trees
* Simplify createDrawArgs
* Fix private/public mismatch on _isContentUnbounded
* Fix lint errors
Co-authored-by: Ray.Bentley <rbbentley@users.noreply.github.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
=> Match global reality model height to match background map bias (bp #367)

common/api/imodeljs-frontend.api.md, common/api/ui-framework.api.md, common/changes/@bentley/imodeljs-common/fix-view-attributes-dialog_2021-01-08-15-24.json, common/changes/@bentley/imodeljs-frontend/fix-view-attributes-dialog_2021-01-08-12-55.json, common/changes/@bentley/ui-framework/fix-view-attributes-dialog_2021-01-08-15-00.json, core/common/src/SkyBox.ts, core/frontend/src/DisplayStyleState.ts, core/frontend/src/ViewState.ts, example-code/app/src/frontend/BlankConnection.ts, full-stack-tests/core/src/frontend/standalone/ViewState.test.ts, test-apps/display-test-app/src/frontend/EnvironmentEditor.ts, test-apps/display-test-app/src/frontend/ViewPicker.ts, ui/framework/src/ui-framework/timeline/SolarTimelineDataProvider.ts
EnvironmentEditor listens for changes to the display style. In its callback, it updates the values of UI components, which triggers callbacks that modify the display style, which trigger (on the next frame) the "display style changed" event in a ceaseless loop.
This only began happening after I made Viewport automatically detect changes to the display style, rather than relying on people to manually invoke `invalidateRenderPlan`.
Changed EnvironmentEditor to listen only for changes to the style's `environment` property, and to set a flag when it is modifying the environment itself so it knows to ignore the change events it produces.
Incidentally changed the type of `ViewState3d.displayStyle` to `DisplayStyle3dState` to eliminate yucky unnecessary casts.
=> Fix unresponsive UI in environment editor.

common/changes/@bentley/imodeljs-backend/docs-next-version-update_2021-01-14-13-45.json, core/backend/src/BriefcaseManager.ts, docs/changehistory/NextVersion.md
With the length of this version doc I think it makes sense to add an overview for it.  I re-ordered the items in the list as well but didn't change the content except for one case.
@kabentley I made a slight change to the actual content of the BriefcaseManager changes to highlight the removal of the `imodelclient` on `BriefcaseManager`.
@pmconne is "Visualization" and accurate header for the list of items under it? Or is there a better term to encompass those changes?
=> Update NextVersion.md to contain an Overview

common/changes/@bentley/ui-framework/ui-fix-toolbar-auto-blur_2021-01-19-15-25.json, ui/framework/src/ui-framework/toolbar/GroupButtonItem.tsx, ui/framework/src/ui-framework/toolbar/ToolbarComposer.tsx
Reported issue:
Focused input element of expandable Toolbar item panel is blurred (looses focus) when mouse is moved.
To fix reported issue this PR reduces unnecessary re-renders of 1.0 Toolbar to prevent PanelsProvider from re-appending panel to panel container.
=> Prevent unnecessary re-renders of 1.0 Toolbar in ToolbarComposer

common/changes/@bentley/imodeljs-backend/fix-guid-mismatch_2021-01-21-14-24.json, core/backend/src/CheckpointManager.ts
Two issues were found after the previous fix to set the DbGuid in the iModel (#590);
1. When calling `native.setDbGuid()`, it clears the changeset Id so resetting that value directly after setting DbGuid.
2. The ProjectGuid is not correctly set in all cases so also setting that value if there is a mis-match
I'll follow with tests later today but want to get this out in a release candidate.
=> Fix mis-matched Guids between the iModel and the iModelHub

common/changes/@bentley/electron-manager/register-electron-protocol_2021-01-21-20-11.json, core/electron-manager/src/ElectronBackend.ts
Weren't calling `registerSchemesAsPrivileged` due to a typo.
=> correctly register electron protocol.

.vscode/launch.json, common/api/presentation-common.api.md, common/api/presentation-frontend.api.md, common/api/summary/presentation-frontend.exports.csv, common/changes/@bentley/presentation-backend/presentation-associate_updates_with_imodel_2021-01-21-14-30.json, common/changes/@bentley/presentation-common/presentation-associate_updates_with_imodel_2021-01-21-14-30.json, common/changes/@bentley/presentation-components/presentation-associate_updates_with_imodel_2021-01-21-14-30.json, common/changes/@bentley/presentation-frontend/presentation-associate_updates_with_imodel_2021-01-21-14-30.json, presentation/backend/src/presentation-backend/UpdatesTracker.ts, presentation/backend/src/test/UpdatesTracker.test.ts, presentation/common/src/presentation-common/Update.ts, presentation/common/src/test/Update.test.snap, presentation/common/src/test/Update.test.ts, presentation/components/src/presentation-components/common/ContentDataProvider.ts, presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts, presentation/components/src/test/_helpers/UiComponents.ts, presentation/components/src/test/common/ContentDataProvider.test.ts, presentation/components/src/test/tree/controlled/TreeHooks.test.ts, presentation/frontend/src/presentation-frontend.ts, presentation/frontend/src/presentation-frontend/PresentationManager.ts, presentation/frontend/src/test/PresentationManager.test.ts, test-apps/presentation-test-app/package.json, test-apps/presentation-test-app/src/backend/main.ts
* Made changes to associate update records with imodel using imodel key. This enabled ui controls to ignore updates from different imodels.
* Added vs code debug configuration for presentation-test-app. This allows to debug presentation-test-app frontend and backend in vs code. With current configuration `npm run start:webserver` should be run before starting debugger.
=> Presentation: Associate updates with imodel

common/api/imodeljs-backend.api.md, common/api/imodeljs-common.api.md, common/api/imodeljs-frontend.api.md, common/api/summary/imodeljs-common.exports.csv, common/api/summary/imodeljs-frontend.exports.csv, common/changes/@bentley/imodeljs-backend/ipc-response-handler_2021-01-22-16-35.json, common/changes/@bentley/imodeljs-common/ipc-response-handler_2021-01-22-16-35.json, common/changes/@bentley/imodeljs-frontend/ipc-response-handler_2021-01-22-16-35.json, core/backend/src/NativeAppBackend.ts, core/common/src/ipc/FrontendIpc.ts, core/common/src/ipc/NativeAppIpc.ts, core/frontend/src/NativeApp.ts, core/frontend/src/Viewport.ts, core/frontend/src/oidc/MobileAuthorizationClient.ts
This is helpful to group sets of notifications sent from backend -> frontend, making them type safe.
=> add ResponseHandler to FrontendIpc

common/changes/@bentley/analytical-backend/fix-analytical-domain-test_2021-01-25-13-13.json, domains/analytical/backend/src/test/AnalyticalSchema.test.ts
Adjust analytical domain unit test for new updateElement behavior when a property is present but undefined.
=> Fix analytical domain test

common/changes/@bentley/frontend-devtools/particle-effect-locate_2021-01-25-16-48.json, common/changes/@bentley/imodeljs-frontend/particle-effect-locate_2021-01-25-16-48.json, core/frontend-devtools/src/effects/Explosion.ts, core/frontend/src/render/ParticleCollectionBuilder.ts
They behave like reality models and maps: select tool will display a tooltip, and they can provide the depth point for zoom/pan/rotate, but they are not selectable.
=> Fix particle effect locate

full-stack-tests/rpc/src/backend/http.ts, full-stack-tests/rpc/src/frontend/_Setup.test.ts
This could cause port conflicts when running multiple builds on the same machine.  Having a larger offset obviously doesn't _guarantee_ the port will be free, but fits our normal convention for avoiding conflicts.
Also, we should really log any ports we use, as it is extremely helpful when tracking down these sorts of things.
=> Fix mobile backend for RPC tests using wrong port.

common/changes/@bentley/ui-abstract/ui-fix-capitalized-syncuieventid_2021-02-01-14-46.json, ui/abstract/src/test/backstage/BackstageItemsManager.test.tsx, ui/abstract/src/test/items/ConditionalBooleanValue.test.ts, ui/abstract/src/test/items/ConditionalStringValue.test.ts, ui/abstract/src/ui-abstract/backstage/BackstageItemsManager.ts, ui/abstract/src/ui-abstract/items/ConditionalBooleanValue.ts, ui/abstract/src/ui-abstract/items/ConditionalStringValue.ts, ui/abstract/src/ui-abstract/statusbar/StatusBarItemsManager.ts, ui/abstract/src/ui-abstract/toolbars/ToolbarItemsManager.ts
This PR fixes an issue where conditional value would not update when capitalized sync event id is provided (since it is lowercased in the dispatcher).
=> Correctly handle capitalized SyncEventIds

docs/changehistory/NextVersion.md
There was a bad merge when cherry-picking the 2.11.0 changelogs that cleared the NextVersion.md.
=> Fix bad merge with NextVersion.md

common/changes/@bentley/ui-framework/presentation-update_models_tree_ruleset_2021-02-04-14-15.json, test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.ModelsTree-GroupedByClass.PresentationRuleSet.json, test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.ModelsTree-Search.PresentationRuleSet.json, test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.ModelsTree.PresentationRuleSet.json, ui/framework/src/ui-framework/imodel-components/models-tree/Hierarchy.GroupedByClass.json, ui/framework/src/ui-framework/imodel-components/models-tree/Hierarchy.json, ui/framework/src/ui-framework/imodel-components/models-tree/ModelsTreeSearch.json
Because of using 'BisCore:Element' class in some rules' instanceFilter hierarchy levels produced by those rules had dependency on 'BisCore:Element' class. This resulted in doing comparison/update for those hierarchy levels when any instance of 'BisCore:Element' subclass is changed in iModel.
=> Presentation: Update ModelsTree rulesets to better handle update

common/changes/@bentley/imodeljs-frontend/volume-classification-in-dpta_2021-02-05-15-05.json, core/frontend/src/render/webgl/SceneCompositor.ts
Fixed a problem which was hanging display-performance-test-app when a saved view was tested which had a volume classifier and one of the classifiers was selected or emphasized.
=> Volume classification in dpta

docs/learning/ui/framework/Widgets.md
=> Add missing closing paren to SampleNavigationWidget

common/api/bentleyjs-core.api.md, common/changes/@bentley/bentleyjs-core/move-property_2021-02-09-11-48.json, core/bentley/src/BentleyError.ts, docs/changehistory/NextVersion.md
ECDb is getting some updates for which we disabled schema changeset reverse/reinstate.
Raman asked me to update NextVersion and update the error message in imodeljs accordingly.
This goes after pull request https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/120522 in imodel02 which by the time of reading is probably merged already.
Please have a look at the change in BentleyError.ts! This is basically a breaking change, but a very obvious one... is this okay, or should I keep the old identifier instead to not break anybody?
=> Adjustments to latest ECDb changes for moving properties

common/changes/@bentley/ui-framework/ui-models-tree-fix-getting-elements-display-status_2021-02-10-10-14.json, test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.ModelsTree-GroupedByClass.PresentationRuleSet.json, test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.ModelsTree.PresentationRuleSet.json, ui/framework/src/ui-framework/imodel-components/models-tree/Hierarchy.GroupedByClass.json, ui/framework/src/ui-framework/imodel-components/models-tree/Hierarchy.json
Need to additionally include "SelectedNodeInstances" spec when requesting assembly elements ids, otherwise the element itself is not included.
=> UI/ModelsTree: Fix getting elements' display status

common/changes/@bentley/imodeljs-frontend/fix-request-redraw_2021-02-15-22-15.json, core/frontend/src/Viewport.ts
It needs to request the next animation frame. Showed up in [screen-space effect sample](https://github.com/imodeljs/frontend-sample-showcase/pull/148#discussion_r576258383) where adjusting the effect parameters did not immediately update the screen.
=> Fix Viewport.requestRedraw

.github/CODEOWNERS
Changes to /common/ are indirect changes caused by changes to files in imodeljs-frontend, where ownership is split between imodeljs/admins and imodeljs/display. Don't require admins to review display-related changes just because they happened to produce API changes or changelogs.
=> Add @imodeljs/display as code owners for /common/**/imodeljs-frontend.

common/changes/@bentley/presentation-frontend/presentation-hilite-rules-for-GroupInformationElement_2021-02-19-09-19.json, docs/changehistory/NextVersion.md, presentation/frontend/src/presentation-frontend/selection/HiliteRules.json
- Change deprecated rules to newer replacements.
- Highlight members of `BisCore.GroupInformationElement`
=> Presentation: Highlight GroupInformationElement members

common/api/presentation-common.api.md, common/api/presentation-frontend.api.md, common/api/summary/presentation-common.exports.csv, common/changes/@bentley/presentation-backend/presentation-persisted_ruleset_variables_2021-02-19-09-51.json, common/changes/@bentley/presentation-common/presentation-persisted_ruleset_variables_2021-02-19-09-51.json, common/changes/@bentley/presentation-frontend/presentation-persisted_ruleset_variables_2021-02-19-09-51.json, presentation/backend/src/presentation-backend/PresentationIpcHandler.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/test/PresentationIpcHandler.test.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/common/src/presentation-common.ts, presentation/common/src/presentation-common/PresentationIpcInterface.ts, presentation/common/src/presentation-common/RulesetVariables.ts, presentation/frontend/src/presentation-frontend/IpcRequestsHandler.ts, presentation/frontend/src/presentation-frontend/PresentationManager.ts, presentation/frontend/src/presentation-frontend/RulesetVariablesManager.ts, presentation/frontend/src/test/IpcRequestsHandler.test.ts, presentation/frontend/src/test/PresentationManager.test.ts, presentation/frontend/src/test/RulesetVariablesManager.test.ts, test-apps/presentation-test-app/package.json, test-apps/presentation-test-app/src/frontend/index.tsx
Added PresentationIpc to allow storing ruleset variables in IpcApp. All variables in IpcApp now are stored in backend. This allows them to be used during hierarchy updates after iModel data changes.
Native PR: 145204
=> Presentation: Store ruleset variables on backend to use them during hierarchy updates

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/dpta-await-secondary-tiles_2021-02-22-14-03.json, core/frontend/src/DrawingViewState.ts, core/frontend/src/SheetViewState.ts, core/frontend/src/ViewState.ts, test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts
display-performance-test-app waits for all tiles required by its viewport to be loaded before it saves the image and begins recording performance metrics. However, view attachments on sheets (and 3d section drawing attachments) use secondary offscreen viewports to select their tiles, which may still have outstanding tile requests while the onscreen viewport reports its own tiles have finished loading.
- Add `@internal` `ViewState.secondaryViewports` to iterate offscreen viewports used to construct the view's scene.
- `waitForTilesToLoad` checks outstanding requests for secondary viewports.
- When dpta logs the Ids of selected tiles, it includes those selected by secondary viewports.
=> Fix inconsistent image tests for view attachments

common/api/ui-components.api.md, common/changes/@bentley/ui-components/ui-components-tree-setnumchildren_2021-02-23-10-00.json, ui/components/src/test/tree/controlled/TreeModel.test.ts, ui/components/src/ui-components/tree/controlled/TreeModel.ts
This change introduces some way to erase the amount of child nodes a parent is expected to contain.
=> UI: Allow setting child node count to undefined in TreeModel

common/api/ui-components.api.md, common/changes/@bentley/ui-components/ui-components-tree-changenodeid_2021-02-24-09-24.json, ui/components/src/test/tree/controlled/TreeModel.test.ts, ui/components/src/test/tree/controlled/internal/SparseTree.test.ts, ui/components/src/ui-components/tree/controlled/TreeModel.ts, ui/components/src/ui-components/tree/controlled/internal/SparseTree.ts
When node id is changed (by modifying presentation rulesets or other ways), it is cheaper just to update the node id instead of rebuilding part of `TreeModel` hierarchy.
=> UI: Add ability to modify tree node ids

common/changes/@bentley/imodeljs-backend/fix-markup-test_2021-02-24-21-19.json, common/changes/@bentley/imodeljs-markup/fix-markup-test_2021-02-24-21-18.json, core/backend/src/IModelHost.ts, core/markup/src/test/Markup.test.ts
comparing XML generated from svg is not stable across platforms/version. Everything about what that returns is tested elsewhere, so that part of the test was unnecessary anyway.
=> Fix unstable markup test

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/handle-context-loss_2021-02-24-22-03.json, core/frontend/src/public/locales/en/iModelJs.json, core/frontend/src/render/RenderSystem.ts, core/frontend/src/render/webgl/FeatureOverrides.ts, core/frontend/src/render/webgl/System.ts, core/frontend/src/test/render/webgl/System.test.ts
Add `RenderSystem.contextLossHandler`. By default it behaves the same as previously: produces an "Oops" dialog with an explanation of what occurred and a link to the WebGL compatibility checker.
Tweaked error message to mention GPU memory.
Fix an exception that could occur after context loss but before context loss is reported, causing an ugly "Oops" dialog to appear before the context loss dialog.
=> Allow applications to react to WebGL context loss.

common/changes/@bentley/imodeljs-frontend/workaround-null-tile-tree-range_2021-02-26-10-49.json, core/frontend/src/tile/IModelTileTree.ts
For an empty model the addon produces TileTreeProps with the components of location.origin set to `Number.MAX_VALUE`. This produces a [bug](https://dev.azure.com/bentleycs/iModelTechnologies/_workitems/edit/554800) affecting SYNCHRO Modeler.
This is a workaround for 2.12 - the version on which SYNCHRO intends to release soon. The proper fix will be applied in the addon in 2.14.
=> Workaround for null tile tree range

.vscode/launch.json, common/api/presentation-backend.api.md, common/api/presentation-common.api.md, common/api/presentation-frontend.api.md, common/api/summary/presentation-common.exports.csv, common/api/summary/presentation-frontend.exports.csv, common/changes/@bentley/presentation-backend/presentation-expanded_nodes_tracking_2021-02-25-13-33.json, common/changes/@bentley/presentation-common/presentation-expanded_nodes_tracking_2021-02-25-13-33.json, common/changes/@bentley/presentation-components/presentation-expanded_nodes_tracking_2021-02-25-13-33.json, common/changes/@bentley/presentation-frontend/presentation-expanded_nodes_tracking_2021-02-25-13-33.json, presentation/backend/src/presentation-backend/BackendLoggerCategory.ts, presentation/backend/src/presentation-backend/NativePlatform.ts, presentation/backend/src/presentation-backend/PresentationIpcHandler.ts, presentation/backend/src/test/NativePlatform.test.ts, presentation/backend/src/test/PresentationIpcHandler.test.ts, presentation/common/src/presentation-common/PresentationIpcInterface.ts, presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts, presentation/components/src/presentation-components/tree/controlled/UseExpandedNodesTracking.ts, presentation/components/src/test/tree/controlled/TreeHooks.test.ts, presentation/components/src/test/tree/controlled/UseExpandedNodesTracking.test.ts, presentation/frontend/src/presentation-frontend.ts, presentation/frontend/src/presentation-frontend/IpcRequestsHandler.ts, presentation/frontend/src/presentation-frontend/PresentationManager.ts, presentation/frontend/src/presentation-frontend/StateTracker.ts, presentation/frontend/src/test/IpcRequestsHandler.test.ts, presentation/frontend/src/test/PresentationManager.test.ts, presentation/frontend/src/test/StateTracker.test.ts
Added ability to track expanded nodes in trees using `usePresentationTreeNodeLoader`. These nodes are stored on a backend in IpcApp cases and used during hierarchy updates after iModel data changes. Having set of expanded nodes during hierarchy updates on a backend allows to avoid updating hierarchy parts that are under collapsed nodes and not visibile in any tree component. 
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/146858)
=> Presentation: Track expanded nodes in tree and store them on the backend for faster updates

common/api/imodeljs-common.api.md, common/changes/@bentley/imodeljs-backend/query-hw-concurrency_2021-02-26-21-44.json, common/changes/@bentley/imodeljs-common/query-hw-concurrency_2021-02-26-21-44.json, core/backend/src/IpcHost.ts, core/common/src/IpcAppProps.ts
Apps that use IPC to communicate with the backend will use this to throttle calls to `IModelTileRpcInterface.requestTileContent` to match the number of tile generation workers available on backend.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/147381)
=> IPC apps can query thread pool concurrency

.github/workflows/sanity.yaml
With the new way we're handling the `common/changes` folder, the "files" check will no longer work properly all the time.  It validates that all patterns in the codeowners file actually match files, which in the case of `common/changes` is no longer true.
=> fix codeowners sanity check job

common/changes/@bentley/ui-framework/keyinPaletteHistoryFix_2021-03-02-20-52.json, ui/framework/src/test/popup/KeyinPalettePanel.test.tsx, ui/framework/src/ui-framework/popup/KeyinPalettePanel.tsx
Ensure any key-ins that are stored in history are still available before displaying in key-in palette.
=> Keyin palette history fix

common/api/presentation-common.api.md, common/api/summary/presentation-common.exports.csv, common/api/ui-components.api.md, common/changes/@bentley/presentation-backend/ui-tree-updates_2021-03-01-14-05.json, common/changes/@bentley/presentation-common/ui-tree-updates_2021-03-01-14-05.json, common/changes/@bentley/presentation-components/ui-tree-updates_2021-03-01-14-05.json, common/changes/@bentley/ui-components/ui-tree-updates_2021-03-01-14-05.json, full-stack-tests/presentation/src/frontend/Update.test.tsx, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts, presentation/common/src/presentation-common/Update.ts, presentation/common/src/presentation-common/hierarchy/Node.ts, presentation/common/src/test/Update.test.snap, presentation/common/src/test/Update.test.ts, presentation/common/src/test/hierarchy/Node.test.ts, presentation/components/src/presentation-components/common/StyleHelper.ts, presentation/components/src/presentation-components/tree/Utils.ts, presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts, presentation/components/src/test/tree/controlled/TreeHooks.test.ts, ui/components/src/ui-components/tree/controlled/TreeModelSource.ts
Until now, we used to handle partial hierarchy updates the same way as full updates: by rebuilding the existing tree model from scratch. This PR aims to support updating existing trees without loosing the UI state such as node selection or expansion.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/146794)
=> Presentation: Handle partial hierarchy updates without losing tree state.

common/api/imodeljs-frontend.api.md, common/api/summary/imodeljs-frontend.exports.csv, common/changes/@bentley/imodeljs-frontend/missing-bing-location-export_2021-03-05-22-39.json, core/frontend/src/GlobeAnimator.ts, core/frontend/src/imodeljs-frontend.ts
- Contents of BingLocation.ts were not exported from imodeljs-frontend.
- GlobeAnimator constructor and other methods were private.
=> Fixes for global display sample

common/api/ui-components.api.md, common/changes/@bentley/ui-components/ui-components-treemodel-movenode_2021-03-15-12-19.json, ui/components/src/test/tree/controlled/TreeModel.test.ts, ui/components/src/test/tree/controlled/internal/SparseTree.test.ts, ui/components/src/ui-components/tree/controlled/TreeModel.ts, ui/components/src/ui-components/tree/controlled/internal/SparseTree.ts
Adds `moveNode` method to `MutableTreeModel`.
Moving a node inside a parent that has `undefined` children count is restricted to avoid creating issues where tree node loader is involved.
=> UI: Add ability to move nodes within MutableTreeModel

common/api/imodeljs-common.api.md, common/api/summary/imodeljs-common.exports.csv, common/changes/@bentley/imodeljs-backend/parameterized-query_2021-03-15-15-56.json, common/changes/@bentley/imodeljs-common/parameterized-query_2021-03-15-15-56.json, core/backend/src/IModelDb.ts, core/backend/src/test/standalone/IModel.test.ts, core/common/src/EntityProps.ts, example-code/snippets/src/backend/ECSQL-queries.test.ts
to be used for query parameters that come from user-entered values.
=> add ability to pass parameterized values to `iModelDb.queryEntityIds`

common/changes/@bentley/presentation-frontend/presentation-fix-hilite-rules-for-functional-elements_2021-03-23-14-50.json, presentation/frontend/src/presentation-frontend/selection/HiliteRules.json
Hilite rules for `BisCore:Element` took precedence over `Functional:FunctionalElement` which broke getting hilite list for the latter.
=> Presentation: Fix hilite rules for functional elements

common/changes/@bentley/ui-components/ui-components-collect-model-changes_2021-03-24-13-34.json, common/changes/@bentley/ui-framework/ui-components-collect-model-changes_2021-03-24-13-34.json, ui/components/src/test/tree/controlled/TreeModelSource.test.ts, ui/components/src/ui-components/tree/controlled/TreeModelSource.ts, ui/framework/src/test/imodel-components/models-tree/ModelsTree.test.tsx
`immer` v8.0.2+ exposed a flaw in the way node additions/removals/modifications were detected via patches. The old implementation used to duplicate same node ids across multiple returned arrays, resulting in unnecessary React state updates.
The new approach aims to be more robust but is by no means perfect. The amount of code required to make it fully reliable would be unjustifiable as I wasn't able to come up with a test case that would break this new implementation.
Added some more tests to help catch future problems with `immer`.
=> UI: Make tree node modicifation detection more robust

clients/itwin/src/Client.ts, common/changes/@bentley/itwin-client/support-buddi-regions_2021-03-24-16-26.json, full-stack-tests/core/src/frontend/hub/MapLayerSettingsService.test.ts
With the update to use a baseUrl vs. Buddi we were missing the backwards compatibility with the `imjs_buddi_resolve_url_using_region` environment variable.  Add support for it in the case a `imjs_url_prefix` is not defined.
There is an issue with the MayLayers usage of product settings service that needs to be investigated. Disabling for now until it can be resolved.
=> Support the existing environment variable. Disable failing test

common/changes/@bentley/imodeljs-backend/fix-checkpoint-dbguid_2021-03-24-20-51.json, core/backend/src/CheckpointManager.ts
The requirement to call saveChanges was missed when we needed to update the DbGuid. This caused a regression in 2.14.x that was caught during testing.
Writing tests now but I'll open separate PR tomorrow as it will take a bit of time to finish them up and I'd like to continue testing 2.14 without the blocker.
=> Add saveChanges to ensure the updated DbGuid is persisted

common/api/imodeljs-common.api.md, common/changes/@bentley/imodeljs-backend/rename-standalone_2021-03-26-14-58.json, common/changes/@bentley/imodeljs-common/rename-standalone_2021-03-26-14-58.json, core/backend/src/BriefcaseManager.ts, core/backend/src/CheckpointManager.ts, core/backend/src/IModelDb.ts, core/backend/src/perftest/ElementCRUD.test.ts, core/backend/src/perftest/MixinImpact.test.ts, core/backend/src/perftest/PerfTestUtils.ts, core/backend/src/perftest/PolymorphicQuery.test.ts, core/backend/src/perftest/PropertiesImpact.test.ts, core/backend/src/perftest/RelationshipImpact.test.ts, core/backend/src/test/integration/BriefcaseManager.test.ts, core/backend/src/test/integration/HubUtility.ts, core/backend/src/test/standalone/ElementRoundTrip.test.ts, core/backend/src/test/standalone/IModel.test.ts, core/common/src/BriefcaseTypes.ts, test-apps/display-test-app/src/backend/SetToStandalone.ts
the term "Standalone" has been used to define a type of iModel use case (not connected to iModelHub) and as the value (0) for BriefcaseId, causing confusion. 
The `Unassigned` briefcaseId is used for several purposes:
- **Snapshots**. Snapshot files are immutable copies of an iModel for archival or data exchange purposes. They can neither generate nor accept new changesets.
- **Checkpoints**. Checkpoints are Snapshots that represent a specific version on an iModel's timeline.
- **PullOnly**. A local briefcase file that may be used to "slide" along a timeline by applying incoming changesets.
They are always opened readonly except to apply changesets.
- **Standalone**. Standalone iModels are local files that are not connected to iModelHub, and therefore cannot accept or create changesets.
=> Rename/deprecate `BriefcaseIdValue.Standalone` to `BriefcaseIdVaue.Unassigned`

common/changes/@bentley/electron-manager/cherrypick-logout_2021-03-30-17-00.json, common/changes/@bentley/imodeljs-backend/cherrypick-logout_2021-03-30-20-53.json, core/backend/src/NativeHost.ts, core/electron-manager/src/backend/ElectronAuthorizationBackend.ts
Cherry-pick 
- DesktopAuthorization must call onuserStateChanged when
token is set (signIn/refreshed), unset (signOut).
From master
=> Cherry-pick d5eb453

common/changes/@bentley/imodeljs-backend/disable-txnmanager-tests_2021-03-31-13-03.json, core/backend/src/test/standalone/TxnManager.test.ts
until we can figure out why they fail randomly on CI jobs
=> Temporarily disable TxnManager tests

common/api/imodeljs-backend.api.md, common/api/imodeljs-common.api.md, common/api/imodeljs-frontend.api.md, common/api/summary/imodeljs-backend.exports.csv, common/api/summary/imodeljs-common.exports.csv, common/api/summary/imodeljs-frontend.exports.csv, common/changes/@bentley/imodeljs-backend/dynamic-graphics_2021-03-31-16-42.json, common/changes/@bentley/imodeljs-common/dynamic-graphics_2021-03-31-16-42.json, common/changes/@bentley/imodeljs-frontend/dynamic-graphics_2021-03-31-16-42.json, core/backend/src/ElementGraphics.ts, core/backend/src/IModelDb.ts, core/backend/src/imodeljs-backend.ts, core/backend/src/rpc-impl/IModelTileRpcImpl.ts, core/backend/src/test/standalone/ElementGraphics.test.ts, core/common/src/imodeljs-common.ts, core/common/src/rpc/IModelTileRpcInterface.ts, core/common/src/tile/ElementGraphics.ts, core/common/src/tile/TileMetadata.ts, core/frontend/src/tile/ImdlReader.ts, core/frontend/src/tile/TileAdmin.ts
`IModelTileRpcInterface.requestElementGraphics()` and `IModelDb.generateElementGraphics()` can now accept a non-persistent geometry stream from which to generate graphics, instead of a persistent element Id.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/154670)
=> Dynamic graphics

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/do-not-precompile-shaders-by-default_2021-04-01-16-32.json, core/frontend/src/ViewManager.ts, core/frontend/src/render/RenderSystem.ts, docs/changehistory/NextVersion.md
Revert the change which defaulted shader precompiling on. It resulted in noticeable UI sluggishness before any viewports were added, while shaders precompiled.
=> Do not precompile shaders by default

common/changes/@bentley/imodeljs-frontend/fix-view-attachment-delay_2021-04-02-16-36.json, core/frontend/src/SheetViewState.ts
As described in [this bug](https://dev.azure.com/bentleycs/iModelTechnologies/_workitems/edit/588816), when the graphics for a 3d view attachment with camera enabled become ready, they are not displayed on the sheet until the sheet viewport's scene is invalidated, e.g. by zooming or panning.
Add them to the sheet viewport's scene as soon as they are ready.
=> Output graphics for raster attachment as soon as they are ready.

common/changes/@bentley/imodeljs-frontend/fix-webgl1-silhouettes_2021-04-02-16-54.json, core/frontend/src/render/webgl/glsl/Edge.ts, core/frontend/src/render/webgl/glsl/RealityMesh.ts, core/frontend/src/render/webgl/glsl/Surface.ts, core/frontend/src/render/webgl/glsl/Vertex.ts
This fixes silhouettes (and also lighting) for instanced geometry when displayed using WebGL1.  When instancing is used, the matrix for transforming normals to view space is now just extracted from the modelView matrix like it used to be.  For models which use a scaled ModelDisplayTransformProvider there was no problem since instancing is turned off in that case.
=> #588248 - fixed silhouettes for WebGL1 instancing

common/changes/@bentley/imodeljs-frontend/fix-ios-edge-shader-bugs_2021-04-08-17-44.json, core/frontend/src/render/webgl/glsl/Viewport.ts
The shader function modelToWindowCoordinates() needs to initialize its output parameters for all code paths.
Not doing so caused the iOS shader compiler to trip up and take very long to compile certain shaders.  Lines could also drop out in certain situations.
This PR fixes this bug item: https://dev.azure.com/bentleycs/iModelTechnologies/_workitems/edit/589235
=> Fix ios edge shader bugs

.github/CODEOWNERS, common/changes/@bentley/imodeljs-frontend/fix-webgl1-clipping_2021-04-14-19-55.json, core/frontend/src/render/webgl/glsl/Clipping.ts, core/frontend/src/test/render/webgl/Technique.test.ts
`Loop index cannot be initialized with non-constant expression`.
Make all shader compilation tests execute using both WebGL 1 and (if available) WebGL 2 such that they would have caught this.
=> Fix clipping shaders for WebGL 1

full-stack-tests/presentation/src/frontend/Content.test.ts, full-stack-tests/presentation/src/frontend/Hierarchies.test.snap, full-stack-tests/presentation/src/frontend/providers/LabelsProvider.test.snap, full-stack-tests/presentation/src/frontend/providers/LabelsProvider.test.ts
Update presentation full stack tests to account for recent Model label rule changes.
There seems to be a problem with label for RepositoryModel. Started an email thread with BIS working group to come up with a proper solution, but for now just adjusted the tests to not fail.
=> Presentation: Adjust tests for RepositoryModel label

common/changes/@bentley/imodeljs-frontend/fallback-on-bad-view_2021-04-20-17-00.json, core/frontend/src/IModelConnection.ts, test-apps/display-test-app/src/frontend/ViewPicker.ts
If `ViewState.load` throws, it's probably because of nonexistent display style or model/category selector. In this case, just display a generated spatial view instead of terminating.
=> Handle bad views in display-test-app.

test-apps/display-test-app/src/backend/SetToStandalone.ts
I have an enormous collection of iModels. Most are already standalone, but have a non-null ProjectGuid. I get really annoyed by the recently-introduced error produced when opening them in display-test-app so I changed SetToStandalone.ts to accept a directory. It will convert any iModels in that directory and subdirectories thereof.
@kabentley:
Some also have pending txns. IModelJsNative.DgnDb.deleteAllTxns() does not appear to work properly in this context.
Previously, we didn't saveChanges after deleteAllTxns and the app would simply crash. Adding a call to saveChanges after deleteAllTxns prevents the crash for undetermined reasons, but I am still informed "Cannot reset BriefcaseId with pending Txns. Create a changeset".
TxnManager claims we still have pending txns after deleting them …
=> Tweak setToStandalone

full-stack-tests/core/src/frontend/hub/ExternalTextures.test.ts
was disabled because throwing native exceptions was broken.
=> re-enable external texture test

common/changes/@bentley/presentation-backend/presentation-generalize-related-properties-rules-for-type-definitions_2021-04-27-07-36.json, presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json, presentation/backend/assets/supplemental-presentation-rules/Functional.PresentationRuleSet.json
We were only loading related `TypeDefinition` properties for `PhysicalElement` and `SpatialLocationElement` instances. Now we're loading them for all core types that have a related type definition: `GeometricElement3d`, `GeometricElement2d` and `FunctionalElement`.
Note: `AnalyticalElement` is covered by the rule for `GeometricElement3d`.
=> Presentation: Add missing related properties specifications for core element types

common/changes/@bentley/presentation-backend/presentation-external-sources_2021-04-27-14-23.json, full-stack-tests/presentation/src/frontend/Content.test.ts, full-stack-tests/presentation/src/frontend/FavoriteProperties.test.ts, full-stack-tests/presentation/src/frontend/providers/PropertyPaneDataProvider.test.snap, presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json, presentation/common/assets/locales/en/BisCore.json
For iModels using BisCore 1.0.13 or above, loading additional related properties using the new `ExternalSource` class.
=> Presentation: External sources

test-apps/presentation-test-app/src/frontend/api/MyAppFrontend.ts, test-apps/presentation-test-app/src/frontend/components/app/App.css, test-apps/presentation-test-app/src/frontend/components/app/App.tsx, test-apps/presentation-test-app/src/frontend/components/diagnostics-selector/DiagnosticsSelector.tsx, test-apps/presentation-test-app/src/frontend/components/grid-widget/GridWidget.tsx, test-apps/presentation-test-app/src/frontend/components/imodel-selector/IModelSelector.css, test-apps/presentation-test-app/src/frontend/components/imodel-selector/IModelSelector.tsx, test-apps/presentation-test-app/src/frontend/components/properties-widget/PropertiesWidget.tsx, test-apps/presentation-test-app/src/frontend/components/ruleset-selector/RulesetSelector.css, test-apps/presentation-test-app/src/frontend/components/ruleset-selector/RulesetSelector.tsx, test-apps/presentation-test-app/src/frontend/components/tree-widget/Tree.tsx, test-apps/presentation-test-app/src/frontend/components/tree-widget/TreeWidget.tsx, test-apps/presentation-test-app/src/frontend/components/unit-system-selector/UnitSystemSelector.css, test-apps/presentation-test-app/src/frontend/components/unit-system-selector/UnitSystemSelector.tsx
- Fix the app not being able to re-open another iModel when one was already opened.
- Fix components not getting default diagnostics options until the dialog is opened and closed.
- Make app header smaller.
- Put all pickers into one line to make more space for content.
- Add ability for the app to remember imodel, ruleset and unit system.
- Change the app to use a new client ID on every page load instead of using one from local store. Allows reloading all rulesets by refreshing the page instead of requiring a backend restart.
=> Presentation: presentation-test-app enhancements

common/changes/@bentley/presentation-backend/presentation-type-definition-properties-display-modifications_2021-04-28-05-19.json, presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
Instead of blacklisting all and whitelisting only `CodeValue` and `UserLabel`, we now blacklist only specific properties: `IsPrivate` and `Recipe` (they're going to be marked hidden at ECSchema level in upcoming release). Also, until a new BisCore version is released, re-label the `PhysicalMaterial` property.
@diegoalexdiaz, can you confirm we want to see `Model` property?
=> Presentation: Modify TypeDefinitionElement properties display

clients/itwin/src/Client.ts, common/changes/@bentley/itwin-client/fix-ApimFallback_2021-04-29-18-44.json
Fixing issue found in https://github.com/imodeljs/imodeljs/pull/1073
`imjs_buddi_resolve_url_using_region` should support both `string` and `number`
itwin-viewer and many other apps uses a number for this env value
=> Fix parsing of buddi fallback for clients #1073

common/api/electron-manager.api.md, common/api/imodeljs-backend.api.md, common/api/imodeljs-common.api.md, common/api/mobile-manager.api.md, common/api/summary/imodeljs-common.exports.csv, common/changes/@bentley/electron-manager/native-auth-fixes_2021-04-28-15-40.json, common/changes/@bentley/extension-cli/native-auth-fixes_2021-04-28-15-40.json, common/changes/@bentley/imodeljs-backend/native-auth-fixes_2021-04-28-15-40.json, common/changes/@bentley/imodeljs-common/native-auth-fixes_2021-04-28-15-40.json, common/changes/@bentley/imodeljs-frontend/native-auth-fixes_2021-04-28-15-40.json, common/changes/@bentley/mobile-manager/native-auth-fixes_2021-04-28-15-40.json, core/backend/src/NativeHost.ts, core/common/src/NativeAppProps.ts, core/electron-manager/src/backend/ElectronAuthorizationBackend.ts, core/electron-manager/src/backend/ElectronHost.ts, core/electron-manager/src/backend/LoopbackWebServer.ts, core/frontend/src/NativeApp.ts, core/mobile-manager/src/backend/MobileAuthorizationBackend.ts, core/mobile-manager/src/backend/MobileHost.ts, full-stack-tests/core/src/frontend/hub/TestUtility.ts, full-stack-tests/native-app/src/frontend/hub/NativeApp.test.ts, test-apps/imodel-transformer/src/IModelHubUtils.ts, tools/extension-cli/src/helpers.ts, tools/extension-cli/src/test/basic.test.ts
Fixes to desktop/mobile authorization
* Deprecated authorization at the frontend. 
* Allowed backend startup to initialize authorization. 
* Avoided initialization of authorization client if offline (Closes #594844)
+ Added test for the same
Fixes to desktop authorization
* Successful/Error in authorization shows message in browser window. 
* Added wrapper methods around signIn() and signOut() to not just start the sign-in/sign-out process, but also to complete it.
=> Fixes to desktop/mobile authorization

common/changes/@bentley/imodeljs-backend/native-2.15.4_2021-05-04-15-40.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json
Fix extremely long shader compilation times on iOS (and possibly on M1 Mac Mini).
Fix excessive facets produced by exportGraphics for 3d line styles.
Fix bad normals for meshes originating from DWG that lack terminating zeroes in index buffers.
=> @bentley/imodeljs-native 2.15.4

common/api/ecschema-rpcinterface-common.api.md, common/changes/@bentley/ecschema-rpcinterface-common/ecschema-rpc-interface-name-fix_2021-05-04-18-28.json, core/ecschema-rpc/common/src/ECSchemaRpcInterface.ts
The interface name for ECSchemaRpcInterface must be different from SchemaRpcInterface.
=> Ecschema rpc interface name fix

common/api/imodeljs-common.api.md, common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-common/default-animation-node-appearance_2021-05-04-17-40.json, common/changes/@bentley/imodeljs-frontend/default-animation-node-appearance_2021-05-04-17-40.json, core/common/src/FeatureSymbology.ts, core/common/src/test/FeatureSymbology.test.ts, core/frontend/src/EmphasizeElements.ts, full-stack-tests/core/src/frontend/standalone/EmphasizeElements.test.ts
(cherry picked from commit d201129fb8fb68bc3b4be1cbfbe152f0a33d8535)
=> Backport override symbology of unanimated nodes (#1333)

common/changes/@bentley/presentation-backend/presentation-patch-PresentationRpc-loadHierarchy_2021-05-04-19-07.json, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts
Return Success instead of Error to avoid frontends throwing. Doesn't matter anyway, since the function is a no-op.
=> Presentation: Fix `PresentationRpcImpl.loadHierarchy` causing older frontends to throw

common/changes/@bentley/certa/fix-certa-logging_2021-05-10-15-46.json, tools/certa/src/runners/chrome/ChromeTestRunner.ts, tools/certa/src/runners/electron/initElectronTests.ts, tools/certa/src/utils/initLogging.ts, tools/certa/src/utils/initMocha.ts
Essentially just reacting to this change in mocha: https://github.com/mochajs/mocha/pull/3725
=> Fix logging in electron certa tests.

common/changes/@bentley/imodeljs-frontend/fix-animation-clips_2021-05-10-17-02.json, core/frontend/src/render/webgl/DrawCommand.ts, core/frontend/src/render/webgl/Graphic.ts, core/frontend/src/render/webgl/RenderCommands.ts
When pushing a branch we would assign directly to its `clips` property if the schedule script applied a clip volume to it.
This would leave random ClipVolumes applied to tiles' graphics.
Previously, this went unnoticed because we would `dispose` of those ClipVolumes each time we updated the target's animation branch states - we'd push an empty clip which was wasteful but had no visual effect.
In #1148 ClipVolume became no longer disposable so random bits of the models started disappearing.
`clips` is now a read-only property and the animation clips are pushed and popped using new dedicated `DrawCommand`s.
=> Fix stale animation clips being assigned to tile graphics.

common/changes/@bentley/imodeljs-backend/processAll-first-time-optimization_2021-05-11-15-48.json, core/backend/src/IModelExporter.ts, core/backend/src/IModelTransformer.ts
No need to run the "brute force" delete detection algorithms if it is the first synchronization.
=> Add "first synchronization" optimization to IModelTransformer

common/changes/@bentley/presentation-components/master_2021-05-17-11-59.json, presentation/components/package.json
`immer` is being imported by `@bentley/presentation-components` library, thus it cannot be a `devDependency`.
=> Presentation: Fix presentation-components incorectly specifying immer as a devDependency

common/api/ui-components.api.md, common/changes/@bentley/ui-components/master_2021-05-20-06-21.json, ui/components/src/test/propertygrid/component/internal/flat-items/CategorizedArrayProperty.test.ts, ui/components/src/test/propertygrid/component/internal/flat-items/CategorizedStructProperty.test.ts, ui/components/src/ui-components/propertygrid/internal/flat-items/MutableCategorizedArrayProperty.ts, ui/components/src/ui-components/propertygrid/internal/flat-items/MutableCategorizedStructProperty.ts
There's not way to expand a composite property if we're not rendering its label. So for such composite properties we have to assume content is visible even if the property is not set as expanded.
=> UI: Fix array and struct property record contents rendering

common/api/imodeljs-common.api.md, common/changes/@bentley/imodeljs-common/fix-gcrs-on-imodelprops_2021-05-20-19-06.json, core/common/src/IModel.ts
geographicCoordinateSystem property in iModelProps was incorrectly defined as GeographicCRS instead of GeographicCRSProps.
=> Fix geographicCoordinateSystem on imodelprops

common/changes/@bentley/presentation-backend/presentation-patch-PresentationRpc-loadHierarchy_2021-05-04-19-07.json, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts
Cherry pick of this pull request https://github.com/imodeljs/imodeljs/pull/1332
loadHierarchy was made a no op, but older frontends and rpc tests would receive an "error" status when calling method. Return success instead of error to avoid breaking older frontends.
=> Presentation: Fix PresentationRpcImpl.loadHierarchy causing older frontends to throw

common/changes/@bentley/ui-components/ui-virtualized-property-grid_2021-05-26-08-19.json, ui/components/src/test/propertygrid/component/VirtualizedPropertyGridWithDataProvider.test.tsx, ui/components/src/ui-components/propertygrid/component/VirtualizedPropertyGrid.scss, ui/components/src/ui-components/propertygrid/component/VirtualizedPropertyGrid.tsx
`VirtualizedPropertyGrid` is overflowing due to padding being inserted *after* container measurements are made. This is noticeable when applying `overflow: auto` style to the parent element. One common place where we would see overflow scrollbars is in ui-framework widgets.
This also removes `uicore-expandable-blocks-list` mixin because the expanding and contracting animations are not working in the virtualized list anyways.
=> UI: Remove padding around VirtualizedPropertyGrid

common/api/imodeljs-common.api.md, common/api/imodeljs-frontend.api.md, common/api/summary/imodeljs-common.exports.csv, common/changes/@bentley/imodeljs-common/external-textures-downsample_2021-06-02-20-02.json, common/changes/@bentley/imodeljs-frontend/external-textures-downsample_2021-06-02-20-02.json, core/common/src/TextureProps.ts, core/common/src/tile/IModelTileIO.ts, core/common/src/tile/TileMetadata.ts, core/frontend/src/IModelConnection.ts, core/frontend/src/render/webgl/Texture.ts, core/frontend/src/tile/TileAdmin.ts, docs/changehistory/NextVersion.md, full-stack-tests/core/src/frontend/hub/ExternalTextures.test.ts
Corresponding native addon PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/167800
The external textures feature is now enabled by default.
Previously, by default the images for textured materials would be embedded in the tile contents. This increased the size of the tile, consumed bandwidth, and imposed other penalties. The external textures feature, however, requires only the Id of the texture element to be included in the tile; the image can then be requested separately. Texture images are cached, so the image need only be requested once no matter how many tiles reference it.
Additionally, if a dimension of the external texture exceeds the client's maximum supported texture size, the image will be downsampled to adhere to that limit before being …
=> External Textures Downsampling Improvements

common/api/presentation-backend.api.md, common/api/presentation-common.api.md, common/api/presentation-components.api.md, common/api/presentation-frontend.api.md, common/api/summary/presentation-common.exports.csv, common/changes/@bentley/presentation-common/presentation-ruleset-variables-id64--_2021-06-02-14-39.json, full-stack-tests/presentation/src/frontend/RulesetVariables.test.ts, presentation/backend/src/presentation-backend/NativePlatform.ts, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/presentation-backend/RulesetVariablesManager.ts, presentation/backend/src/test/PresentationIpcHandler.test.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts, presentation/backend/src/test/RulesetVariablesManager.test.ts, presentation/common/src/presentation-common/PresentationManagerOptions.ts, presentation/common/src/presentation-common/PresentationRpcInterface.ts, presentation/common/src/presentation-common/RpcRequestsHandler.ts, presentation/common/src/presentation-common/RulesetVariables.ts, presentation/common/src/test/PresentationRpcInterface.test.ts, presentation/common/src/test/RpcRequestsHandler.test.ts, presentation/common/src/test/RulesetVariable.test.ts, presentation/components/src/presentation-components/common/ContentDataProvider.ts, presentation/components/src/presentation-components/tree/DataProvider.ts, presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts, presentation/components/src/test/tree/controlled/TreeHooks.test.ts, presentation/frontend/src/presentation-frontend/IpcRequestsHandler.ts, presentation/frontend/src/presentation-frontend/PresentationManager.ts, presentation/frontend/src/presentation-frontend/RulesetVariablesManager.ts, presentation/frontend/src/test/PresentationManager.test.ts, presentation/frontend/src/test/RulesetVariablesManager.test.ts
We may be sending a lot of these IDs to the backend, so need to make sure the payload is as little as possible. Send them as a `CompressedId64Set`.
The PR doesn't directly require addon changes, but the newly added full stack test crashes the backend without this: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/168205.
=> Presentation: Handling large number of IDs in a ruleset variable

test-apps/display-performance-test-app/src/frontend/TestRunner.ts
This PR makes display-performance-test-app wait for all external textures to finish loading before taking image captures.
=> Make display-performance-test-app wait for all external textures to load

common/api/imodeljs-backend.api.md, common/api/imodeljs-common.api.md, common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-backend/restart-undo2_2021-06-04-18-36.json, common/changes/@bentley/imodeljs-common/restart-undo2_2021-06-04-18-36.json, common/changes/@bentley/imodeljs-frontend/restart-undo2_2021-06-04-18-36.json, core/backend/src/IModelDb.ts, core/backend/src/IpcHost.ts, core/backend/src/TxnManager.ts, core/backend/src/test/standalone/TxnManager.test.ts, core/common/src/BriefcaseTypes.ts, core/common/src/IpcAppProps.ts, core/frontend/src/BriefcaseTxns.ts
Allows applications to clear undo history in case their changes should not be undoable (@bbastings will use it when setting geolocation).
**BREAKING CHANGE**: removed "allowCrossSession" optional argument to undo methods. There was no real use case for it and I'm confident no one is using it (and I don't see any way to deprecate an optional argument in TS).
relies on [this](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/168978) iModel02 PR
=> add nativeDb.restartTxnSession, take 2

common/api/ui-framework.api.md, common/changes/@bentley/ui-framework/ui-visibility-widget-improvements_2021-06-10-08-24.json, test-apps/ui-test-app/src/frontend/appui/widgets/VisibilityWidget.tsx, ui/framework/src/test/imodel-components/models-tree/ModelsTree.test.tsx, ui/framework/src/ui-framework/imodel-components/category-tree/Categories.json, ui/framework/src/ui-framework/imodel-components/models-tree/Hierarchy.GroupedByClass.json, ui/framework/src/ui-framework/imodel-components/models-tree/Hierarchy.json, ui/framework/src/ui-framework/imodel-components/models-tree/ModelsTree.tsx
Add a way to filter Models Tree by element IDs. ui-test-app demonstrates this by adding a key-in to filter the hierarchy by elements visible in the active viewport.
=> UI: Visibility widget improvements

common/changes/@bentley/build-tools/fix-dotonly-ban_2021-06-18-15-15.json, common/changes/@bentley/imodeljs-backend/fix-dotonly-ban_2021-06-18-15-58.json, core/backend/src/test/standalone/IModel.test.ts, tools/build/src/mocha-reporter/index.ts
Updating mocha to 8.3.2 (#1190) broke our mechanism for failing builds when someone pushes a commit that uses `.only` in a test.
I could probably come up with a cleaner implementation for this by moving it out of our reporter file entirely and configuring all tests to require another file, but keeping this in the reporter is awfully convenient given the multitude of test configurations we have today...
=> Fix BentleyMochaReporter to ban `.only` in PR builds again

test-apps/export-gltf/src/ExportGltf.ts, test-apps/export-gltf/src/GltfTypes.ts
* Recenter GLTF output based on project extents
* Define default scene for spec compliance (specifically for Unity glTFast)
* Don't export template elements
=> export-gltf enhancements

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-backend/animated-tile-tree-checksum_2021-06-24-18-27.json, common/changes/@bentley/imodeljs-frontend/animated-tile-tree-checksum_2021-06-24-18-27.json, core/backend/src/test/standalone/TileTree.test.ts, core/frontend/src/Tiles.ts, core/frontend/src/tile/ClassifierTileTree.ts, core/frontend/src/tile/PrimaryTileTree.ts, core/frontend/src/tile/TileAdmin.ts, core/frontend/src/tile/TileTreeSupplier.ts
The contents of animated tiles depend upon the contents of the schedule script that animates them, but that is not captured in the tiles' cache keys.
Add a hash of the schedule script contents to the tile tree's contentIdQualifier.
Provide `Tiles.updateForScheduleScript` that an app's frontend can use to update tiles after it modifies the schedule script.
I don't think it's currently worth trying to detect changes to scripts and automatically update tile trees - the app ought to know when the script changes.
[Bug](https://dev.azure.com/bentleycs/iModelTechnologies/_workitems/edit/623840).
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/173904).
=> Update tile trees when script changes.

common/api/imodeljs-common.api.md, common/changes/@bentley/imodeljs-common/synch-background-map-settings_2021-06-24-14-53.json, common/changes/@bentley/imodeljs-frontend/synch-background-map-settings_2021-06-24-14-53.json, core/common/src/BackgroundMapSettings.ts, core/common/src/MapImagerySettings.ts, core/common/src/test/BackgroundMapSettings.test.ts, core/common/src/test/DisplayStyle.test.ts, core/frontend/src/DisplayStyleState.ts, core/frontend/src/test/DisplayStyleState.test.ts
The provider settings in legacy background map settings were not being updated if the map base layer was changed.
=> Synch legacy map settings when base layer provider is changed

common/api/imodeljs-common.api.md, common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-common/section-cut-element-graphics_2021-06-25-13-56.json, common/changes/@bentley/imodeljs-frontend/section-cut-element-graphics_2021-06-25-13-56.json, core/common/src/tile/ElementGraphics.ts, core/frontend/src/tile/ClassifierTileTree.ts, core/frontend/src/tile/DynamicIModelTile.ts, core/frontend/src/tile/IModelTileTree.ts, core/frontend/src/tile/PrimaryTileTree.ts, docs/changehistory/NextVersion.md
Supply stringified ClipVector via `ElementGraphicsRequestProps.sectionCut`.
Temporary graphics generated during interactive editing automatically produce section-cut graphics based on the view's ClipStyle.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/174083).
=> requestElementGraphics can produce section-cut graphics.

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/purge-tile-trees-on-project-extents-change_2021-06-25-15-19.json, core/frontend/src/Tiles.ts, core/frontend/src/tile/ClassifierTileTree.ts, core/frontend/src/tile/PrimaryTileTree.ts, core/frontend/src/tile/TileTreeSupplier.ts
The range and transform associated with a spatial tile tree depends upon the project extents. When the extents change, purge the trees.
Native PR forthcoming.
=> Purge spatial tile trees when project extents change.

common/changes/@bentley/geometry-core/create-arc3d-fix_2021-06-28-13-37.json, core/geometry/src/curve/Arc3d.ts, core/geometry/src/test/curve/Arc3d.test.ts
Use `AxisOrder.ZXY` in `Arc3d.createCenterNormalRadius()` to correctly create an Arc.
Perpendicular vector should match provided normal, i.e.:
```
const arc = Arc3d.createCenterNormalRadius(undefined, Vector3d.unitZ(), 1);
console.log(arc.perpendicularVector); // currently outputs { x: 0, y: 0, z: -1 }, but we expect { x: 0, y: 0, z: 1 }
```
=> Fix Arc3d.createCenterNormalRadius()

common/api/imodeljs-common.api.md, common/api/summary/imodeljs-common.exports.csv, common/changes/@bentley/imodeljs-common/tile-options-from-ids_2021-06-29-13-14.json, core/common/src/test/TileMetadata.test.ts, core/common/src/tile/TileMetadata.ts
To implement [this feature](https://dev.azure.com/bentleycs/iModelTechnologies/_workitems/edit/630936) requested for tile agents.
It assumes tile format version 4 or later because that version pre-dates cloud storage tile cache.
=> Reconstruct TileOptions from tree and content Ids

common/changes/@bentley/imodeljs-common/minor-doc-fix_2021-06-29-23-21.json, core/common/src/ChangedElements.ts
Without the periods it doesn't flow correctly on the [docs site](https://www.itwinjs.org/reference/imodeljs-common/entities/changedelements/).
=> Minor API doc update to ChangedElements 

common/api/summary/ui-core.exports.csv, common/api/ui-core.api.md, common/changes/@bentley/ui-components/fixTableInWidgetResizeBug_2021-06-30-04-31.json, common/changes/@bentley/ui-core/fixTableInWidgetResizeBug_2021-06-30-04-31.json, common/changes/@bentley/ui-framework/fixTableInWidgetResizeBug_2021-06-30-04-31.json, ui/components/src/test/breadcrumb/breadcrumbdetails/BreadcrumbDetails.test.tsx, ui/components/src/test/table/component/Table.test.tsx, ui/components/src/ui-components/lineweight/WeightPickerButton.tsx, ui/components/src/ui-components/table/component/Table.tsx, ui/components/src/ui-components/timeline/SolarTimeline.tsx, ui/core/src/test/utils/hooks/useResizeObserver.test.tsx, ui/core/src/ui-core/utils/hooks/useResizeObserver.tsx, ui/framework/src/ui-framework/messages/StatusMessagesContainer.tsx
- Fixed useLayoutResizeObserver by requiring an HTMLElement and not a React reference
- Update test to set up Element.getBoundingClientRect to provide container sizes used by resize hooks.
- Update uses of ResizableContainerObserver to pass element instead of Ref.
=> Fix table column resize bug when table was created in an closed widget tab

common/api/summary/ui-core.exports.csv, common/api/ui-core.api.md, common/changes/@bentley/ui-core/updateResizableContainerObserverToAllowMonitoringParent_2021-07-01-11-38.json, ui/core/src/test/utils/hooks/useResizeObserver.test.tsx, ui/core/src/ui-core/utils/hooks/useResizeObserver.tsx
Updates to support following class-based component scenario.
```tsx
<div className="component-parent-container">
<div className="component-sibling" />
<ResizableContainerObserver onResize={this._onResize} />
</div>
```
This allows the ResizableContainerObserver to call the components _onResize method when the size of the parent div changes.
=> Update ResizableContainerObserver to allow monitoring parent resizing

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/geo-esriMinLod_2021-07-01-13-38.json, core/frontend/src/tile/RealityModelTileTree.ts, core/frontend/src/tile/RealityTileLoader.ts, core/frontend/src/tile/RealityTileTree.ts, core/frontend/src/tile/map/ImageryProviders/ArcGISMapLayerImageryProvider.ts, core/frontend/src/tile/map/ImageryTileTree.ts, core/frontend/src/tile/map/MapLayerImageryProvider.ts, core/frontend/src/tile/map/MapTileLoader.ts
Some ESRI Mapserver define a minimum LOD in its capabilities.  Any tile request made for a tile on a smaller LOD, will result in a failed tile request.  In the previous implement, this would prevent the proper display of children tiles on levels inside the lod validity range (i.e. level>=minLod && level<=maxLod).
The solution is to flag as disabled tiles on LOD outside the validity range.  Disabled tiles can have visible children per definition.
To reproduce the issue, following key-in can be used:
`fdt attach arcgis maplayer https://tiles.arcgis.com/tiles/IMCZpp2qXhYVmRXp/arcgis/rest/services/Stockholm_%C3%96P_Stadsutvecklingskartan/MapServer stockholm`
Dataset is geo located in Stockholm/Sweden.
A sample BIM can be found in attachment of this …
=> Support minimum LOD for ESRI layers

common/changes/@bentley/presentation-backend/presentation-do-not-initialize-UpdatesTracker-if-ipc-unavailable_2021-07-01-13-20.json, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/test/PresentationManager.test.ts
In some backends iModels are getting modified even when IPC host is not available. Ensure that doesn't cause issues for `PresentationManager`.
=> Presentation: Do not initialize UpdatesTracker if IPC host is not available

common/changes/@bentley/webpack-tools-core/fix-missing-externals_2021-07-01-16-04.json, tools/webpack-core/src/plugins/CopyExternalsPlugin.ts, tools/webpack-core/src/test/CopyExternalsPlugin.test.ts, tools/webpack-core/src/test/TestUtils.ts
Trying to avoid getting mysterious unhandled exceptions when `CopyExternalsPlugin` tries to handle a package that's not installed.
Basically, if an "external" module is not installed, we will always log a warning, but this will only bubble up as a webpack compilation warning if the module was not considered "optional" (that is, if the `import`/`require` was _not_ wrapped in a `try`/`catch`).
This is pretty similar to how this all worked prior to #1253, except now we can confidently say the package is not installed, so we no longer have to warn just because something is not a "direct" dependency.
=> Fix CopyExternalsPlugin not logging/warning for missing externals.

common/changes/@bentley/build-tools/fix-mocha-reporter_2021-07-01-16-45.json, tools/build/src/mocha-reporter/index.ts
Sometimes npm is lazy and just leaves duplicate copies of mocha lying around node_modules.
=> Fix BentleyMochaReporter error when packages are not correctly hoisted.

common/changes/@bentley/ui-components/ensureViewportDropped_2021-07-01-18-06.json, ui/components/src/ui-components/viewport/ViewportComponent.tsx
Fix issue caused when frontstage is changed while there is a pop-out window displaying a ViewportComponent. The ViewportComponent must ensure it is properly disconnected from ViewManager before the pop-out window is closed.
=> Ensure viewport dropped from ViewManager before window is unloaded

common/changes/@bentley/imodeljs-frontend/drop-psuedo-files_2021-07-02-14-19.json, common/changes/@bentley/imodeljs-markup/drop-psuedo-files_2021-07-02-14-19.json, common/changes/@bentley/presentation-common/drop-psuedo-files_2021-07-02-14-19.json, common/changes/@bentley/ui-abstract/drop-psuedo-files_2021-07-02-14-19.json, common/changes/@bentley/ui-components/drop-psuedo-files_2021-07-02-14-19.json, common/changes/@bentley/ui-core/drop-psuedo-files_2021-07-02-14-19.json, common/changes/@bentley/ui-framework/drop-psuedo-files_2021-07-02-14-19.json, core/frontend/.npmignore, core/markup/.npmignore, presentation/common/.npmignore, ui/abstract/.npmignore, ui/components/.npmignore, ui/core/.npmignore, ui/framework/.npmignore
Stop delivering pseudolocalized files from core.
Now that the CopyStaticAssetsPlugin has been released, all assets are available at app startup, and users have been complaining about some strings looking "weird". 
We've had other discussions about this, I believe the consensus then was provide a plugin in our cra fork to do pseudolocalization, and have users opt into that if they want it.
=> update npmignore to not deliver pseudolocalized files

common/changes/@bentley/imodeljs-backend/rpc-open-fix_2021-07-06-13-13.json, core/backend/src/rpc-impl/RpcBriefcaseUtility.ts, core/backend/src/test/integration/BriefcaseManager.test.ts, core/backend/src/test/integration/RpcBriefcaseOpen.test.ts
In ReadWrite workflows using the soon-to-be-removed RPC interfaces -- acquire a new briefcase when a local briefcase belonging to the user wasn't found. 
This closes VSTS #651570
=> Do not reuse briefcase ids in ReadWrite workflows when using the RPC interfaces (if the briefcase was not found in the local file system)

common/changes/@bentley/eslint-plugin/fix-vscode-eslint_2021-07-06-18-37.json, common/config/rush/pnpm-lock.yaml, tools/eslint-plugin/package.json
I noticed I had recently stopped getting lint warnings in VSCode, and tracked it back to this error:
```
[2:27 PM] Bill Goehrig
[Info  - 12:13:09 PM] ESLint server is starting
[Info  - 12:13:10 PM] ESLint server running in node v14.16.0
[Info  - 12:13:10 PM] ESLint server is running.
(node:73032) UnhandledPromiseRejectionWarning: Error: Failed to load plugin '@bentley' declared in '--config': Cannot find module 'typescript'
Require stack:
- D:\src\imodeljs\imodeljs\tools\eslint-plugin\dist\rules\import-spacing.js
- D:\src\imodeljs\imodeljs\common\temp\node_modules\.pnpm\require-dir@1.2.0\node_modules\require-dir\index.js
- D:\src\imodeljs\imodeljs\tools\eslint-plugin\dist\index.js
- D:\src\imodeljs\imodeljs\common\temp\node_modules\.pnpm\eslint@6.8.0\node_modules\eslint\lib\cli-engine\conf …
```
=> Fix VSCode eslint extension failing to load @bentley/eslint-plugin

common/changes/@bentley/imodeljs-frontend/geo-fix_2colors_skybox_map_2021-07-07-15-37.json, core/frontend/src/render/webgl/glsl/SkySphere.ts
2 colors sky box became opaque when background map was turned ON
=> Fix the Nadir color for 2 colors skybox in the context of background map.

common/api/presentation-common.api.md, common/api/ui-components.api.md, common/changes/@bentley/presentation-backend/presentation-fix-tree-autoupdate_2021-07-02-12-25.json, common/changes/@bentley/presentation-common/presentation-fix-tree-autoupdate_2021-07-02-12-25.json, common/changes/@bentley/presentation-components/presentation-fix-tree-autoupdate_2021-07-02-12-25.json, common/changes/@bentley/ui-components/presentation-fix-tree-autoupdate_2021-07-02-12-25.json, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts, presentation/common/src/presentation-common/Update.ts, presentation/common/src/test/Update.test.snap, presentation/common/src/test/Update.test.ts, presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts, presentation/components/src/test/tree/controlled/TreeHooks.test.ts, ui/components/src/test/tree/controlled/TreeModel.test.ts, ui/components/src/test/tree/controlled/internal/SparseTree.test.ts, ui/components/src/ui-components/tree/controlled/TreeModel.ts, ui/components/src/ui-components/tree/controlled/internal/SparseTree.ts
When tree hierarchy is responding to iModel or ruleset data changes, frontends fail to remove not loaded nodes from the hierarchy, because nodes do not have known ids while in placeholder state.
In addition to reporting deleted node keys, also report deleted node's parent and position among its siblings, so that even not loaded nodes can be correctly identified for removal.
The fix for incorrect tree state after update is not included here, as it will be a bigger overhaul of the tree auto update logic.
[Parallel change for the native addon.](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/175813)
=> Presentation: Report deleted node positions in hierarchy comparison results

common/api/geometry-core.api.md, common/api/imodeljs-frontend.api.md, common/changes/@bentley/geometry-core/analysis-mesh-range-2_2021-07-09-15-02.json, common/changes/@bentley/imodeljs-common/analysis-mesh-range-2_2021-07-09-15-02.json, common/changes/@bentley/imodeljs-frontend/analysis-mesh-range-2_2021-07-09-15-02.json, core/common/src/DisplayStyleSettings.ts, core/frontend/src/Viewport.ts, core/frontend/src/render/primitives/geometry/GeometryAccumulator.ts, core/frontend/src/render/primitives/geometry/GeometryListBuilder.ts, core/frontend/src/render/webgl/Graphic.ts, core/frontend/src/render/webgl/Layer.ts, core/frontend/src/render/webgl/Mesh.ts, core/frontend/src/render/webgl/Primitive.ts, core/frontend/src/test/Viewport.test.ts, core/frontend/src/test/render/primitives/GeometryAccumulator.test.ts, core/geometry/src/polyface/AuxData.ts, full-stack-tests/core/src/frontend/standalone/PrimitiveBuilder.test.ts, full-stack-tests/core/src/frontend/standalone/ViewportChangedEvents.test.ts, test-apps/display-test-app/src/frontend/AnalysisStyleExample.ts
Element locate culls based on the range of the graphic. The graphic's range is computed from the static mesh. If an analysis mesh has displacement, locate fails when mousing over portions of the deformed mesh outside the static mesh's range.
To fix this, the viewport's AnalysisStyleDisplacement is supplied to the GeometryAccumulator, which uses it to compute a range that accounts for the style's displacement.
The example decorator discards its cached analysis mesh graphic whenever the analysis style changes.
Incidentally fixed failure to locate pickable decorations that were inside a GraphicsArray.
=> Adjust analysis mesh range based on analysis style displacement.

common/changes/@bentley/imodeljs-frontend/bug-fallback-models-query_2021-07-12-16-45.json, core/frontend/src/ViewCreator3d.ts
isNotSpatiallyLocated property may not be available in the iModel's schema
=> Add fallback query when models query fails

common/changes/@bentley/ui-framework/fixBlankImodelConnection_2021-07-15-16-02.json, ui/framework/src/test/syncui/SyncUiEventDispatcher.test.ts, ui/framework/src/ui-framework/syncui/SyncUiEventDispatcher.ts
Now that calling `UiFramework.setIModelConnection`  calls `SyncUiEventDispatcher.initializeConnectionEvents` we must avoid doing certain set-up processing if the  `IModelConnection` is blank (ie `IModelConnection.isBlankConnection()`) to avoid exceptions being thrown.
=> Fix blank imodel connection

common/changes/@bentley/imodeljs-backend/IModelTransformer-ElementId-check_2021-07-07-12-54.json, core/backend/src/IModelTransformer.ts, core/backend/src/test/standalone/IModelTransformer.test.ts
Avoid hasElementChanged if ElementId is invalid since it will cause hasElementChanged to fail.
The following PR: [Add IModelTransformer CodeScope check #1741](https://github.com/imodeljs/imodeljs/pull/1741) introduced a stricter condition check which can result in missed invalid element ids because their codescope is also invalid. An additional id validity check is needed to correctly fall back on finding the missing predecessors later in the same method.
=> Add IModelTransformer ElementId check

common/changes/@bentley/imodeljs-backend/activate-ecef-gcs-depend-test_2021-07-16-14-19.json, core/backend/src/test/standalone/IModel.test.ts
Reactivated a test that stopped working when the changes from another PR was reverted. Now that ecef is computed when iModel has a gcs and stored value is not used then, the test makes sure that previous ecef value is recomputed when a GCS is set.
=> Activate ecef gcs depend test

common/changes/@bentley/ui-components/ui-components-fix-tree-background_2021-07-26-08-06.json, ui/components/src/ui-components/tree/controlled/component/ControlledTree.scss
After swapping the order of some divs, the tree background became transparent. The difference it makes in presentation-test-app is subtle, but it is much more prominent in dark-themed UIs.
=> UI: Fix tree background not being rendered

common/changes/@bentley/imodeljs-backend/fix-snap-cancellation_2021-07-27-10-27.json, common/changes/@bentley/rpcinterface-full-stack-tests/fix-snap-cancellation_2021-07-27-10-06.json, core/backend/src/test/standalone/DgnDbWorker.test.ts, full-stack-tests/rpc-interface/src/frontend/IModelConnection.test.ts
With `cancelSnap` outside of the try-catch, there was a possibility it produces an uncaught exception, failing the test.
With `expect` inside the `try` block followed by an empty `catch`, any errors would have been silently swallowed.
With an empty `catch` block, no verification of cancellation behavior.
Usage of `Promise.all` unnecessary for a single promise.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/181138).
=> Fix rpc-interface test for snapping

common/changes/@bentley/ui-framework/ui-framework-fix-test-pollution_2021-07-26-14-57.json, ui/framework/src/test/imodel-components/category-tree/CategoriesTree.test.snap, ui/framework/src/test/imodel-components/category-tree/CategoriesTreeWithSearchBox.test.snap, ui/framework/src/test/imodel-components/models-tree/ModelsTree.test.snap, ui/framework/src/test/imodel-components/spatial-tree/SpatialContainmentTree.test.snap, ui/framework/src/test/setup.test.ts
I noticed that `ModelsTree` tests fail when run in isolation.
It turns out that there is a dependency on previously run tests that mount components from iTwinUI-React, which manipulate the global state by inserting a class attribute into document's `body`.
The solution is to reset `jsdom` state between each test.
=> UI: Fix test pollution caused by iTwinUI-React components

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/query-2d-or-3d-placements_2021-07-28-18-21.json, core/frontend/src/IModelConnection.ts, core/frontend/src/Viewport.ts, core/frontend/src/tools/ClipViewTool.ts, docs/changehistory/NextVersion.md, full-stack-tests/core/src/frontend/standalone/Elements.test.ts
See NextVersion.md for details.
Also, previous implementation used `isPlacement2dProps`. It checks if `props.angle` is defined, and while the Placement2dProps interface suggests that property is required, it is often null in the database and defaults to zero.
=> zoomToElements ignores 2d for 3d view and vice-versa

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/query-2d-or-3d-placements_2021-07-28-18-21.json, core/frontend/src/IModelConnection.ts, core/frontend/src/Viewport.ts, core/frontend/src/tools/ClipViewTool.ts, docs/changehistory/NextVersion.md, full-stack-tests/core/src/frontend/standalone/Elements.test.ts
(cherry picked from commit 93b33b535f40357051fb544526f49812b068f804)
Co-authored-by: Ray.Bentley <rbbentley@users.noreply.github.com>
=> zoomToElements ignores 2d for 3d view and vice-versa (backport #1961)

common/changes/@bentley/ui-components/ui-components-tree-node-loader_2021-08-04-12-38.json, ui/components/src/test/tree/controlled/TreeNodeLoader.test.ts, ui/components/src/ui-components/tree/controlled/TreeNodeLoader.ts
`TreeDataSource.requestItems` performs two async operations on the same `TreeDataProvider` instance, which is prone to race conditions. For example, `getNodesCount` result may not correlate with what `getNodes` will return when a presentation ruleset changes in between the calls (if there was no memoization involved, but that's just a `PresentationTreeDataProvider` implementation detail).
This change makes it so `TreeDataSource` does not call `getNodes` if there are no active subscribers, and also fixes `TreeNodeLoader` tests not setting up mocks for some `getNodeCount` calls.
=> UI: Avoid loading stale data from TreeDataProvider

common/config/azure-pipelines/ci.yaml, common/config/azure-pipelines/jobs/fast-ci.yaml
Upgrading the Node version used in the CI to 14.17.4.
Node 14.17.0 has a known, and fixed, issue that causes a crash within the NAPI during the destructor routines. The fix for this was first introduced in 14.17.4, all other Node versions prior to this version within 14.x could exhibit the crash.
=> Update CI to Node 14.17.4

.github/CODEOWNERS
make Colin Kerr the secondary owner of the imodel transformer
=> make colin kerr the secondary for imodel transformer

common/changes/@bentley/imodeljs-editor-frontend/project-loc-save-message_2021-08-11-13-11.json, editor/frontend/src/ProjectLocation/ProjectExtentsDecoration.ts, editor/frontend/src/public/locales/en/Editor.json
Don't return false when showing a more detailed error to avoid having toast message closed by default unable to run key-in message.
=> Improve error messages for "editor project location save".

clients/reality-data/CHANGELOG.json, common/changes/@bentley/reality-data-client/2.18.4-changelog-fix_2021-08-13-21-18.json
Made a mistake with the changelogs for 2.18.4 which was preventing rush from bumping versions. Fixing on 2.19 first to unblock 2.19.5 release then cherry picking into master with 2.19.5 changelogs.
=> Fix reality data client changelog

core/backend/src/test/standalone/TileTree.test.ts, core/common/src/RenderSchedule.ts
`ModelTimelineBuilder` has this function: `addElementTimeline(elementIds: CompressedId64Set | Iterable<Id64String>)`
It is very easy to forget to put a single element Id inside of an array - `builder.addElementTimeline(0x123)` vs `builder.addElementTimeline([0x123])`
CompressedId64Set and Id64String are just typedefs for `string`, so the compiler is happy to accept this (also, a `string` is an `Iterable<string>`).
Help out callers by detecting this mistake and correcting it. Otherwise we end up trying (and failing) to parse the string as a CompressedId64Set.
=> Correct mistake of passing a single element Id as a string instead of an array

test-apps/display-test-app/README.md, test-apps/display-test-app/public/locales/en/SVTTools.json, test-apps/display-test-app/src/frontend/App.ts, test-apps/display-test-app/src/frontend/DisplayTestApp.ts, test-apps/display-test-app/src/frontend/Surface.ts, test-apps/display-test-app/src/frontend/Viewer.ts, test-apps/display-test-app/src/frontend/openIModel.ts, test-apps/display-test-app/src/frontend/signIn.ts
User must download the briefcase first using whatever method they choose - no UI or keyins are supplied for choosing a project and iModel within display-test-app.
Adds keyins for pushing and pulling changes and for signing in.
The primary purpose is to enable testing/debugging editing workflows involving pushing and pulling changes.
=> display-test-app supports briefcases

common/api/imodeljs-backend.api.md, common/api/summary/imodeljs-backend.exports.csv, common/changes/@bentley/imodeljs-backend/add-queryv2checkpoint-to-hubaccess_2021-08-18-14-47.json, core/backend/src/BackendHubAccess.ts, core/backend/src/CheckpointManager.ts, core/backend/src/IModelHubBackend.ts, core/backend/src/test/HubMock.ts
Allows IModelBank to support V2 checkpoints (or not).
=> Add `queryV2Checkpoint` to `BackendHubAccess` interface

common/changes/@bentley/backend-itwin-client/download_delay_on_small_files_2021-08-24-13-36.json, common/changes/@bentley/imodeljs-common/download_delay_on_small_files_2021-08-24-13-36.json, core/backend-itwin-client/src/imodelhub/AzureFileHandler.ts, core/common/src/Paging.ts
This cause a performance hit when briefcase/checkpoint are smaller then 500Mb. The probe take 5-8 seconds which is added to startup time of backend.
There is unrelated documentation fix included in this change.
=> Defer probe azcopy version for small files

common/api/imodeljs-common.api.md, core/backend/src/IModelDb.ts, core/backend/src/IModelHost.ts, core/backend/src/test/integration/TileUpload.test.ts, core/backend/src/test/standalone/TileCache.test.ts, core/common/src/IModel.ts
The directory where the checkpoint files are stored is protected.
=> use cacheDir for temp files when opening V2 checkpoints

common/changes/@bentley/imodeljs-backend/fix-async-promise-rejection_2021-08-30-13-01.json, core/backend/src/test/standalone/DgnDbWorker.test.ts
...by installing rejection handler before `await`ing.
=> Install rejection handler before await to avoid PromiseRejectionHandledWarning in test.

common/changes/@bentley/imodeljs-frontend/fix-graphicbuilder-xform-2_2021-09-01-12-06.json, core/frontend/src/render/primitives/geometry/GeometryAccumulator.ts, core/frontend/src/render/primitives/geometry/GeometryPrimitives.ts, core/frontend/src/test/TestDecorators.ts, core/frontend/src/test/render/webgl/Decorations.test.ts, core/frontend/src/test/render/webgl/PickableGraphics.test.ts
The previous fix to the graphicbuilder transform problem actually resulted in some graphicbuilder primitives being transformed twice because they already had the transform applied to them. This fixes that issue by moving the transformation only to primitives that were missing it. This also adds code to ensure that GeometryAccumulator does not mutate the graphicbuilder's transform in-place.
=> Fix graphicbuilder transform part 2

common/changes/@bentley/imodel-bridge/chickneas-bad-imodel-bridge-repo-url_2021-08-30-03-46.json, core/imodel-bridge/package.json
FutureOn were trying to access the bridge framework code through the repository link in NPM and found it broken.
=> fix broken link due to moving imodel-bridge

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/Reduce-map-tile-occlusion-tolerance_2021-09-01-17-54.json, core/frontend/src/tile/RealityTileTree.ts, core/frontend/src/tile/map/MapTile.ts, core/frontend/src/tile/map/MapTileTree.ts
The logic for rejecting map tiles occluded by the ellipsoid was allowing tile beyond the horizon to be accepted.  With depth buffer turned off (the default) these tiles would display incorrectly.
=> Correct display of map tiles with depth buffering off

common/api/frontend-devtools.api.md, common/api/imodeljs-common.api.md, common/api/imodeljs-frontend.api.md, common/api/summary/frontend-devtools.exports.csv, common/api/summary/imodeljs-common.exports.csv, common/changes/@bentley/frontend-devtools/wow-ignore-background_2021-09-08-13-58.json, common/changes/@bentley/imodeljs-common/wow-ignore-background_2021-09-08-13-58.json, common/changes/@bentley/imodeljs-frontend/wow-ignore-background_2021-09-08-13-58.json, core/common/src/DisplayStyleSettings.ts, core/common/src/ViewFlags.ts, core/common/src/WhiteOnWhiteReversalSettings.ts, core/common/src/imodeljs-common.ts, core/common/src/test/DisplayStyle.test.ts, core/common/src/test/WhiteOnWhiteReversalSettings.test.ts, core/frontend-devtools/README.md, core/frontend-devtools/public/locales/en/FrontendDevTools.json, core/frontend-devtools/src/FrontEndDevTools.ts, core/frontend-devtools/src/tools/DisplayStyleTools.ts, core/frontend/src/Viewport.ts, core/frontend/src/render/RenderPlan.ts, core/frontend/src/render/webgl/StyleUniforms.ts, core/frontend/src/render/webgl/glsl/Fragment.ts, docs/changehistory/NextVersion.md, full-stack-tests/core/src/frontend/standalone/WhiteOnWhiteReversal.test.ts
As requested by SYNCHRO Field, who want white lines to be displayed as black on their light grey background.
Introduces DisplayStyleSettings.whiteOnWhiteReversal.
Currently it has a single boolean flag indicating whether to ignore the background color. In future we may add other options to it to handle more general cases like "light color on light background", "dark color on dark background", and/or "similar color to background color".
=> Allow white-on-white reversal to be applied to non-white backgrounds

common/changes/@bentley/ui-components/ui-components-property-grid-style_2021-09-02-11-20.json, ui/components/src/test/propertygrid/component/VirtualizedPropertyGridWithDataProvider.test.tsx, ui/components/src/test/propertygrid/component/internal/FlatPropertyRenderer.test.tsx, ui/components/src/ui-components/properties/renderers/PropertyView.scss, ui/components/src/ui-components/propertygrid/component/VirtualizedPropertyGrid.scss, ui/components/src/ui-components/propertygrid/component/VirtualizedPropertyGrid.tsx, ui/components/src/ui-components/propertygrid/internal/flat-properties/FlatPropertyRenderer.tsx
Some more adjustments to element positioning in VirtualizedPropertyGrid after migrating to @itwinui-react components. Notable changes: 
* Adds padding around the whole property grid to match previous look
* Simplifies some CSS rules
* Increases information density in vertical mode
Known issues:
* Expandable block chevrons are misaligned
* There is no top padding in expandable block content
* Editors cause properties to nudge slightly
=> UI: Update VirtualizedPropertyGrid element spacing

common/changes/@bentley/presentation-common/presentation-fix_nested_merged_content_2021-09-09-12-44.json, presentation/common/src/presentation-common/content/ContentTraverser.ts, presentation/common/src/test/content/ContentTraverser.test.ts
Fixed `traverseContentItem` to correctly handle merged values that are nested under nested content field.
=> Presentation: Correctly handle merged values under nested content field

.github/CODEOWNERS, common/changes/@bentley/webpack-tools-core/bug-copy-version_2021-09-09-19-33.json, common/config/rush/pnpm-lock.yaml, tools/webpack-core/package.json
7+ requires Webpack 5, which we don't yet use:
https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v7.0.0
=> Revert copy-webpack-plugin version

common/changes/@bentley/mobile-manager/fix-auth-init-called-before-its-registered_2021-09-10-17-40.json, core/mobile-manager/src/backend/AndroidHost.ts, core/mobile-manager/src/backend/MobileHost.ts, core/mobile-manager/src/backend/MobileRpcServer.ts, core/mobile-manager/src/backend/iOSHost.ts
The issue happen when auth config is provided on backend and startup attempt to call authInit(). It does nothing as native device interface has not been registered yet.
imodel02: https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/192205
=> Fix auth init called before its registered

common/api/imodeljs-frontend.api.md, common/api/summary/imodeljs-frontend.exports.csv, common/changes/@bentley/imodeljs-common/OnViewExtentsError_2021-09-14-12-11.json, common/changes/@bentley/imodeljs-frontend/OnViewExtentsError_2021-09-13-20-27.json, core/common/src/Frustum.ts, core/frontend/src/ViewAnimation.ts, core/frontend/src/ViewGlobalLocation.ts, core/frontend/src/ViewState.ts, core/frontend/src/Viewport.ts, core/frontend/src/tools/ToolAdmin.ts, core/frontend/src/tools/ViewTool.ts, docs/changehistory/NextVersion.md
the onExtentsError method can be used where "view change" isn't appropriate. Caused confusion in places that only wanted the error handler. Allow methods to accept `OnViewExtentsError` without the rest of `ViewChangeOptions`.
=> Separate OnViewExtentsError from ViewChangeOptions

common/changes/@bentley/ui-components/master_2021-09-13-11-07.json, ui/components/src/ui-components/tree/controlled/component/TreeRenderer.tsx
There is a regression that is only present in 2.19.x releases which causes `TreeRenderer` to repeat the last `scrollToNode` call on each component render. It is caused by `TreeRenderer` ref being re-set because we do not specify a dependency list in  `useImperativeHandle` call.
After refactoring and simplifying `ControlledTree` component for the 3.0 release, we can no longer observe the effect of a missing dependency list, so there are no tests or changelog entry for this change. Instead, this PR will be backported to 2.19.x branch where tests and a changelog entry will be added.
=> UI: Make TreeRenderer keep the same imperative handle between renders

common/api/summary/ui-components.exports.csv, common/api/ui-components.api.md, common/changes/@bentley/ui-components/ui-drag-drop-context_2021-09-16-22-26.json, test-apps/ui-test-app/src/frontend/index.tsx, ui/components/src/test/table/component/BeDragDropContext.test.tsx, ui/components/src/ui-components.ts
BeDragDropContext is required at the top level if an app uses the Table component in ui-components. Republish it and use it in ui-test-app to fix the frontstages that have Table components.
=> Publish BeDragDropContext

common/changes/@bentley/build-tools/fix-rush-test_2021-09-17-15-23.json, tools/build/bin/betools.js, tools/build/scripts/rush/utils.js, tools/build/src/mocha-reporter/index.ts
This has been broken ever since we updated to use mocha 8 in #1190.  Turns out we just needed to react a change (https://github.com/mochajs/mocha/pull/3725) in the base reporter intended to prevent _tests_ from accidentally redirecting reporter output.
Also updated betools to stop logging useless "Error: Command failed: ..." errors (and call stacks) when a test process fails.
=> Fix error output not being included in rush test/cover summaries.

common/changes/@bentley/ui-components/presentation-fix_merged_values_rendering_2021-09-20-10-59.json, ui/components/src/test/properties/ValueRendererManager.test.tsx, ui/components/src/test/properties/renderers/value/MergedPropertyValueRenderer.test.tsx, ui/components/src/ui-components/properties/ValueRendererManager.tsx
Merged PropertyRecords might not have any value set and typename specific renderers renders an empty value. Check if MergedPropertyValueRenderer might be used before looking for typename specific renderer.
=> Presentation: render merged property values before using typename specific renderer

common/api/bentleyjs-core.api.md, common/api/summary/bentleyjs-core.exports.csv, common/changes/@bentley/bentleyjs-core/changeset-apply_2021-09-21-11-07.json, common/changes/@bentley/imodeljs-frontend/changeset-apply_2021-09-21-11-07.json, core/bentley/src/BeSQLite.ts, core/bentley/src/ClientRequestContext.ts, core/frontend/src/CheckpointConnection.ts, full-stack-tests/core/src/frontend/hub/IModelApp.test.ts
- `ChangeSetApplyOption` is now @internal. Will be removed with next addon build
- removed unused `ClientRequestContext.useContextForRpc`
=> Remove ChangeSetApplyOption and ClientRequestContext.useContextForRpc

common/api/geometry-core.api.md, common/changes/@bentley/geometry-core/EDL-ClipPrimitiveInvisibleBitCleanup_2021-09-21-21-28.json, core/geometry/src/clipping/ClipPrimitive.ts, core/geometry/src/geometry3d/PolylineOps.ts, core/geometry/src/test/clipping/ClipPrimitives.test.ts, core/geometry/src/test/clipping/ClipVector.test.ts, core/geometry/src/test/geometry3d/PolylineCompression.test.ts, core/geometry/src/test/topology/Triangulator.test.ts
* New method PolylineOps.compressDanglers(points, true) : Point3d[] -- removes (trees of) points that stray into the area and return on the same path.
* with dangler: 
* dangler removed 
* When triangulating a ClipShape (leading to making UnionOfConvexClipPlaneSets), a user case failed because of dangling edges that break the triangulator.    Prevent this be calling PolylineOps.compressDanglers
* Eliminate incorrect use of _isInvisible property in ClipPrimitive's point classification.  (mask property in ClipShape does this correctly)
=> When building planes for a ClipShape, pre-filter the shape edges to remove danglers that violate triangulation requirements

common/api/imodeljs-common.api.md, common/changes/@bentley/imodeljs-common/remove-any_2021-09-22-13-59.json, common/changes/@bentley/rpcinterface-full-stack-tests/remove-any_2021-09-22-14-20.json, core/common/src/GeometryContainment.ts, core/common/src/Snapping.ts, full-stack-tests/rpc-interface/src/frontend/IModel.test.ts
There are plenty more. In particular I wish we would use a union type like `number | string | Uint8Array | undefined` for pulling values out of a SqliteStatement, but it looks like too late for 3.0.
=> Replace some uses of `any`

common/changes/@bentley/imodeljs-frontend/Point-cloud-symbology-overrides_2021-09-22-14-40.json, core/frontend/src/render/webgl/BatchUniforms.ts, core/frontend/src/render/webgl/glsl/FeatureSymbology.ts
Point clouds supported overriding color but not symbology.  This extends the override support to include transparency.
=> Support transparency overrides for point clouds

common/changes/@bentley/imodeljs-frontend/min-pattern-tolerance_2021-09-23-17-00.json, core/frontend/src/tile/TileAdmin.ts
We added this option a long time ago for Shell and they still have not taken advantage of it.
The default was "no minimum". It's now 1mm. If somebody wants to view spatial models at a higher level of detail than that, they can override this minimum.
=> Impose default minimum spatial tolerance of 1mm

common/api/imodeljs-frontend.api.md, common/changes/@bentley/imodeljs-frontend/track-instance-buffers-memory_2021-09-24-15-06.json, core/frontend/src/render/RenderMemory.ts, core/frontend/src/render/RenderSystem.ts, core/frontend/src/render/webgl/AttributeBuffers.ts, core/frontend/src/render/webgl/InstancedGeometry.ts, core/frontend/src/render/webgl/Mesh.ts, core/frontend/src/render/webgl/Primitive.ts, core/frontend/src/render/webgl/System.ts, core/frontend/src/render/webgl/Texture.ts, core/frontend/src/test/render/webgl/RenderMemory.test.ts, core/frontend/src/tile/ImdlReader.ts
The instancing data allocated on the GPU can be shared amongst multiple primitives (e.g., a mesh's surface and edges), or owned by a single primitive (e.g., a polyline or point string). Ensure that each set of instances is reported exactly once, and freed when its single owner is disposed of.
=> Ensure memory consumed by instanced geometry is accurately reported and freed

common/api/presentation-common.api.md, common/api/summary/presentation-common.exports.csv, common/changes/@bentley/presentation-backend/presentation-add-assertions-for-correct-classmap-3.0_2021-09-28-11-46.json, common/changes/@bentley/presentation-common/presentation-add-assertions-for-correct-classmap-3.0_2021-09-21-13-07.json, common/changes/@bentley/presentation-common/presentation-add-assertions-for-correct-classmap-3.0_2021-09-28-11-46.json, presentation/backend/src/test/PresentationManager.test.snap, presentation/backend/src/test/PresentationManager.test.ts, presentation/common/src/presentation-common/EC.ts, presentation/common/src/presentation-common/Utils.ts, presentation/common/src/presentation-common/content/Descriptor.ts, presentation/common/src/presentation-common/content/Fields.ts, presentation/common/src/test/EC.test.ts, presentation/common/src/test/_helpers/EC.ts, presentation/common/src/test/content/Descriptor.test.snap, presentation/common/src/test/content/Descriptor.test.ts
The assertions also revealed that our `SelectClassInfo.pathFromInputToSelectClass` type definition doesn't match what we're sending from the addon. In case of recursive relationships we're don't have a relationship information. Updated the type definition to match that.
=> Presentation: Add assertions for correct classmap 3.0

common/changes/@bentley/ui-components/ui-components-expandable-block_2021-09-28-12-14.json, common/changes/@bentley/ui-core/ui-components-expandable-block_2021-09-28-12-14.json, test-apps/presentation-test-app/src/frontend/components/properties-widget/PropertiesWidget.css, ui/components/src/test/propertygrid/component/VirtualizedPropertyGridWithDataProvider.test.tsx, ui/components/src/ui-components/propertygrid/component/VirtualizedPropertyGrid.scss, ui/components/src/ui-components/propertygrid/component/VirtualizedPropertyGrid.tsx, ui/core/src/ui-core/style/itwinui-overrides.scss
Recent upgrade to newer version of iTwinUI has broken our style overrides for compact expandable blocks.
This PR makes the following changes to `VirtualizedPropertyGrid`:
* Fixes chevron centering, again.
* Gives category labels more vertical space to fix inconsistent spacing between expandable block borders.
* Fixes an older issue where the top-most expandable block has slightly protruding background through the top edge.
* Drops extra padding around the component to make reasoning about its sizing more straightforward. Previously, if user set its width to `100px`, the component would actually take up `106px` horizontally. This change also removes the need for negative margin in presentation-test-app.
=> UI: Update VirtualizedPropertyGrid styles

common/changes/@itwin/core-webpack-tools/fix-copy-static-plugin_2021-09-30-13-28.json, tools/webpack-core/src/plugins/CopyBentleyStaticResourcesPlugin.ts, tools/webpack-core/src/test/CopyBentleyStaticResourcesPlugin.test.ts
With the renaming of many packages to the `@itwin` scope the copying is broken within master of the imodeljs repo.
I think we should backport this to 2.19.x so it can easily be pulled into `@bentley/react-scripts`.
=> Update copy static plugin to support the '@itwin' scope

common/api/components-react.api.md, common/api/summary/components-react.exports.csv, common/changes/@itwin/components-react/ui-promote-property-grid-related-apis_2021-10-01-08-55.json, ui/components/src/components-react/propertygrid/PropertyCategoryRendererManager.ts, ui/components/src/components-react/propertygrid/PropertyDataProvider.ts, ui/components/src/components-react/propertygrid/component/PropertyCategoryBlock.tsx, ui/components/src/components-react/propertygrid/component/PropertyGridCommons.ts, ui/components/src/components-react/propertygrid/dataproviders/FilteringDataProvider.ts, ui/components/src/components-react/propertygrid/dataproviders/filterers/CompositePropertyDataFilterer.ts, ui/components/src/components-react/propertygrid/dataproviders/filterers/DisplayValuePropertyDataFilterer.ts, ui/components/src/components-react/propertygrid/dataproviders/filterers/LabelPropertyDataFilterer.ts, ui/components/src/components-react/propertygrid/dataproviders/filterers/PropertyCategoryLabelFilterer.ts, ui/components/src/components-react/propertygrid/dataproviders/filterers/PropertyDataFiltererBase.ts, ui/components/src/components-react/propertygrid/internal/PropertyGridHooks.ts
Promote property grid related APIs:
- Action button rendering
- Records' highlighting
- Filtering
Left `@beta`:
- Stuff related to `VirtualizedPropertyGrid` - we feel like it's not ready to be `@public` yet.
- Orientation and editing related props in `CommonPropertyGridProps` - I'm not sure about the state of those. @DanEastBentley can you have a look at them?
=> UI: Promote property grid related apis

common/api/components-react.api.md, common/api/summary/components-react.exports.csv, common/changes/@itwin/components-react/ui-promote-tree-apis_2021-10-01-14-35.json, docs/changehistory/NextVersion.md, ui/components/src/components-react/tree/controlled/TreeHooks.ts, ui/components/src/components-react/tree/controlled/component/ControlledTree.tsx, ui/components/src/components-react/tree/controlled/component/TreeNodeEditor.tsx, ui/components/src/components-react/tree/controlled/component/TreeNodeRenderer.tsx, ui/components/src/components-react/tree/controlled/component/TreeRenderer.tsx
Promotions from `alpha` to `beta` and from `beta` to `public`.
Hides `TreeRendererContext` API because it is only usable within `TreeNodeRenderer`.
Removes `ExtentedTreeNodeRendererProps` as it seems unnecessary.
=> UI: Promote and prune ControlledTree APIs

common/changes/@itwin/ecschema-rpcinterface-impl/fix-publishing_2021-10-04-18-19.json, common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, core/ecschema-rpc/impl/package.json
The missing devDependency (`@bentley/itwin-client`) is causing the `rush publish --pack` step to fail when attempting to bundle all of our packages.
=> Add missing devDep on ecschema-impl causing publish failures

common/changes/@itwin/core-backend/fix-access-token-in-cancel-tile-requests_2021-10-05-10-34.json, core/backend/src/rpc-impl/IModelTileRpcImpl.ts
Induced by #2401. cancelTileContentRequests is an Ipc method - it should not be trying to access `RpcTrace.currentActivity!.accessToken` - currentActivity will be undefined.
=> Fix exception in cancelTileContentRequests

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/fix-plan-projection-exceptions_2021-10-05-11-03.json, core/frontend/src/PlanarClipMaskState.ts, core/frontend/src/tile/PrimaryTileTree.ts
The nightly ImageTests runs have begun hanging due to a modal dialog popping up because of failed assertion in PlanProjectionTreeReference.computeBaseTransform.
MaskTreeReference always sets `isPlanProjection` to `false` in its tree Id, but whether or not it's a plan projection is determined by the model, not the tree reference.
Later, when we have a PlanProjectionTreeReference for the same model, we expect a PlanProjectionTileTree to have been created, but MaskTreeReference caused us to create an IModelTileTreeReference instead.
See PrimaryTreeSupplier.compareTileTreeIds.
We still need to figure out why display-performance-test-app is running with assertion enabled now, and popping up this dialog that doesn't look like one we created - probably some obscure regression from one of the …
=> MaskTreeReference must set isPlanProjection appropriately

.vscode/extensions.json
The list of recommendations is outdated as the latest VSCode versions come with the functionality already built-in this Extension provides.
=> Remove the chrome debugger extension as it is now built-in to VSCode

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/feature-overrides-source_2021-10-05-17-09.json, core/frontend/src/render/FeatureSymbology.ts, core/frontend/src/render/webgl/FeatureOverrides.ts, core/frontend/src/render/webgl/Graphic.ts, core/frontend/src/test/render/webgl/Batch.test.ts, full-stack-tests/core/src/frontend/standalone/FeatureOverrides.test.ts
OpenCitiesPlanner draws the same tiles repeatedly into the same viewport, applying different symbology overrides each time.
This causes the texture by which we pass the overrides to the GPU to be recomputed constantly and unnecessarily.
Introduced the concept of FeatureSymbology.Source which can be associated with a FeatureSymbology.Overrides.
Now, instead of caching the textures by the combination of tile (aka "batch") and viewport (aka "target"), we cache by the combination of tile and viewport and source.
It is imperative that the caller raise the onSourceDisposed event when the source becomes dissociated from the viewport so we can reclaim the texture memory.
TODO: Backport to 2.19.x.
=> Allow multiple FeatureOverrides per tile per viewport

common/api/imodeljs-frontend.api.md, common/api/summary/imodeljs-frontend.exports.csv, common/changes/@bentley/imodeljs-frontend/backport-2419_2021-10-05-18-26.json, common/changes/@itwin/core-frontend/feature-overrides-source_2021-10-05-17-09.json, core/frontend/src/render/FeatureSymbology.ts, core/frontend/src/render/webgl/FeatureOverrides.ts, core/frontend/src/render/webgl/Graphic.ts, core/frontend/src/test/render/webgl/Batch.test.ts, full-stack-tests/core/src/frontend/standalone/FeatureOverrides.test.ts
Backport #2419 for OpenCities Planner.
(cherry picked from commit be5cfd8b8045749c3dd48ecde78ff88eb6edfea3)
=> Allow multiple FeatureOverrides per tile per viewport (backport #2419)

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml
The updated webpack plugin fixes the issue with localization files not being copied correctly. Looks like the lock file was reverted somehow to no longer pull in the new version.
This fixes key-ins in all of the test apps.
Note: This is an implicit upgrade since `@bentley/react-scripts` uses `^2.16.2` as it's version of `@bentley/webpack-tools-core` so it's going to get the latest but could get a previous version.
=> Update deps to pick up webpack plugin fix

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/OPCFromLocalHTTPServer_2021-11-01-13-15.json, core/frontend/src/RealityDataSource.ts, core/frontend/src/test/RealityDataSouce.test.ts, core/frontend/src/tile/OrbitGtTileTree.ts
Currently, the code extract the reality data type from context share or assume that we always have a 3dTile when hosted locally (e.g. from http.server)
This change extracts reality data format from the extension found in the tileset url when not from context share.
=> Support open reality data point cloud (opc) from any http server

common/api/core-common.api.md, common/api/frontend-devtools.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-common/planar-mask-inversion_2021-11-01-14-29.json, common/changes/@itwin/core-frontend/planar-mask-inversion_2021-11-01-14-29.json, common/changes/@itwin/frontend-devtools/planar-mask-inversion_2021-11-01-14-29.json, core/common/src/PlanarClipMask.ts, core/common/src/test/ContextRealityModel.test.ts, core/common/src/test/DisplayStyle.test.ts, core/common/src/test/PlanarClipMaskSettings.test.ts, core/frontend-devtools/README.md, core/frontend-devtools/src/tools/PlanarMaskTools.ts, core/frontend/src/render/webgl/PlanarClassifier.ts, core/frontend/src/render/webgl/glsl/PlanarClassification.ts
Add support for inverting planar clip masks to mask outside rather than inside.   This is useful for confining either reality model or background maps to the interior of a mask.
Addresses #2585.
=> Planar mask inversion

common/changes/@itwin/core-frontend/fix-canvas-animation-not-updating-when-dropping-viewport_2021-11-02-17-56.json, core/frontend/src/Viewport.ts
When dropping a second viewport and re-enabling direct-to-screen WebGL rendering, we really want the WebGL canvas' zIndex to be lower than the 2d canvas, but if we do that, browsers can decide to not update the WebGL canvas contents once it is re-added to the parent div after dropping other viewports. The offending element is the 2d canvas sitting on top of the WebGL canvas. We need to clear the 2d canvas' contents in order to ensure browsers allow the underlying WebGL canvas to update. If a decorator is present, the 2d canvas is cleared during the frame render process by virtue of updating the decorator. For the non-decorator case, and for iOS, we must make sure we still clear the 2d canvas, done here. iOS appears to need this clear even when decorators clear the canvas later in the …
=> Fix WebGL view not updating when dropping second viewport

common/api/appui-react.api.md, common/api/presentation-common.api.md, common/api/presentation-frontend.api.md, common/api/summary/presentation-common.exports.csv, common/api/summary/presentation-frontend.exports.csv, common/changes/@itwin/appui-react/presentation-get-content-instance-keys_2021-11-02-09-44.json, common/changes/@itwin/presentation-backend/presentation-get-content-instance-keys_2021-11-02-09-13.json, common/changes/@itwin/presentation-common/presentation-get-content-instance-keys_2021-11-02-09-13.json, common/changes/@itwin/presentation-frontend/presentation-get-content-instance-keys_2021-11-02-09-13.json, full-stack-tests/presentation/src/frontend/Content.test.ts, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts, presentation/common/src/presentation-common/PresentationManagerOptions.ts, presentation/common/src/presentation-common/PresentationRpcInterface.ts, presentation/common/src/presentation-common/RpcRequestsHandler.ts, presentation/common/src/test/PresentationRpcInterface.test.ts, presentation/common/src/test/RpcRequestsHandler.test.ts, presentation/frontend/src/presentation-frontend/PresentationManager.ts, presentation/frontend/src/test/PresentationManager.test.ts, ui/appui-react/src/appui-react/imodel-components/VisibilityTreeEventHandler.ts, ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsVisibilityHandler.ts, ui/appui-react/src/test/imodel-components/models-tree/ModelsVisibilityHandler.test.ts
The RPC only sends instance keys instead of content records. In addition, the IDs are sent as a `KeySet`, which compresses them, and that substantially reduces the payload size.
=> Presentation: Get content instance keys

common/api/core-backend.api.md, common/api/summary/core-backend.exports.csv, common/changes/@itwin/core-backend/cloud-workspace-containers_2021-11-02-16-33.json, core/backend/src/ECDb.ts, core/backend/src/IModelDb.ts, core/backend/src/IModelHost.ts, core/backend/src/test/IModelHost.test.ts, core/backend/src/test/standalone/Settings.test.ts, core/backend/src/test/standalone/Workspace.test.ts, core/backend/src/workspace/Settings.ts, core/backend/src/workspace/Workspace.ts, docs/learning/backend/Workspace.md, example-code/snippets/src/backend/ExampleCode.test.ts
The `workspace` member on `IModelHost` is now called `appWorkspace` and it cannot hold iModel settings. There is now a new member `IModelDb.workspace` that may hold information at the organization, iTwin, and iModel priorities. Calling `IModelDb.workspace.settings.getValue` will resolve settings from all priorities (including application). 
This makes it possible to have more than one `IModelDb` at a time, each with their own independent workspaces.
=> Add IModelDb.workspace

common/changes/@itwin/appui-react/widget-default-state_2021-11-04-08-29.json, test-apps/ui-test-app/src/frontend/appui/frontstages/ViewsFrontstage.tsx, test-apps/ui-test-app/src/frontend/tools/AppUi2StageItemsProvider.tsx, ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
This PR fixes an issue where Hidden defaultState was ignored when initializing an app layout.
Also setting a Hidden defaultState on a WidgetDef will now hide a widget from the UI when the frontstage is activated.
=> Respect Hidden defaultState of a widget.

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/geo-wms_4326_support_2021-11-04-17-55.json, core/frontend/src/test/public/assets/wms_capabilities/continents.xml, core/frontend/src/test/tile/map/MapLayerImageryProvider.test.ts, core/frontend/src/tile/map/ImageryProviders/WmsMapLayerImageryProvider.ts, core/frontend/src/tile/map/MapLayerImageryProvider.ts, core/frontend/src/tile/map/WmsCapabilities.ts
Based on the WMS GetCapabilities response, and the currently visible layers, the provider will automatically switch between EPSG:4326 or EPSG:3857, EPSG:3857 being our favorite CRS if both options are available.
Previously only EPSG:3857 was supported.
=> Adds support for EPSG:4326 CRS in WMS imagery provider

test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app/ViewController.swift
Make display-test-app for iOS use "public.data" as the documentType for UIDocumentPickerViewController. Otherwise, it will try to filter to .bim, which can malfunction and result in constantly grayed-out files in the file open dialog.
=> Make display-test-app for iOS use "public.data" as the documentType

common/changes/@itwin/components-react/components-react-virtualized-property-grid_2021-11-08-15-38.json, ui/components-react/src/components-react/propertygrid/component/VirtualizedPropertyGrid.tsx, ui/components-react/src/test/propertygrid/component/VirtualizedPropertyGridWithDataProvider.test.tsx
Reacting to #2618. Small expandable block header in iTwinUI-react is 1px taller than the override we used.
=> Adjust VirtualizedPropertyGrid category header height

common/changes/@itwin/webgl-compatibility/update-intel-renderer-string_2021-11-09-20-13.json, core/webgl-compatibility/src/Capabilities.ts, core/webgl-compatibility/src/test/Compatibility.test.ts
Long ago we implemented a workaround for a bug in particular integrated GPUs that caused transparenct geometry to display behind other geometry.
We detect these GPUs using a regex match against the unmasked renderer string provided by WebGL.
It appears Intel has slightly changed that string, so our regex has ceased working and the bug has recurred.
Previously (for example):
`ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)`
Now:
`ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)`
=> Update renderer string for buggy Intel chips

common/changes/@itwin/appui-layout-react/fixTypeEditorCssStyle_2021-11-10-13-23.json, common/changes/@itwin/components-react/fixTypeEditorCssStyle_2021-11-10-13-23.json, ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.scss, ui/components-react/src/components-react/editors/CustomNumberEditor.tsx, ui/components-react/src/components-react/editors/EnumEditor.tsx
- Since type editors are now using iTwinUi components those components must use size="small" prop to be properly sized for AppUI.
- Removed the prop on `<Select>` component that was forcing popup to be child of document as that was messing up z-index in many situations.
- Updated to allow overflow on FloatingWidgets so popups, like from `<Select>` would be properly shown.
=> Fix styling of number editor to properly fit into toolsettings

tools/internal/scripts/copyConfig.js
Since the move from imodeljs to itwinjs-core, developers who clone a new repo get (by default) a directory named "itwinjs-core".
copyConfig.js expects the repo to be in a directory named "imodeljs", with a sibling directory named "imodeljs-config", causing it to fail to locate the sibling directory and copy the config files.
Change it so it just looks in the parent directory of the repo root for the imodeljs-config directory.
=> Make copy-config script agnostic to imodeljs repo directory name.

common/api/core-geometry.api.md, common/changes/@itwin/core-geometry/treeshake-geom_2021-11-09-21-04.json, core/geometry/package.json, core/geometry/src/geometry3d/Point3dVector3d.ts, core/geometry/src/geometry3d/Ray3d.ts, core/geometry/src/test/geometry3d/Point3d.test.ts
Now that we're delivering ES modules, bundlers like webpack are able to do [tree-shaking](https://webpack.js.org/guides/tree-shaking/) to remove unused code.  The @itwin/core-geometry package ought to be a perfect candidate for tree-shaking, because it is large (>1MB minified), free of [side-effects](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free), and often times a consumer of core-geometry really only actually needs a few primitive types.
However, after explicitly marking @itwin/core-geometry as free of side-effects, some experimentation revealed that just importing `Point2d`, `Point3d`, `Range2d` into an extension still pulled more than 200KB from core-geometry into the bundle: 
After some investigation, it turns out that a lot of this can be eliminated …
=> Improve tree-shaking in core-geometry.

common/changes/@itwin/core-frontend/fix-sky-cube-buffers-bound_2021-11-11-12-54.json, core/frontend/src/render/webgl/CachedGeometry.ts, core/frontend/src/test/ExpectColors.ts, core/frontend/src/test/render/webgl/SkyRender.test.ts
Sky cubes were not rendering; now they will render properly.  The GL buffers were not bound when calling drawArrays for the cube primitive.  This must have worked previously as a side effect of some buffer being left bound which no longer happens.
This also adds a set of tests which verifies that skies render properly so this cannot happen again.
https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/741367
=> Fix sky cube rendering

common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-common/view-independent-transparency-override_2021-11-12-15-20.json, common/changes/@itwin/core-frontend/view-independent-transparency-override_2021-11-12-15-20.json, core/common/src/FeatureSymbology.ts, core/common/src/test/FeatureSymbology.test.ts, core/frontend/src/render/webgl/FeatureOverrides.ts, core/frontend/src/render/webgl/RenderCommands.ts, core/frontend/src/render/webgl/RenderFlags.ts, core/frontend/src/render/webgl/glsl/FeatureSymbology.ts, core/frontend/src/render/webgl/glsl/Surface.ts, full-stack-tests/core/src/frontend/standalone/Transparency.test.ts, test-apps/display-test-app/src/frontend/FeatureOverrides.ts
Today, if you override a feature's transparency it will only draw with transparency if the transparency ViewFlag is enabled and the render mode is wireframe or smooth.
That makes EmphasizeElements utterly useless, as the de-emphasized stuff doesn't actually get de-emphasized.
Also, Brien wants to draw elements or faces thereof as transparent during push-pull modeling operations, regardless of whether the view enables transparency.
We could have simply changed this behavior but SubCategoryOverrides from a display style are also applied using the same transparency override.
It would be silly to create a display style that overrides subcategory transparency but doesn't enable transparency, but very easy to accidentally create such a style by modifying an existing one.
So, this PR introduces …
=> View independent transparency override

common/changes/@itwin/components-react/components-react-property-grid-test_2021-11-17-16-16.json, ui/components-react/src/test/propertygrid/component/PropertyGrid.test.tsx
This PR fixes a test that used to produce `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.` log message during a test run.
The test sets up a property grid in the following configuration:
- Root1 category
- Child category
- Root2 category
It then used to attempt to click on Child header to expand its category *after* collapsing Root1 category, which is obviously an issue. 
This fix changes the order in which clicks are issued so that all three categories toggle their expansion state properly. It also gets rid of `flushAsyncOperations` and rewrites expectations to follow best testing practices.
=> UI: Fix PropertyGrid unit test producing a warning

common/api/appui-react.api.md, common/changes/@itwin/appui-react/presentation-remove_preloading_flag_2021-11-17-17-07.json, docs/changehistory/NextVersion.md, test-apps/ui-test-app/src/frontend/appui/widgets/VisibilityWidget.tsx, ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsTree.tsx
Removed deprecated ModelsTreeProps.enablePreloading flag.
=> Presentation: Remove ModelsTreeProps.enablePreloading flag 

test-apps/display-performance-test-app/src/backend/DefaultConfig.json
Changing line tests to use 200 views instead of 351, to stop crashing on firefox on mac.
=> Fixing default config file for firefox on mac

common/changes/@itwin/core-frontend/ui-about-box-styling_2021-11-18-14-10.json, core/frontend/src/IModelApp.ts, core/frontend/src/IModeljs-css.ts, core/frontend/src/Viewport.ts
Modify iModelJSLogoCard to
1. Use local CSS variables and classes to avoid having the styling changed by apps
2. Pass in the ownerDocument.body of the Viewport so that the card opens properly in a popped-out Viewport.
=> Fixes to iModelJSLogoCard

common/api/appui-react.api.md, common/changes/@itwin/appui-react/ui-filterOutDuplicatesFromItemsProviders_2021-11-18-14-31.json, ui/appui-react/src/appui-react/backstage/BackstageComposer.tsx, ui/appui-react/src/appui-react/shared/ToolItemDef.ts, ui/appui-react/src/appui-react/statusbar/StatusBarComposer.tsx, ui/appui-react/src/test/backstage/BackstageComposer.test.tsx, ui/appui-react/src/test/shared/Item.test.tsx, ui/appui-react/src/test/statusbar/StatusBarComposer.test.tsx, ui/appui-react/src/test/widget-panels/Frontstage.test.tsx
- Ensure duplicates items are ignored when gathering backstage, toolbar, status bar, and widget items from registered UiItemProviders.
- Fixed bug in ToolItemDef.getItemDefForTool where arguments meant for passing to tool's run method where not properly handled.
=> Filter out duplicates from UiItemsProviders

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-tile-content-keyin_2021-11-19-17-27.json, core/frontend/src/Tiles.ts, core/frontend/src/tile/TileAdmin.ts, test-apps/display-test-app/README.md, test-apps/display-test-app/public/locales/en/SVTTools.json, test-apps/display-test-app/src/frontend/App.ts, test-apps/display-test-app/src/frontend/TileContentTool.ts
I frequently need to debug the generation and/or deserialization of a specific tile.
Every time, I think about how much more efficient that process would be if I could simply key in `dta gen tile -modelId=0x123 -contentId=-whatever` to trigger generation of exactly that tile.
Well, now I finally can.
Incidentally makes `IModelConnection.tiles` iterable.
=> Keyin to generate tile content

full-stack-tests/backend/src/integration/BlockcacheManifest.test.ts
The upload command in this test doesn't actually return once the upload is complete. The upload command returns once the upload has been "dispatched". As a result, we don't actually know when the upload has been completed. Dan from SQLite will be rewriting some blockcache stuff which will hopefully get rid of this behavior and then we can revisit the test.
=> Skip Query Manifest test

common/changes/@itwin/map-layers/fix-map-layers_2021-11-23-19-46.json, common/config/rush/pnpm-lock.yaml, extensions/map-layers/package.json
This prevents the packages from currently being published.
=> fix the map-layers dependency list

common/config/azure-pipelines/jobs/ci-core.yaml, common/config/azure-pipelines/templates/integration-test-steps.yaml, common/config/azure-pipelines/templates/setup-integration-users.yaml
Our git checkout time on every build is around 25-30 seconds for a full checkout. With doing a clone of only depth 1 it goes down to ~15 seconds.
With ~200 PR triggers a week * 5 builds a PR * 10 second savings = ~167 minutes of build time spent git cloning we save a week.
Also, minor clean up on the variables used in the integration tests.
=> Build: clone repo with depth level 1

test-apps/ui-test-app/src/frontend/index.tsx, test-apps/ui-test-app/src/frontend/tools/AppUi2StageItemsProvider.tsx
Updates to remove setting UiStateStorage - it is not needed as it UiFramework defaults to using local storage.
Also fix AppUi2StageItemsProvider to properly check stageId.
=> Updates to remove setting UiStateStorage

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/fix-animated-root-node_2021-11-25-11-02.json, core/frontend/src/tile/DynamicIModelTile.ts, core/frontend/src/tile/IModelTile.ts, core/frontend/src/tile/IModelTileTree.ts, core/frontend/src/tile/ImdlReader.ts, full-stack-tests/core/src/frontend/standalone/tile/Disposable.test.ts, full-stack-tests/core/src/frontend/standalone/tile/TileIO.test.ts, test-apps/display-test-app/src/frontend/TileContentTool.ts
Previously we were always creating a branch for the root node, which is unnecessary and wasteful for non-animated tile trees.
This was detected by a TileIO test. The test was fixed by [this commit](9d7b8d9e595f6bcedb455e46bb674d18fab89397).
But that is also wrong: a tile containing one node in a tile tree containing transform nodes still needs to put that one node into a branch. This produced some image differences in the proj.ibim.animated.bim ImageTests data set.
Fix: Create a branch for the root node in the tile if and only if the tile tree contains transform nodes.
Forward to ImdlReader the flag indicating whether or not transform nodes are present.
Incidentally clean up the garbage pile of optional/default arguments to `ImdlReader.create`.
=> Fix regression in ImageTests animated test cases

core/frontend/src/tile/GltfReader.ts, docs/changehistory/NextVersion.md
Overlooked in #2787:
- If deduplication of vertices increases the number of points from below 64k to above 64k, we must allocate 32-bit indices.
- NextVersion.md
=> Wiremesh addenda

test-apps/display-test-app/README.md, test-apps/display-test-app/ios/backend.config.js
The native dependency on key tar is tripping up webpack and it's not needed for the iOS app, only valid for Electron.
=> [iOS] Update dta webpack to ignore the ElectronBackend setup

common/changes/@itwin/appui-react/deprecation-message_2021-11-29-14-56.json, common/changes/@itwin/core-react/deprecation-message_2021-11-29-14-56.json, ui/appui-react/src/appui-react/backstage/BackstageItemProps.tsx, ui/appui-react/src/appui-react/backstage/BackstageItemUtilities.ts, ui/appui-react/src/appui-react/shared/CustomItemProps.ts, ui/appui-react/src/appui-react/shared/ItemDefBase.ts, ui/appui-react/src/appui-react/shared/ItemProps.ts, ui/appui-react/src/appui-react/statusbar/StatusBarItemsManager.ts, ui/core-react/src/core-react/dialog/DialogButtonDef.ts, ui/core-react/src/core-react/messagebox/MessageSeverity.ts
Make deprecation messages consistent in UI packages (mainly to fix references to renamed bentley/appui-abstract).
=> Consistent deprecation messages.

common/changes/@itwin/ecschema-rpcinterface-tests/full-stack-oidcauthority_2021-12-02-16-27.json, common/changes/@itwin/rpcinterface-full-stack-tests/full-stack-oidcauthority_2021-12-02-16-27.json, full-stack-tests/ecschema-rpc-interface/src/common/Settings.ts, full-stack-tests/ecschema-rpc-interface/src/frontend/setup/TestContext.ts, full-stack-tests/rpc-interface/src/common/Settings.ts, full-stack-tests/rpc-interface/src/frontend/setup/TestContext.ts
RPC full stack tests would try to use non-existing dev-ims.bentley.com when testing in DEV (required by GPB)
=> add configurable auth URL to full stack tests

clients/reality-data/package.json, common/changes/@bentley/reality-data-client/oidc-signin-tool-version_2021-12-03-16-13.json, common/changes/@itwin/ecschema-rpcinterface-tests/oidc-signin-tool-version_2021-12-03-16-13.json, common/changes/@itwin/imodelhub-client-tests/oidc-signin-tool-version_2021-12-03-16-13.json, common/changes/@itwin/rpcinterface-full-stack-tests/oidc-signin-tool-version_2021-12-03-16-13.json, common/config/rush/pnpm-lock.yaml, example-code/app/package.json, example-code/snippets/package.json, full-stack-tests/backend/package.json, full-stack-tests/core/package.json, full-stack-tests/ecschema-rpc-interface/package.json, full-stack-tests/imodelhub-client/package.json, full-stack-tests/presentation/package.json, full-stack-tests/rpc-interface/package.json
NPM is not clever enough to figure out that `3.0.0-dev.110` satisfies `^3.0.0-dev.110`. Backends can't pull in rpcinterface-full-stack-tests for that reason.
=> use strict version of oidc-signin-tool

common/changes/@itwin/core-backend/gcs-interpret-test-fix_2021-12-05-18-10.json, core/backend/src/test/misc/GeoServices.test.ts
Reactivated GCS interpret test after fixing native.
Goes with PR: https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/211759
=> Gcs interpret test fix

common/changes/@itwin/presentation-backend/presentation-ruleset_variables_in_electron_2021-12-06-14-39.json, presentation/backend/src/presentation-backend/PresentationIpcHandler.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/test/PresentationIpcHandler.test.ts, presentation/backend/src/test/PresentationManager.test.ts
* Do not create unique ids for rulesets in IPC apps as it causes to lose variables for those rulesets.
* Parse variable json before setting it's value on a backend.
=> Presentation: fix ruleset variables storing in IPC apps

common/changes/@itwin/imodelhub-client-tests/imodelhub-tests-fix_2021-12-07-13-07.json, full-stack-tests/imodelhub-client/src/imodelhub/Checkpoint.test.ts
In this PR:
- Fixed the test setup logic to skip the Checkpoint test suite not only when no Checkpoints exist but also when the only Checkpoint that exists is a Baseline. This accommodates the new behavior in iModelHub service.
=> iModelHub full stack tests fix

test-apps/display-test-app/README.md, test-apps/display-test-app/public/locales/en/SVTTools.json, test-apps/display-test-app/src/backend/Backend.ts, test-apps/display-test-app/src/backend/WebMain.ts, test-apps/display-test-app/src/common/DtaConfiguration.ts, test-apps/display-test-app/src/common/DtaRpcInterface.ts, test-apps/display-test-app/src/frontend/App.ts, test-apps/display-test-app/src/frontend/DisplayTestApp.ts, test-apps/display-test-app/src/frontend/MacroTools.ts
Add a keyin macro capabililty to display-test-app, including a way to run a macro file at startup by setting an enviroment variable IMJS_STARTUP_MACRO=pathToMacroFile.
Besides being generally useful, this allows the overnight runs of ImageTests to have a reliable way to capture the shader usage.
https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/764411
=> Add macro capability to display-test-app

common/api/core-transformer.api.md, common/api/summary/core-transformer.exports.csv, common/changes/@itwin/core-transformer/transformer-filter-maintain-ids_2021-12-03-14-03.json, core/backend/src/IModelDb.ts, core/transformer/src/IModelImporter.ts, core/transformer/src/IModelTransformer.ts, core/transformer/src/test/standalone/IModelTransformer.test.ts
- add option to transformer to preserve element ids during transformations, valid during a pure-filter transform where no elements are added during the transformation
[imodel02 PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/211450)
=> add option to transformer to preserve element ids

common/changes/@itwin/core-common/set-ecef-location_2021-12-08-13-09.json, common/changes/@itwin/editor-backend/set-ecef-location_2021-12-08-13-09.json, common/changes/@itwin/editor-common/set-ecef-location_2021-12-08-13-09.json, core/common/src/IModel.ts, editor/backend/src/EditBuiltInCommand.ts, editor/common/src/EditorBuiltInIpc.ts
Require schema lock to save changes to project extents and ecef location file properties.
=> Fix for IModel._ecefTrans not being updated when setting IModel._ecefLocation.

full-stack-tests/core/src/frontend/standalone/ECSqlQuery.test.ts
Fails more often than it succeeds on macOS. Virtually every PR is now requiring multiple builds or force-merge. @khanaffan will fix.
=> Skip flaky test.

common/api/imodeljs-common.api.md, common/changes/@bentley/imodeljs-common/backport-fix-gradient-caching-2866_2021-12-09-14-38.json, common/changes/@bentley/imodeljs-frontend/backport-fix-gradient-caching-2866_2021-12-09-14-38.json, core/common/src/Gradient.ts, core/common/src/ThematicDisplay.ts, core/common/src/test/ThematicGradientSettings.test.ts, core/frontend/src/test/render/webgl/System.test.ts
This is a manual backport of 2.19.x-relevant portions of #2866.
This resolves issues brought up in this discussion thread: https://github.com/iTwin/itwinjs-core/discussions/2818
=> Backport fix gradient caching 2866

common/api/core-common.api.md, common/changes/@itwin/core-common/marc.bedard8-FixRealityDataSourceKey.toString_2021-12-09-14-53.json, common/changes/@itwin/core-frontend/marc.bedard8-FixRealityDataSourceKey.toString_2021-12-09-14-53.json, core/common/src/ContextRealityModel.ts, core/frontend/src/RealityDataSource.ts, core/frontend/src/test/RealityDataSouce.test.ts
RealityDataSourceKey namespace defines a method call toString(key: RealityDataSourceKey), this was call by mistake without any parameter.
This results to a call to default toString(). Prevent this confusion by renaming toString to convertToString(key: RealityDataSourceKey) and change call accordingly.
=> Fix convert RealityDataSourceKey to string

common/changes/@itwin/core-frontend/Fix-map-layer-collation-to-meshes_2021-12-10-14-43.json, core/frontend/src/render/webgl/RealityMesh.ts
Mesh primitives were generated incorrectly when collating the imagery textures.  The spurious primitives caused the tool tips to stop working.
=> Fix map layer collation to meshes

common/changes/@itwin/core-frontend/marc.bedard8-Remove_unnecessary_realityDataSourceList_2021-12-14-13-20.json, core/frontend/src/RealityDataSource.ts
We are keeping RealityDataSource created from key and a list so that every time the source is required it doesn't need to call the context share server.
This was causing several problem with state that change but list is not updated (see https://github.com/iTwin/itwinjs-core/pull/2882#issuecomment-992944899)
This optimization is not required any more since underlying code has been optimize to only use one RealityDataSource instead of calling create several time.
=> Remove optimization that keep RealityDataSource from key in a list.

test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts
display-performance-test-app lets you specify tile admin properties in the config file, but these were being totally overridden by recent changes so that they were ignored.
=> stop overriding tile admin props

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/apply-terrain-fallback_2021-12-10-12-40.json, core/frontend/src/public/locales/en/iModelJs.json, core/frontend/src/tile/map/CesiumTerrainProvider.ts, core/frontend/src/tile/map/MapTileTree.ts
This PR enables rendering of 2d map when terrain data is not available.
The user is notified about that via the notifications system.
=> Render 2d map when terrain data is not available

docs/bis/ec/ec-relationship-class.md
After adding tests and discussing with  @ColinKerr , we decided to update the inheritance rules and delete two which we don't enforce anyways, and which in reality are not followed.
=> Update ECRelationship inheritance rules docs

common/api/core-react.api.md, common/changes/@itwin/core-react/select-in-popup_2021-12-20-13-55.json, ui/core-react/src/core-react/popup/Popup.scss, ui/core-react/src/core-react/popup/Popup.tsx, ui/core-react/src/test/popup/Popup.test.tsx
Remove `transform` CSS property from a `Popup` after animation ends (by removing `animation-name`).
This fixes an issue where `Select` dropdown/menu is not visible when rendered in a `Popup` (by default `Select` uses fixed positioning, which doesn't work correctly when parent element has a CSS `transform` property applied).
=> Remove transform CSS property when animation ends.

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/gltf-fixes_2021-12-21-13-46.json, core/frontend/src/tile/B3dmReader.ts, core/frontend/src/tile/GltfReader.ts, core/frontend/src/tile/I3dmReader.ts
1. A RealityMeshPrimitive was always produced for textured meshes. Reality meshes don't support lighting, so these meshes appeared unlit despite having normals.
- Added a "vertex table required" flag to force creation of a lit mesh. readGltfGraphics() sets this flag. This remains a problem for 3d tilesets that want lighting though.
2. Some images and other data were not being loaded because `byteOffset` was omitted. This property is optional and defaults to zero.
3. Incidental cleanup related to the above.
=> Fix some oversights in GltfReader

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/fix-map-provider-listener_2021-12-21-16-25.json, core/frontend/src/Viewport.ts, core/frontend/src/test/Viewport.test.ts, core/frontend/src/tile/map/MapTiledGraphicsProvider.ts
Fix terrain bug described in #2608.
Given a Viewport `vp` with a display style that has enabled the background map but disabled terrain display:
```
vp.overrideDisplayStyle({ backgroundMap: { applyTerrain: true } });
```
...correctly displays 3d terrain.
The following:
```
const style = vp.,displayStyle.clone();
vp.displayStyle = style;
vp.overrideDisplayStyle({ backgroundMap: { applyTerrain: true } });
```
...fails to display 3d terrain - it displays a flat map.
The following:
```
const style = vp.displayStyle.clone();
vp.overrideDisplayStyle({ backgroundMap: { applyTerrain: true } });
vp.displayStyle = style;
```
...incorrectly displays 3d terrain - it should display a flat map, because `style` did not have terrain enabled.
The problem is that Viewport listens for the event dispatched …
=> Fix terrain when changing display style

common/api/presentation-common.api.md, common/api/summary/presentation-common.exports.csv, common/changes/@itwin/presentation-backend/presentation-avoid-repeating-requests_2021-12-17-14-51.json, common/changes/@itwin/presentation-common/presentation-avoid-repeating-requests_2021-12-17-14-51.json, common/changes/@itwin/presentation-testing/presentation-avoid-repeating-requests_2021-12-27-09-06.json, presentation/backend/src/presentation-backend/Presentation.ts, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/presentation-backend/TemporaryStorage.ts, presentation/backend/src/test/Presentation.test.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts, presentation/backend/src/test/TemporaryStorage.test.ts, presentation/common/src/presentation-common/PresentationRpcInterface.ts, presentation/common/src/presentation-common/RpcRequestsHandler.ts, presentation/common/src/test/RpcRequestsHandler.test.ts, presentation/testing/src/presentation-testing/Helpers.ts
Response of the initial request contains the most valuable diagnostics that may give answers to why the request took long in the first place. Throwing it away and repeating the request may return the result, but it loses valuable diagnostics data.
The change makes our RPC implementation store the response promises temporarily just to ensure we return the same promise if the request is repeated within 10 seconds window. If not, the behavior is as before - make a similar request to `PresentationManager`.
=> Presentation: Avoid making the same request to PresentationManager

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/fix-gltf-bugs_2022-01-03-15-46.json, core/frontend/src/render/primitives/Primitives.ts, core/frontend/src/test/tile/GltfReader.test.ts, core/frontend/src/tile/GltfReader.ts
Khronos supplies a wide variety of [sample glTF models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0) to test spec conformance. Our current implementation fails many of them.
Some of those failures we don't intend to rectify any time soon - e.g., PBR materials, animations, etc.
This PR addresses the following that are likely to affect iTwin.js users:
- BoxTextured: texture sampler shouldn't clamp to edge unless explicitly specified.
- UnlitTest: support the KHR_materials_unlit extension indicating the mesh should be displayed without lighting.
- AlphaBlendModeTest: support 8-bit vertex indices.
- AlphaBlendModeTest: render transparent IFF material explicitly requests alpha blending.
- Fox: manufacture vertex indices for non-indexed mesh vertices.
- Lantern: prefer …
=> Improve glTF spec conformance

common/changes/@itwin/core-backend/v2-download-log-improvement_2022-01-03-19-12.json, core/backend/src/CheckpointManager.ts
Incorrectly logged the id of the changeset downloaded if the requested version does not exist and a previous checkpoint exists
=> V2 download log improvement

common/api/appui-layout-react.api.md, common/api/summary/appui-layout-react.exports.csv, common/changes/@itwin/appui-layout-react/ui-widgetTabStyleUpdates_2022-01-04-21-23.json, test-apps/ui-test-app/src/frontend/tools/AppUi2StageItemsProvider.tsx, ui/appui-layout-react/src/appui-layout-react/widget/Tab.scss, ui/appui-layout-react/src/appui-layout-react/widget/Tab.tsx, ui/appui-layout-react/src/appui-layout-react/widget/Tabs.tsx, ui/appui-layout-react/src/appui-layout-react/widget/_variables.scss, ui/appui-layout-react/src/test/widget/Tab.test.tsx
- update styling to provide a slightly taller tab and a bit of padding at top for active stripe.
- adjust algorithim that determines if tabs should be rendered using icon only to allow single tabs to show both text and icon as long as possible. Still did not make it too fancy as supporting overflow changes the number of tabs being considered.
=> Widget tab style updates

common/changes/@itwin/core-common/web-ipc-fix_2022-01-06-15-45.json, core/common/src/ipc/IpcWebSocketTransport.ts
Since the process of reading IPC message data is async (in the browser), we can only store bookkeeping data about the incoming message sequence in local variables associated with the async call site.
=> Web IPC fix

common/config/rush/command-line.json, common/scripts/install-run-rush.js, common/scripts/install-run.js, rush.json
Move to the latest Rush version to pick up some fixes (referenced [here](https://github.com/microsoft/rushstack/issues/2418)) that should make life easier with the peer dependency hell introduced in #2912.
Updated pnpm to keep both up-to-date.
=> Update to latest Rush and pnpm versions

common/changes/@itwin/core-frontend/fix-animated-viewport-sync_2022-01-07-14-29.json, core/frontend/src/Viewport.ts, full-stack-tests/core/src/frontend/standalone/ViewportChangedEvents.test.ts
As described in #2999.
When we animate a frustum change in a Viewport, we first set the viewport's frustum to the *final* frustum, then invalidate its render plan. This causes renderFrame to be invoked on the next frame, which invokes the animator to set up the first stage of the frustum animation.
However if the viewport is synced with another viewport then the other viewport only sees the final frustum, until the animator is invoked, at which point it will see the intermediate frustum.
If the "source" viewport renders before the "target" viewport, this works fine, because the first viewport will invoke its animator, updating the second's frustum before it renders.
If the target viewport renders before the source viewport, it will render the *final* frustum on the first frame of the …
=> Fix flickering in TwoWayViewportSync

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/geo-maplayers_auth_refactor_2022-01-10-14-48.json, common/changes/@itwin/map-layers/geo-maplayers_auth_refactor_2022-01-10-14-48.json, core/frontend/src/core-frontend.ts, core/frontend/src/tile/internal.ts, core/frontend/src/tile/map/ArcGisUtilities.ts, core/frontend/src/tile/map/MapLayerAuthentication.ts, core/frontend/src/tile/map/MapLayerFormatRegistry.ts, core/frontend/src/tile/map/MapLayerImageryFormats.ts, core/frontend/src/tile/map/MapLayerImageryProvider.ts, core/frontend/src/tile/map/MapLayerSources.ts, extensions/map-layers/src/test/MapUrlDialog.test.tsx, extensions/map-layers/src/ui/widget/MapUrlDialog.tsx
No longer display username/password fields by default  in the custom map layers dialog:  If validation fails and reports authentication is needed, we then ask end-user for credentials.
=> Revisited the way map layers authentication is handled in the UI.

common/changes/@itwin/appui-layout-react/lock-itwinui-ver_2022-01-11-19-01.json, common/changes/@itwin/appui-react/lock-itwinui-ver_2022-01-11-19-01.json, common/changes/@itwin/components-react/lock-itwinui-ver_2022-01-11-19-01.json, common/changes/@itwin/core-react/lock-itwinui-ver_2022-01-11-19-01.json, common/changes/@itwin/imodel-components-react/lock-itwinui-ver_2022-01-11-19-01.json, common/changes/@itwin/map-layers/lock-itwinui-ver_2022-01-11-19-01.json, common/config/rush/pnpm-lock.yaml, extensions/map-layers/package.json, test-apps/presentation-test-app/package.json, test-apps/ui-items-providers-test/package.json, test-apps/ui-test-app/package.json, ui/appui-layout-react/package.json, ui/appui-react/package.json, ui/components-react/package.json, ui/core-react/package.json, ui/imodel-components-react/package.json
There was an update to iTwinUI-react that is breaking out build. Until we can resolve the issue, locking down to the last working version.
=> lock down itwinui-react version

core/frontend/src/tools/ViewTool.ts
I don't know why document.exitPointerLock is undefined when running on iOS, but this should prevent it from being called if it is undefined.
=> Fix unhandled exception on iOS when exitPointerLock is called.

common/api/presentation-frontend.api.md, common/changes/@itwin/presentation-frontend/presentation-empty-selection-set-after-clear-and-replace_2022-01-13-09-21.json, full-stack-tests/presentation/src/frontend/UnifiedSelection.test.ts, presentation/frontend/src/presentation-frontend/selection/HiliteSetProvider.ts, presentation/frontend/src/presentation-frontend/selection/SelectionManager.ts
We were caching the hilite set with guid of selection **after** retrieving the hilite set. If selection changed during the async request, we cached the result with GUID of the new selection. Then, if someone asked a hilite set for the new selection, we'd take whatever we have cached, which is not correct for the new selection.
=> Presentation: Empty selection set after clear and replace

common/config/azure-pipelines/templates/publish.yaml
The previousVer variable is not available to the determineDistTag function since it's only defined within the for loop. Instantiate the variable prior to the for loop like the other two variables.
Test build here: https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1250045&view=results
=> Fix the use of the previousVer variable

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/fix-readimage_2022-01-13-13-38.json, core/frontend/src/ImageUtil.ts, core/frontend/src/NoRenderApp.ts, core/frontend/src/SheetViewState.ts, core/frontend/src/Viewport.ts, core/frontend/src/render/RenderTarget.ts, core/frontend/src/render/webgl/Target.ts, core/frontend/src/test/ExpectColors.ts, core/frontend/src/test/Viewport.test.ts, core/frontend/src/test/openBlankViewport.ts, core/frontend/src/test/render/webgl/Decorations.test.ts, docs/changehistory/NextVersion.md, full-stack-tests/core/src/frontend/TestViewport.ts, full-stack-tests/core/src/frontend/standalone/RenderTarget.test.ts, test-apps/display-test-app/src/frontend/Viewer.ts
[Viewport.readImage](https://www.itwinjs.org/reference/imodeljs-frontend/views/viewport/readimage/) is broken:
- If you supply a capture rect smaller than the view rect, it will capture the wrong area due to confusion between ViewRect's origin at top-left and WebGL's origin at bottom-left.
- If you request a resized image it won't preserve background transparency.
It's also confusing and awkward:
- By default, it returns an upside-down image; the caller must explicitly request it to be flipped right-side-up.
- It takes special sigil values like "size = (0, 0) | undefined" to indicate no resizing and "rect = (0, 0, -1, -1) | undefined" to indicate the full image should be captured.
The lack of complaints about these issues suggests few people are relying on this suboptimal behavior …
=> Replace Viewport.readImage

tools/internal/scripts/rush/audit.js
The new audit error is with a dev dependency of our build-tools package for typedoc. @williamkbentley is look into it and hopefully will have a fix soon. In the meantime, ignore the audit issue to allow PRs.
=> temporarily skip a new audit error

tools/internal/scripts/rush/audit.js
The current audit failure is due to one of our localization dependencies. We'll follow up with a fix to the dependency but for now ignore to unblock the CI build.
=> Temporarily add node-fetch audit to excluded advisories list

common/api/linear-referencing-backend.api.md, common/changes/@itwin/linear-referencing-backend/reinstate-linearly-located-base-impl_2022-01-25-12-07.json, domains/linear-referencing/backend/src/LinearReferencingElements.ts
#3052 erroneously removed "implements LinearlyLocatedBase" when removing implementations of ElementProps.
This has no functional impact but explicit interface implementations provide better type-checking and clear documentation.
=> Reinstate implementations of LinearlyLocatedBase.

common/changes/@itwin/editor-frontend/accudraw-smart-rotation_2022-01-25-13-24.json, editor/frontend/src/SketchTools.ts
Simple change to allow ctrl+data to orient AccuDraw from snap even when not continuing an existing open path.
=> Make it easier to sketch on faces of solids.

common/api/core-common.api.md, common/changes/@itwin/core-backend/web-ipc-reload-fix_2022-01-25-15-56.json, common/changes/@itwin/core-common/web-ipc-reload-fix_2022-01-25-15-56.json, common/changes/@itwin/core-frontend/web-ipc-reload-fix_2022-01-25-15-56.json, core/backend/src/LocalhostIpcHost.ts, core/common/src/ipc/IpcWebSocket.ts, core/common/src/ipc/IpcWebSocketTransport.ts, core/frontend/src/LocalhostIpcApp.ts
The bookeeping necessary for tracking the sequence of IPC messages must be connection-specific, not global.
Otherwise, issues will arise like a new frontend (after reload) expecting message 0 but the backend sending whatever message number it was on with the previous (before reload) frontend session.
=> Web IPC fix (support for reloading frontend).

common/changes/@itwin/build-tools/packageroot-on-docs_2022-01-26-22-19.json, tools/build/scripts/docs.js, tools/build/scripts/utils/addSourceDir.js
- Adds the root directory of the package to the Typedoc output
- This is needed for the "Defined In" links on API reference pages
- The data currently in Typedoc output is sometimes relative to repo's root and other times relative to package root. Likely due to Typedoc's file discovery algorithm.
=> Add packageRoot directory to Typedoc output

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/reinstate-margin-options_2022-02-02-13-06.json, core/frontend/src/Viewport.ts, core/frontend/src/tools/ViewTool.ts
#2233 extracted `MarginOptions` from `ViewChangeOptions` rendering several functions like `Viewport.zoomToElements` to produce compilation errors in previously-valid code that attempts to specify a margin in those options.
The options are eventually forwarded to functions like `ViewState.lookAtVolume` that do accept a `MarginOptions` so without the compiler's interference they would still respect the margin.
Adjust function signatures to reflect this.
=> Reinstate margin option for functions that fit a view to a volume

common/changes/@itwin/core-frontend/dta-save-image_2022-02-02-15-26.json, core/frontend/src/ImageUtil.ts, test-apps/display-test-app/README.md, test-apps/display-test-app/src/frontend/App.ts, test-apps/display-test-app/src/frontend/SaveImageTool.ts, test-apps/display-test-app/src/frontend/Viewer.ts
`dta save image` stopped working in electron a while ago (it is supposed to display the captured image in a new window, but was displaying a blank window instead). Fix that.
Add option to copy image directly to clipboard.
Add option to specify image dimensions. If none specified, capture at full size.
This is extraordinarily useful for capturing images for comparison with ImageDiffs and for creating snapshots for documentation etc.
=> Enhance SaveImageTool

common/changes/@itwin/frontend-devtools/recursive-geometry-summary_2022-02-03-11-31.json, core/frontend-devtools/README.md, core/frontend-devtools/src/tools/InspectElementTool.ts
I find myself debugging elements with hundreds or thousands of part references in their geometry streams.
`fdt inspect element e=1` will include a summary of each part's geometry in the output.
=> InspectElementTool optionally also reports on part references' geometry.

core/frontend/src/quantity-formatting/QuantityFormatter.ts, test-apps/ui-test-app/src/frontend/index.tsx
@christophermlawson - Chris here is an update we need to be able to reset to BasicUnitsProvider for both BlankIModelConnections and IModelConnections that may not have a units schema... of which I have several.
=> provide way to reset to basic units provider

common/api/core-backend.api.md, core/backend/src/ClassRegistry.ts, core/backend/src/Entity.ts, core/backend/src/test/assets/TestGeneratedClasses.ecschema.xml, core/backend/src/test/schema/ClassRegistry.test.ts
- the previous method of getting the super class of `this` causes infinite recursion in deep class hierarchies. Instead, reference the super class's method directly so the call propagates up the prototype chain.
- because users may choose to not manually register a class in a hierarchy where they do manually register other classes, do not automatically implement `collectPredecessorIds` for generated classes that have a non-BisCore, manually-registered ancestor. This leaves the responsibility to the implementer to make sure they report all necessary predecessors. 
When a user registers custom javascript classes for some schema, but "skips" implementing one class, (for example having A superclasses B superclasses C in the schema, and registering custom classes for A and C but leaving B …
=> fix super call in automatic collectPredecessorIds impl and make stricter conditions for auto-implementing collectPredecessorIds

.devcontainer/Dockerfile
The version of Git packaged with Debian 10 (2.20.1) is too old for the
current version of Rush (which requires at least 2.30.0).
=> Update devcontainer base to Debian 11

common/config/rush/pnpm-lock.yaml, test-apps/display-performance-test-app/src/backend/backend.ts, test-apps/display-test-app/src/backend/Backend.ts, test-apps/presentation-test-app/src/backend/electron/ElectronMain.ts, test-apps/ui-test-app/package.json, test-apps/ui-test-app/src/backend/electron/ElectronMain.ts, test-apps/ui-test-app/src/backend/main.ts, test-apps/ui-test-app/tsconfig.json
With a recent change to the Electron auth client to not allow an empty string to be provided as a client id, fix the test apps to only setup Electron auth if the configuration exists.
=> fix the setup of the test-apps in a disconnected workflow

common/changes/@itwin/core-react/core-react-checkbox-workaround_2022-02-02-10-47.json, ui/core-react/src/core-react/tree/Node.tsx, ui/core-react/src/test/tree/Node.test.tsx
[Details regarding the Checkbox bug](https://github.com/iTwin/iTwinUI-react/issues/533)
The bug affects all iTwin.js versions starting from 3.0.0-dev.4. 
Once the bug is fixed on the iTwinUI-react side, this workaround should be removed.
=> UI: Apply workaround to TreeNode for iTwinUI-react Checkbox bug

common/changes/@itwin/core-frontend/pnts-spec-conformance_2022-02-10-10-58.json, core/frontend/src/tile/PntsReader.ts
@RBBentley's initial implementation required quantized positions; the point cloud to be used in our upcoming hackathon contains unquantized positions so fails to load.
Also, that implementation requires RGB colors or else makes all points white; the spec permits other color formats, including a constant color for all points.
[Specification](https://docs.opengeospatial.org/cs/18-053r2/18-053r2.html#199)
[JSON schema](https://github.com/CesiumGS/3d-tiles/blob/main/specification/schema/pnts.featureTable.schema.json)
TODO in future: we currently ignore alpha channel.
=> Implement pnts 3d tile spec

test-apps/display-performance-test-app/src/backend/backend.ts
Dunno why tsc doesn't complain that `authClient` may be undefined, even when I explicitly type it as potentially undefined.
=> Fix dpta signin when env vars undefined.

common/api/components-react.api.md, common/api/summary/components-react.exports.csv, common/changes/@itwin/appui-react/ui-fixAutoHideOfToolPanels_2022-02-11-20-21.json, common/changes/@itwin/components-react/ui-fixAutoHideOfToolPanels_2022-02-11-20-21.json, ui/appui-react/src/appui-react.ts, ui/appui-react/src/appui-react/hooks/useUiVisibility.tsx, ui/appui-react/src/appui-react/uiprovider/DefaultDialogGridContainer.scss, ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx, ui/appui-react/src/appui-react/widgets/BasicNavigationWidget.tsx, ui/appui-react/src/appui-react/widgets/BasicToolWidget.tsx, ui/appui-react/src/appui-react/widgets/ContentToolWidgetComposer.tsx, ui/appui-react/src/appui-react/widgets/ViewToolWidgetComposer.tsx, ui/components-react/src/components-react/toolbar/Overflow.scss, ui/components-react/src/components-react/toolbar/Overflow.tsx, ui/components-react/src/components-react/toolbar/PopupItem.scss, ui/components-react/src/components-react/toolbar/PopupItem.tsx, ui/components-react/src/components-react/toolbar/ToolbarWithOverflow.tsx, ui/components-react/src/test/toolbar/ToolbarWithOverflow.test.tsx
When the tool widgets are hidden automatically because of inactivity, any open popups were left visible. Add a React context to monitor the status of the parent tool widgets and hide popups with them.
=> Autohide popups from the toolbar

common/changes/@itwin/core-frontend/imodelapp-debugger_2022-02-15-15-34.json, core/frontend/src/IModelApp.ts, core/frontend/src/test/IModelApp.test.ts
Prevent users from having access to IModelApp via the console in production apps by default. Should still be possible for apps to add it on the window on their end if they choose to, but not recommended.
=> only expose IModelAppForDebugger in development

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/spatial-view-attachment-clip-transform_2022-02-16-19-58.json, core/frontend/src/DrawingViewState.ts, core/frontend/src/SheetViewState.ts, core/frontend/src/ViewState.ts, core/frontend/src/Viewport.ts
For some reason, we have always defined clip volumes in world coordinates. That seems like a poor (and probably unintentional) choice - really, a clip associated with a node in the scene graph should be defined in that node's coordinate space.
When we display a spatial view within a section drawing view, we transform the spatial view's clip into drawing (world) coordinates.
When we display that section drawing view as a view attachment on a sheet, the clip remains in drawing space - but it needs to be in sheet (world) coordinates.
There were two options for fixing this:
- Rectify the mistake of always defining clips in world coordinates. Far too error-prone and disruptive.
- Allow the sheet view to tell the drawing view how to transform the clip to world coordinates.
The latter is …
=> Transform spatial view attachment's clip from drawing to sheet.

test-apps/display-performance-test-app/src/frontend/TestRunner.ts
Revit connector has begun including colons in their view names.
display-performance-test-app creates filenames from iModel and view names.
Replace illegal characters with hyphens.
=> Do not produce illegal filenames on windows.

common/config/azure-pipelines/integration-pr-validation.yaml, common/config/azure-pipelines/integration-validation.yaml, common/config/azure-pipelines/jobs/fast-ci.yaml, common/config/azure-pipelines/templates/integration-test-steps.yaml
This PR splits the full set of integration tests out of the PR validation build and sets up a set a new pipeline to run our integration test on all supported operating systems and node versions on a weekly schedule (currently set to run every Sunday at midnight).
This also enables autocancel on our integration and core builds, which will cancel and replace an ongoing PR build if a new commit is pushed to a PR branch.
=> Run integration tests on all platforms

common/changes/@itwin/core-frontend/frontend-missing-localization-namespace_2022-02-08-00-00.json, core/frontend/src/AccuSnap.ts, core/frontend/src/IModelApp.ts, core/frontend/src/ViewState.ts, core/frontend/src/tile/map/CesiumTerrainProvider.ts, core/frontend/src/tools/ViewTool.ts
The 'iModelJs' namespace was missing in some calls to getLocalizedString in core-frontend. This resulted in untranslated strings in Design Review.
=> Supply missing 'iModelJs' namespace in some calls to getLocalizedString

tools/internal/scripts/rush/audit.js
Build is failing due to https://github.com/advisories/GHSA-rqff-837h-mm52. This is a deeply nested dependency to something used in one of our test apps, suppress the failure to allow the build to pass.
=> Suppress npm audit failure 

common/changes/@itwin/webgl-compatibility/workaround-mali-gp7-mp20-bug_2022-02-18-11-45.json, core/webgl-compatibility/src/Capabilities.ts
Apply same workaround as for iOS >= 15 from #2552.
In future, we need to investigate whether this is truly a driver bug or a deficiency in our renderer.
=> Transparency+shadows workaround for Galaxy Note 8

common/changes/@itwin/appui-react/fix-categories-trees_2022-02-22-20-47.json, common/changes/@itwin/core-frontend/fix-categories-trees_2022-02-22-20-47.json, core/frontend/src/CategorySelectorState.ts, ui/appui-react/src/appui-react/imodel-components/category-tree/CategoryVisibilityHandler.tsx, ui/appui-react/src/test/imodel-components/category-tree/CategoriesTree.test.tsx
Categories Tree has been broken in 3.0 due to the breaking change wrt [ecsql query row format](https://www.itwinjs.org/changehistory/#changes-to-ecsql-apis)
=> react to breaking change in 3.0 wrt ecsql query row format

common/api/core-transformer.api.md, common/api/summary/core-transformer.exports.csv, common/changes/@itwin/core-backend/inline-geom-part-refs_2022-02-24-22-06.json, common/changes/@itwin/core-common/inline-geom-part-refs_2022-02-24-22-06.json, common/changes/@itwin/core-transformer/inline-geom-part-refs_2022-02-24-22-06.json, core/backend/src/test/standalone/InlineGeometryPartReferences.test.ts, core/common/src/geometry/GeometryStream.ts, core/transformer/src/IModelImporter.ts, core/transformer/src/IModelTransformer.ts, docs/changehistory/NextVersion.md
Some connectors produce many geometry parts that are referenced only once, as do some transformation workflows. This is inefficient for tile generation and data representation - more often than not, these parts don't really mean anything.
Add an optional post-process step to IModelTransformer to identify these parts. For each, embed the part's geometry stream directly into the referencing element's geometry stream, then delete the part.
In future we may find additional criteria for identifying parts that should be inlined, in which case we can add options. e.g., if the part geometry is so trivial that it would be cheaper to embed regardless of number of references (e.g., we've seen geometry parts consisting of a single point or triangle).
Incidentally fix some bugs in …
=> IModelTransformer optionally embeds and deletes single-reference geometry parts

common/changes/@itwin/core-geometry/fix-geom-barrel_2022-02-25-23-37.json, core/geometry/package.json
Optimized builds of display-test-app are currently broken with a runtime error `Cannot access 'CurveCollection_CurveChain' before initialization`, which seems to be caused by the following circular dependency: 
> `CurveChain` _uses_ `LineString3d` _which uses_ `OffsetOptions` _which uses_ `Loop` _which extends_ `CurveChain`
This is actually even reproducible in node without webpack:
```js
import { CurveChain } from "@itwin/core-geometry/lib/cjs/curve/CurveCollection";
abstract class X extends CurveChain {} // throws TypeError: Class extends value undefined is not a constructor or null
```
However, as you can probably tell from that example, the ordering of imports in the core-geometry barrel file manages to avoid that error, my guess is by (indirectly) importing `LineString3d` before …
=> Fix import ordering in core-geometry

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/idle-tool-type_2022-02-28-10-41.json, core/frontend/src/tools/ToolAdmin.ts, docs/learning/frontend/Tools.md
As discussed in #3246. `IdleTool` is structurally identical to `InteractiveTool`; the current typing leads users to believe they must subclass and manually override all of IdleTool's behavior if they want to replace the default idle tool.
=> Change the type of ToolAdmin.idleTool from IdleTool to InteractiveTool

common/changes/@itwin/appui-react/presentation-models-tree-search-ruleset-change_2022-02-28-08-02.json, test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.ModelsTree-Search.PresentationRuleSet.json, ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsTreeSearch.json
Use `bis.Element` instead of `bis.GeometricElement3d` elements for filtering-out `bis.GeometricModel3d` models that have no elements. The models should contain only geometric elements anyway, and filtering by `Element` is quicker as it doesn't require joining the geometric elements' table.
=> Presentation: Optimize ModelsTree search ruleset

common/config/rush/.pnpmfile.cjs, common/config/rush/pnpm-lock.yaml
update the pnpmfile.cjs, so all external pkgs to the repo which have dependencies found in this one all resolve to the same pkg. 
previously youd have another instance of core-{bentley, geometry, frontend} in your tree
=> update the pnpmfile.cjs

common/api/components-react.api.md, common/changes/@itwin/components-react/ui-property-grid_2022-03-01-16-01.json, ui/components-react/src/components-react/propertygrid/internal/flat-items/FlatGridItem.ts, ui/components-react/src/components-react/propertygrid/internal/flat-items/MutableFlatGridItem.ts, ui/components-react/src/components-react/propertygrid/internal/flat-items/MutableGridCategory.ts, ui/components-react/src/test/propertygrid/component/internal/flat-items/GridCategory.test.ts, ui/components-react/src/test/propertygrid/component/internal/flat-items/MutableCustomGridCategory.test.ts
`getChildCategories` and `getDescendantCategoriesAndSelf` methods make use of duplicated state and do not play well with [immer](https://github.com/immerjs/immer). Attempting to mutate the returned arrays will leave `IMutableGridCategoryItem` in an invalid, partially updated state.
=> UI: Deprecate broken `IMutableGridCategoryItem` methods

common/api/core-frontend.api.md, common/changes/@itwin/core-backend/reimplement-get-view-thumbnail_2022-03-07-17-37.json, common/changes/@itwin/core-frontend/reimplement-get-view-thumbnail_2022-03-07-17-37.json, common/changes/@itwin/rpcinterface-full-stack-tests/reimplement-get-view-thumbnail_2022-03-07-17-37.json, core/backend/src/rpc-impl/IModelReadRpcImpl.ts, core/frontend/src/IModelConnection.ts, full-stack-tests/core/src/frontend/standalone/ModelState.test.ts, full-stack-tests/rpc-interface/src/frontend/IModelConnection.test.ts
More or less reverts #3138.
That PR made getViewThumbnail always throw. It should instead attempt to obtain and return the thumbnail, only throwing if no thumbnail exists.
=> Reimplement deprecated getViewThumbnail function to resolve regression

common/changes/@bentley/build-tools/ignore-webpack-audit-err_2022-03-07-15-23.json, tools/build/scripts/rush/audit.js
The url-parse error is an additional audit error for a previously reported url-parse. Both issues are due to the dependencies on webpack-dev-server
=> Add the additional url-parse to the list of audit exceptions

common/changes/@itwin/map-layers/geo-fix_outsideclick_handling_2022-03-07-21-03.json, extensions/map-layers/src/ui/widget/AttachLayerPopupButton.tsx, extensions/map-layers/src/ui/widget/MapUrlDialog.tsx
When the 'Add Layer' button is clicked, it triggers the display of the `AttachLayerPanel` like this:
By design, is you click anywhere outside the panel, that will close the panel.
When the 'New' button of the  `AttachLayerPanel` is clicked, a new custom layer maplayer definition (modal) dialog appears:
When this modal dialog is active, we don't want click event to be handled, otherwise that would result in the closure of  `AttachLayerPanel` and ultimately the modal dialog itself.  So 'click' events should be ignored as long as there is a modal dialog opened on top of the `AttachLayerPanel'.  We used to examine the target element (and all of his ancestry) of the click event to determine if the element clicked was part of a modal dialog.  
Turn out, this approach is incorrect in some …
=> Fixed issue that would close the new maplayer dialog when a new layer type was picked.

common/changes/@itwin/core-frontend/geo-validateEsriMapService_2022-03-08-20-15.json, core/frontend/src/tile/map/ArcGisUtilities.ts
The actual implementation of ESRI service supports request of type 'Map'.  If a service only support feature requests, map layer will be added successfully but further tile requests will fail.
=> Improved validation of ESRI services before adding map layer

test-apps/display-test-app/src/frontend/IdPicker.ts
Due to limit in # of categories on query (1,000), some categories were getting turned off on larger models when recalling a saved view (8,000+ categories) so I just removed the limit.
=> Remove limit for categories query in display-test-app

common/api/core-common.api.md, common/changes/@itwin/core-common/pmc-fix-background-map-ui_2022-03-11-22-25.json, common/changes/@itwin/core-frontend/pmc-fix-background-map-ui_2022-03-11-22-25.json, core/common/src/BackgroundMapProvider.ts, core/frontend/src/DisplayStyleState.ts
It claims to preserve existing values for any properties not explicitly specified, but recently stopped doing so.
=> Fix DisplayStyleState.changeBackgroundMapProvider

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/briefcase-active-settings_2022-03-11-11-43.json, common/changes/@itwin/editor-frontend/briefcase-active-settings_2022-03-11-11-43.json, core/frontend/src/BriefcaseConnection.ts, core/frontend/src/tools/PrimitiveTool.ts, core/frontend/src/tools/ToolAdmin.ts, editor/frontend/src/CreateElementTool.ts, editor/frontend/src/SketchTools.ts, test-apps/display-test-app/src/frontend/EditingTools.ts, test-apps/display-test-app/src/frontend/IdPicker.ts, test-apps/display-test-app/src/frontend/Viewer.ts, test-apps/ui-test-app/src/frontend/api/ActiveSettingsManager.ts, test-apps/ui-test-app/src/frontend/appui/widgets/editing/ActiveSettingsWidget.tsx
Previously ToolAdmin.activeSettings specified the default model and category for use by placement tools, but those Ids are specific to an iModel.
Conceivably apps could contain multiple viewports in which editing tools can be used, but more realistically leftover Ids might remain when switching between iModels producing surprising results.
Moved the settings to BriefcaseConnection. Added events to notify when they change.
Note these settings are only defaults; more specialized tools will have their own logic for determining category and model.
=> BriefcaseConnection.activeSettings

docs/presentation/index.md
Some tiles in https://www.itwinjs.org/presentation/ link to specific rule/specification rather than category index. For example the "Content" tile should link to https://www.itwinjs.org/presentation/content/, but links to https://www.itwinjs.org/presentation/content/contentinstancesofspecificclasses/
=> Presentation: Fix tile links in the documentation index page

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/tcobbs-bentley-image-cross-origin_2022-03-18-21-58.json, core/frontend/src/ImageUtil.ts
Update imageElementFromUrl and tryImageElementFromUrl to have a new optional parameter (default false) that when set to true will skip the cross origin check when loading the image.
Note: we are using this in a mobile app that uses a custom URL scheme to load images from the local device, and this fails the cross origin check.
=> Add the ability to skip the cross origin check

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/markschlosser-fix-fbo-resize-errors_2022-03-28-14-00.json, core/frontend/src/Viewport.ts, core/frontend/src/render/webgl/Target.ts, core/frontend/src/test/ViewManager.test.ts
This PR resolves a problem that can happen when viewports are resized after quickly dropping and adding them.
When a viewport is quickly dropped and added, an internal render-to-screen optimization gets toggled off and on.
The function that does this toggling updates the internally-tracked view rectangle in case of resize.  However, it does not then recreate the WebGL framebuffers with the new dimensions, causing this error to occur.
Work items: [here](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/534091) and [here](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/847343) and [here](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/824046)
Repro steps of the fixed issue:
1. Have display-test-app maximized with a file open …
=> Fix framebuffer resize issue that causes WebGL errors

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/geo-wms_111_2022-03-30-19-08.json, core/frontend/src/test/public/assets/wms_capabilities/mapproxy_111.xml, core/frontend/src/test/public/assets/wms_capabilities/mapproxy_130.xml, core/frontend/src/test/tile/map/MapLayerImageryProvider.test.ts, core/frontend/src/test/tile/map/WmsCapabilities.test.ts, core/frontend/src/tile/map/ImageryProviders/WmsMapLayerImageryProvider.ts, core/frontend/src/tile/map/WmsCapabilities.ts
Improved the support for WMS 1.1.1 servers.
**Three main changes:**
1. In 1.1.1 and prior, 'SRS' must be used instead of 'CRS'. This is applicable for the following 2 cases:
a. GetMap request parameter
b. When reading the GetCapabilities response, the JSON contains the 'SRS' key instead of 'CRS'
2. The axis order in 1.1.1 is always x/longitude y/latitude.  In 1.3.0 it depends on the coord. sys. definition, for EPSG:4326, it must be x/latitude y/longitude. 
3. The cursor position parameters passed to the 'GetFeatureInfo' request must be i/j for 1.3.0 and x/y for 1.1.1.
=> Improve support for WMS  server 1.1.1

common/changes/@itwin/core-frontend/pmc-rerender-on-selection-set-change_2022-03-31-11-35.json, core/frontend/src/ViewManager.ts, full-stack-tests/presentation/package.json, full-stack-tests/presentation/src/IntegrationTests.ts
Eliminate delay between calling, e.g., `iModel.hilited.clear()` and seeing the viewport update.
=> Request next animation frame when selection set changes

common/changes/@itwin/core-frontend/pmc-unquantized-webgl-1_2022-03-31-17-34.json, core/frontend/src/render/webgl/glsl/Vertex.ts
#3445 was failing to increment texture coordinates when reading unquantized vertex data in WebGL 1.
=> Fix unquantized vertex read for WebGL 1.

common/changes/@itwin/core-frontend/reality-tile-priority-on-target-center_2022-04-01-14-54.json, core/frontend/src/tile/RealityTileLoader.ts
Prior to this pull request, tile priority calculation was using the point on screen at coordinates (0.5, 0.5) to load in priority tiles close to the center of the screen.
This change uses the last zoom location as center instead of (0.5, 0.5) when possible. This point being more likely the focus of the user attention, it makes sense to prioritize tiles around it.
=> Reality tile priority on zoom target

common/api/presentation-backend.api.md, common/api/summary/presentation-backend.exports.csv, common/changes/@itwin/presentation-backend/presentation-schemas_preloading_on_initialize_2022-04-04-14-56.json, presentation/backend/src/presentation-backend/Presentation.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/test/Presentation.test.ts, presentation/backend/src/test/PresentationManager.test.ts
Add listener for `BriefcaseDb.onOpened` from `Presentation.initialize` instead of `PresentationManager` constructor because there might be no `PresentationManager` created when `BriefcaseDb` is opened.
=> Presentation: Initialize schemas preloading on Presentation.initialize

docs/changehistory/NextVersion.md, full-stack-tests/presentation/src/frontend/Hierarchies.test.snap, full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
Adjusted NextVersion.md to match fixed child specifications handling. 
Related [native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/239921)
=> Presentation: Get correct child specifications

common/changes/@itwin/core-frontend/markschlosser-fix-drop-add-viewport-bug_2022-04-05-19-06.json, core/frontend/src/render/webgl/Target.ts, core/frontend/src/test/ViewManager.test.ts
Dropping and immediately re-adding an unresized viewport to the view manager would result in a black rendering until the viewport was manually resized. This happened because when the viewport was removed it would have a 0,0 dimension, which was internally recorded (but not acted upon with regard to framebuffers). Once re-adding the viewport, it would be flagged as having a size change because its dimensions were no longer 0 (they became the original dimensions). Disposing and recreating the framebuffers with the same dimensions as the previous framebuffers caused the black rendering in the particular case of re-adding the viewport.
We resolve this problem by adding a check to not record a dimension change if the new dimensions are 0 -- we really do not want to create framebuffers with …
=> Fix blank rendering when dropping and immediately re-adding the same viewport

common/api/core-mobile.api.md, common/changes/@itwin/core-frontend/restore-mobile-auth_2022-04-06-18-12.json, common/changes/@itwin/core-mobile/master_2022-04-05-18-49.json, core/frontend/src/test/ToolRegistry.test.ts, core/mobile/src/backend/MobileHost.ts
This logic was stripped out of core/mobile prematurely, and we didn't have a replacement API in place to restore functionality to mobile applications. This resulted in some difficult workarounds in mobile-samples. It can be removed again when auth is addressed more comprehensively in 3.2
=> Restore Mobile Authorization

common/api/webgl-compatibility.api.md, common/changes/@itwin/webgl-compatibility/markschlosser-fix-msaa-hang-malig71-malig76_2022-04-08-13-29.json, core/webgl-compatibility/src/Capabilities.ts, core/webgl-compatibility/src/RenderCompatibility.ts, core/webgl-compatibility/src/test/Compatibility.test.ts
This PR resolves the behavior observed in [this work item](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/860321).
If MSAA was applied, it could hang certain mobile GPUs.  This problem was observed to affect certain mobile Mali chipsets (G71 and G76).
The workaround for this bug means MSAA cannot be enabled on those devices.
A new entry to `GraphicsDriverBugs` titled `msaaWillHang` was added.
=> Fix MSAA hang for Mali-G71 and Mali-G76 GPUs

common/api/webgl-compatibility.api.md, common/changes/@bentley/imodeljs-frontend/backport-tex-limit_2022-04-07-20-37.json, common/changes/@bentley/webgl-compatibility/backport-tex-limit_2022-04-07-20-37.json, core/frontend/src/render/webgl/Texture.ts, core/webgl-compatibility/src/Capabilities.ts
Partial backport of [#2244](https://github.com/iTwin/itwinjs-core/pull/2244).
This resolves [a bug on iOS for 2.19](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/861470).  On 3.0, iTwin.js enforces a limit of 4096 for textures.  On 2.19, this is not the case.
This can cause canvas draws to fail on iOS -- iOS has a 4096x4096 canvas limit.
=> Partial backport of texture size limit from Fix large textures (partial bp #2244)

common/config/rush/pnpm-lock.yaml
2.19.x builds are hitting rush audit failure due to https://github.com/advisories/GHSA-8hfj-j24r-96c4. Regenerating pnpm-lock to pull in fixed version of "moment" dependency.
=> Fix rush audit failure in azurite subdependency

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/touch-zoom-fixes_2022-04-08-11-24.json, core/frontend/src/tools/ViewTool.ts
Fixes two issues:
1. When pinch gesture is fast, view zooms, pans and sometimes jumps back to initial zoom level.
* If only the last processed touch drag event contained zoom, inertia was not reset, causing an unnecessary animated pan after touches ended. The change removes inertia as soon as zoom is detected.
1. When multiple pinches are done by lifting only one finger, zoom level jumps when starting subsequent pinches.
* If there was no drag events between lifting one finger and setting it down at another place, the gesture start position was not reinitialized. The change reinitializes start position as soon as any new touch happens (and therefore touches count changes) instead of waiting for a drag event.
=> Fix jumpy view zoom on touch devices

tools/internal/scripts/rush/audit.js
@bentley/react-scripts has a dependency on fast-sass-loader 2.0.1, which is the latest version and was released 6 months ago. Fast-sass-loader has a dependency on the async package "^2.x.x", but the async vulnerability is fixed in major version 3.
Here is the failing line from rush audit:
##[error]HIGH Security Vulnerability: Prototype Pollution in async in async (from ..__..__test-apps__display-performance-test-app>@bentley/react-scripts>fast-sass-loader>async).  See https://github.com/advisories/GHSA-fwr7-v2mv-hh25 for more info.
Here is the fast-sass-loader package (Latest release 2.0.1): https://www.npmjs.com/package/fast-sass-loader
And here is a screenshot of what fast-sass-loader requires
=> Exclude advisory for async package introduced by fast-sass-loader

test-apps/presentation-test-app/src/frontend/components/app/App.css, test-apps/presentation-test-app/src/frontend/components/ruleset-selector/RulesetSelector.tsx, test-apps/presentation-test-app/src/frontend/components/unit-system-selector/UnitSystemSelector.tsx
Fixed various pickers styles to match and align
=> Presentation: Fix test app pickers styling

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/read-pixel-improvements_2022-04-14-08-40.json, core/frontend/src/AccuSnap.ts, core/frontend/src/render/webgl/Target.ts, core/frontend/src/tools/ToolAdmin.ts, core/frontend/src/tools/ToolSettings.ts
This PR aims to reduce the footprint of ReadPixel calls triggered by accuSnap tool. ReadPixel is an expensive call forcing synchronization and currently it is being called each time the mouse is moved. Most of the time this is not necessary.
It tries to reuse the textures and fbo generated in the call when possible.
It imposes a delay between each to avoid unnecessary calls. To avoid using invalid data at the end of a movement, a callback is created to detect when the mouse stops moving and to trigger a last readPixel call.
When the use press a mouse button, ReadPixel is also called to make sure the clicked point is accurate.
=> Read pixel improvements

common/changes/@itwin/appui-react/ui-exampleOfHidingWidgetsInUi1and2_2022-04-19-12-24.json, test-apps/ui-items-providers-test/src/ui/providers/NetworkTracingUiProvider.tsx, test-apps/ui-items-providers-test/src/ui/widgets/SelectedElementDataWidget.tsx, ui/appui-react/src/appui-react/widgets/WidgetHost.tsx
Fix UI 1.0 bug were widgets defined by providers did not honor the Center Zone position. Since UI 2.0 now only supports two panel sections the widgets in 1.0 were being moved for center to bottom, but for UI 1 the center zone should be supported.
=> Fix UI 1.0 bug were widgets defined by providers did not honor the Center Zone position

common/changes/@itwin/core-frontend/dispose-reality-mesh-textures_2022-04-21-12-24.json, core/frontend/src/render/webgl/RealityMesh.ts
This pull request adds dispose calls to ``RealityTextureParam``in order to correctly dispose the texture of the Reality Mesh once it is unloaded.
Previously, it seems that the textures were never disposed. If this was not intentional, this PR should solve the issue.
=> Dispose render textures in RealityMesh

common/changes/@itwin/core-frontend/pmc-instanced-monochrome-fix_2022-04-23-16-53.json, core/frontend/src/render/webgl/InstancedGeometry.ts
Instanced geometry was always using flat (not scaled) monochrome color.
=> Fix scaled monochrome for instanced geometry.

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-no-mip-reality-textures_2022-04-23-16-38.json, core/frontend/src/test/tile/GltfReader.test.ts, core/frontend/src/tile/GltfReader.ts, core/frontend/src/tile/RealityTileLoader.ts
glTF spec defaults wrap mode to "repeat" if unspecified. We only produce mip-maps for repeating textures.
Some reality tiles were not specifying wrap mode, but they do not repeat and LOD is baked into the tiles so we do not want to generate mip-maps for them.
Allow GltfReader to override the default wrap mode. Make RealityTileLoader default it to ClampToEdge.
Eliminating mip-maps for these textures will reduce GPU memory usage and most likely also reduce time spent creating the textures.
This issue was reported by @TitouanLeDuigou; he discovered it in the Orlando reality model.
=> Do not produce mip-maps for reality tile textures

.github/mergify.yml, tools/internal/scripts/rush/audit.js
Add mergify rule to automatically add @iTwin/itwinjs-core-backport-reviewers as reviewers to any backport PR.
=> Add mergify config with backport reviewer rule

common/api/appui-react.api.md, common/changes/@itwin/appui-react/ui-standard-frontstage-provider_2022-05-04-20-04.json, test-apps/ui-test-app/src/frontend/appui/frontstages/FrontStageWithNoWidgets.tsx, ui/appui-react/src/appui-react/frontstage/StandardFrontstageProvider.tsx
The StandardFrontstageProvider gives apps an easy way to create a custom frontstage for their app, but overriding the default tool was more complicated. Adding an optional prop to override the default tool via StandardFrontstageProps allows the new default tool to be set up with the rest of the frontstage.
=> Add option defaultTool prop to StandardFrontstageProps

common/changes/@itwin/core-frontend/pmc-read-pixels-check-target_2022-05-07-13-03.json, core/frontend/src/Viewport.ts, core/frontend/src/test/Viewport.test.ts
Tools often invoke `Viewport.readPixels` from within an async callback, e.g., in response to mouse motion. It is possible for the Viewport to become disposed in between the async call and execution of the callback, in which case `this.target.readPixels` will produce an uncaught exception because `this.target` is `undefined.
This problem was made more apparent by @TitouanLeDuigou's PR #3504, which introduced a delay between mouse motion and readPixels. It was observed by @DStradley when accidentally mousing over a window running display-performance-test-app. But it can occur in "real" apps too when they close viewports due to switching front-stages etc.
The documentation for `readPixels` already falsely claimed to produce `undefined` if the viewport was not "active" (i.e., had been …
=> Viewport.readPixels returns undefined if viewport is disposed.

common/changes/@itwin/core-frontend/pmc-fix-popup-toolbar_2022-05-10-15-11.json, common/changes/@itwin/hypermodeling-frontend/pmc-fix-popup-toolbar_2022-05-10-15-11.json, core/frontend/src/tools/ToolAdmin.ts, core/hypermodeling/src/PopupToolbar.ts
Regression introduced in @TitouanLeDuigou's #3504: the hypermodeling popup toolbar disappears after a short delay while trying to interact with it.
When we mouse over a canvas decoration, don't enqueue a delayed `readPixels` call.
Also, double the delay before the popup toolbar disappears to 1 second.
=> Fix hypermodeling popup toolbar

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/markschlosser-fix-map-texture-disposal-bugs_2022-05-10-18-34.json, core/frontend/src/render/RenderSystem.ts, core/frontend/src/render/webgl/RealityMesh.ts, core/frontend/src/render/webgl/System.ts, core/frontend/src/tile/map/MapTile.ts, core/frontend/src/tile/map/MapTileLoader.ts
This PR resolves a regression introduced in @TitouanLeDuigou's #3536: background map textures will get corrupted after a period of time, especially triggered after opening a second viewport.
Map tiles (a type of reality mesh) currently need to retain their textures longer than the dispose introduced in the previous PR allows.
This PR makes map tiles retain their textures (like they previously would) by allowing them to skip the dispose.  Other reality meshes will still make use of the dispose introduced in the previous PR.
=> Fix corrupted background map textures

common/api/core-mobile.api.md, common/changes/@itwin/core-mobile/mobile-auth_2022-04-29-15-42.json, core/mobile/src/backend/MobileAuthorizationBackend.ts, core/mobile/src/backend/MobileHost.ts, core/mobile/src/common/MobileAppProps.ts, core/mobile/src/frontend/IOSApp.ts, core/mobile/src/frontend/MobileApp.ts, core/mobile/src/frontend/MobileAuthorizationFrontend.ts, test-apps/display-test-app/src/backend/MobileMain.ts, test-apps/display-test-app/src/frontend/App.ts, test-apps/ui-test-app/src/frontend/index.tsx
This PR should be in sync with the following PRs in imodel02 and mobile-sdk-ios:
[Narrow the iModelJsMobile auth API](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/244115)
[Update ITMAuthorizationClient to conform to the new protocol](https://github.com/iTwin/mobile-sdk-ios/pull/55)
Mobile auth has been refactored such that logic like sign-in, sign-out and token fetching now take place natively. Developers on iOS are expected to consume the itwin-mobile-sdk Swift package and use `ITMAuthorizationClient` if they need auth. 
The authorization interface in iModelJsMobile has been reduced to a single function: `authGetAccessToken`. The same change has been made to the AuthorizationClient protocol. From TypeScript, the mobile auth strategy becomes simpler; if …
=> Refactor Mobile Auth Strategy

common/changes/@itwin/map-layers/geo-widget_colorpicker_rgb_2022-05-13-20-20.json, extensions/map-layers/src/ui/widget/BasemapPanel.tsx
The control letting you pick preset color was missing in the color picker:
After the fix, It now loos like this:
=> Fix a display issue with background color's ColorPicker where part of the dialog was missing.

common/changes/@itwin/appui-layout-react/fix-widget-send-back_2022-05-16-09-29.json, ui/appui-layout-react/src/appui-layout-react/base/NineZoneState.ts, ui/appui-layout-react/src/test/base/NineZoneState.test.ts
Fix an issue where a widget is not removed correctly in FLOATING_WIDGET_SEND_BACK action.
This results in ignored `WidgetState.Hidden` for initial frontstage load, since there are multiple tabs with matching tab id and only one is removed.
=> Correctly remove a widget in FLOATING_WIDGET_SEND_BACK

common/changes/@itwin/core-backend/origin-no-geom-bug_2022-05-18-17-58.json, common/changes/@itwin/core-transformer/origin-no-geom-bug_2022-05-18-17-58.json, core/backend/src/IModelDb.ts, core/backend/src/test/DeepEqualWithFpTolerance.ts, core/backend/src/test/element/ElementRoundTrip.test.ts, core/backend/src/test/index.ts, core/transformer/src/test/IModelTransformerUtils.ts
- hoist `deepEqualWithFpTolerance` to the backend tests so it can be used there and in transformer tests
- minor jsdoc fix in iModelDb I noticed
- tests for this [native pr](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/248644)
=> test native fixes for roundtripping placement when no geometry is present

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/pmc-fix-duplicate-logo-cards_2022-05-19-19-45.json, core/frontend/src/tile/RealityModelTileTree.ts, core/frontend/src/tile/map/CesiumTerrainProvider.ts, core/frontend/src/tile/map/ImageryProviders/ArcGISMapLayerImageryProvider.ts, core/frontend/src/tile/map/ImageryProviders/AzureMapsLayerImageryProvider.ts, core/frontend/src/tile/map/ImageryProviders/BingImageryProvider.ts, core/frontend/src/tile/map/ImageryProviders/MapBoxLayerImageryProvider.ts, core/frontend/src/tile/map/ImageryTileTree.ts, core/frontend/src/tile/map/MapLayerImageryProvider.ts, core/frontend/src/tile/map/MapTileTree.ts, core/frontend/src/tile/map/TerrainMeshProvider.ts
Turn on background map with terrain.
Click the iTwin.js logo in the bottom-left corner of the viewport.
Observe 2 identical Cesium ION copyright notices.
A viewport has two map tile tree references: one for background map, the other for overlay map. Each has its own terrain provider. Each produces the same attribution.
Similar issues could arise with other types of tile trees.
Use [HTMLElement.dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) to keep track of which attribution has already been provided to avoid duplicates.
The required function signature changes also now enable providers to add multiple logo cards, and/or to customize the logo card based on the contents of the viewport (like the bing imagery provider does). …
=> Prevent duplicate logo cards.

common/changes/@itwin/core-backend/close-transformer-state-on-error_2022-05-13-15-34.json, common/changes/@itwin/core-transformer/close-transformer-state-on-error_2022-05-12-20-25.json, common/changes/@itwin/core-transformer/close-transformer-state-on-error_2022-05-13-15-34.json, core/backend/src/test/HubMock.ts, core/backend/src/test/IModelTestUtils.ts, core/backend/src/test/LocalHub.ts, core/backend/src/test/hubaccess/BriefcaseManager.test.ts, core/transformer/src/IModelTransformer.ts, core/transformer/src/test/HubMock.ts, core/transformer/src/test/IModelTransformerUtils.ts, core/transformer/src/test/KnownTestLocations.ts, core/transformer/src/test/standalone/Catalog.test.ts, core/transformer/src/test/standalone/IModelTransformer.test.ts, core/transformer/src/test/standalone/IModelTransformerHub.test.ts, core/transformer/src/test/standalone/IModelTransformerResumption.test.ts
- fixes an issue when basing a branch on imodel02 right now where 3 lines are based on a namespace import made in this commit but do not actually exist
- this is intended to not have to merge master yet, but still have the fixes from that PR
- cherry-picked, deleted the rush change files, and replaced them with a separate rush change... I'm actually not sure if it is better to merge in the existing change files so I can revert that as necessary
=> Cherry pick fix race condition fix on master to imodel02

.github/mergify.yml
Mergify would re request a review from the @iTwin/itwinjs-core-backport-reviewers team each time a review was submitted on that teams behalf. Update the "Add reviewers to backports" conditions so that it will not add the team if the PR was already approved by a team member.
=> Fix repeated requesting of backport reviewers team

common/changes/@itwin/core-frontend/pmc-fix-viewrect-rounding_2022-05-20-13-07.json, core/frontend/src/ViewRect.ts, core/frontend/src/Viewport.ts, core/frontend/src/render/webgl/Target.ts, core/frontend/src/test/ViewRect.test.ts, core/frontend/src/test/Viewport.test.ts
ViewRect coordinates are expected to be non-negative, but nothing enforces that.
They are expected to be integers, and we enforce that by flooring inputs.
`getCenteredViewRect` does some floating point arithmetic that can produce rounding error such that non-negative inputs produce results just slightly less than zero, which get floored to -1.
Ex: given left=top=0, right=390, bottom=844, the centered rect has left=-1.
If you pass such a ViewRect to `Viewport.readImage`, you get back `undefined`.
Now we enforce the non-negative constraint too. This addresses rounding error specifically when the value is negative. It does not attempt to address rounding error for non-negative values (by e.g. rounding instead of flooring, or checking for "almost equal to next highest integer").
=> Convert negative ViewRect coordinates to zero.

common/changes/@itwin/appui-react/ui-models-tree-fix-determining-subject-models-performance_2022-05-24-08-55.json, ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsVisibilityHandler.ts, ui/appui-react/src/test/imodel-components/models-tree/ModelsVisibilityHandler.test.ts
Fixes itwin/itwinjs-backlog#79
Doing the join in a single query takes up to a minute in the problematic iModel. Doing 2 separate queries and joining them on the frontend takes up to 200 ms.
=> UI: Fix performance of getting subject models in Models Tree

common/changes/@itwin/appui-react/ui-models-tree-optimize-creating-subjects-hierarchy_2022-05-24-12-58.json, test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.ModelsTree-GroupedByClass.PresentationRuleSet.json, test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.ModelsTree.PresentationRuleSet.json, ui/appui-react/src/appui-react/imodel-components/models-tree/Hierarchy.GroupedByClass.json, ui/appui-react/src/appui-react/imodel-components/models-tree/Hierarchy.json
We create nodes for Models only if they have elements. If a GeometricModel has an element, it means it definitely has a child node of a Category instance. Put a hint for this so we don't have to run a query to check what we already know.
This makes a huge difference for the initial Models Tree load performance, because we don't need to run the slow Models-to-Categories queries. Local run on the performance test suite:
Before (s) | After (s)
-- | --
5.217 | 0.774
4.037 | 0.263
2.3635 | 0.421
3.016 | 0.355
6.0315 | 0.414
2.0585 | 0.374
0.726 | 0.393
0.7 | 0.432
0.2775 | 0.171
0.302 | 0.226
1.819 | 0.391
1.756 | 0.607
0.21 | 0.215
5.7805 | 1.545
0.2285 | 0.165
0.167 | 0.167
0.585 | 0.23
0.352 | 0.226
0.578 | 0.243
0.261 | 0.225
0.6225 | 0.376
0.251 | 0.187
0.228 | 0.143
0.181 | 0.163
0.203 | …
=> UI: Optimize creating subjects hierarchy in Models Tree

common/changes/@itwin/core-frontend/pmc-fix-3682_2022-05-25-13-04.json, core/frontend/certa.json, core/frontend/src/render/primitives/geometry/GeometryListBuilder.ts, core/frontend/src/test/DeferredMarkerHtmlRemoval.test.ts, core/frontend/src/test/render/primitives/PrimitiveBuilder.test.ts
Fixes #3682
Also bumps default timeout for core-frontend tests from 2 to 10 seconds because the mac build agents frequently time out on even very simple tests.
=> Do not create a Batch with an empty FeatureTable

common/changes/@itwin/core-transformer/transformer-mapId64-assert-fix_2022-05-26-08-36.json, core/transformer/src/IModelTransformer.ts
Scenario:
Passing object containing an `id` property to `mapId64` function.
Problem:
`isId64String` is executed first and `assert(Id64.isValidId64(arg)` fires an error due to `arg` not being a string.
=> Fix assertion on valid case in IModelExporter.exportElement.

common/changes/@itwin/appui-layout-react/widget-tab-tippy_2022-05-25-13-12.json, ui/appui-layout-react/src/appui-layout-react/base/DragHandle.tsx, ui/appui-layout-react/src/appui-layout-react/base/PointerCaptor.tsx, ui/appui-layout-react/src/appui-layout-react/widget/rectangular/ResizeGrip.tsx, ui/appui-layout-react/src/test/base/PointerCaptor.test.snap, ui/appui-layout-react/src/test/base/PointerCaptor.test.tsx, ui/appui-layout-react/src/test/widget/rectangular/tab/Tab.test.tsx
This PR fixes an issue where tippy.js popup was not being closed if the widget tab or resize handle was clicked/dragged.
=> Close popup when the widget tab is clicked

common/changes/@itwin/webgl-compatibility/pmc-mali-g72-workaround_2022-05-30-15-45.json, core/webgl-compatibility/src/Capabilities.ts, core/webgl-compatibility/src/test/Compatibility.test.ts, tools/internal/scripts/rush/audit.js
Addresses #3700 using same workaround as #3234 for incorrect transparency.
Also applies workaround from #3499 for hang after enabling MSAA.
=> Add workarounds for Mali-G72 GPU.

common/api/core-common.api.md, common/changes/@itwin/core-common/fill-range-index-from-spatial_2022-06-01-21-23.json, core/common/src/tile/IModelTileIO.ts
For [corresponding native PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/251307) which populates the range index from the iModel's spatial index instead of querying element ranges.
=> Bump tile format version

common/api/presentation-backend.api.md, common/api/presentation-common.api.md, common/api/presentation-frontend.api.md, common/api/summary/presentation-common.exports.csv, common/api/summary/presentation-frontend.exports.csv, common/changes/@bentley/presentation-backend/presentation-nth-level-element-selection-scope_2022-06-03-12-22.json, common/changes/@bentley/presentation-common/presentation-nth-level-element-selection-scope_2022-06-03-12-22.json, common/changes/@bentley/presentation-components/presentation-nth-level-element-selection-scope_2022-06-03-12-22.json, common/changes/@bentley/presentation-frontend/presentation-nth-level-element-selection-scope_2022-06-03-12-22.json, full-stack-tests/presentation/src/frontend/SelectionScopes.test.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/presentation-backend/SelectionScopesHelper.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts, presentation/backend/src/test/SelectionScopesHelper.test.ts, presentation/common/src/presentation-common/PresentationManagerOptions.ts, presentation/common/src/presentation-common/PresentationRpcInterface.ts, presentation/common/src/presentation-common/RpcRequestsHandler.ts, presentation/common/src/presentation-common/selection/SelectionScope.ts, presentation/common/src/test/PresentationManagerOptions.test.ts, presentation/common/src/test/PresentationRpcInterface.test.ts, presentation/common/src/test/RpcRequestsHandler.test.ts, presentation/components/src/presentation-components/favorite-properties/DataProvider.ts, presentation/frontend/src/presentation-frontend/selection/SelectionManager.ts, presentation/frontend/src/presentation-frontend/selection/SelectionScopesManager.ts, presentation/frontend/src/test/selection/SelectionManager.test.ts, presentation/frontend/src/test/selection/SelectionScopesManager.test.ts
Resolves itwin/itwinjs-backlog#164.
Introduced a new type `ComputeSelectionScopeProps` that has an `id` attribute for available scopes and also has a `params: { level: number }` attribute for the scope with `id: "element"`. On the frontend objects of this new type can now be set on `Presentation.selection.scopes.activeScope` or passed to `Presentation.selection.scopes.activeScope.computeSelection`. This allows passing the level of requested ancestor when using "element" scope.
The PR also increases minor version of `PresentationRpcInterface` to make sure new frontends don't request old backends to compute selection in the new way and assume the backends handles the added params. Old frontends can still safely use updated backends.
=> Presentation: Introduce nth level element selection scope support

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/djs-ignore-uniform-errors_2022-06-07-03-18.json, core/frontend/src/render/RenderSystem.ts, core/frontend/src/render/webgl/ShaderProgram.ts, core/frontend/src/render/webgl/UniformHandle.ts, core/frontend/src/test/render/webgl/Technique.test.ts, test-apps/display-test-app/README.md, test-apps/display-test-app/src/common/DtaConfiguration.ts, test-apps/display-test-app/src/frontend/DisplayTestApp.ts
Currently we fail on missing shader uniforms, terminating the application, but there are cases where the shader will still operate correctly, typically when the graphics driver has optimized away a uniform variable.  Changed this to not fail by default.
Added a new RenderSystem.Options errorOnMissingUniform which defaults to false.  When false, it will report the missing uniform through the Logger.  When true it will throw an error as before.  Also added the shader description to the error messages.
Changed the shader compilation tests to set this option to true and enable the Logger to console.
Changed display-test-app to set this option to true by default, unless IMJS_DISABLE_UNIFORM_ERRORS is set.
=> Ignore shader uniform errors by default

common/changes/@itwin/components-react/ui-tree-fix-out-of-sync-tree-model_2022-06-08-13-48.json, ui/components-react/src/components-react/tree/controlled/TreeHooks.ts, ui/components-react/src/test/tree/controlled/TreeHooks.test.tsx
Fixes https://github.com/iTwin/itwinjs-backlog/issues/198
We were getting into a situation where a model source changes, but `useTreeModel` returns a stale tree model from state. The stale model was of the newly created filtered model source and was absolutely empty. This caused node loader to load root nodes and place them into the non-filtered model source, thus loosing any expanded nodes.
The change makes sure we always return model of the given model source. In addition, we don't store the model in state anymore, which saves us one re-render on model source changes.
=> UI: Fix `useTreeModel` returning stale model for the given model source

common/api/presentation-backend.api.md, common/api/presentation-common.api.md, common/api/presentation-frontend.api.md, common/api/summary/presentation-common.exports.csv, common/api/summary/presentation-frontend.exports.csv, common/changes/@itwin/presentation-backend/presentation-nth-level-element-selection-scope-on-master_2022-06-09-10-53.json, common/changes/@itwin/presentation-common/presentation-nth-level-element-selection-scope-on-master_2022-06-09-10-53.json, common/changes/@itwin/presentation-components/presentation-nth-level-element-selection-scope-on-master_2022-06-09-10-53.json, common/changes/@itwin/presentation-frontend/presentation-nth-level-element-selection-scope-on-master_2022-06-09-10-53.json, full-stack-tests/presentation/src/frontend/SelectionScopes.test.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/presentation-backend/SelectionScopesHelper.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts, presentation/backend/src/test/SelectionScopesHelper.test.ts, presentation/common/src/presentation-common/PresentationManagerOptions.ts, presentation/common/src/presentation-common/PresentationRpcInterface.ts, presentation/common/src/presentation-common/RpcRequestsHandler.ts, presentation/common/src/presentation-common/selection/SelectionScope.ts, presentation/common/src/test/PresentationManagerOptions.test.ts, presentation/common/src/test/PresentationRpcInterface.test.ts, presentation/common/src/test/RpcRequestsHandler.test.ts, presentation/components/src/presentation-components/favorite-properties/DataProvider.ts, presentation/frontend/src/presentation-frontend/selection/SelectionManager.ts, presentation/frontend/src/presentation-frontend/selection/SelectionScopesManager.ts, presentation/frontend/src/test/selection/SelectionManager.test.ts, presentation/frontend/src/test/selection/SelectionScopesManager.test.ts
Cherry-pick of https://github.com/iTwin/itwinjs-core/pull/3743. Issue: https://github.com/iTwin/itwinjs-backlog/issues/164.
=> Presentation: Add support for nth level element selection scopes

common/api/appui-react.api.md, common/api/summary/appui-react.exports.csv, common/changes/@itwin/appui-react/raplemie-useToolAsToolSettingsLabel_2022-06-14-18-56.json, ui/appui-react/public/locales/en/UiFramework.json, ui/appui-react/src/appui-react/UiFramework.ts, ui/appui-react/src/appui-react/configurableui/state.ts, ui/appui-react/src/appui-react/settings/ui/UiSettingsPage.tsx, ui/appui-react/src/appui-react/uistate/AppUiSettings.ts, ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx, ui/appui-react/src/test/redux/StateManager.test.ts, ui/appui-react/src/test/settings/UiSettingsPage.test.tsx, ui/appui-react/src/test/uisettings/AppUiSettings.test.ts, ui/appui-react/src/test/widget-panels/Frontstage.test.tsx
This adds an option so the Tool Settings widget label will use the active tool "flyover" localized text.
This also adds localisation to the normal "Tool Settings" label.
`UiFramework.setUseToolAsToolSettingsLabel(false)` (default)
`UiFramework.setUseToolAsToolSettingsLabel(true)`
=> Use active tool name as tool settings label

common/api/presentation-common.api.md, common/changes/@itwin/presentation-backend/presentation-content-descriptor-optimisation_2022-06-15-12-56.json, common/changes/@itwin/presentation-common/presentation-content-descriptor-optimisation_2022-06-15-12-56.json, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/common/src/presentation-common/content/Descriptor.ts
We only need to count target instances in order to figure out how to merge their content. Since `getContentDescriptor` returns content descriptor without any instance data, we can skip counting and achieve 10-20% performance uplift.
[Related native addon PR.](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/256796)
=> Presentation: Avoid counting target instances when calling getContentDescriptor RPC operation

common/changes/@itwin/core-common/nick-cache-getModelProps_2022-06-20-13-16.json, core/common/src/rpc/IModelReadRpcInterface.ts
Some types of tile trees (ClassifierTileTree, RealityModelTileTree, MapTileTree) need to load models which results in a call to GetModelProps. We want to cache getModelProps so that initial View creation (and tile generation) is speedy and requires little assistance from a backend while these RPC requests are cached.
=> Convert getModelProps RPC operation to a GET request from POST

common/api/core-common.api.md, common/changes/@itwin/core-common/remove-preflight_2022-06-17-14-57.json, core/common/src/rpc/core/RpcProtocol.ts, core/common/src/rpc/core/RpcRequest.ts, core/common/src/rpc/web/WebAppRpcProtocol.ts, core/common/src/rpc/web/WebAppRpcRequest.ts, full-stack-tests/rpc/src/backend/TestRpcImpl.ts, full-stack-tests/rpc/src/common/TestRpcInterface.ts, full-stack-tests/rpc/src/frontend/Routing.test.ts, full-stack-tests/rpc/src/frontend/_Setup.test.ts
In commit d415d8c34a672aa03b52f47053d6e966304acd34, a new HTTP header (`X-Protocol-Version`) was added to all RPC requests (and responses) sent via the `BentleyCloudRpcProtocol`.  This exchange of protocol versions allows us to detect backend capabilities and gracefully roll out new capabilities while maintaining backwards compatibility.
However, that change _itself_ presented its own backwards compatibility problem: When the frontend and backed are served from separate [origins](https://developer.mozilla.org/en-US/docs/Glossary/Origin) (this is usually the case), [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) requires browsers to automatically send a [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) before each HTTP request[^1] and …
=> Remove RPC preflight and InitializeInterface

common/changes/@itwin/workspace-editor/workspace-editor-eol_2022-06-21-13-40.json, utils/workspace-editor/src/WorkspaceEditor.ts
The WorkspaceEditor CLI utility allows executing an "@ script" file listing separate WorkspaceEditor commands, but splitting by `\r` meant that files written w/ unix-style line endings (`\n`) were not parsed correctly.
=> Support unix line endings in WorkspaceEditor

common/changes/@itwin/core-frontend/nick-blank-connection-load_2022-06-22-14-37.json, core/frontend/src/ViewState.ts
The addition of the RPC operation "hydrateViewState" causes load() to now fail when the iModel associated with the viewState is a blankConnection. This PR returns if the iModel is a blank connection to avoid this problem. 
Before the RPC operation hydrateViewState, load() likely failed gracefully in the case of a BlankConnection.
=> Return in viewState.load() if iModel associated with viewState is a blankConnection

common/api/appui-react.api.md, common/api/summary/appui-react.exports.csv, common/changes/@itwin/appui-react/transient-state_2022-06-22-12-47.json, test-apps/ui-test-app/src/frontend/appui/widgets/VisibilityWidget.tsx, ui/appui-react/src/appui-react.ts, ui/appui-react/src/appui-react/widget-panels/Content.tsx, ui/appui-react/src/appui-react/widget-panels/useTransientState.tsx
This PR exposes previously @internal `useTransientState` hook as a **@beta** API (from **appui-react** to avoid exposing new APIs from **appui-layout-react** package). Example usage of this is added to **ModelsTree** of **ui-test-app**.
This PR also ensures that previously existing handlers `AbstractWidgetProps["saveTransientState"]` and `AbstractWidgetProps["restoreTransientState"]` are fired correctly.
=> Expose useTransientState hook

common/changes/@itwin/core-common/fix-remaining-predecessor-vocab_2022-06-24-14-07.json, core/common/src/RenderSchedule.ts
#3858 left this reference to the deprecated `collectPredecessorIds`
=> clean up last dead collectPredecessorIds references

core/backend/src/IModelHost.ts
Corresponding [native PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/259596)
=> use NativeLibrary.isDevBuild to detect locally installed development builds of imodeljs-native

common/config/azure-pipelines/templates/gather-docs.yaml
The docs build pulls in documentation artifacts from other builds, this PR locks down the version of the bis-schemas build artifact to one compatible with 3.2.x releases.
=> Lock down bis-schemas docs version

common/api/editor-frontend.api.md, common/changes/@itwin/editor-frontend/torus-tool_2022-06-30-16-43.json, editor/frontend/src/SolidPrimitiveTools.ts, editor/frontend/src/public/locales/en/Editor.json
Change in behavior from the MicroStation torus tool to better support AccuDraw. Requiring an additional step to define the secondary radius allows AccuDraw to be positioned such that it's distance input can specify the radius value.
=> Define secondary radius and angle in separate phases.

common/changes/@itwin/core-frontend/marcbedard8-AttachCesiumAssetFromUrl_2022-06-30-16-08.json, common/changes/@itwin/frontend-devtools/marcbedard8-AttachCesiumAssetFromUrl_2022-06-30-16-08.json, core/frontend-devtools/src/tools/RealityModelTools.ts, core/frontend/src/RealityDataSource.ts, core/frontend/src/test/RealityDataSouce.test.ts
We should be able to attach a cesium asset from id and key using code like this:
const cesiumProps = {
tilesetUrl: getCesiumAssetUrl(
cesiumAssetId,
requestKey ? requestKey : (IModelApp.tileAdmin.cesiumIonKey ?? "")
),
};
const vp = IModelApp.viewManager.selectedView;
if (vp)
vp.displayStyle.attachRealityModel(cesiumProps);
=> Restore the possibility to attach any cesium asset using getCesiumAssetUrl

common/changes/@itwin/appui-abstract/pmc-unpin-ts-node_2022-07-03-21-28.json, common/changes/@itwin/appui-layout-react/pmc-unpin-ts-node_2022-07-03-21-28.json, common/changes/@itwin/appui-react/pmc-unpin-ts-node_2022-07-03-21-28.json, common/changes/@itwin/components-react/pmc-unpin-ts-node_2022-07-03-21-28.json, common/changes/@itwin/core-react/pmc-unpin-ts-node_2022-07-03-21-28.json, common/changes/@itwin/imodel-components-react/pmc-unpin-ts-node_2022-07-03-21-28.json, common/config/rush/pnpm-lock.yaml, ui/appui-abstract/package.json, ui/appui-layout-react/package.json, ui/appui-react/package.json, ui/components-react/package.json, ui/core-react/package.json, ui/imodel-components-react/package.json
#3832 pinned ts-node to 10.8.0 because a bug in 10.8.1 [broke nyc](https://github.com/istanbuljs/nyc/issues/1473).
It is [fixed in 10.8.2](https://github.com/TypeStrong/ts-node/pull/1771).
=> Unpin ts-node.

tools/internal/scripts/rush/audit.js
https://github.com/advisories/GHSA-wc69-rhjr-hc9g
backend-integration-tests uses azurite which uses sequelize which uses moment.
Latest version of azurite (3.18.0) wants sequelize ^6.3.0. It gets 6.20.1_mysql2@2.3.3+tedious@14.5.0 (ok...?) which gets moment 2.29.3.
As far as I can tell sequelize has since removed its dependency on moment.
=> Temporarily bypass moment vulnerability

common/api/core-backend.api.md, common/changes/@itwin/core-backend/nick-retry-v2-checkpoint-downloads_2022-07-08-14-59.json, core/backend/src/CheckpointManager.ts, core/backend/src/test/hubaccess/CheckpointManager.test.ts
This is a short term solution to a problem surrounding Transient Fault handling with v2 checkpoints. In the long term, we expect to work with SQLite and hopefully have them provide a way for us to better control what we do in the event of an error when downloading blocks. 
Resumable downloads are supported by blockcachevfs, meaning that we will not be repeating the same block downloads when retrying these v2 checkpoint downloads.
=> Retry v2 checkpoint downloads in the case of "Failure when receiving data from the peer" error message

common/api/core-bentley.api.md, common/api/core-electron.api.md, common/api/summary/core-bentley.exports.csv, common/changes/@itwin/core-bentley/electron-ipc_2022-05-11-13-46.json, common/changes/@itwin/core-electron/electron-ipc_2022-05-11-13-46.json, core/bentley/src/UtilityTypes.ts, core/electron/src/__DOC_ONLY__.ts, core/electron/src/backend/ElectronHost.ts, core/electron/src/common/ElectronIpcInterface.ts, core/electron/src/frontend/ElectronApp.ts, docs/changehistory/NextVersion.md
This PR fixes an issue where Electron IPC handler allows the frontend part of the application to invoke any electron main process module API (bypassing `sandbox`/`nodeIntegration` configuration).
The issue is fixed by specifying a **white-list of allowed modules/methods** in the handler for **`dialog` module**. `ElectronApp.callDialog` types are updated to reflect that (breaking change, `ElectronApp` is marked as @beta).
This PR also suggests to remove `ElectronApp.callShell` and `ElectronApp.callApp` methods until a real use case  for such APIs emerges (breaking change, `ElectronApp` is marked as `@beta`, also couldn't find any usage of these APIs in iTwin/internal repositories).
=> White-list dialog module methods in Electron IPC handler

common/changes/@itwin/presentation-backend/presentation-AvoidPollingNativeAddon_2022-07-12-14-35.json, common/changes/@itwin/presentation-common/presentation-AvoidPollingNativeAddon_2022-07-12-14-35.json, presentation/backend/src/presentation-backend/NativePlatform.ts, presentation/backend/src/test/NativePlatform.test.ts
Use promise instead of polling the result from native addon.
https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/261621
Closes iTwin/itwinjs-backlog#120
=> Presentation: Use promise instead of polling native addon

common/changes/@itwin/presentation-components/presentation-usepresentationtreenodeloader_fix_2022-07-13-13-15.json, presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts
When using `usePresentationTreeNodeLoader` hook `customizeTreeNodeItem` was not passed through to `PresentationTreeDataProvider` during creation. Because of this there was no way to customize tree node items when loading nodes.
=> Presentation: correctly handle customizeTreeNodeItem in usePresentationTreeNodeLoader hook

common/changes/@itwin/presentation-backend/presentation-FixNativePlatformCoverage_2022-07-13-15-35.json, presentation/backend/src/presentation-backend/NativePlatform.ts
Line `throw new PresentationError(this.getStatus(response.error.status), response.error.message);` in `handleResult<T>` was not covered.
=> Presentation: Fix NativePlatform coverage

common/api/presentation-common.api.md, common/changes/@itwin/presentation-common/presentation-add_navigation_property_target_info_2022-07-15-13-58.json, full-stack-tests/presentation/src/frontend/Content.test.ts, presentation/common/src/presentation-common/EC.ts, presentation/common/src/presentation-common/content/Fields.ts, presentation/common/src/test/content/Descriptor.test.snap, presentation/common/src/test/content/Descriptor.test.ts, presentation/common/src/test/content/Fields.test.snap, presentation/common/src/test/content/Fields.test.ts
Added info about target class to `NavigationPropertyInfo`
Related [native changes](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/264272)
=> Presentation: Add navigation property target info

common/api/core-backend.api.md, common/api/summary/core-backend.exports.csv, common/changes/@itwin/core-backend/optional-opentelemetry_2022-07-20-12-06.json, core/backend/src/IModelHost.ts, core/backend/src/RpcBackend.ts
There is a problem with dynamic loading that I didn't anticipate: if the dependency tree contains an incompatible version of `@opentelemetry/api`, it will still be resolved even though it doesn't match the version range specified in peerDependencies. To prevent such issues, I'm adding an additional step that needs to be done explicitly to enable openTelemetry.
=> make openTelemetry configurable

test-apps/appui-test-app/standalone/src/backend/electron/ElectronMain.ts
One import was importing directly from src folder, which causes issues at compile time.
=> UI: appui-test-app/standalone, Remove inner path to import

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/promote-toolsettings-apis_2022-07-22-15-32.json, core/frontend/src/tools/Tool.ts
Tool Settings APIs that have been in use for some time were overlooked when promoting APIs to public.
=> Promote Tool Settings APIs

core/backend/src/IModelHost.ts
Seems like something would have to be very wrong for the imodeljs-native version not to match that specified in core-backend's package.json, and recent changes to the install scripts have broken this validation.
[Related native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/266294).
@kabentley
=> Remove native platform validation

common/changes/@itwin/webgl-compatibility/markschlosser-workaround-mali-g76-transparency-issues_2022-07-25-13-51.json, core/webgl-compatibility/src/Capabilities.ts
Mali G-76 is unable to render transparency when using full floating point textures.  Fall back to non-full floating textures when that chipset is detected (like we do for other similar chipsets).
=> Work around Mali G-76 transparency issues

common/changes/@bentley/webgl-compatibility/markschlosser-bp-workaround-mali-g76-transparency-issues_2022-07-25-19-38.json, core/webgl-compatibility/src/Capabilities.ts
Backport of: https://github.com/iTwin/itwinjs-core/pull/3963
=> Work around Mali G-76 transparency issues (bp #3963)

common/changes/@itwin/editor-frontend/editor-deps_2022-07-27-17-37.json, common/config/rush/pnpm-lock.yaml, editor/frontend/package.json
In its current state, an application that imports both core-frontend and editor-frontend will fail when the extension runtime attempts to hoist:
This is technically a breaking change for any consumers of editor-frontend that are not currently importing core-frontend, appui-abstract, and core-geometry, if any exist.
=> move core deps in editor-frontend to peerDeps

docs/learning/backend/ConcurrencyControl.md
The fact that exclusively locking a model locks its children wasn't documented.
=> document that locking models locks elements

common/changes/@itwin/appui-react/presentation-models_tree_handle_all_grouped_elements_2022-07-29-06-37.json, ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsVisibilityHandler.ts, ui/appui-react/src/appui-react/imodel-components/models-tree/Utils.ts, ui/appui-react/src/test/imodel-components/models-tree/ModelsVisibilityHandler.test.ts
In some cases ModelsTree might ignore children when changing ancestor visibility because we were reusing AsyncGenerator in `for await` loop. Generator is [closed when for loop terminates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#do_not_reuse_generators). This caused some element ids to be lost in cases we didn't iterator over all children.
=> Presentation: ModelsTree might ignore some children when changing parent visbility

common/changes/@itwin/core-webpack-tools/webpack4-electron_2022-07-29-13-28.json, common/config/azure-pipelines/templates/gather-docs.yaml, tools/webpack-core/src/plugins/BackendDefaultsPlugin.ts
To make sure you can properly webpack an electron backend with webpack@4 before we upgrade to webpack@5
=> add keytar as an external

.vscode/launch.json, common/changes/@itwin/imodel-components-react/raplemie-navcubeInMarkup_2022-07-29-21-15.json, ui/imodel-components-react/src/imodel-components-react/navigationaids/CubeNavigationAid.tsx, ui/imodel-components-react/src/test/navigationaids/CubeNavigationAid.test.tsx
This uses the same technique as the ViewTools to prevent interactions with the NavCube.
fixes iTwin/itwinjs-backlog#296
=> UI: Lock Navicube in Markup viewports

common/changes/@itwin/appui-layout-react/send-back-fix_2022-08-04-12-33.json, ui/appui-layout-react/src/appui-layout-react/base/NineZoneState.ts, ui/appui-layout-react/src/test/base/NineZoneState.test.ts
This PR fixes an issue where widgets are duplicated in the panel when multiple `FLOATING_WIDGET_SEND_BACK` actions are fired with the same home state.
=> Fix widget duplication in send back action

common/changes/@itwin/core-common/ipc-test-fix_2022-08-10-16-47.json, core/common/src/ipc/IpcWebSocket.ts
During the BriefcaseTxns tests, the frontend sends a purgeTileTrees RPC request and then a closeIModel IPC message.
When RPC is transported over IPC, this crashes occasionally on web.
The crash happens when the impl function for the first message (purgeTileTrees) awaits. This yields to the impl function for the second mesage (closeIModel). When control returns to purgeTileTrees, the imodel is gone.
When RPC is implemented using HTTP requests, there are two separate network connections. So, I think the purgeTileTrees request is able to complete fully (including any awaits, which only go out to the v8 microtask queue and do not spin the outer node/uv loop again, which would allow closeIModel IPC message to sneak in).
The fix here is to process IPC messages (including RPC ones) sequentially …
=> Process IPC invokes sequentially

common/api/core-backend.api.md, common/changes/@itwin/core-backend/withOpenDb-internal_2022-08-11-21-03.json, core/backend/src/SQLiteDb.ts
@kabentley has changed its signature in #4057. Rather than backport that change to 3.3, just mark it internal until 3.4 is released.
=> Make withOpenDb internal.

common/api/core-transformer.api.md, common/api/summary/core-transformer.exports.csv, common/changes/@itwin/core-backend/transformer-reverse-sync-no-delete_2022-08-12-18-07.json, common/changes/@itwin/core-transformer/transformer-reverse-sync-no-delete_2022-08-12-18-07.json, core/backend/src/LocalHub.ts, core/transformer/src/IModelExporter.ts, core/transformer/src/IModelImporter.ts, core/transformer/src/IModelTransformer.ts, core/transformer/src/test/IModelTransformerUtils.ts, core/transformer/src/test/standalone/IModelTransformerHub.test.ts, docs/changehistory/NextVersion.md
fixes #4072
- Extract element id remaps from deleted elements and their deleted ExternalSourceAspects using change summary ECSQL queries
- modify the existing branch tests to cover this case
- add a new test specific to this case that also covers model deletion
- Handle model deletes which the transformer previously did not do
I am going to add coverage for deleting relationships while processing changes in [reverse]synchronizations in the upcoming transform-non-element-entities work.
=> fix deletion of elements in transformer during branch reverse synchronization 

common/changes/@itwin/core-frontend/pmc-fix-reality-shadow-casting_2022-08-15-19-39.json, core/frontend/src/render/webgl/RealityMesh.ts, core/frontend/src/tile/RealityTileTree.ts
Fixes #3946
[This commit](https://github.com/iTwin/itwinjs-core/pull/163/commits/f649df81995825e455715c6c813f5e05cc1f4212) initially broke it. SolarShadowMap relies on TileDrawArgs.processSelectedTiles being called, but it's only called by TileTree.selectTiles. That commit changed how we select tiles for shadow map, calling TileTree.draw, which for reality models goes through a totally different code path (selectRealityTiles) which does not invoke processSelectedTiles.
Subsequently Ray converted TerrainMesh into RealityMesh and started using it to draw reality models too. TerrainMesh.getPass returned "none" while drawing shadow map. Unclear why, given we should never have selected any terrain meshes for the shadow map in the first place.
@DStradley please add your test case to ImageTests …
=> Fix reality model shadow casting.

common/changes/@itwin/core-backend/fix-workspace-slash_2022-08-15-21-37.json, core/backend/src/assets/Settings/backend.setting.json5
This should resolve the transient "attach error: HTTP/1.1 400" errors we've been seeing periodically.
=> Remove trailing slash from geocoord workspace URL.

common/changes/@itwin/core-frontend/pmc-global-shadows_2022-08-16-18-56.json, core/frontend/src/render/webgl/SolarShadowMap.ts
When shadows are enabled we ask each shadow-casting tile tree to disclose the volume of space containing shadow-casting geometry. For global tilesets like the OpenStreetMap buildings, that volume is the size of the Earth, making the shadow map useless. In such cases, limit the shadow-casting range to the viewed volume.
Unless you're zoomed very far in and/or looking mostly top-down, the resolution of the shadow map is still pretty lousy, but at least it produces recognizable shadows.
=> Limit shadow range for global tile trees.

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/geo-fix_ArcGisFilterByRange_2022-08-16-19-56.json, core/frontend/src/tile/map/ArcGisUtilities.ts, core/frontend/src/tile/map/ImageryProviders/ArcGISMapLayerImageryProvider.ts
When publishing from [Geologic Map of North America](https://certmapper.cr.usgs.gov/server/rest/services/geology/northamerica_gmna/MapServer), only northen tiles would be displayed.  This occurs because the data range is read from a 'footprints' request, which turns out to be unreliable for some servers.  We now rely on 'fullextent' of the service metadata, which appears to be more reliable (at least it works for several USGS servers tested)
=> Fix display issue with ArcGIS server of 'Geologic Map of North America'

common/api/core-backend.api.md, common/api/presentation-testing.api.md, common/changes/@itwin/analytical-backend/workspace-cloud-cache_2022-08-16-18-38.json, common/changes/@itwin/core-backend/workspace-cloud-cache_2022-08-16-18-38.json, common/changes/@itwin/ecschema-rpcinterface-tests/workspace-cloud-cache_2022-08-16-18-38.json, common/changes/@itwin/linear-referencing-backend/workspace-cloud-cache_2022-08-16-18-38.json, common/changes/@itwin/physical-material-backend/workspace-cloud-cache_2022-08-16-18-38.json, common/changes/@itwin/presentation-backend/workspace-cloud-cache_2022-08-16-18-38.json, common/changes/@itwin/presentation-testing/workspace-cloud-cache_2022-08-17-08-35.json, core/backend/src/GeoCoordConfig.ts, core/backend/src/IModelDb.ts, core/backend/src/IModelHost.ts, core/backend/src/test/IModelHost.test.ts, core/backend/src/test/standalone/ConcurrentQuery_Perf.test.ts, core/backend/src/workspace/Workspace.ts, domains/analytical/backend/src/test/AnalyticalSchema.test.ts, domains/linear-referencing/backend/src/test/LinearReferencingSchema.test.ts, domains/physical-material/backend/src/test/PhysicalMaterialSchema.test.ts, full-stack-tests/backend/src/integration/CloudWorkspace.test.ts, full-stack-tests/core/src/backend/RpcImpl.ts, full-stack-tests/ecschema-rpc-interface/src/test/backend.ts, full-stack-tests/presentation/src/IntegrationTests.ts, full-stack-tests/presentation/src/performance/GetElementProperties.test.ts, full-stack-tests/rpc/src/backend/CommonBackendSetup.ts, presentation/backend/src/test/NativePlatform.test.ts, presentation/backend/src/test/Presentation.test.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/SelectionScopesHelper.test.ts, presentation/testing/src/presentation-testing/Helpers.ts
All workspaces should use the same `cloudCache`, but previously they were each creating their own.
Also:
- clean up diagnostics for GCS workspace loading. Previous attempt could cause errors while reporting the errors
- attempt to ensure each test uses its own `cacheDir`. I think there's still a problem with `full-stack-tests\presentation`, but it is non-fatal
=> share cloudCache for all workspaces

common/changes/@itwin/core-common/send-400s-for-junk-reqs_2022-08-17-20-06.json, core/common/src/rpc/web/BentleyCloudRpcProtocol.ts, core/common/src/rpc/web/WebAppRpcProtocol.ts, core/common/src/rpc/web/WebAppRpcRequest.ts, full-stack-tests/rpc/src/frontend/Routing.test.ts
Now that more RPC requests are sent as GET requests, our dynamic fuzzing scans have started (incorrectly) flagging those endpoints as potentially vulnerable to SQL injection, due to the fact that appending junk to the request URL query string results in inconsistent behavior (depending on what's appended this can either be ignored when the value is base64 decoded or result in invalid JSON).
While we can safely ignore the SQL injection concern (again, that is a false positive), this inconsistent behavior itself should probably be fixed for its own sake.  I think the easiest thing to do here is to simply scan the query params for any characters that don't belong in a base64-encoded value and fail the request handling early if any are detected.  Also, these invalid requests should result in …
=> Improve handling of invalid/malformed web RPC requests.

common/changes/@itwin/components-react/fix-new-icon-sizes_2022-08-25-14-47.json, ui/components-react/src/components-react/toolbar/_variables.scss
Changed width and height variables for the toolbar to be 40px, which matches the toolbar items and will create 1:1 square icon sizes.
=> fix: Updated CSS variables for desktop toolbar width/height to 40px for square icons

common/changes/@itwin/core-backend/nick-getcustomviewstate3ddata-freeup-loop_2022-08-29-16-31.json, core/backend/src/CustomViewState3dCreator.ts
This is meant as a short term solution to the problem that we have been seeing where we're unable to distinguish between a long-running RPC operation and a hanging backend. The reason for the inability to distinguish is that getCustomViewState3dData does work on the main thread in the form of the native function "queryModelExtents". Since this function is called in a loop for each modelId from the typescript side we can call "await new Promise((resolve) => setImmediate(resolve));" before each call to queryModelExtents. This will allow for the backend to respond to pings which allows us to know that the backend is not hung.
Ideally, we move queryModelExtents off the main thread in the near future, in which case we will not need this call "await new Promise((resolve) => …
=> Free up event loop in getCustomViewState3dData RPC operation between calls to queryModelExtents

common/changes/@itwin/appui-react/master_2022-08-30-13-25.json, ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
This PR fixes an issue where tool settings widget is removed from the UI when saving/restoring the state.
=> Dock tool settings if tab is removed

common/changes/@bentley/build-tools/fix-cve_2022-08-30-10-34.json, common/config/rush/pnpm-lock.yaml, test-apps/display-performance-test-app/package.json, test-apps/ninezone-test-app/package.json, tools/build/package.json, tools/build/scripts/rush/audit.js
I had to do some semver-major upgrades on some packages, but I verified that any breaking changes they made were limited to things we don't use.
All the remaining issues come from `@bentley/react-scripts`, except [CVE-2022-31129](https://github.com/advisories/GHSA-wc69-rhjr-hc9g).
https://github.com/iTwin/itwinjs-backlog/issues/390
=> Fix some security issues in 2.19

common/changes/@itwin/appui-layout-react/widget-target-visibility_2022-09-08-15-37.json, ui/appui-layout-react/src/appui-layout-react/target/_variables.scss
Use higher elevation box-shadow to increase widget target visibility.
Before:
After:
=> Increase visibility of widget targets

common/config/azure-pipelines/jobs/fast-ci.yaml
Add the protected branch appui-4.0 to the list of branches that run the ci job.
=> Add appui-4.0 branch to CI job
