- common/changes/@bentley/geometry-core/master_2020-10-29-20-06.json
- core/geometry/src/curve/PointString3d.ts
- core/geometry/src/serialization/BGFBReader.ts
- core/geometry/src/serialization/BGFBWriter.ts
- core/geometry/src/test/serialization/FlatBuffer.test.ts
Read and Write PointString3d in flatbuffer
> Read and Write PointString3d in flatbuffer

- common/changes/@bentley/imodeljs-backend/native-2-8-8_2020-10-30-16-47.json
- common/config/azure-pipelines/templates/core-build.yaml
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
Update to @bentley/imodeljs-native@2.8.8 to consume bug fix for ECPresentation issue.
> Update to @bentley/imodeljs-native@2.8.8

- common/changes/@bentley/imodeljs-backend/native-2-8-9_2020-10-31-04-15.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
Pull in an additional update to the native library for the next patch release.
> Update to @bentley/imodeljs-native@2.8.9

- common/config/azure-pipelines/templates/core-build.yaml
Hopefully the last change needed to fix this build.
> Fix 'rush change' condition order

- test-apps/display-performance-test-app/README.md
Added instructions for hilite/emphasis changes and also made some small markdown fixes to the README.md.
> Updated for hilite/emphasis + small markdown fixes

- common/api/imodeljs-backend.api.md
- common/changes/@bentley/imodeljs-backend/bind-id-set_2020-11-06-17-26.json
- core/backend/src/ECSqlStatement.ts
- core/backend/src/test/standalone/ECSqlStatement.test.ts
(cherry picked from commit d31b2725757bef7b408480e004daa3a332ff6e4d)
> bindidset support and tests

- common/changes/@bentley/ecschema-metadata/koq-inverted-fix_2020-11-10-14-56.json
- core/ecschema-metadata/src/Metadata/KindOfQuantity.ts
- core/ecschema-metadata/test/Metadata/KindOfQuantity.test.ts
- core/ecschema-metadata/test/TestUtils/FormatTestHelper.ts
A recent change introduced a bug where InvertedUnits are not deserialized properly.  This PR addresses the issue.
> KindOfQuantity InvertedUnit deserialization fix

- common/config/azure-pipelines/integration-pr-validation.yaml
- common/config/azure-pipelines/jobs/fast-ci.yaml
- common/config/azure-pipelines/jobs/regression-testing.yaml
Incorrectly using `releases/*` instead of `release/*`.
> Fix pr triggers for the release branch

- common/api/ui-core.api.md
- common/changes/@bentley/ui-core/ui-auto-suggest_2020-11-10-14-45.json
- ui/core/src/test/autosuggest/AutoSuggest.test.tsx
- ui/core/src/ui-core/autosuggest/AutoSuggest.tsx
* Added AutoSuggest props - renderInputComponent, renderSuggestionsContainer, onSuggestionsClearRequested
* extract-api
* Change log
* Fixed AutoSuggest unit test warning
* Made new props @internal. Calling onSuggestionsClearRequested outside of setState.
* extract-api
* Fixed lint issue after merge
> Ui/auto suggest (#206)

- common/changes/@bentley/presentation-backend/presentation-enter-request-context-at-correct-place_2020-12-01-15-32.json
- presentation/backend/src/presentation-backend/NativePlatform.ts
Response polling logs were associated with invalid requests
> Presentation: Enter request context in a correct scope

- common/changes/@bentley/imodeljs-frontend/geo-wms_getfeatureinfo_bugfix_2020-12-04-20-26.json
- core/frontend/src/tile/map/MapLayerImageryFormats.ts
Fixed an issue where WMS GetFeatureInfo would not work correctly on all sublayers.
> Geo/wms getfeatureinfo bugfix (#369)

- common/api/presentation-common.api.md
- common/changes/@bentley/presentation-common/presentation-include-all-field-properties-into-field-descriptor_2020-12-11-11-52.json
- presentation/common/src/presentation-common/PresentationRpcInterface.ts
- presentation/common/src/presentation-common/content/Fields.ts
- presentation/common/src/test/content/Fields.test.ts
Properties field descriptor is expected to match any field that has at least one property in common.
imodel02 PR !132490
> Presentation: Include all field properties into field descriptor

- common/api/imodeljs-common.api.md
- common/changes/@bentley/imodeljs-backend/native-2.10.8_2020-12-18-00-38.json
- common/changes/@bentley/imodeljs-common/fix-planar-uv-params_2020-12-16-15-09.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/common/src/tile/IModelTileIO.ts
- full-stack-tests/core/src/frontend/standalone/Render.test.ts
Includes a few fixes already in 2.9.9 for presentation and a fix to tile generation that requires a tile version bump.
> Update to @bentley/imodeljs-native@2.10.8

- common/changes/@bentley/webpack-tools-core/fix-exports-webpack-plugin_2020-12-29-20-55.json
- tools/webpack-core/src/plugins/IModeljsLibraryExportsPlugin.ts
* remove extra json.stringify
* Rush change
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
> Fix exports webpack plugin (#508)

- common/api/imodeljs-backend.api.md
- common/api/imodeljs-common.api.md
- common/api/summary/imodeljs-backend.exports.csv
- common/changes/@bentley/imodeljs-backend/vc-prop-checksums_2021-01-13-14-21.json
- common/changes/@bentley/imodeljs-common/vc-prop-checksums_2021-01-13-14-21.json
- core/backend/src/ChangedElementsDb.ts
- core/backend/src/test/integration/ChangedElements.test.ts
- core/common/src/ChangedElements.ts
Handle property checksums generated in new addon code
> Version compare: property checksums

- common/changes/@bentley/ui-framework/ui-prompt-at-cursor-lag_2021-01-14-18-38.json
- ui/framework/src/ui-framework/cursor/cursorprompt/CursorPrompt.tsx
Fixes "Prompt at Cursor" lag reported by Design Review team
> Preventing cursor prompt lag

- common/api/electron-manager.api.md
- common/changes/@bentley/electron-manager/allow-dialog-electron_2021-01-19-14-40.json
- core/electron-manager/src/ElectronBackend.ts
- core/electron-manager/src/ElectronFrontend.ts
- core/electron-manager/src/ElectronIpcTransport.ts
- test-apps/display-test-app/src/frontend/FileOpen.ts
also, Ipc for Electron was broken.
> allow calling safe electron methods from frontend

- common/changes/@bentley/imodeljs-backend/fix-guid-mismatch_2021-01-21-14-24.json
- common/changes/@bentley/imodeljs-backend/revert-fix-contextid_2021-01-21-16-03.json
- core/backend/src/CheckpointManager.ts
Bring the two PRs from the 2.11 release to master.  #620 and #624
> Fix mis-matched Guid between iModel and iModelHub

- common/changes/@bentley/imodeljs-backend/partial-update-tests_2021-01-22-20-25.json
- core/backend/src/IModelDb.ts
- core/backend/src/test/standalone/IModel.test.ts
- docs/changehistory/NextVersion.md
Improve partial update tests, react to native FromJson changes
> Partial update tests

- common/api/imodeljs-frontend.api.md
- common/api/summary/imodeljs-frontend.exports.csv
- common/changes/@bentley/imodeljs-frontend/thematic-terrain-slope-and-hillshade_2021-01-25-16-37.json
- core/frontend/src/DisplayStyleState.ts
- core/frontend/src/render/primitives/mesh/TerrainMeshPrimitive.ts
- core/frontend/src/render/webgl/AttributeMap.ts
- core/frontend/src/render/webgl/BranchUniforms.ts
- core/frontend/src/render/webgl/DrawCommand.ts
- core/frontend/src/render/webgl/TerrainMesh.ts
- core/frontend/src/render/webgl/glsl/Surface.ts
- core/frontend/src/render/webgl/glsl/TerrainMesh.ts
- core/frontend/src/render/webgl/glsl/Thematic.ts
- core/frontend/src/tile/map/CesiumTerrainProvider.ts
- core/frontend/src/tile/map/MapTileTree.ts
Added support for thematic slope and hillshade modes to terrain.
> Thematic terrain slope and hillshade

- docs/changehistory/NextVersion.md
Fix broken API link in NextVersion.md for external-textures
> Fix broken API link in NextVersion.md for external-textures

- docs/learning/ECSQLTutorial/BuiltInFunctions.md
- docs/learning/ECSQLTutorial/ChangeSummaryQueries.md
- docs/learning/ECSQLTutorial/ConditionalExpr.md
- docs/learning/ECSQLTutorial/TypeFilter.md
> Fixed Previous and Next links in ECSQL tutorial

- presentation/backend/src/presentation-backend/NativePlatform.ts
- presentation/backend/src/presentation-backend/PresentationManager.ts
- test-apps/presentation-test-app/src/backend/main.ts
Associated imodel02 PR: !140885.
> Presentation: Enable an option for backend to use memory mapped i/o for worker SQLite connections

- common/changes/@bentley/ui-framework/updateAdditionalSyncUiCases_2021-02-01-19-23.json
- docs/changehistory/NextVersion.md
- ui/framework/src/test/syncui/SyncUiEventDispatcher.test.ts
- ui/framework/src/ui-framework/backstage/BackstageComposer.tsx
- ui/framework/src/ui-framework/hooks/useActiveIModelConnection.tsx
- ui/framework/src/ui-framework/statusbar/StatusBarComposer.tsx
- ui/framework/src/ui-framework/syncui/BooleanListener.tsx
- ui/framework/src/ui-framework/syncui/SyncUiEventDispatcher.ts
- ui/framework/src/ui-framework/toolbar/ActionItemButton.tsx
- ui/framework/src/ui-framework/toolbar/GroupItem.tsx
- ui/framework/src/ui-framework/toolbar/PopupButton.tsx
- ui/framework/src/ui-framework/toolbar/ToolButton.tsx
- ui/framework/src/ui-framework/toolbar/Toolbar.tsx
- ui/framework/src/ui-framework/widgets/WidgetDef.tsx
Additional work to support making SyncEventId checking case insensitive. This builds on the work from PR#693.
> Additional work to support case insensitive SyncEventId checking

- common/changes/@bentley/bentleyjs-core/fix-64-bit-arithmetic_2021-02-03-13-20.json
- core/bentley/src/CompressedId64Set.ts
- core/bentley/src/test/Id.test.ts
If only a language running primarily on 64-bit hardware could efficiently add two 64-bit integers. One can dream...
> Fix 64-bit addition.

- common/changes/@bentley/bentleyjs-core/fix-64-bit-arithmetic_2021-02-03-13-20.json
- core/bentley/src/CompressedId64Set.ts
- core/bentley/src/test/Id.test.ts
(cherry picked from commit fac144502c51501174e5d92f6fb07800b9a87c87)
> Fix 64-bit addition. (bp #703) 2.10.0

- common/api/ui-core.api.md
- common/changes/@bentley/ui-core/ui-floating-widget-opacity_2021-02-10-14-54.json
- common/changes/@bentley/ui-ninezone/ui-floating-widget-opacity_2021-02-10-14-54.json
- test-apps/ui-test-app/public/locales/en/SampleApp.json
- test-apps/ui-test-app/src/frontend/AppUiSettings.ts
- test-apps/ui-test-app/src/frontend/appui/frontstages/Settings.tsx
- test-apps/ui-test-app/src/frontend/appui/frontstages/component-examples/ComponentExamplesProvider.tsx
- ui/core/src/test/slider/Slider.test.tsx
- ui/core/src/ui-core/slider/Slider.tsx
- ui/ninezone/src/ui-ninezone/widget/FloatingWidget.scss
Added support for Floating widget opacity for UI 2.0. 
Added Slider formatMin, formatMax props.
Added Widget Opacity slider to ui-test-app Settings page.
> Floating widget opacity for UI 2.0

- common/api/imodeljs-frontend.api.md
- common/changes/@bentley/imodeljs-frontend/dpta-record-tile-ids_2021-02-08-13-22.json
- core/frontend/src/tile/IModelTile.ts
- core/frontend/src/tile/Tile.ts
- test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts
> Backport #725 to revert minor tile selection change

- docs/changehistory/NextVersion.md
- docs/learning/presentation/ECExpressions.md
imodel02 PR that introduces documented changes: !143718
> Presentation: Docs for instance context method improvements

- test-apps/display-test-app/src/backend/SetToStandalone.ts
should only be run with briefcase owner's permission.
> add utility to display-test-app to set a briefcase to be standalone for testing

- common/api/imodeljs-common.api.md
- common/changes/@bentley/imodeljs-common/fix-planar-clip-mask-docs_2021-02-19-10-59.json
- common/changes/@bentley/ui-components/fix-planar-clip-mask-docs_2021-02-19-11-46.json
- core/common/src/DisplayStyleSettings.ts
- core/common/src/PlanarClipMask.ts
- ui/components/package.json
Docs build for #754 failed to catch several invalid links. Errors are blocking #804.
> Clean up planar clip mask docs

- common/api/presentation-common.api.md
- common/changes/@bentley/presentation-common/presentation-typeName-lowercase_2021-03-02-13-38.json
- common/changes/@bentley/presentation-components/presentation-typeName-lowercase_2021-03-02-13-38.json
- presentation/common/src/presentation-common/EC.ts
- presentation/components/src/presentation-components/common/ContentBuilder.ts
- presentation/components/src/test/common/ContentBuilder.test.snap
- presentation/components/src/test/propertygrid/DataProvider.test.snap
Addon PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/147521
> TypeName to lowerCase

- full-stack-tests/presentation/scripts/setup-tests.js
- full-stack-tests/presentation/src/IntegrationTests.ts
- full-stack-tests/presentation/src/backend/PresentationManager.test.ts
- presentation/backend/src/presentation-backend/RulesetEmbedder.ts
- presentation/backend/src/test/RulesetEmbedder.test.ts
- presentation/frontend/src/presentation-frontend/PresentationManager.ts
- presentation/frontend/src/test/PresentationManager.test.ts
> Presentation: Fix issues found through additional logs

- common/api/imodeljs-frontend.api.md
- common/changes/@bentley/imodeljs-frontend/fix-turn-camera-on_2021-03-04-19-40.json
- core/frontend/src/Viewport.ts
> Viewport.turnCameraOn invokes setupFromView; add turnCameraOff.

- core/backend/src/TxnManager.ts
Add stub of method invoked by addon, to be completed in separate PR.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/151237)
> Fix for native/2.14.3

- common/changes/@bentley/ui-core/listboxFix_2021-03-16-18-30.json
- ui/core/src/test/listbox/listbox.test.tsx
- ui/core/src/ui-core/listbox/Listbox.tsx
Fix to ensure listbox is rerendered when selectedVaue prop is changed.
> Fix for listbox not rerendering when selectedVaue prop is changed

- common/api/presentation-components.api.md
- common/changes/@bentley/presentation-common/presentation-fix-categorized-aspect-properties-display_2021-03-15-08-54.json
- common/changes/@bentley/presentation-components/presentation-fix-categorized-aspect-properties-display_2021-03-23-07-07.json
- common/changes/@bentley/presentation-testing/presentation-fix-categorized-aspect-properties-display_2021-03-23-07-07.json
- presentation/common/src/presentation-common/content/Fields.ts
- presentation/common/src/test/_helpers/Content.ts
- presentation/common/src/test/_helpers/EC.ts
- presentation/components/src/presentation-components/common/ContentBuilder.ts
- presentation/components/src/presentation-components/propertygrid/DataProvider.ts
- presentation/components/src/presentation-components/table/DataProvider.ts
- presentation/components/src/test/common/ContentBuilder.test.snap
- presentation/components/src/test/common/ContentBuilder.test.ts
- presentation/components/src/test/propertygrid/DataProvider.test.snap
- presentation/components/src/test/propertygrid/DataProvider.test.ts
- presentation/testing/src/presentation-testing/ContentBuilder.ts
Refactor mapping from presentation type of content to UI type of content
> Presentation: Fix categorized aspect properties display

- common/api/hypermodeling-frontend.api.md
- common/api/summary/hypermodeling-frontend.exports.csv
- common/changes/@bentley/hypermodeling-frontend/promote-hypermodeling-apis_2021-04-01-11-05.json
- core/hypermodeling/src/HyperModeling.ts
- core/hypermodeling/src/HyperModelingConfig.ts
- core/hypermodeling/src/HyperModelingDecorator.ts
- core/hypermodeling/src/SectionDrawingLocationState.ts
- core/hypermodeling/src/SectionGraphicsProvider.ts
- core/hypermodeling/src/SectionMarkerHandler.ts
- core/hypermodeling/src/SectionMarkers.ts
- docs/changehistory/NextVersion.md
All are public. Add start/stop methods.
> Promote hypermodeling APIs.

- common/api/imodeljs-frontend.api.md
- common/api/summary/imodeljs-frontend.exports.csv
- common/changes/@bentley/imodeljs-frontend/promote-globe-tools-api-public_2021-04-01-14-08.json
- core/frontend/src/tools/ViewTool.ts
- docs/changehistory/NextVersion.md
Promote globe view tools to public.
> Promote globe tools API to public

- common/changes/@bentley/imodeljs-frontend/fix-silhouettes-2_2021-04-06-17-00.json
- core/frontend/src/render/webgl/glsl/Edge.ts
Added a tolerance on silhouette determination to make the flickering of some silhouettes more stable.
> Fix silhouettes 2

- common/api/imodeljs-frontend.api.md
- common/api/summary/imodeljs-frontend.exports.csv
- common/changes/@bentley/imodeljs-editor-frontend/accudraw-api_2021-04-08-14-30.json
- common/changes/@bentley/imodeljs-frontend/accudraw-api_2021-04-08-14-30.json
- core/frontend/src/AccuDraw.ts
- core/frontend/src/ViewContext.ts
- core/frontend/src/tools/ClipViewTool.ts
- core/frontend/src/tools/EditManipulator.ts
- core/frontend/src/tools/ElementSetTool.ts
- core/frontend/src/tools/MeasureTool.ts
- editor/frontend/src/TransformElementsTool.ts
- test-apps/display-test-app/src/frontend/App.ts
- test-apps/display-test-app/src/frontend/EditingTools.ts
- test-apps/display-test-app/src/frontend/SectionTools.ts
- test-apps/display-test-app/src/frontend/TimePointComparison.ts
- test-apps/ui-test-app/src/frontend/tools/editing/PlaceBlockTool.ts
- test-apps/ui-test-app/src/frontend/tools/editing/PlaceLineStringTool.ts
Note: Matrix3d use is expected column format, not rows historically used by AccuDraw.
* Use grid plane loop points from GridInViewContext in case shader doesn't work out...
> Make AccuDrawHintBuilder public and include everything needed by an InteractiveTool.

- common/api/imodeljs-frontend.api.md
- common/api/summary/imodeljs-frontend.exports.csv
- common/changes/@bentley/frontend-devtools/sync-viewports-tool_2021-04-09-08-33.json
- common/changes/@bentley/imodeljs-frontend/sync-viewports-tool_2021-04-09-08-33.json
- common/changes/@bentley/ui-framework/sync-viewports-tool_2021-04-09-08-33.json
- core/frontend-devtools/src/effects/EffectTools.ts
- core/frontend-devtools/src/tools/FrustumDecoration.ts
- core/frontend-devtools/src/widgets/MemoryTracker.ts
- core/frontend-devtools/src/widgets/TileMemoryBreakdown.ts
- core/frontend/src/AccuDraw.ts
- core/frontend/src/IModelConnection.ts
- core/frontend/src/ViewManager.ts
- test-apps/display-test-app/README.md
- test-apps/display-test-app/public/locales/en/SVTTools.json
- test-apps/display-test-app/src/frontend/App.ts
- test-apps/display-test-app/src/frontend/FpsMonitor.ts
- test-apps/display-test-app/src/frontend/SyncViewportsTool.ts
- test-apps/display-test-app/src/frontend/TileLoadIndicator.ts
- ui/framework/src/test/imodel-components/category-tree/CategoriesVisibilityHandler.test.ts
- ui/framework/src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx
- ui/framework/src/ui-framework/pickers/ModelSelector/ModelSelector.tsx
Added for diagnosing [this bug](https://dev.azure.com/bentleycs/iModelTechnologies/_workitems/edit/592522).
Also adds an iterator to ViewManager and deprecates `forEachViewport`.
> Sync viewports tool (display-test-app)

- common/api/ecschema-rpcinterface-common.api.md
- common/changes/@bentley/ecschema-rpcinterface-common/rpc-schema-locater_2021-04-12-17-40.json
- core/ecschema-rpc/common/src/ECSchemaRpcLocater.ts
- core/ecschema-rpc/common/src/ecschema-rpc-interface.ts
@593660 
A simple implementation of a schema locater using a RPC interface.
> Initial pass at schema rpc locater

- common/api/imodeljs-backend.api.md
- common/api/summary/imodeljs-backend.exports.csv
- common/changes/@bentley/imodeljs-backend/ts-change-events_2021-04-14-11-02.json
- core/backend/src/Category.ts
- core/backend/src/Element.ts
- core/backend/src/ElementAspect.ts
- core/backend/src/IModelDb.ts
- core/backend/src/Model.ts
- core/backend/src/test/assets/TestFunctional.ecschema.xml
- core/backend/src/test/standalone/FunctionalDomain.test.ts
- docs/changehistory/NextVersion.md
Adds events for notifying parent elements of modifications to their children.
requires [this iModel02 PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/157099)
> call element, model, and aspect events from native code.

- common/changes/@bentley/imodeljs-frontend/fix-has-same-coordinates_2021-04-15-19-50.json
- core/frontend/src/ViewState.ts
- full-stack-tests/core/src/frontend/standalone/ViewState.test.ts
[Bug](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/595697?src=WorkItemMention&src-action=artifact_link).
> Fix ViewState.hasSameCoordinates for model selector containing 2d model

- common/api/imodeljs-backend.api.md
- common/api/summary/imodeljs-backend.exports.csv
- common/api/ui-framework.api.md
- common/changes/@bentley/imodeljs-backend/ts-change-events_2021-04-14-11-02.json
- common/changes/@bentley/map-layers/native-2.16.0_2021-04-16-17-38.json
- common/changes/@bentley/ui-components/native-2.16.0_2021-04-16-17-38.json
- common/changes/@bentley/ui-core/native-2.16.0_2021-04-16-17-38.json
- common/changes/@bentley/ui-framework/native-2.16.0_2021-04-16-17-38.json
- common/changes/@bentley/ui-ninezone/native-2.16.0_2021-04-16-17-38.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/backend/src/Category.ts
- core/backend/src/Element.ts
- core/backend/src/ElementAspect.ts
- core/backend/src/IModelDb.ts
- core/backend/src/Model.ts
- core/backend/src/test/assets/TestFunctional.ecschema.xml
- core/backend/src/test/standalone/FunctionalDomain.test.ts
- core/backend/src/test/standalone/TxnManager.test.ts
- docs/changehistory/NextVersion.md
- extensions/iot-demo/package.json
- extensions/map-layers/package.json
- test-apps/ninezone-test-app/package.json
- test-apps/ui-test-app/package.json
- test-apps/ui-test-extension/package.json
- ui/components/package.json
- ui/core/package.json
- ui/framework/package.json
- ui/ninezone/package.json
Locked down version of classnames and @types/react-autosuggest packages pending investigation by UI team.
Skipped test that fails due to change in behavior made by @swwilson-bsi - he will revisit - new behavior is correct.
> @bentley/imodeljs-native 2.16.0

- common/changes/@bentley/imodeljs-frontend/fix-solid-fill-materials_2021-04-21-13-41.json
- core/frontend/src/render/webgl/Mesh.ts
- core/frontend/src/render/webgl/glsl/Surface.ts
[Bug](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/600367).
We were checking ViewFlags.material but ignoring render mode.
> Ignore materials unless smooth render mode

- clients/reality-data/src/test/integration/RealityDataClient.test.ts
- common/changes/@bentley/reality-data-client/reality-data-client-test-fix_2021-04-21-22-01.json
Update reality data client tests to account for changes to RDS
> Fix reality data client tests

- common/api/presentation-common.api.md
- common/api/summary/presentation-common.exports.csv
- common/changes/@bentley/presentation-backend/presentation-schema-requirements_2021-04-22-07-06.json
- common/changes/@bentley/presentation-common/presentation-schema-requirements_2021-04-21-12-45.json
- docs/changehistory/NextVersion.md
- docs/learning/presentation/Content/ContentModifier.md
- docs/learning/presentation/Content/ContentRule.md
- docs/learning/presentation/Content/DefaultPropertyCategoryOverride.md
- docs/learning/presentation/Customization/CheckBoxRule.md
- docs/learning/presentation/Customization/ExtendedDataRule.md
- docs/learning/presentation/Customization/ImageIdOverride.md
- docs/learning/presentation/Customization/InstanceLabelOverride.md
- docs/learning/presentation/Customization/LabelOverride.md
- docs/learning/presentation/Customization/SortingRule.md
- docs/learning/presentation/Customization/StyleOverride.md
- docs/learning/presentation/Hierarchies/ChildNodeRule.md
- docs/learning/presentation/Hierarchies/GroupingRule.md
- docs/learning/presentation/Hierarchies/NodeArtifactsRule.md
- docs/learning/presentation/Hierarchies/RootNodeRule.md
- docs/learning/presentation/SchemaRequirements.md
- full-stack-tests/presentation/src/frontend/providers/PropertyPaneDataProvider.test.snap
- presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
- presentation/common/Ruleset.schema.json
- presentation/common/src/presentation-common/PresentationRpcInterface.ts
- presentation/common/src/presentation-common/rules/Rule.ts
- presentation/common/src/presentation-common/rules/SchemasSpecification.ts
- presentation/common/src/presentation-common/rules/hierarchy/SubCondition.ts
imodel02 PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/159178
> Presentation: Schema requirements

- common/api/presentation-common.api.md
- common/api/ui-abstract.api.md
- common/api/ui-components.api.md
- common/changes/@bentley/presentation-components/presentation-misc-fixes-for-properties-display_2021-04-26-05-02.json
- common/changes/@bentley/ui-abstract/presentation-misc-fixes-for-properties-display_2021-04-26-05-29.json
- common/changes/@bentley/ui-components/presentation-misc-fixes-for-properties-display_2021-04-26-05-29.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- full-stack-tests/presentation/src/frontend/providers/PropertyPaneDataProvider.test.snap
- presentation/backend/src/test/PresentationManager.test.snap
- presentation/common/src/presentation-common/content/Fields.ts
- presentation/common/src/test/_helpers/Content.ts
- presentation/common/src/test/content/Descriptor.test.snap
- presentation/common/src/test/content/Fields.test.snap
- presentation/common/src/test/content/Fields.test.ts
- presentation/components/package.json
- presentation/components/src/presentation-components/common/Utils.ts
- presentation/components/src/presentation-components/propertygrid/DataProvider.ts
- presentation/components/src/presentation-components/table/DataProvider.ts
- presentation/components/src/test/common/Utils.test.ts
- presentation/components/src/test/propertygrid/DataProvider.test.snap
- presentation/components/src/test/propertygrid/DataProvider.test.ts
- presentation/components/src/test/table/DataProvider.test.ts
- ui/abstract/src/ui-abstract/properties/Description.ts
- ui/components/src/test/propertygrid/component/internal/flat-items/CategorizedArrayProperty.test.ts
- ui/components/src/test/propertygrid/component/internal/flat-items/CategorizedStructProperty.test.ts
- ui/components/src/ui-components/propertygrid/internal/flat-items/MutableCategorizedArrayProperty.ts
- ui/components/src/ui-components/propertygrid/internal/flat-items/MutableCategorizedStructProperty.ts
- ui/components/src/ui-components/propertygrid/internal/flat-items/MutableFlatGridItem.ts
- Sort categories and fields based on priority and label rather than name
- Add ability to not render array/struct property label in virtualized property grid
- Expose relationship meaning through NestedContentField (required imodel02 PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/159776)
- Improve nested content destructuring:
- hide array record fields when they're the only record in list
- destructure "same instance" struct records even if they have sibling records
> Presentation: Misc. improvements for properties display

- core/backend/src/TxnManager.ts
- full-stack-tests/core/src/frontend/_Setup.test.ts
- full-stack-tests/core/src/frontend/standalone/BriefcaseTxns.test.ts
This PR depends on [this native PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/159974)
> Update TxnManager tests for multi-txn undo/redo

- test-apps/presentation-test-app/src/frontend/api/MyAppFrontend.ts
- test-apps/presentation-test-app/src/frontend/components/diagnostics-selector/DiagnosticsSelector.tsx
- test-apps/presentation-test-app/src/frontend/components/imodel-selector/IModelSelector.tsx
React to comments in #1289 which got accidentally merged before resolving them.
> Presentation: More presentation-test-app fixes

- common/api/ui-abstract.api.md
- common/changes/@bentley/ui-abstract/is-active-override_2021-04-27-09-02.json
- common/changes/@bentley/ui-framework/is-active-override_2021-04-27-09-02.json
- ui/abstract/src/ui-abstract/backstage/BackstageItem.ts
- ui/framework/src/test/backstage/BackstageComposer.test.snap
- ui/framework/src/test/backstage/BackstageComposerItem.test.tsx
- ui/framework/src/ui-framework/backstage/BackstageComposerItem.tsx
Adding ability to override isActive property for BackstageItem
> Adding ability to override isActive property for BackstageItem

- common/api/imodeljs-backend.api.md
- common/changes/@bentley/imodeljs-backend/version-compare-addon-update_2021-04-28-18-55.json
- core/backend/src/ChangedElementsDb.ts
- core/backend/src/ChangedElementsManager.ts
- core/backend/src/test/assets/Items.PresentationRuleSet.xml
- core/backend/src/test/integration/ChangedElements.test.ts
Update ChangedElementsDb, Manager and tests with new functionality and add presentation ruleset to test property output.
> Version Compare: Update for Addon Changes

- common/config/rush/pnpm-lock.yaml
- full-stack-tests/core/src/frontend/standalone/tile/TileIO.test.ts
- full-stack-tests/core/src/frontend/standalone/tile/TileRequest.test.ts
- full-stack-tests/core/src/frontend/standalone/tile/Tolerance.test.ts
> Fix fake view states

- common/changes/@bentley/presentation-components/presentation-fix-colors_2021-04-30-09-06.json
- full-stack-tests/presentation/src/frontend/Update.test.tsx
- full-stack-tests/presentation/src/frontend/providers/TreeDataProvider.test.snap
- presentation/components/src/presentation-components/common/StyleHelper.ts
- presentation/components/src/test/common/StyleHelper.test.ts
- presentation/components/src/test/tree/DataProvider.test.snap
- presentation/components/src/test/tree/FilteredDataProvider.test.snap
- presentation/components/src/test/tree/Utils.test.snap
`ui-components` expects colors in RGB format, we were setting in RGBA.
> Presentation: Fix wrong colors being assigned to objects

- common/changes/@bentley/imodeljs-backend/abandon-changes_2021-04-30-17-02.json
- core/backend/src/test/integration/IModelWrite.test.ts
relies on [this PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/161104)
> Re-enable test for Abandon changes

- common/api/imodeljs-backend.api.md
- common/changes/@bentley/imodeljs-backend/onInsert_2021-05-03-14-58.json
- core/backend/src/Element.ts
- core/backend/src/test/standalone/FunctionalDomain.test.ts
and update tests to reflect this changes.
requires [this PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/161363) of addon
> allow Element.onInsert and Element.onUpdate to modify properties

- test-apps/display-test-app/src/backend/Backend.ts
@khanaffan added an exclamation mark that threw during initialization of web backend.
> Fix display-test-app in browser

- common/api/imodeljs-frontend.api.md
- common/api/summary/imodeljs-frontend.exports.csv
- common/changes/@bentley/imodeljs-frontend/graphic-builder-primitive_2021-05-12-16-42.json
- core/frontend/src/imodeljs-frontend.ts
- core/frontend/src/render/GraphicBuilder.ts
- core/frontend/src/render/GraphicPrimitive.ts
- core/frontend/src/test/render/GraphicPrimitive.test.ts
@bbastings and @mdastous-bentley both recently expressed a desire for a generic type representing anything that can be added to a GraphicBuilder.
Added a union type GraphicPrimitive and GraphicBuilder.addPrimitive().
> GraphicPrimitive

- clients/frontend-authorization/src/oidc/browser/BrowserAuthorizationCallbackHandler.ts
- common/api/imodeljs-backend.api.md
- common/api/imodeljs-common.api.md
- common/api/summary/imodeljs-backend.exports.csv
- common/api/summary/imodeljs-common.exports.csv
- common/changes/@bentley/frontend-authorization-client/promote-BriefcaseManager_2021-05-13-16-40.json
- common/changes/@bentley/imodeljs-backend/promote-BriefcaseManager_2021-05-13-15-41.json
- common/changes/@bentley/imodeljs-common/promote-BriefcaseManager_2021-05-13-15-41.json
- core/backend/src/BriefcaseManager.ts
- core/backend/src/ChangeSummaryManager.ts
- core/backend/src/CheckpointManager.ts
- core/backend/src/IModelDb.ts
- core/backend/src/perftest/Changeset.test.ts
- core/backend/src/test/integration/BriefcaseManager.test.ts
- core/backend/src/test/integration/ChangeSummary.test.ts
- core/common/src/BriefcaseTypes.ts
@pmconne this PR will generate conflicts with my unmerged iModel02 PR since I had to edit several methods here too. Let me know when ready and I will do the merge.
> Promote BriefcaseManager to @public

- common/api/presentation-common.api.md
- common/changes/@bentley/presentation-common/presentation-associate-content-items-with-input-keys_2021-05-19-10-16.json
- docs/changehistory/NextVersion.md
- full-stack-tests/presentation/src/frontend/Content.test.ts
- presentation/common/src/presentation-common/content/Descriptor.ts
- presentation/common/src/presentation-common/content/Item.ts
- presentation/common/src/test/content/Item.test.ts
Related imode02 PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/164880
> Presentation: Associate content item with input keys

- common/api/imodeljs-editor-frontend.api.md
- common/api/summary/imodeljs-editor-frontend.exports.csv
- common/changes/@bentley/imodeljs-editor-frontend/create-arc-tool_2021-05-25-13-43.json
- common/changes/@bentley/imodeljs-frontend/create-arc-tool_2021-05-25-13-43.json
- core/frontend/src/tools/ToolAdmin.ts
- editor/frontend/src/CreateElementTool.ts
- editor/frontend/src/EditTool.ts
- editor/frontend/src/SketchTools.ts
- editor/frontend/src/public/locales/en/Editor.json
Ensure tools always get motion event before decorate or onDynamicFrame.
> Added arc by 3 points tool.

- common/api/imodeljs-editor-frontend.api.md
- common/api/imodeljs-frontend.api.md
- common/api/summary/imodeljs-frontend.exports.csv
- common/changes/@bentley/imodeljs-editor-frontend/edit-manipulator_2021-05-27-17-33.json
- common/changes/@bentley/imodeljs-frontend/edit-manipulator_2021-05-27-17-33.json
- core/frontend/src/AccuDraw.ts
- core/frontend/src/Viewport.ts
- core/frontend/src/tools/ClipViewTool.ts
- core/frontend/src/tools/EditManipulator.ts
- core/frontend/src/tools/ElementSetTool.ts
- core/frontend/src/tools/Tool.ts
- core/frontend/src/tools/ViewTool.ts
- editor/frontend/src/CreateElementTool.ts
Sunand's group has a requirement to modify faces of transient "box" similar to how the view clip controls work.
> Make EditManipulator public

- common/api/presentation-backend.api.md
- common/api/presentation-common.api.md
- common/api/summary/presentation-backend.exports.csv
- common/changes/@bentley/presentation-backend/presentation-ruleset-versioning_2021-05-27-06-20.json
- common/changes/@bentley/presentation-backend/presentation-ruleset-versioning_2021-05-31-08-48.json
- common/changes/@bentley/presentation-common/presentation-ruleset-versioning_2021-05-27-06-45.json
- full-stack-tests/presentation/src/backend/RulesetsEmbedding.test.ts
- presentation/backend/package.json
- presentation/backend/src/presentation-backend/RulesetEmbedder.ts
- presentation/backend/src/presentation-backend/Utils.ts
- presentation/backend/src/presentation-backend/domain/RulesetElements.ts
- presentation/backend/src/test/RulesetEmbedder.test.ts
- presentation/backend/src/test/Utils.test.ts
- presentation/common/Ruleset.schema.json
- presentation/common/src/presentation-common/rules/Ruleset.ts
Introduce `version` attribute for `Ruleset`. Take it into account when embedding rulesets.
Also, _PresentationRules_ model and partition should be marked private.
Related imodel02 PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/167554
> Presentation: Ruleset versioning

- common/changes/@bentley/imodeljs-backend/set-imodel-gcs_2021-06-04-02-37.json
- core/backend/src/test/standalone/IModel.test.ts
Fixed UpdateIModelProps() so it actually updates geographicCoordinateSystem properties.
Tests to go with AddOn changes Pull Request https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/167876
> Set imodel gcs

- test-apps/ui-test-app/src/frontend/appui/frontstages/ViewsFrontstage.tsx
- test-apps/ui-test-app/src/frontend/appui/frontstages/component-examples/ComponentExamples.tsx
- test-apps/ui-test-app/src/frontend/index.tsx
- test-apps/ui-test-app/src/frontend/tools/UiProviderTool.tsx
Update pop-out window example in ui-test-app to show all example components.  This will make it easier to find and debug components that don't work properly in pop-out windows.
> Update pop-out window example in ui-test-app

- common/api/presentation-backend.api.md
- common/api/presentation-common.api.md
- common/api/presentation-frontend.api.md
- common/api/summary/presentation-common.exports.csv
- common/changes/@bentley/presentation-backend/presentation-ruleset-variable-fixes_2021-06-04-13-29.json
- common/changes/@bentley/presentation-backend/presentation-ruleset-variable-fixes_2021-06-07-06-17.json
- common/changes/@bentley/presentation-common/presentation-ruleset-variable-fixes_2021-06-07-06-17.json
- common/changes/@bentley/presentation-components/presentation-ruleset-variable-fixes_2021-06-07-06-17.json
- common/changes/@bentley/presentation-frontend/presentation-ruleset-variable-fixes_2021-06-07-06-17.json
- presentation/backend/src/presentation-backend/NativePlatform.ts
- presentation/backend/src/presentation-backend/PresentationIpcHandler.ts
- presentation/backend/src/presentation-backend/PresentationRpcImpl.ts
- presentation/backend/src/presentation-backend/RulesetVariablesManager.ts
- presentation/backend/src/test/NativePlatform.test.ts
- presentation/backend/src/test/PresentationIpcHandler.test.ts
- presentation/backend/src/test/PresentationRpcImpl.test.ts
- presentation/backend/src/test/RulesetVariablesManager.test.ts
- presentation/common/src/presentation-common/PresentationIpcInterface.ts
- presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts
- presentation/components/src/test/tree/controlled/TreeHooks.test.ts
- presentation/frontend/src/presentation-frontend/IpcRequestsHandler.ts
- presentation/frontend/src/presentation-frontend/RulesetVariablesManager.ts
- presentation/frontend/src/test/IpcRequestsHandler.test.ts
- presentation/frontend/src/test/RulesetVariablesManager.test.ts
related imodel02 PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/169140
> Presentation: Ruleset variable fixes

- common/api/ecschema-metadata.api.md
- common/api/summary/ecschema-metadata.exports.csv
- common/changes/@bentley/ecschema-metadata/ecname-validation_2021-06-07-15-02.json
- core/ecschema-metadata/src/Deserialization/JsonParser.ts
- core/ecschema-metadata/src/Deserialization/XmlParser.ts
- core/ecschema-metadata/src/ECName.ts
- core/ecschema-metadata/src/Metadata/Enumeration.ts
- core/ecschema-metadata/src/Metadata/Property.ts
- core/ecschema-metadata/src/Metadata/Schema.ts
- core/ecschema-metadata/src/SchemaKey.ts
- core/ecschema-metadata/src/ecschema-metadata.ts
- core/ecschema-metadata/src/test/Metadata/ECName.test.ts
@ramanujam-raman claims this is needed urgently by a user; another user requested it a while ago in github discussions.
Also promotes ECName to `@public`.
> Functions to encode and decode ECNames

- common/changes/@bentley/imodeljs-common/remove-only_2021-06-08-13-47.json
- core/common/src/test/MapLayerSettings.test.ts
CI job is supposed to catch this, I thought.
> Remove .only

- common/changes/@bentley/imodeljs-backend/native-2.17.5_2021-06-08-15-57.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
Note: this is going to be a normal squash as there are no changes on `imodel02` branch.
> @bentley/imodeljs-native 2.17.5

- docs/changehistory/2.16.0.md
- docs/changehistory/index.md
Add missing breaking change documentation for PopupInfo per request from Jason Crow.
> Add missing breaking change documentation for PopupInfo.

- common/changes/@bentley/imodeljs-backend/native-2.10.13_2021-06-09-12-34.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
Backporting a native fix for ECSql busy handling.
> Update to @bentley/imodeljs-native@2.10.13

- test-apps/ui-test-app/src/frontend/appui/statusfields/DisplayStyleField.tsx
- ui/framework/src/ui-framework.ts
- ui/framework/src/ui-framework/content/DefaultViewOverlay.tsx
- ui/framework/src/ui-framework/hooks/useActiveViewport.tsx
- ui/framework/src/ui-framework/hooks/useAnalysisAnimationDataProvider.tsx
- ui/framework/src/ui-framework/hooks/useScheduleAnimationDataProvider.tsx
- ui/framework/src/ui-framework/hooks/useSolarDataProvider.tsx
clean-up hooks
fix setting display style
fix setting state on unmounted scrubber
> Updates to timeline branch

- docs/learning/tutorials/develop-desktop-viewer.md
- More changes in desktop-starter main.ts requiring documentation changes
> desktop-starter build steps updated

- docs/learning/index.md
addresses [this issue](https://github.com/imodeljs/imodeljs/issues/1673)
> update index.md to clarify that iTwin.js can work on snapshots.

- common/api/imodeljs-editor-frontend.api.md
- common/api/summary/imodeljs-editor-frontend.exports.csv
- common/changes/@bentley/imodeljs-editor-frontend/more-sketch-tools_2021-06-18-20-02.json
- editor/frontend/src/EditTool.ts
- editor/frontend/src/SketchTools.ts
- editor/frontend/src/TransformElementsTool.ts
- editor/frontend/src/public/locales/en/Editor.json
Use Bill's new api for lock toggle + text field.
> Create circle, ellipse, and rectangle tools.

- common/changes/@bentley/imodeljs-backend/IModelTransformer-relationship-delete-fix_2021-06-28-17-27.json
- core/backend/src/IModelTransformer.ts
- test-apps/imodel-transformer/src/Main.ts
- test-apps/imodel-transformer/src/Transformer.ts
Also, the imodel-transformer test app is now better prepared to test the processing of changes.
> Fix for IModelTransformer relationship delete propagation

- test-apps/display-test-app/src/frontend/AnalysisStyleExample.ts
For sprint review demo and subsequent port to frontend sample showcase.
> Tweak analysis example

- common/api/presentation-common.api.md
- common/changes/@bentley/presentation-backend/presentation-RelatedPropertiesSpecification.skipIfDuplicate_2021-07-07-07-51.json
- common/changes/@bentley/presentation-common/presentation-RelatedPropertiesSpecification.skipIfDuplicate_2021-07-07-07-51.json
- docs/changehistory/NextVersion.md
- docs/learning/presentation/Content/RelatedPropertiesSpecification.md
- presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
- presentation/common/Ruleset.schema.json
- presentation/common/src/presentation-common/rules/content/modifiers/RelatedPropertiesSpecification.ts
Related imodel02 PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/176543
> Add `RelatedPropertiesSpecification.skipIfDuplicate` attribute

- docs/changehistory/NextVersion.md
@kabentley erroneously deleted the contents of NextVersion.md in his most recent PR.
> Reinstate contents of NextVersion.md

- common/changes/@bentley/backend-itwin-client/skip-hanging-test_2021-07-15-14-09.json
- core/backend-itwin-client/src/test/FileHandlers.test.ts
> Skip test that hangs on linux

- common/api/imodeljs-common.api.md
- common/api/summary/imodeljs-common.exports.csv
- common/changes/@bentley/imodeljs-backend/offset-body_2021-07-15-17-43.json
- common/changes/@bentley/imodeljs-common/offset-body_2021-07-15-17-43.json
- core/backend/src/test/standalone/GeometryStream.test.ts
- core/common/src/geometry/ElementGeometry.ts
https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/178723
> Add offset body operation for IFC connector.

- common/changes/@bentley/imodeljs-backend/subtract-consumes-target_2021-07-16-13-19.json
- core/backend/src/test/standalone/GeometryStream.test.ts
https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/178992
> Correctly handle case where subtract operation consumes target body.

- common/api/imodeljs-editor-frontend.api.md
- common/api/summary/imodeljs-editor-frontend.exports.csv
- common/changes/@bentley/imodeljs-editor-frontend/bcurve-tool_2021-07-16-15-34.json
- editor/frontend/src/EditTool.ts
- editor/frontend/src/SketchTools.ts
- editor/frontend/src/public/locales/en/Editor.json
Will enhance to include support for InterpolationCurve3d when it becomes available.
> Create open pole based bcurve. Move decoration pick and construction curves to base class.

- common/changes/@bentley/imodeljs-backend/mass-props-worker-thread_2021-07-16-18-38.json
- core/backend/src/IModelDb.ts
https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/179106
> Use worker thread for mass properties calculations.

- common/api/imodeljs-backend.api.md
- common/changes/@bentley/imodeljs-backend/texture-image-worker_2021-07-21-19-44.json
- core/backend/src/IModelDb.ts
- core/backend/src/rpc-impl/IModelReadRpcImpl.ts
- core/backend/src/test/standalone/GetTextureImage.test.ts
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/180076)
> getTextureImage is async

- common/changes/@bentley/imodeljs-frontend/handle-degenerate-frustum_2021-07-22-16-00.json
- core/frontend/src/BackgroundMapGeometry.ts
(cherry picked from commit 93b33b535f40357051fb544526f49812b068f804)
> Handle undefined rotation (degenerate frustum crash)

- common/api/imodeljs-common.api.md
- common/api/imodeljs-frontend.api.md
- common/changes/@bentley/eslint-plugin/reality-tile-reprojection_2021-07-21-14-32.json
- common/changes/@bentley/imodeljs-common/reality-tile-reprojection_2021-07-21-14-32.json
- common/changes/@bentley/imodeljs-frontend/reality-tile-reprojection_2021-07-21-14-32.json
- core/common/src/Frustum.ts
- core/frontend/src/tile/RealityModelTileTree.ts
- core/frontend/src/tile/RealityTile.ts
- core/frontend/src/tile/RealityTileTree.ts
- core/frontend/src/tile/Tile.ts
- core/frontend/src/tile/map/ImageryTileTree.ts
- core/frontend/src/tile/map/MapTile.ts
- core/frontend/src/tile/map/MapTileTree.ts
(cherry picked from commit 93b33b535f40357051fb544526f49812b068f804)
Co-authored-by: Ray.Bentley <rbbentley@users.noreply.github.com>
> Reality tile reprojection (#1906)

- common/changes/@bentley/ui-ninezone/ui-popout-fix-backport_2021-07-26-16-18.json
- ui/ninezone/src/ui-ninezone/base/NineZoneState.ts
Initialize popout window size and position when popping out from floating state to avoid crash.
> Initialize popout window when popping out from floating state

- common/api/presentation-backend.api.md
- common/api/presentation-common.api.md
- common/api/presentation-frontend.api.md
- common/api/summary/presentation-common.exports.csv
- common/changes/@bentley/presentation-backend/presentation-expose-getContentClasses-api_2021-08-03-06-33.json
- common/changes/@bentley/presentation-common/presentation-expose-getContentClasses-api_2021-08-03-06-33.json
- common/changes/@bentley/presentation-frontend/presentation-expose-getContentClasses-api_2021-08-03-06-33.json
- common/changes/@bentley/rpcinterface-full-stack-tests/presentation-expose-getContentClasses-api_2021-08-03-06-39.json
- full-stack-tests/presentation/src/frontend/Content.test.ts
- full-stack-tests/rpc-interface/src/frontend/PresentationRpc.test.ts
- presentation/backend/src/presentation-backend/NativePlatform.ts
- presentation/backend/src/presentation-backend/PresentationManager.ts
- presentation/backend/src/presentation-backend/PresentationRpcImpl.ts
- presentation/backend/src/test/PresentationManager.test.snap
- presentation/backend/src/test/PresentationManager.test.ts
- presentation/backend/src/test/PresentationRpcImpl.test.ts
- presentation/common/src/presentation-common/EC.ts
- presentation/common/src/presentation-common/PresentationManagerOptions.ts
- presentation/common/src/presentation-common/PresentationRpcInterface.ts
- presentation/common/src/presentation-common/RpcRequestsHandler.ts
- presentation/common/src/presentation-common/content/Descriptor.ts
- presentation/common/src/presentation-common/content/Fields.ts
- presentation/common/src/test/EC.test.ts
- presentation/common/src/test/PresentationRpcInterface.test.ts
- presentation/common/src/test/RpcRequestsHandler.test.ts
- presentation/common/src/test/_helpers/EC.ts
- presentation/common/src/test/content/Descriptor.test.snap
- presentation/common/src/test/content/Descriptor.test.ts
- presentation/frontend/src/presentation-frontend/PresentationManager.ts
- presentation/frontend/src/test/PresentationManager.test.ts
imodel02: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/182801
> Presentation: Expose an API to get content sources

- common/changes/@bentley/extension-cli/update-tar-dep_2021-08-04-10-19.json
- common/changes/@bentley/presentation-components/bp-release-2.19.x-pr-1987_2021-08-04-12-55.json
- common/changes/@bentley/ui-framework/bp-release-2.19.x-pr-1987_2021-08-04-12-06.json
- common/config/rush/pnpm-lock.yaml
- presentation/components/package.json
- tools/extension-cli/package.json
- ui/framework/package.json
(cherry picked from commit 93b33b535f40357051fb544526f49812b068f804)
> Update tar dependency (backport #1987)

- common/changes/@bentley/imodeljs-backend/apply-schema-changeset-fails_2021-08-05-11-43.json
- core/backend/src/BriefcaseManager.ts
> Clear statement caches before applying schema changesets

- common/api/imodeljs-backend.api.md
- common/api/imodeljs-common.api.md
- common/changes/@bentley/imodeljs-backend/remove-deprecated-common_2021-08-09-17-12.json
- common/changes/@bentley/imodeljs-common/remove-deprecated-common_2021-08-09-17-12.json
- common/changes/@bentley/rpcinterface-full-stack-tests/remove-deprecated-common_2021-08-09-17-12.json
- core/backend/src/BackendHubAccess.ts
- core/backend/src/BriefcaseManager.ts
- core/backend/src/ConcurrencyControl.ts
- core/backend/src/IModelDb.ts
- core/backend/src/IModelHubBackend.ts
- core/backend/src/test/HubMock.ts
- core/backend/src/test/LocalHub.ts
- core/backend/src/test/integration/IModelWrite.test.ts
- core/backend/src/test/standalone/HubMock.test.ts
- core/common/src/Code.ts
- core/common/src/IModel.ts
- core/common/src/IModelVersion.ts
- core/common/src/test/Code.test.ts
- docs/changehistory/2.0.0.md
- docs/changehistory/NextVersion.md
- full-stack-tests/rpc-interface/src/frontend/IModelConnection.test.ts
See `NextVersion.md` for details.
> Remove deprecated apis in imodeljs-common

- common/api/imodeljs-common.api.md
- common/api/imodeljs-frontend.api.md
- common/changes/@bentley/imodeljs-common/brep-worker_2021-08-13-11-53.json
- common/changes/@bentley/imodeljs-frontend/brep-worker_2021-08-13-11-53.json
- core/backend/src/perftest/TilesGenUtils.ts
- core/common/src/test/TileMetadata.test.ts
- core/common/src/tile/TileMetadata.ts
- core/frontend/src/tile/TileAdmin.ts
- test-apps/display-test-app/src/backend/Backend.ts
- test-apps/display-test-app/src/common/DtaConfiguration.ts
- test-apps/display-test-app/src/frontend/DisplayTestApp.ts
[Corresponding native PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/183448).
> Feature flag for optimized BRep processing (Default: ON)

- common/api/imodeljs-common.api.md
- common/api/imodeljs-frontend.api.md
- common/changes/@bentley/imodeljs-backend/bp-brep-worker_2021-08-16-18-02.json
- common/changes/@bentley/imodeljs-common/brep-worker_2021-08-13-11-53.json
- common/changes/@bentley/imodeljs-frontend/brep-worker_2021-08-13-11-53.json
- core/backend/src/perftest/TilesGenUtils.ts
- core/common/src/test/TileMetadata.test.ts
- core/common/src/tile/TileMetadata.ts
- core/frontend/src/test/tile/TileAdmin.test.ts
- core/frontend/src/tile/TileAdmin.ts
- test-apps/display-test-app/src/backend/Backend.ts
- test-apps/display-test-app/src/common/DtaConfiguration.ts
- test-apps/display-test-app/src/frontend/DisplayTestApp.ts
On master this feature defaults to ON.
On 2.19.x it defaults to OFF.
The actual feature is implemented in [this PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/185970).
(cherry picked from commit 3fa98221c19cf59c9b0309d1d2eb2741815e34fd)
> Feature flag for optimized BRep processing (Default: OFF) (bp #2047)

- common/changes/@bentley/ui-core/backportResizeObserverFix_2021-08-24-01-39.json
- ui/core/src/ui-core/utils/hooks/useResizeObserver.tsx
Test resizeObserver.current before calling unobserve.
> Backport resize observer fix

- common/changes/@bentley/imodeljs-backend/imodelhost-startup_2021-08-25-11-11.json
- core/backend/src/IModelHost.ts
> throw better exception if IModelHost.startup has not been called

- common/changes/@bentley/imodeljs-frontend/fix-graphicbuilder-transform_2021-08-30-12-17.json
- core/frontend/src/render/primitives/geometry/GeometryPrimitives.ts
- core/frontend/src/test/BoxDecorator.ts
- core/frontend/src/test/ExpectColors.ts
- core/frontend/src/test/render/webgl/Decorations.test.ts
- core/frontend/src/test/render/webgl/PickableGraphics.test.ts
- test-apps/display-test-app/src/frontend/IncidentMarkerDemo.ts
Geometry created by a GraphicBuilder needs to have its specified placement transform applied properly.  This PR also modularizes some test functionality used by tests in frontend/src/test/render/webgl/
> Fix graphicbuilder transform

- docs/changehistory/NextVersion.md
Backported from master to 2.19.x in #2201.
> Remove 2.19.x change from NextVersion.md.

- common/api/frontend-devtools.api.md
- common/api/imodeljs-common.api.md
- common/api/imodeljs-frontend.api.md
- common/api/summary/frontend-devtools.exports.csv
- common/api/summary/imodeljs-common.exports.csv
- common/changes/@bentley/frontend-devtools/wow-ignore-background_2021-09-08-13-58.json
- common/changes/@bentley/imodeljs-common/wow-ignore-background_2021-09-08-13-58.json
- common/changes/@bentley/imodeljs-frontend/wow-ignore-background_2021-09-08-13-58.json
- core/common/src/DisplayStyleSettings.ts
- core/common/src/ViewFlags.ts
- core/common/src/WhiteOnWhiteReversalSettings.ts
- core/common/src/imodeljs-common.ts
- core/common/src/test/DisplayStyle.test.ts
- core/common/src/test/WhiteOnWhiteReversalSettings.test.ts
- core/frontend-devtools/README.md
- core/frontend-devtools/public/locales/en/FrontendDevTools.json
- core/frontend-devtools/src/FrontEndDevTools.ts
- core/frontend-devtools/src/tools/DisplayStyleTools.ts
- core/frontend/src/Viewport.ts
- core/frontend/src/render/RenderPlan.ts
- core/frontend/src/render/webgl/StyleUniforms.ts
- core/frontend/src/render/webgl/glsl/Fragment.ts
- docs/changehistory/NextVersion.md
- full-stack-tests/core/src/frontend/standalone/WhiteOnWhiteReversal.test.ts
(cherry picked from commit 17f75107cf07edd90c15afdfb58e4c77f2d1223c)
> Allow white-on-white reversal to be applied to non-white backgrounds (bp #2198)

- common/changes/@bentley/geometry-core/EDL-BoxTriangulation_2021-09-09-16-12.json
- core/geometry/src/polyface/PolyfaceBuilder.ts
- core/geometry/src/test/solid/Solid.test.ts
* PolyfaceBuilder code to facet a `Box` solid previously did not triangulate.
* Observing triangulation flag in AddUVGridBody corrects this.
> PolyfaceBuilder code to facet a `Box` solid previously did not triangulate.

- common/api/imodeljs-frontend.api.md
- common/api/summary/imodeljs-frontend.exports.csv
- common/changes/@bentley/imodeljs-frontend/lookAt_2021-09-10-12-05.json
- core/frontend/src/FrustumAnimator.ts
- core/frontend/src/ViewState.ts
- core/frontend/src/ViewStatus.ts
- core/frontend/src/Viewport.ts
- core/frontend/src/tools/ToolAdmin.ts
- core/frontend/src/tools/ViewTool.ts
- docs/changehistory/NextVersion.md
- full-stack-tests/core/src/frontend/standalone/ViewState.test.ts
@MarcNeely I'm sorry I missed the review of your previous changes, but this is what I think we should have for 3.0. Obviously this is a breaking change, but I think worth doing.
> Make ViewState3d.lookAt take named parameters

- common/api/geometry-core.api.md
- common/changes/@bentley/geometry-core/EDL-ClipPrimitiveWithNonConvexHoles_2021-09-11-03-29.json
- core/geometry/src/clipping/AlternatingConvexClipTree.ts
- core/geometry/src/clipping/ClipPrimitive.ts
- core/geometry/src/clipping/ClipVector.ts
- core/geometry/src/geometry3d/GrowableXYZArray.ts
- core/geometry/src/geometry3d/PointHelpers.ts
- core/geometry/src/serialization/GeometrySamples.ts
- core/geometry/src/test/Checker.ts
- core/geometry/src/test/clipping/AlternatingConvexClipTree.test.ts
- core/geometry/src/test/clipping/ClipPrimitives.test.ts
- core/geometry/src/test/clipping/ClipVector.test.ts
- core/geometry/src/test/topology/Triangulator.test.ts
- core/geometry/src/topology/Triangulation.ts
* triangulate the zone between the clip shape and an expanded convex hull
* build unbounded outer regions beyond the expanded clip shape.
> Revise implementation of "mask" ClipPrimitives.

- common/api/bentleyjs-core.api.md
- common/api/imodeljs-common.api.md
- common/api/summary/bentleyjs-core.exports.csv
- core/backend/src/IModelDb.ts
- core/backend/src/rpc-impl/IModelReadRpcImpl.ts
- core/backend/src/test/standalone/DgnDbWorker.test.ts
- core/common/src/rpc/IModelReadRpcInterface.ts
- core/frontend/src/GeoServices.ts
- docs/changehistory/NextVersion.md
- editor/backend/src/EditBuiltInCommand.ts
- full-stack-tests/rpc-interface/src/frontend/IModelConnection.test.ts
- presentation/backend/src/presentation-backend/NativePlatform.ts
- presentation/backend/src/test/NativePlatform.test.ts
simplifies TS code.
Depends on [#194214](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/194214)
> Make async worker methods return Promises

- common/api/imodeljs-backend.api.md
- common/changes/@bentley/imodeljs-backend/master_2021-09-20-14-23.json
- core/backend/src/IModelDb.ts
- core/backend/src/LineStyle.ts
- core/backend/src/test/standalone/GeometryStream.test.ts
- core/backend/src/test/standalone/IModel.test.ts
- docs/changehistory/NextVersion.md
cleaner api, but a breaking change
> Throw rather than returning status for `IModelDb.saveFileProperty` and `deleteFileProperty`

- common/changes/@bentley/imodeljs-backend/presentation-add-assertions-for-correct-classmap_2021-09-21-19-34.json
- common/changes/@bentley/presentation-common/presentation-add-assertions-for-correct-classmap_2021-09-21-19-34.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- presentation/common/src/presentation-common/EC.ts
- presentation/common/src/presentation-common/content/Descriptor.ts
- presentation/common/src/presentation-common/content/Fields.ts
Added assertions to confirm the classes map in compressed descriptor has all the necessary classes. Makes full stack fail without the fix: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/194740.
> Presentation: Add assertions for correct class map

- common/api/imodeljs-editor-frontend.api.md
- common/changes/@bentley/imodeljs-editor-backend/promote-and-simplify-breps_2021-09-21-18-34.json
- common/changes/@bentley/imodeljs-editor-frontend/promote-and-simplify-breps_2021-09-21-18-34.json
- editor/backend/src/EditBuiltInCommand.ts
- editor/frontend/src/ElementGeometryTool.ts
native PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/194871
> Don't hide original elements until we get a result. Cache filterHit status.

- common/changes/@bentley/imodeljs-backend/fix-txn-crash_2021-09-21-21-06.json
- core/backend/src/test/standalone/TxnManager.test.ts
See [native fix](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/194906).
> Test for TxnManager crash

- common/changes/@bentley/imodelhub-client-tests/remove-env-use_2021-09-22-14-08.json
- common/changes/@bentley/imodeljs-backend/remove-env-use_2021-09-22-14-08.json
- core/backend/src/test/IModelTestUtils.ts
- full-stack-tests/imodelhub-client/src/imodelhub/UrlValidator.test.ts
Small clean up on the magic env vars we support.
> Remove rarely used env var for logging

- common/changes/@bentley/presentation-backend/presentation-unique_modified_ruleset_ids_2021-09-24-12-03.json
- presentation/backend/src/presentation-backend/PresentationManager.ts
- presentation/backend/src/test/PresentationManager.test.ts
- test-apps/presentation-test-app/package.json
Create unique ruleset id even in case of native apps
> Presentation: Always create unique ruleset id in backend

- common/api/imodeljs-frontend.api.md
- common/api/summary/imodeljs-frontend.exports.csv
- common/changes/@bentley/imodeljs-frontend/remove-cesium-ion-key_2021-09-25-12-37.json
- core/frontend/src/DisplayStyleState.ts
- core/frontend/src/tile/TileAdmin.ts
- core/frontend/src/tile/map/CesiumTerrainProvider.ts
- docs/changehistory/NextVersion.md
- test-apps/display-performance-test-app/README.md
- test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts
- test-apps/display-test-app/README.md
- test-apps/display-test-app/src/backend/Backend.ts
- test-apps/display-test-app/src/common/DtaConfiguration.ts
- test-apps/display-test-app/src/frontend/App.ts
- test-apps/display-test-app/src/frontend/DisplayTestApp.ts
Supply with TileAdmin options at startup instead.
> Remove hard-coded Cesium ION API key

- test-apps/ui-test-app/src/common/TestAppConfiguration.ts
- test-apps/ui-test-app/src/frontend/index.tsx
BingMaps and MapBox access keys were not correctly initialized from config.
> Setup Mapbox/bing maps keys from config in ui-test-app

- common/changes/@bentley/ui-framework/ui-2.19-tool-settings-update-bug_2021-09-27-20-26.json
- ui/framework/src/ui-framework/frontstage/Frontstage.tsx
Force Tool Settings 1.0 to render when the active tool restarts.
> Tool Settings doesn't update

- common/changes/@itwin/presentation-backend/presentation-react-to-changed-default-nodes-cache-location_2021-09-30-11-58.json
- full-stack-tests/presentation/assets/datasets/.gitignore
- full-stack-tests/presentation/src/IntegrationTests.ts
- full-stack-tests/presentation/src/backend/NativePlatform.test.ts
- presentation/backend/src/presentation-backend/PresentationManager.ts
imodel02: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/197205
Update tests and docs
> Presentation: React to changed default hierarchy cache location

- test-apps/ui-test-app/src/frontend/index.tsx
Fix Fix bad uri in ui-test-app startup
> Get browser version of ui-test-app running again

- common/changes/@itwin/core-frontend/fix-getaccesstoken_2021-10-01-19-05.json
- common/config/rush/pnpm-lock.yaml
- core/frontend/src/tile/RealityModelTileTree.ts
- test-apps/ui-test-app/src/frontend/appui/frontstages/IModelOpenFrontstage.tsx
- test-apps/ui-test-app/src/frontend/appui/imodelindex/IModelIndex.tsx
- test-apps/ui-test-app/src/frontend/appui/imodelopen/IModelCard.tsx
- test-apps/ui-test-app/src/frontend/appui/imodelopen/IModelOpen.tsx
- test-apps/ui-test-app/src/frontend/appui/imodelopen/ProjectDialog.tsx
- test-apps/ui-test-app/src/frontend/appui/statusfields/editing/PushPullStatusField.tsx
- test-apps/ui-test-app/src/frontend/index.tsx
@NancyMcCallB Can you try out this change?
> Fix getAccessToken in ui-test-app

- common/changes/@itwin/core-common/fix-rendermode-link_2021-10-06-13-16.json
- core/common/src/ViewFlags.ts
Doc link pointed to wrong render mode.
> Fix incorrect doc link.

- core/backend/src/test/imodel/IModel.test.ts
Potential fix for reprojection issues in ImageTest compare bench: Tests only!
This pull request goes with native change: https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/204033
> Added additional tests for GCS reprojection

- common/api/core-common.api.md
- core/backend/src/test/standalone/DisplayStyle.test.ts
- core/common/src/SkyBox.ts
Adjust SkyBoxImageType enum to match native persistence layer.
Add tests to verify fixes to native persistence layer.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/204519).
> Fix skybox persistence

- common/api/editor-backend.api.md
- common/api/editor-common.api.md
- common/api/editor-frontend.api.md
- common/api/summary/editor-common.exports.csv
- common/api/summary/editor-frontend.exports.csv
- common/changes/@itwin/editor-backend/profile-operations_2021-11-02-14-29.json
- common/changes/@itwin/editor-common/profile-operations_2021-11-02-14-29.json
- common/changes/@itwin/editor-frontend/profile-operations_2021-11-02-14-29.json
- editor/backend/src/EditBuiltInCommand.ts
- editor/common/src/EditorBuiltInIpc.ts
- editor/frontend/src/EditTool.ts
- editor/frontend/src/ElementGeometryTool.ts
- editor/frontend/src/SolidModelingTools.ts
- editor/frontend/src/editor-frontend.ts
- editor/frontend/src/public/locales/en/Editor.json
native pr: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/204721
> Basic solid modeling operations are now covered.

- clients/reality-data/tsconfig.json
- common/changes/@bentley/reality-data-client/reality-data-esmodule_2021-11-02-18-30.json
> Add esModuleInterop to reality-data-client

- test-apps/display-test-app/src/frontend/ViewAttributes.ts
This is the style presented as a proposed new default lighting and built-in preset for apps like Design Review.
> Add 'ambient' rendering style to display-test-app.

- common/api/appui-abstract.api.md
- common/changes/@itwin/appui-abstract/addUiItemsProviderOnBeforeUnregisterFunction_2021-11-05-17-40.json
- ui/appui-abstract/src/appui-abstract/UiItemsManager.ts
- ui/appui-abstract/src/test/UiItemsManager.test.ts
- allows UiItemsProvider instances to unregister event listeners when UiItemsProvider are unregistered.
> Add UiItemsProvider onUnregister function

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/embed-font_2021-11-10-15-55.json
- core/backend/src/IModelDb.ts
embedding fonts will be removed in 3.0
> Make `IModelDb.embedFont` @internal

- common/api/summary/appui-abstract.exports.csv
- common/api/summary/appui-layout-react.exports.csv
- common/api/summary/appui-react.exports.csv
- common/api/summary/components-react.exports.csv
Looks like a previous commit missed the csv exports and only pushed the api.md files.
> Update api csv files

- common/changes/@itwin/core-backend/do-not-load-full-schema_2021-11-16-14-02.json
- core/backend/src/ClassRegistry.ts
This issue cause backend node process to go out of memory for very large schema.
> Skip full schema load for checking a schema custom attribute

- common/api/core-backend.api.md
- common/api/presentation-common.api.md
- common/changes/@itwin/presentation-common/presentation_excludedClassesSupport_2021-11-17-11-57.json
- docs/changehistory/NextVersion.md
- full-stack-tests/presentation/src/frontend/Hierarchies.test.snap
- full-stack-tests/presentation/src/frontend/providers/TreeDataProvider.test.snap
- presentation/common/Ruleset.schema.json
- presentation/common/src/presentation-common/rules/ClassSpecifications.ts
- presentation/common/src/presentation-common/rules/content/ContentInstancesOfSpecificClassesSpecification.ts
- presentation/common/src/presentation-common/rules/hierarchy/InstanceNodesOfSpecificClassesSpecification.ts
Added excludedClasses properties for ContentInstancesOfSpecificClassesSpecification and InstanceNodesOfSpecificClassesSpecification.
> Class exclusion support for ContentInstances and InstanceNodes of specific classes.

- common/changes/@bentley/oidc-signin-tool/fix-signin-tool_2021-11-22-17-15.json
- tools/oidc-signin-tool/src/TestBrowserAuthorizationClient.ts
The Ping consent page has been updated again, react to those changes.
> Fix signin tool handling of consent page

- common/changes/@bentley/map-layers/fix-map-layers-spacing_2021-11-23-19-42.json
- extensions/map-layers/src/ui/widget/BasemapPanel.scss
- extensions/map-layers/src/ui/widget/BasemapPanel.tsx
- extensions/map-layers/src/ui/widget/TransparencyPopupButton.scss
Some CSS changes to fix bad spacing in the header section (toggle visibility, base dropdown, transparency) of the map-layers widget.
> Fixed map-layers widget UI spacing.

- common/api/core-common.api.md
- common/changes/@itwin/core-backend/gcs-interpret2_2021-11-30-17-42.json
- common/changes/@itwin/core-common/gcs-interpret2_2021-11-30-17-42.json
- core/backend/src/test/misc/GeoServices.test.ts
- core/common/src/GeoCoordinateServices.ts
Added GeoServices class in backend with first method to parse of complete a GCS in JSON or WKT.
The corresponding PR on the native side is: https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/210173
> GCS interpret take 2

- full-stack-tests/core/src/backend/backend.ts
tests were writing to system cacheDir
> Use local cacheDir for core full stack tests

- common/changes/@itwin/core-common/eceflocation-add-doc_2021-12-05-19-24.json
- core/common/src/IModel.ts
Added documentation on interpretation of ECEFLocation properties and document in iModel on how to use ecefLocation.
> Eceflocation add doc

- common/changes/@bentley/imodelhub-client-tests/checkpoint-test-fix-2.19_2021-12-07-15-29.json
- full-stack-tests/imodelhub-client/src/imodelhub/Checkpoint.test.ts
Backporting this PR to 2.19 for stability: https://github.com/iTwin/itwinjs-core/pull/2852
> Checkpoint test fix 2.19

- clients/reality-data/src/test/integration/RealityDataClient.test.ts
- common/changes/@bentley/reality-data-client/skip-failing-test_2021-12-15-17-28.json
- common/changes/@itwin/core-frontend/skip-failing-test_2021-12-15-20-52.json
- core/frontend/src/test/render/GraphicBuilder.test.ts
The client is imminently going to be removed so skipping test for now.
> Skip failing test in reality data client

- common/api/editor-frontend.api.md
- common/changes/@itwin/editor-frontend/pending-subentity_2021-12-17-19-28.json
- editor/frontend/src/ElementGeometryTool.ts
This prevents the browser from becoming unresponsive when using ipc websocket (talking to SW about this), Regardless of whether it should be necessary, it's a good idea.
> Don't try to locate sub-entity under cursor until previous request completes.

- common/changes/@itwin/map-layers/ui-remove-themed-select_2022-01-03-21-12.json
- common/config/rush/pnpm-lock.yaml
- extensions/map-layers/package.json
- extensions/map-layers/src/ui/widget/BasemapPanel.tsx
- extensions/map-layers/src/ui/widget/MapLayerManager.scss
ThemedSelect is deprecated for the 3.0 release. Replace this component in BasemapPanel with the iTwinUI-react Select component.
> Replace deprecated ThemedSelect in MapLayers extension

- clients/itwin/src/itwin-client.ts
- common/changes/@bentley/itwin-client/v3-docs_2022-01-04-15-47.json
- docs/config/docSites.json
- docs/learning/GeometrySqlFuncs.md
- docs/learning/geometry/ClipPlaneAndLargerClipStructures.md
- Add v2 to archived versions
- Set current version to v3
- Fix broken markdown tables
- Fix broken link
> Add v2 to archived versions

- .github/CODEOWNERS
This left @dassaf4 as the sole owner for imjs-importer, so added @bbastings to that one.
> Remove @EarlinLutz from CODEOWNERS.md

- common/changes/@itwin/core-frontend/optimize-matrix-calculation_2022-01-11-16-46.json
- core/frontend/src/render/webgl/BranchUniforms.ts
Found an expensive matrix calculation that is not always needed.
> Optimize matrix calculation

- common/api/core-backend.api.md
- common/api/core-common.api.md
- common/api/editor-backend.api.md
- common/api/editor-common.api.md
- common/api/summary/core-common.exports.csv
- common/api/summary/editor-common.exports.csv
- common/changes/@itwin/core-backend/remove-element-geometry-update_2022-01-14-18-19.json
- common/changes/@itwin/core-common/remove-element-geometry-update_2022-01-14-18-19.json
- common/changes/@itwin/editor-backend/remove-element-geometry-update_2022-01-14-18-19.json
- common/changes/@itwin/editor-common/remove-element-geometry-update_2022-01-14-18-19.json
- core/backend/src/IModelDb.ts
- core/backend/src/test/standalone/GeometryStream.test.ts
- core/common/src/geometry/ElementGeometry.ts
- editor/backend/src/EditBuiltInCommand.ts
- editor/common/src/EditorBuiltInIpc.ts
Can specify elementGeometryBuilderParams on props for insert/update now.
> Remove element geometry update

- common/changes/@itwin/build-tools/bump-typedoc-version_2022-01-18-16-57.json
- common/config/rush/pnpm-lock.yaml
- tools/build/package.json
- tools/internal/scripts/rush/audit.js
- Bump patch version of Typedoc for security alert
- Remove audit alert exclusion
> Bump patch version of Typedoc

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/fix-return-status_2022-01-20-15-05.json
- common/changes/@itwin/editor-backend/fix-return-status_2022-01-20-15-05.json
- core/backend/src/IModelDb.ts
- core/backend/src/test/standalone/GeometryStream.test.ts
- editor/backend/src/EditBuiltInCommand.ts
native pr: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/220932
> Correct return status for processGeometryStream and createBRepGeometry.

- Steering.md
charter document for iTwin.js steering committee.
> Steering.md

- full-stack-tests/presentation/src/learning-snippets/Content.test.ts
Broken with https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/221223
> Presentation: Fix failing full stack test

- core/common/src/tile/IModelTileIO.ts
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/223361).
> Bump tile format version

- common/config/rush/pnpm-lock.yaml
- full-stack-tests/core/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- test-apps/imodel-transformer/package.json
- test-apps/presentation-test-app/package.json
- test-apps/ui-test-app/package.json
- tools/internal/scripts/rush/audit.js
+ remove simple-get exception from rush audit
> Update electron-authorization version

- docs/changehistory/index.md
Add links to storybook pages for each itwinui component that replaces a deprecated core UI component.
> Point to itwinui-react replacements for deprecated components

- common/api/core-bentley.api.md
- common/api/core-frontend.api.md
- common/changes/@itwin/core-bentley/marc.bedard8-RealityDataError_2022-02-18-13-56.json
- common/changes/@itwin/core-frontend/marc.bedard8-RealityDataError_2022-02-18-13-56.json
- core/bentley/src/BentleyError.ts
- core/frontend/src/RealityDataSource.ts
- core/frontend/src/tile/OPCFormatInterpreter.ts
- core/frontend/src/tile/ThreeDTileFormatInterpreter.ts
-Add RealityDataError class that can be throw by RealityDataSource API.
-Throw RealityDataError when RealityDataSource cannot be read or interpreted.
> Marc.bedard8/reality data error

- common/changes/@bentley/build-tools/imodeljs-native-2.19.37_2022-03-24-14-00.json
- common/changes/@bentley/imodeljs-backend/imodeljs-native-2.19.37_2022-03-23-19-31.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- tools/build/scripts/rush/audit.js
[Fix a crash when formatting a quantity with a format that has composite spec but no numeric spec](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/commit/f50d6e7a03e14546417b270cd21ef5beb7666691?refName=refs/heads/imodeljs/2.x)
> @bentley/imodeljs-native 2.19.37

- docs/changehistory/NextVersion.md
- full-stack-tests/presentation/src/frontend/Hierarchies.test.snap
- full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
Broken with https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/234828
> Presentation: Fix failing full stack test and document the fix that broke the test

- .vscode/launch.json
- full-stack-tests/presentation/src/performance/DataViz.test.ts
Note: requires this fix: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/237913
> Presentation: Use sample iModel for perf test

- presentation/common/src/presentation-common/CommonLoggerCategory.ts
- presentation/common/src/presentation-common/RpcRequestsHandler.ts
- presentation/common/src/test/RpcRequestsHandler.test.ts
Remove unneeded attributes from ruleset before sending it to the backend
> Presentation: Remove unneeded attributes from ruleset before sending it to the backend

- presentation/common/src/test/content/Descriptor.test.snap
- presentation/common/src/test/content/Descriptor.test.ts
Additional test to cover the code related to navigation property info.
https://github.com/iTwin/itwinjs-core/pull/3442/files
> Presentation: Tests for navigation property

- common/api/core-common.api.md
- common/api/summary/core-common.exports.csv
- common/changes/@itwin/core-common/new-datum-grid-file-formats_2022-04-05-23-57.json
- core/common/src/geometry/GeodeticDatum.ts
Added two identifiers for grid file format for OSTN02 and OSTN15
> New datum grid file formats identifiers

- common/changes/@itwin/presentation-backend/Presentation-RepositoryLabelCalculationFix_2022-04-06-11-25.json
- full-stack-tests/presentation/src/frontend/Hierarchies.test.snap
- full-stack-tests/presentation/src/frontend/ruleset-testing-snapshots/my-test-content-BisCore.DefinitionPartition.snap
- full-stack-tests/presentation/src/frontend/ruleset-testing-snapshots/my-test-content-BisCore.DocumentPartition.snap
- full-stack-tests/presentation/src/frontend/ruleset-testing-snapshots/my-test-content-BisCore.GroupInformationPartition.snap
- full-stack-tests/presentation/src/frontend/ruleset-testing-snapshots/my-test-content-BisCore.LinkPartition.snap
- full-stack-tests/presentation/src/frontend/ruleset-testing-snapshots/my-test-content-BisCore.PhysicalPartition.snap
- full-stack-tests/presentation/src/frontend/ruleset-testing-snapshots/my-test-content-BisCore.RepositoryLink.snap
- full-stack-tests/presentation/src/frontend/ruleset-testing-snapshots/my-test-content-BisCore.Subject.snap
- full-stack-tests/presentation/src/learning-snippets/content/customization/PropertySpecification.test.tsx
- full-stack-tests/presentation/src/learning-snippets/customization/InstanceLabelOverride.test.ts
- full-stack-tests/presentation/src/rpc/PresentationRpcInterface.test.snap
- presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/240216
> Presentation: Repository label calculation fix

- common/changes/@itwin/core-frontend/nick-bug-fix-hydrate_2022-04-13-19-03.json
- core/frontend/src/ViewState.ts
> Bug fix for hydrateViewState

- presentation/backend/src/presentation-backend/NativePlatform.ts
Associated imodel02 PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/242275
> Presentation: Cleanup unused addon code

- common/api/imodeljs-frontend.api.md
- common/changes/@bentley/imodeljs-frontend/eimantas-backport-jumpy-zoom-fix_2022-04-12-11-32.json
- core/frontend/src/tools/ViewTool.ts
> Fix jumpy view zoom on touch devices (backport #3498)

- common/api/core-frontend.api.md
- common/changes/@itwin/core-frontend/master_2022-04-29-20-47.json
- core/frontend/src/FrustumAnimator.ts
- core/frontend/src/Viewport.ts
This function is used by mobile-ui-react:
https://github.com/iTwin/mobile-ui-react/blob/f46fc96cc5286f2a31c731ebb66d6fc39dbbe8f6/src/mobile-ui-react/PanViewport.ts#L191
https://github.com/iTwin/mobile-ui-react/blob/f46fc96cc5286f2a31c731ebb66d6fc39dbbe8f6/src/mobile-ui-react/RotateViewport.ts#L92
> Mark animateFrustumChange Public (Previously internal)

- common/changes/@itwin/appui-react/ui-visibility-tree-checkbox_2022-05-03-12-17.json
- ui/appui-react/src/appui-react/imodel-components/VisibilityTreeBase.scss
Adjust visibility tree CSS overrides to be compatible with 3.0 checkbox style changes. Related PR: #2853.
> UI: Fix visibility tree checkbox alignment

- common/changes/@itwin/core-frontend/snap-abandoned_2022-05-17-17-06.json
- core/frontend/src/AccuSnap.ts
Fix for [backlog item](https://github.com/iTwin/itwinjs-backlog/issues/67)
> Catch snap abandoned exception.

- docs/presentation/content/PropertySpecification.md
- full-stack-tests/presentation/src/learning-snippets/content/customization/PropertySpecification.test.tsx
Learning snippets for property specification `isReadOnly` and `priority` attributes.
> Presentation: learning snippets for property specification attributes

- common/changes/@itwin/imodel-components-react/ui-clampTimelineCurrentDuration_2022-05-24-15-25.json
- ui/imodel-components-react/src/imodel-components-react/timeline/TimelineComponent.tsx
- fix for blue progress bar disappearing when current duration exceeds max duration. Closes https://github.com/iTwin/itwinjs-backlog/issues/75.
> Fix schedule timeline by clamping current duration to specified range - closes issue #75

- common/api/core-common.api.md
- common/changes/@itwin/core-backend/pmc-bp-3.2-fix-elem-gfx_2022-06-07-10-26.json
- common/changes/@itwin/core-common/pmc-bp-3.2-fix-elem-gfx_2022-06-06-21-37.json
- common/changes/@itwin/core-frontend/pmc-bp-3.2-fix-elem-gfx_2022-06-06-21-37.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/common/src/tile/ElementGraphics.ts
- core/frontend/src/tile/TileAdmin.ts
- full-stack-tests/backend/package.json
- full-stack-tests/core/src/frontend/standalone/tile/ElementGraphics.test.ts
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Backported fix for #3696 from #3748. Requires new addon to be published.
> @bentley/imodeljs-native 3.2.10

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/publish-LocalHub_2022-06-08-17-13.json
- core/backend/src/IModelHost.ts
- core/backend/src/LocalHub.ts
- core/backend/src/test/HubMock.ts
- core/backend/src/test/IModelHost.test.ts
- core/backend/src/test/index.ts
- core/backend/src/test/standalone/HubMock.test.ts
So it can be used for tests outside of core-backend.
> Move LocalHub to core-backend

- test-apps/ui-items-providers-test/src/ui/widgets/SelectedElementDataWidget.tsx
- test-apps/ui-items-providers-test/src/ui/widgets/ViewAttributesWidget.tsx
Change setImmediate() to setTimeout() in ui-items-providers-test code.
> UI: Change setImmediate to setTimeout

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/workspace-cleanup_2022-06-21-15-51.json
- core/backend/src/GeoCoordConfig.ts
- core/backend/src/IModelDb.ts
- core/backend/src/IModelHost.ts
Also remove potential circular import problem @pmconne correctly pointed out in `GeoCoordConfig`.
> Clean up Workspace api documentation

- common/api/core-backend.api.md
- common/api/summary/core-backend.exports.csv
- common/changes/@itwin/core-backend/sqliteDb-container-methods_2022-06-24-15-05.json
- core/backend/src/CheckpointManager.ts
- core/backend/src/GeoCoordConfig.ts
- core/backend/src/IModelDb.ts
- core/backend/src/SQLiteDb.ts
- core/backend/src/test/standalone/SQLiteDb.test.ts
- core/backend/src/workspace/Workspace.ts
- full-stack-tests/backend/src/integration/CloudSqlite.test.ts
- full-stack-tests/backend/src/perftest/Sqlite.test.ts
- utils/workspace-editor/src/WorkspaceEditor.ts
Also test that vacuum throws when database not opened. Corresponding [native PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/259296)
> Add `withOpenDb` and `withLockedContainer` methods to `SQLiteDb`

- common/config/rush/pnpm-lock.yaml
- full-stack-tests/backend/package.json
- tools/internal/scripts/rush/audit.js
Proper fix to workaround from this PR: #3907
> Upgrade azurite to version 3.18.0 to fix moment vulnerability

- common/changes/@itwin/core-backend/update-native-3.2.13_2022-07-12-20-48.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- full-stack-tests/backend/package.json
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Consume fix: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/commit/78622c40566c905110bcc9ec9207e04864ed08dd?refName=refs%2Fheads%2Fimodeljs%2F3.x
> @bentley/imodeljs-native 3.2.13

- common/config/rush/pnpm-lock.yaml
Let me know if anything is missing
> Bump terser from 4.8.0 to 4.8.1, 5.14.0 to 5.14.2

- core/backend/src/test/imodel/IModel.test.ts
(cherry picked from commit 2b4cee67fc882ef25106e97df30cf9c3e896a58c)
Regression test for [native fix](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/265733).
> Ecef zero orientation regression test

- common/api/presentation-backend.api.md
- common/api/presentation-common.api.md
- common/api/summary/presentation-common.exports.csv
- common/changes/@itwin/presentation-backend/presentation-CancelDanglingRequests_2022-07-20-14-07.json
- common/changes/@itwin/presentation-common/presentation-CancelDanglingRequests_2022-07-20-14-07.json
- full-stack-tests/presentation/src/backend/PresentationManager.test.ts
- presentation/backend/src/presentation-backend/NativePlatform.ts
- presentation/backend/src/presentation-backend/PresentationManager.ts
- presentation/backend/src/presentation-backend/PresentationRpcImpl.ts
- presentation/backend/src/test/NativePlatform.test.ts
- presentation/backend/src/test/PresentationManager.test.ts
- presentation/backend/src/test/PresentationRpcImpl.test.ts
- presentation/common/src/presentation-common/PresentationManagerOptions.ts
Cancel dangling presentation requests.
Related PR: https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/265385
iTwin/itwinjs-backlog#274
> Presentation: Cancel dangling requests

- common/changes/@itwin/core-backend/native-3.3.7_2022-07-28-15-20.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- full-stack-tests/backend/package.json
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Includes fix for race condition between load and store BRep facets.
> @bentley/imodeljs-native 3.3.7

- common/changes/@itwin/appui-react/fix-duplicate-widgets_2022-07-28-13-32.json
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/test/widget-panels/Frontstage.test.tsx
This PR fixes an issue where a widget is added to the layout multiple times.
> Fix duplicate widgets

- common/changes/@itwin/core-common/fix-dta-ios_2022-08-11-20-58.json
- core/common/package.json
- test-apps/display-test-app/.gitignore
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app/AppDelegate.swift
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app/ViewController.swift
- test-apps/display-test-app/package.json
uses itwin/mobile-native-ios w/ xcframework
only snapshots work
> get ios dta working on 3.2

- common/changes/@itwin/core-webpack-tools/webpack-ignore-warnings_2022-08-22-10-58.json
- common/config/rush/pnpm-lock.yaml
- tools/webpack-core/package.json
- tools/webpack-core/src/plugins/BackendDefaultsPlugin.ts
- tools/webpack-core/src/plugins/FrontendDefaultsPlugin.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/349
> replace old webpack plugin with new config option

- common/config/rush/pnpm-lock.yaml
- full-stack-tests/core/src/frontend/_Setup.test.ts
- full-stack-tests/core/src/frontend/standalone/tile/TileIO.test.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/368.
> Compare tolerance for floating point numbers in core frontend test instead of equality

- common/api/presentation-common.api.md
- common/changes/@itwin/presentation-common/presentation-AddRulesToDiagnostics_2022-08-19-08-04.json
- presentation/common/src/presentation-common/Diagnostics.ts
Related PR: https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/272610
#3796
> Presentation: Add rules to diagnostics

- common/changes/@itwin/core-backend/native-3.2.15_2022-08-26-13-27.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- full-stack-tests/backend/package.json
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
> native 3.2.15

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/chunk-traversal-changed-elements_2022-09-01-19-05.json
- core/backend/src/ChangedElementsDb.ts
Changed Elements chunk traversal perf improvement options.
> Add option for chunk traversal.

- common/changes/@itwin/appui-react/restore-floating-widgets_2022-09-08-08-11.json
- full-stack-tests/ui/tests/Utils.ts
- full-stack-tests/ui/tests/floating-widget.test.ts
- full-stack-tests/ui/tests/popout-widget.test.ts
- full-stack-tests/ui/tests/widget-auto-size.test.ts
- full-stack-tests/ui/tests/widget-state.test.ts
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/test/widget-panels/Frontstage.test.snap
- ui/appui-react/src/test/widget-panels/Frontstage.test.tsx
This PR fixes an issue where floating widgets are docked back to the panel after a reload.
> Restore floating widgets

- common/changes/@itwin/appui-react/fix-append-widgets_2022-09-12-10-32.json
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/test/widget-panels/Frontstage.test.tsx
This PR fixes an issue where `maxWidgetCount` of a panel is exceeded when adding a widget.
> Fix append widgets

- common/changes/@itwin/core-frontend/pmc-fix-pan-planar-map_2022-09-17-17-52.json
- core/frontend/src/tools/ViewTool.ts
> Fix pan tool with planar globe mode

- docs/learning/tutorials/create-test-imodel-itwin-sync.md
One liner to update to correct link
> Fix iTwin Synchronizer link

- core/backend/src/test/imodel/IModel.test.ts
Added test for error when reprojecting coordinate to/from iModel GCS
This PR goes with https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/281181
> Added tests to verify reproject error codes

- common/changes/@itwin/core-backend/pmc-skip-flaky-tests_2022-09-25-15-51.json
- common/changes/@itwin/core-webpack-tools/pmc-skip-flaky-tests_2022-09-25-15-51.json
- core/backend/src/test/ecdb/ECSqlQuery.test.ts
- core/backend/src/test/ecdb/ECSqlStatement.test.ts
- tools/webpack-core/src/test/RequireMagicCommentsPlugin.test.ts
#4354 @aruniverse 
#4355 @khanaffan 
These have become a plague upon every PR recently, requiring repeated reruns of CI to get a successful test run.
See for example #4352 and #4353.
> Skip flaky tests

- common/changes/@itwin/core-react/scss-deprecations_2022-09-27-14-19.json
- ui/core-react/src/core-react/_z-index.scss
> fix scss deprecation warning

- common/changes/@itwin/core-backend/fix-mobile-missing-settings_2022-09-29-19-10.json
- core/backend/src/IModelJsFs.ts
> IModelJsFs check dir exists before reading

- common/api/core-common.api.md
- common/changes/@itwin/core-common/pmc-ecef-zero-origin_2022-10-04-15-00.json
- core/common/src/IModel.ts
- core/common/src/test/IModel.test.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/449
> Reject an EcefLocation at the center of the Earth

- common/api/presentation-backend.api.md
- common/changes/@bentley/imodeljs-backend/presentation-memory-consumtion-config_2022-09-30-08-46.json
- common/changes/@bentley/presentation-backend/presentation-memory-consumtion-config_2022-09-29-12-26.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- presentation/backend/src/presentation-backend/NativePlatform.ts
- presentation/backend/src/presentation-backend/PresentationManager.ts
- presentation/backend/src/test/PresentationManager.test.ts
Associated addon PR: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/282806
> Presentation: Expose props for presentation manager to configure memory consumption

- full-stack-tests/core/src/frontend/standalone/RenderTarget.test.ts
> Skip flaky test

- docs/changehistory/NextVersion.md
- docs/presentation/hierarchies/InfiniteHierarchiesPrevention.md
Related to:
Change PR - https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/284431
Closes https://github.com/iTwin/itwinjs-core/issues/3780
> Presentation: similar ancestor fix documentation

- common/api/presentation-backend.api.md
- common/api/summary/presentation-backend.exports.csv
- common/changes/@itwin/presentation-backend/presentation-fixup-presentation-manager-config-docs_2022-10-10-05-56.json
- docs/presentation/advanced/Caching.md
- presentation/backend/src/presentation-backend/PresentationManager.ts
Fixing issue noticed in https://github.com/iTwin/itwinjs-core/pull/4452#discussion_r990520599
> Presentation: Fixup `PresentationManager` config docs

- common/api/core-bentley.api.md
- common/api/editor-frontend.api.md
- common/api/summary/core-bentley.exports.csv
- common/changes/@itwin/core-bentley/edittool-api-changes_2022-10-20-15-44.json
- common/changes/@itwin/editor-frontend/edittool-api-changes_2022-10-20-15-44.json
- core/bentley/src/UtilityTypes.ts
- editor/frontend/src/DeleteElementsTool.ts
- editor/frontend/src/EditTool.ts
- editor/frontend/src/ElementGeometryTool.ts
- editor/frontend/src/ModifyCurveTools.ts
- editor/frontend/src/ProjectLocation/ProjectExtentsDecoration.ts
- editor/frontend/src/SketchTools.ts
- editor/frontend/src/SolidModelingTools.ts
- editor/frontend/src/SolidPrimitiveTools.ts
- editor/frontend/src/TransformElementsTool.ts
- full-stack-tests/core/src/frontend/Editing.ts
- full-stack-tests/core/src/frontend/standalone/EditTool.test.ts
- test-apps/display-test-app/src/frontend/EditingTools.ts
- test-apps/ui-test-app/src/frontend/tools/editing/PlaceBlockTool.ts
- tools/internal/scripts/rush/audit.js
use a typed proxy created via `EditTools.connect` in EditTools rather than untyped `EditTools.callCommand`.
remove all occurrences of `callCommand`
> replace `callCommand` with `commandConnection` typed ipc proxy

- test-apps/display-test-app/src/backend/Backend.ts
- test-apps/display-test-app/src/frontend/App.ts
defer auth client sign in to after ElectronHost.startup where we register the electron schema
> fix dta key ins

- common/api/core-geometry.api.md
- common/changes/@itwin/core-geometry/saeed-torabi-geomlib-Point3dVector3d_2022-11-04-15-49.json
- core/geometry/src/geometry3d/Point3dVector3d.ts
- core/geometry/src/polyface/PolyfaceBuilder.ts
- core/geometry/src/test/geometry3d/Point3dVector3d.test.ts
- Fixed code style issues.
- Fixed minor logical issues.
- Improved comments and namings.
- Added 34 unit tests to increase test coverage to 100% for statements, functions, and lines and to 90% for branches.
> Point3dVector3D: clean up src and add more test coverage

- common/api/presentation-components.api.md
- common/changes/@itwin/presentation-components/presentation-update_diagnostics_props_type_2022-11-11-14-35.json
- presentation/components/src/presentation-components/common/Diagnostics.ts
- presentation/components/src/test/common/Diagnostics.test.ts
Fixes https://github.com/iTwin/itwinjs-core/issues/4442
Updated DiagnosticsProps to match DiagnosticsOptions interface
> Presentation: Update DiagnosticsProps type

- common/changes/@itwin/core-backend/nick-add-customviewstate3dcreator-tests_2022-11-17-14-10.json
- core/backend/src/test/standalone/CustomViewState3dCreator.test.ts
- full-stack-tests/core/src/frontend/standalone/ViewCreator3d.test.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/485
> Add a few tests for the customviewstate3dcreator

- docs/learning/tutorials/develop-desktop-viewer.md
> Fix typos in develop-desktop-viewer.md

- common/changes/@itwin/core-frontend/cve-GHSA-hrpp-h998-j3pp_2022-12-06-22-28.json
- common/changes/@itwin/core-mobile/cve-GHSA-hrpp-h998-j3pp_2022-12-06-22-28.json
- common/config/rush/pnpm-lock.yaml
- core/frontend/package.json
- core/mobile/package.json
update dep on qs to resolve https://github.com/advisories/GHSA-hrpp-h998-j3pp
> resolve GHSA-hrpp-h998-j3pp

- common/api/presentation-backend.api.md
- common/api/presentation-common.api.md
- common/api/presentation-frontend.api.md
- common/api/summary/presentation-frontend.exports.csv
- full-stack-tests/presentation/src/IntegrationTests.ts
- full-stack-tests/presentation/src/frontend/Hierarchies.test.snap
- full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
- full-stack-tests/presentation/src/frontend/providers/TreeDataProvider.test.snap
- presentation/backend/src/presentation-backend/NativePlatform.ts
- presentation/backend/src/presentation-backend/PresentationIpcHandler.ts
- presentation/backend/src/test/NativePlatform.test.ts
- presentation/backend/src/test/PresentationIpcHandler.test.ts
- presentation/common/src/presentation-common/PresentationIpcInterface.ts
- presentation/common/src/presentation-common/PresentationManagerOptions.ts
- presentation/common/src/presentation-common/Update.ts
- presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts
- presentation/components/src/presentation-components/tree/controlled/UseHierarchyStateTracking.ts
- presentation/components/src/test/tree/controlled/UseHierarchyStateTracking.test.ts
- presentation/frontend/src/presentation-frontend/IpcRequestsHandler.ts
- presentation/frontend/src/presentation-frontend/StateTracker.ts
- presentation/frontend/src/test/IpcRequestsHandler.test.ts
- presentation/frontend/src/test/StateTracker.test.ts
Related: https://github.com/iTwin/imodel-native/pull/65
Part of https://github.com/iTwin/imodel-native/issues/14
> Presentation: Hierarchy level filtering

- common/changes/@itwin/core-frontend/pmc-remove-64k-assertions_2022-12-16-11-20.json
- core/frontend/src/render/RealityMeshParams.ts
- core/frontend/src/test/render/RealityMeshParams.test.ts
Inaccurate as of #4788.
Also add tests that should have been included in #4788.
> Remove obsolete assertions

- test-apps/display-test-app/src/frontend/ViewClipByElementGeometryTool.ts
Thanks @EarlinLutz and @dassaf4.
> Test convexity before decomposition

- common/changes/@itwin/appui-layout-react/fix-widget-resize_2022-12-20-10-06.json
- ui/appui-layout-react/src/appui-layout-react/state/NineZoneStateReducer.ts
- ui/appui-layout-react/src/test/state/NineZoneState.test.ts
This PR fixes a floating widget resize issue by maintaining min size of a widget when resizing.
> Fix a floating widget resize issue

- common/api/presentation-common.api.md
- common/changes/@itwin/presentation-common/presentation-complex-hierarchy-level-instance-filters_2023-01-04-05-31.json
- full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
- presentation/common/src/presentation-common/PresentationManagerOptions.ts
Part of https://github.com/iTwin/itwinjs-backlog/issues/556.
Related to https://github.com/iTwin/imodel-native/pull/89.
> Presentation: Support complex instance filters for hierarchy levels

- docs/bis/guide/other-topics/index.md
- docs/bis/guide/other-topics/kindOfQuantities.md
- docs/bis/guide/other-topics/units.md
- docs/bis/leftNav.md
Refect duscussions on this topic at the BWG.
> Add an article clarifying introduction of KOQ schemas

- tools/internal/ios/ios.webpack.config.js
fix [build](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1896546&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=96d68eba-7198-517e-3083-eb7169f4ccb9)
> update webpack config to build ios webpack build

- common/changes/@itwin/core-frontend/pmc-remove-spurious-assertion_2023-01-25-12-44.json
- core/frontend/src/tile/map/MapTile.ts
> Remove spurious assertion

- rush.json
https://rushjs.io/pages/configs/rush_json/
common/config/azure-pipelines/templates/publish.yaml
https://rushjs.io/pages/commands/rush_publish/
> dont publish appui & presentation pkgs

- common/config/rush/pnpm-lock.yaml
Resolves [CVE-2022-25881](https://github.com/advisories/GHSA-rc47-6667-2j5j)
> Fix CVE-2022-25881 audit failure

- common/config/rush/pnpm-lock.yaml
https://github.com/advisories/GHSA-rc47-6667-2j5j
> resolve cve GHSA-rc47-6667-2j5j

- .github/workflows/extract-api.yaml
- common/config/azure-pipelines/jobs/docs-build.yaml
- tools/internal/scripts/rush/audit.js
dont build the entire monorepo only the library
> speed up docs build

- common/config/rush/pnpm-lock.yaml
- tools/internal/scripts/rush/audit.js
suppress https://github.com/advisories/GHSA-8mwq-mj73-qv68
> suppress GHSA-8mwq-mj73-qv68

- common/config/rush/pnpm-lock.yaml
Update pnpm-lock to resolve https://github.com/advisories/GHSA-vqfx-gj96-3w95
> Resolve GHSA-vqfx-gj96-3w95

- .github/mergify.yml
add a comment asking original author to fix bp if there are conflicts
since we are currently backporting across 3 minors atm, updated bp title to include destination branch
> update mergify templates

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/pmc-spatial-view-definition-from-props_2023-02-28-18-23.json
- core/backend/src/ViewDefinition.ts
> SpatialViewState.fromJSON

- common/changes/@itwin/presentation-backend/presentation-api-doc-improvements_2023-03-14-11-34.json
- presentation/backend/src/presentation-backend/PresentationManager.ts
Closes https://github.com/iTwin/itwinjs-core/issues/3774
> Presentation: API documentation improvements

- common/changes/@itwin/backend-webpack-tools/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/core-backend/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/core-electron/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/core-frontend/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/core-i18n/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/core-markup/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/core-telemetry/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/core-webpack-tools/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/ecschema-rpcinterface-tests/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/hypermodeling-frontend/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/rpcinterface-full-stack-tests/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/changes/@itwin/webgl-compatibility/cve-GHSA-hc6q-2mpp-qw7j_2023-03-14-18-30.json
- common/config/azure-pipelines/jobs/docs-build.yaml
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/electron/package.json
- core/frontend/package.json
- core/hypermodeling/package.json
- core/i18n/package.json
- core/markup/package.json
- core/telemetry/package.json
- core/webgl-compatibility/package.json
- full-stack-tests/core/package.json
- full-stack-tests/ecschema-rpc-interface/package.json
- full-stack-tests/rpc-interface/package.json
- full-stack-tests/rpc/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- tools/backend-webpack/package.json
- tools/webpack-core/package.json
https://github.com/advisories/GHSA-hc6q-2mpp-qw7j
> update to webpack@^5.76.0 to resolve GHSA-hc6q-2mpp-qw7j

- common/api/core-geometry.api.md
- common/changes/@itwin/core-geometry/saeed-torabi-transform-src-part1_2023-03-10-17-47.json
- core/geometry/src/curve/CurveCurveIntersectXY.ts
- core/geometry/src/curve/CurveCurveIntersectXYZ.ts
- core/geometry/src/geometry3d/Matrix3d.ts
- core/geometry/src/geometry3d/Transform.ts
- core/geometry/src/geometry3d/XYZProps.ts
- core/geometry/src/test/geometry3d/Matrix3d.test.ts
- core/geometry/src/test/geometry3d/Transform.test.ts
- improved src code formatting
- improved documentation
- added new tests
- fixed few minor bugs
> Improving Transform: Part 1 (src - line 1 to 500)

- common/changes/@itwin/core-mobile/5227-handle-token-fetch-error_2023-03-17-21-11.json
- core/mobile/src/frontend/MobileAuthorizationFrontend.ts
Fix for issue: https://github.com/iTwin/itwinjs-core/issues/5227
> 5227 handle token fetch error

- common/api/core-backend.api.md
- common/api/core-common.api.md
- common/api/core-frontend.api.md
- common/api/summary/core-common.exports.csv
- common/api/summary/core-frontend.exports.csv
- common/changes/@itwin/core-backend/pmc-more-api-promotions_2023-03-21-11-29.json
- common/changes/@itwin/core-common/pmc-more-api-promotions_2023-03-21-11-29.json
- common/changes/@itwin/core-frontend/pmc-more-api-promotions_2023-03-21-11-29.json
- core/backend/src/BackendLoggerCategory.ts
- core/common/src/GeoCoordinateServices.ts
- core/frontend/src/AuxCoordSys.ts
- core/frontend/src/CategorySelectorState.ts
- core/frontend/src/DisplayStyleState.ts
- core/frontend/src/DrawingViewState.ts
- core/frontend/src/EntityState.ts
- core/frontend/src/GeoServices.ts
- core/frontend/src/IModelApp.ts
- core/frontend/src/IModelConnection.ts
- core/frontend/src/ModelSelectorState.ts
- core/frontend/src/ModelState.ts
- core/frontend/src/SheetViewState.ts
- core/frontend/src/SpatialViewState.ts
- core/frontend/src/ViewState.ts
- core/frontend/src/Viewport.ts
> API promotions - geocoord, frontend, backend

- common/api/core-frontend.api.md
- common/api/summary/core-frontend.exports.csv
- common/changes/@itwin/core-frontend/accudraw-api-promotions_2023-03-29-18-04.json
- core/frontend/src/AccuDraw.ts
- core/frontend/src/IModelApp.ts
Make AccuDraw public so applications can provide the UI.
Part of #4851
> API Promotions - AccuDraw

- common/config/azure-pipelines/jobs/fast-ci.yaml
- common/config/azure-pipelines/templates/core-build.yaml
This PR fixes conditions so we aren't skipping steps on individual CI runs, as well as simplifies some of the step conditions in the CI pipeline.
> Fix CI build conditions

- common/api/core-geometry.api.md
- common/api/summary/core-geometry.exports.csv
- common/changes/@itwin/core-geometry/saeed-torabi-Geometry-test_2023-04-04-20-54.json
- core/geometry/src/Geometry.ts
- core/geometry/src/test/Geometry.test.ts
- Add new tests to increase coverage to 99%
- Note: Depricated method isHugeCoordinate is not testable due to lint error
> Improve Geometry: Part 3 (tests)

- common/changes/@itwin/core-geometry/saeed-torabi-Geometry-Ray3d_2023-04-05-18-14.json
- core/geometry/src/geometry3d/Ray3d.ts
- core/geometry/src/test/geometry3d/Ray3d.test.ts
- Improved documentation
- Improved format style
> Improve Geometry: Ray3d

- common/changes/@itwin/presentation-backend/presentation-fix-biscore-supplemental-rules-for-external-sources_2023-04-12-06-41.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- full-stack-tests/presentation/package.json
- full-stack-tests/presentation/src/Utils.ts
- full-stack-tests/presentation/src/backend/DefaultSupplementalRules.test.ts
- full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
- presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
Fixes https://github.com/iTwin/itwinjs-core/issues/5374
> Presentation: Fix `BisCore` supplemental rules for related `bis.ExternalSource` properties

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/bp-appui-pr-261_2023-04-13-12-23.json
- ui/appui-react/public/locales/en/UiFramework.json
- ui/appui-react/src/appui-react/statusfields/SelectionScope.tsx
- ui/appui-react/src/test/statusfields/SelectionScope.test.tsx
* Update available scopes in standalone test app.
* SelectionScopeFieldComponent as function component.
* Update NextVersion.
* Extract API.
* Rush change.
> Fix selection scope field (#261)

- common/api/core-common.api.md
- common/changes/@itwin/core-common/man-constant-lod-texture-mapping_2023-03-21-21-20.json
- common/changes/@itwin/core-frontend/man-constant-lod-texture-mapping_2023-03-21-21-20.json
- core/common/src/TextureMapping.ts
- core/frontend/src/render/webgl/BranchUniforms.ts
- core/frontend/src/render/webgl/MeshData.ts
- core/frontend/src/render/webgl/RenderFlags.ts
- core/frontend/src/render/webgl/SurfaceGeometry.ts
- core/frontend/src/render/webgl/glsl/CopyStencil.ts
- core/frontend/src/render/webgl/glsl/Surface.ts
- core/frontend/src/render/webgl/glsl/Vertex.ts
Co-authored-by: Paul Connelly <22944042+pmconne@users.noreply.github.com>
(cherry picked from commit ca02195cdd8e6d2684022abddf2638650341ba83)
> Implement constant LOD texture mapping mode. (cherry-pick #5264)

- .devcontainer/Dockerfile
- .github/CODEOWNERS
Also in the PR is an update to the devcontainer to use Node18.
> Update codeowners. 

- common/api/core-common.api.md
- common/api/core-frontend.api.md
- common/api/summary/core-common.exports.csv
- common/changes/@itwin/core-common/pmc-preserve-tile-leafness_2023-04-25-15-09.json
- common/changes/@itwin/core-frontend/pmc-preserve-tile-leafness_2023-04-25-15-09.json
- common/changes/@itwin/frontend-tiles/pmc-preserve-tile-leafness_2023-04-25-15-09.json
- core/common/src/tile/TileMetadata.ts
- core/frontend/src/tile/ImdlReader.ts
- core/frontend/src/tile/RealityTileTree.ts
- core/frontend/src/tile/TileAdmin.ts
- core/frontend/src/tile/TileDrawArgs.ts
- core/frontend/src/tile/TileTree.ts
- extensions/frontend-tiles/src/BatchedTile.ts
- extensions/frontend-tiles/src/BatchedTileTree.ts
- test-apps/display-test-app/README.md
- test-apps/display-test-app/src/common/DtaConfiguration.ts
- test-apps/display-test-app/src/frontend/DisplayTestApp.ts
(cherry picked from commit c4ae8a52dd3a6bef71c5a720ec307cf6f156045a)
> Address tile content disposal issues (bp #5440)

- common/changes/@itwin/core-mobile/mobile-backend-access-token-fixes_2023-04-27-18-41.json
- common/config/azure-pipelines/jobs/docs-build.yaml
- core/mobile/src/backend/MobileAuthorizationBackend.ts
- core/mobile/src/backend/MobileHost.ts
* Apply fixes from MobileAuthorizationFrontend to backend
* Don't resolve a promise after it has been rejected
> Mobile backend access token fixes

- common/changes/@itwin/core-geometry/saeed-torabi-Point2dArrayCarrierTests_2023-05-02-16-00.json
- core/geometry/src/geometry3d/BarycentricTriangle.ts
- core/geometry/src/geometry3d/Ray3d.ts
- core/geometry/src/test/geometry3d/Point2dVector2d.test.ts
- Also increased Point2dArrayCarrier test coverage from 80% to 100%
> Added new sandbox links

- common/changes/@itwin/presentation-backend/presentation-document-link-properties_2023-05-08-13-04.json
- full-stack-tests/presentation/src/IntegrationTests.ts
- full-stack-tests/presentation/src/Utils.ts
- full-stack-tests/presentation/src/backend/DefaultSupplementalRules.test.ts
- full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
- presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
Closes https://github.com/iTwin/presentation/issues/149.
> Presentation: Include more `RepositoryLink` properties

- common/config/azure-pipelines/jobs/docs-build.yaml
- common/config/azure-pipelines/templates/copy-docs-artifact.yaml
- common/config/azure-pipelines/templates/gather-docs.yaml
- Add auth clients docs artifact into docs build
- bump bemetalsmith to 5.0.5 -> few bug fixes
> add auth clients docs; bump bemetalsmith

- docs/changehistory/NextVersion.md
Fixing some grammar and typos that I noticed
> Fix some grammar and typos in NextVersion

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/make-channel_2023-05-12-12-14.json
- core/backend/src/ChannelControl.ts
- core/backend/src/ElementAspect.ts
- core/backend/src/test/schema/FunctionalDomain.test.ts
Allows any element to become a Channel root.
> Add `ChannelAdmin.makeChannelRoot`

- common/changes/@itwin/core-geometry/saeed-torabi-CurvePrimitive_2023-05-12-19-28.json
- common/changes/@itwin/core-geometry/saeed-torabi-CurvePrimitive_2023-05-12-19-29.json
- common/changes/@itwin/core-geometry/saeed-torabi-CurvePrimitive_2023-05-12-19-30.json
- core/geometry/src/curve/Arc3d.ts
- core/geometry/src/curve/CurveCollection.ts
- core/geometry/src/curve/CurveLocationDetail.ts
- core/geometry/src/curve/CurvePrimitive.ts
- core/geometry/src/curve/GeometryQuery.ts
- core/geometry/src/curve/LineSegment3d.ts
- core/geometry/src/curve/LineString3d.ts
- core/geometry/src/curve/Query/StrokeCountMap.ts
- core/geometry/src/curve/StrokeOptions.ts
- core/geometry/src/geometry3d/Matrix3d.ts
- docs/learning/geometry/CurveCollection.md
- docs/learning/geometry/CurvePrimitive.md
Improved formatting and documentations of CurvePremitive.ts and other related classes.
> Improved CurvePrimitive

- docs/reference/leftNav.md
Add electron, node-cli, and service authorization docs.
> Add docs for newly published auth clients

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/default-block-size_2023-05-18-16-12.json
- common/changes/@itwin/workspace-editor/default-block-size_2023-05-18-16-12.json
- core/backend/src/CloudSqlite.ts
- full-stack-tests/backend/src/integration/AzuriteTest.ts
- full-stack-tests/backend/src/integration/CloudSqlite.test.ts
- utils/workspace-editor/src/WorkspaceEditor.ts
imodel-native: https://github.com/iTwin/imodel-native/tree/default-block-size
> Add `baseUri` and `storageType` members to CloudContainer

- common/api/presentation-common.api.md
- full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
- presentation/common/src/presentation-common/hierarchy/Key.ts
Closes: https://github.com/iTwin/imodel-native/issues/257
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/support-guid-in-hierarchies
imodel-native-pr: https://github.com/iTwin/imodel-native/pull/300
> Presentation: Support BeGuid type properties in hierarchies

- docs/getting-started/leftNav.md
We will soon be turning on My iTwins for all users. This PR updates a link.
> My iModels -> My iTwins

- common/config/azure-pipelines/templates/core-build.yaml
Run Extract-api when build is triggered from native PR validation
https://github.com/iTwin/imodel-native-internal/pull/107
> Add Extract-api to Native PR validation

- full-stack-tests/presentation/src/frontend/Hierarchies.test.snap
Closes: https://github.com/iTwin/imodel-native/issues/291
Closes: https://github.com/iTwin/itwinjs-core/issues/3789
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/unique-hash-for-every-node
native pr: https://github.com/iTwin/imodel-native/pull/317
> Presentation: relatedInstances in a specification affects other specifications in the same hierarchy level

- common/api/frontend-tiles.api.md
- common/api/summary/frontend-tiles.exports.csv
- common/changes/@itwin/frontend-tiles/pmc-compute-spatial-tileset-url_2023-06-28-20-01.json
- common/changes/@itwin/frontend-tiles/pmc-compute-spatial-tileset-url_2023-06-28-20-02.json
- common/config/rush/pnpm-lock.yaml
- extensions/frontend-tiles/.npmignore
- extensions/frontend-tiles/certa.json
- extensions/frontend-tiles/package.json
- extensions/frontend-tiles/src/FrontendTiles.ts
- extensions/frontend-tiles/src/test/FrontendTiles.test.ts
- extensions/frontend-tiles/src/test/utils/webpack-config.js
Backport #5690
(cherry picked from commit e1eca3efecfc2a43864501857de482c5bfb143d2)
> [frontend-tiles] promote to beta; mesh export service APIs; unit tests (bp #5690)

- docs/index.html
Core principals -> Core principles
> Fix spelling error on documentation index

- test-apps/display-performance-test-app/src/backend/backend.ts
- test-apps/display-test-app/src/backend/Backend.ts
- test-apps/display-test-app/src/backend/SetToStandalone.ts
- test-apps/export-gltf/src/ExportGltf.ts
- test-apps/imodel-from-geojson/src/Main.ts
- test-apps/imodel-from-orbitgt/src/Main.ts
- test-apps/imodel-from-reality-model/src/Main.ts
Prevent contention for the default profile when multiple apps are running simultaneously.
> Add profiles for test apps

- common/changes/@itwin/core-backend/imodeljs-native-3.7.2_2023-07-05-14-58.json
- common/changes/@itwin/core-frontend/imodeljs-native-3.7.2_2023-07-11-14-18.json
- common/config/azure-pipelines/ci.yaml
- common/config/azure-pipelines/integration-client-regression-pr-validation.yaml
- common/config/azure-pipelines/integration-pr-validation.yaml
- common/config/azure-pipelines/integration-validation.yaml
- common/config/azure-pipelines/jobs/fast-ci.yaml
- common/config/azure-pipelines/jobs/regression-testing.yaml
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/frontend/src/tile/map/ImageryProviders/ArcGISImageryProvider.ts
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Includes fix for segfault on 18.16.1, 16.20.1.
> @bentley/imodeljs-native 3.7.2 [release/3.7.x]

- common/config/azure-pipelines/templates/copy-docs-artifact.yaml
- common/config/azure-pipelines/templates/gather-docs.yaml
This fix will unblock https://github.com/iTwin/itwinjs-core/pull/5713
> cherry pick docs build changes from master to 4.x

- common/api/core-backend.api.md
- common/api/core-common.api.md
- common/changes/@itwin/core-backend/pmc-promote-rpcinterface-and-aspect-constructors_2023-07-19-19-14.json
- common/changes/@itwin/core-common/pmc-promote-rpcinterface-and-aspect-constructors_2023-07-19-19-14.json
- core/backend/src/ElementAspect.ts
- core/common/src/RpcInterface.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/782
> Promote constructors of ElementAspect and RpcInterface

- common/changes/@itwin/core-frontend/alexandrina-DracoTexture_2023-07-20-08-30.json
- core/frontend/src/tile/GltfReader.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/769
> Fix Draco Texture issue

- full-stack-tests/presentation/src/frontend/Content.test.ts
Closes: https://github.com/iTwin/itwinjs-core/issues/5748
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/filter-unique-values
imodel-native PR: https://github.com/iTwin/imodel-native/pull/370
> Presentation: Filtering unique values

- common/api/presentation-common.api.md
- common/changes/@itwin/core-backend/native-4.1.6_2023-07-28-13-11.json
- common/changes/@itwin/presentation-common/presentation-unique-values-based-on-parent-node_2023-07-20-14-39.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- full-stack-tests/presentation/src/IModelSetupUtils.ts
- full-stack-tests/presentation/src/Utils.ts
- full-stack-tests/presentation/src/backend/DefaultSupplementalRules.test.ts
- full-stack-tests/presentation/src/frontend/Content.test.ts
- full-stack-tests/presentation/src/frontend/Hierarchies.test.snap
- full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
- presentation/common/src/presentation-common/content/Descriptor.ts
- presentation/common/src/test/content/Descriptor.test.snap
- presentation/common/src/test/content/Descriptor.test.ts
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
integrate new addon which will deliver node18 for mobile
> imodeljs-native@4.1.6

- common/changes/@itwin/ecschema-locaters/string-schema-locater_2023-07-26-20-26.json
- core/ecschema-locaters/src/SchemaStringLocater.ts
- core/ecschema-locaters/src/SchemaXmlStringLocater.ts
- core/ecschema-locaters/src/test/SchemaXmlStringLocater.test.ts
Following the file locater design, I've implemented a base class. If we even want a JSON string locater in the future, it will be very easy to write.
> SchemaXmlStringLocater implementation

- common/changes/@itwin/core-backend/pmc-material-code-spec_2023-08-01-18-56.json
- core/backend/src/Material.ts
As pointed out by @c-macdonald.
> Fix RenderMaterial code spec

- common/changes/@itwin/core-backend/workspace-replace_2023-08-14-19-03.json
- core/backend/src/workspace/Workspace.ts
This seems much more convenient behavior for something like workspace-editor.
> Change updateBlob and updateString to insert if resource does not exist

- common/changes/@itwin/core-webpack-tools/restore-relative-srcmaps_2023-08-16-16-28.json
- tools/webpack-core/src/plugins/BackendDefaultsPlugin.ts
patches, https://github.com/iTwin/itwinjs-core/pull/5845
> readd relative path for src maps for prod builds

- .github/workflows/automation-scripts/update-changelogs.mjs
- .github/workflows/finalize-release.yaml
this is a copy of another PR into master. Might be more beneficial to merge here first though
remove extra parameters to push. The github token appears to not do anything, and removing the "origin/" from the target branch string should allow the push to function correctly. Only question I cannot answer is if this admin account is allowed to push to a protected branch without using some kind of token.
If anyone knows the expected behavior please let me know. I couldn't find anything online so I may be looking in the wrong place.
> fix finalize release errors

- core/backend/src/test/standalone/TxnManager.test.ts
Test in test fixture carry state from one test to another.
> Fixed TxnManager test which fails when rush cover is ran

- common/changes/@itwin/core-backend/BenPusey-FixesForCheckpointLogging_2023-09-01-18-04.json
- core/backend/src/BriefcaseManager.ts
- core/backend/src/CheckpointManager.ts
Fixes for issues mentioned in comments of this PR #5930. Updates the download checkpoint message and changes the timing for changeset application to be for each individual changeset.
> Fixes checkpoint download, changeset apply logging

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/rohitptnkr-use-instance-queries-getAspects_2023-09-11-12-17.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/backend/src/IModelDb.ts
- core/backend/src/test/element/ElementAspect.test.ts
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
integrate 4.2.4 to master branch
> imodeljs-native@4.2.4

- common/changes/@itwin/core-backend/rohitptnkr-update-tests-instance-query-getAspects_2023-09-13-08-49.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/backend/src/IModelDb.ts
- core/backend/src/test/ecdb/ECSqlAst.test.ts
- core/backend/src/test/element/ElementAspect.test.ts
- full-stack-tests/core/src/frontend/standalone/ECSqlAst.test.ts
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
> imodeljs-native@4.2.5

- common/changes/@itwin/core-frontend/AlfonsoM-Blank-Connection-Invalid-Name_2023-09-15-19-19.json
- core/frontend/src/IModelConnection.ts
- core/frontend/src/test/BlankConnection.test.ts
> Preserve BlankConnection name

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/ecdb-get-schema-props_2023-09-28-09-47.json
- core/backend/src/ECDb.ts
- core/backend/src/test/ecdb/ECDb.test.ts
imodel-native: https://github.com/iTwin/imodel-native/pull/474
> `core-backend`: Add `ECDb.getSchemaProps()`

- common/api/core-geometry.api.md
- common/api/summary/core-geometry.exports.csv
- common/changes/@itwin/core-geometry/saeed-torabi-CurveCurveIntersect_2023-09-29-20-36.json
- core/geometry/src/curve/CurveCurve.ts
- core/geometry/src/curve/CurveLocationDetail.ts
- core/geometry/src/curve/internalContexts/CurveCurveIntersectXY.ts
- core/geometry/src/curve/internalContexts/CurveCurveIntersectXYZ.ts
- core/geometry/src/geometry4d/Map4d.ts
- core/geometry/src/polyface/PolyfaceBuilder.ts
- core/geometry/src/test/curve/CurveCurveIntersectionXY.test.ts
- core/geometry/src/test/curve/CurveCurveIntersectionXYZ.test.ts
- Added new consistent methods
- Deprecated inconsistent methods
- Improved tests
- Improved docs and formatting
> Improved CurveCurveIntersection XY and XYZ

- common/changes/@itwin/core-backend/imodeljs-native-4.1.14_2023-10-04-21-46.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
integrating addon with:
https://github.com/iTwin/imodel-native/pull/483
> imodeljs-native@4.1.14

- common/changes/@itwin/core-frontend/mb-improve_tileset_contenttype_detection_2023-09-12-06-42.json
- core/frontend/src/RealityDataSourceTilesetUrlImpl.ts
- core/frontend/src/test/RealityDataSourceTilesetUrl.test.ts
By request of Arun this is the same PR as #5970 but created as a branch inside this repo.
> Improve 3D Tiles tileset content type detection (recreated)

- common/config/rush/pnpm-lock.yaml
`rush update --full` to resolve [CVE-2023-5217](https://github.com/advisories/GHSA-qqvq-6xgj-jw8g)
> resolve CVE-2023-5217

- common/changes/@itwin/core-backend/imodeljs-native-3.7.5_2023-10-10-16-58.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
> imodeljs-native@3.7.5

- common/changes/@itwin/core-backend/imodeljs-native-4.2.10_2023-10-12-19-16.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
> imodeljs-native@4.2.10

- common/changes/@itwin/core-backend/imodeljs-native-3.7.6_2023-10-13-19-21.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
> imodeljs-native@3.7.6

- common/config/rush/pnpm-lock.yaml
https://github.com/babel/babel/security/advisories/GHSA-67hx-6x53-jw92
> resolve GHSA-67hx-6x53-jw92

- common/changes/@itwin/core-backend/remove_reserved_keywords_from_tests_2023-10-16-07-34.json
- core/backend/src/test/ecdb/ECSqlStatement.test.ts
- example-code/snippets/src/backend/ECSQL-queries.test.ts
cherry-picked [this commit](https://github.com/iTwin/itwinjs-core/commit/30c4a2d74749d5a8f4cb0b84c2cf1fdc218edf39)
imodel-native: https://github.com/iTwin/imodel-native/pull/515
> Remove reserved SQLite keywords from tests (#6105)

- common/changes/@itwin/core-geometry/docs-polyface-deep-clone-spelling_2023-10-18-19-02.json
- core/geometry/src/polyface/PolyfaceData.ts
Deep clone. Not depp clone. 
Closes #6116
> fix minor spelling issue - PolyfaceData.clone jsdoc

- common/api/core-geometry.api.md
- common/changes/@itwin/core-geometry/saeed-troabi-Newton_2023-10-13-21-45.json
- core/geometry/src/numerics/Newton.ts
- core/geometry/src/numerics/Polynomials.ts
- core/geometry/src/test/numerics/Newton.test.ts
- Improved docs and formatting
- Improved test coverage
> Improved Newton class

- common/config/rush/pnpm-lock.yaml
Rush update --full
https://github.com/advisories/GHSA-xwcq-pm8m-c4vf
https://github.com/advisories/GHSA-x9w5-v3q2-3rhw
> Resolve GHSA-x9w5-v3q2-3rhw and GHSA-xwcq-pm8m-c4vf with rush update --full

- docs/changehistory/3.7.0.md
- docs/changehistory/4.1.0.md
file was cherry picked over with:
```
git checkout release/4.1.x docs/changehistory/4.1.0.md -p
```
> commit missing 4.1.0 changelog

- docs/changehistory/3.7.0.md
file cherry-picked via `git checkout release/3.7.x docs/changehistory/3.7.0.md -p`
> 3.7.0 changelog

- common/changes/@itwin/core-geometry/fix-multiplyTransformTransform-comments_2023-11-16-21-38.json
- core/geometry/src/geometry3d/Transform.ts
Fix a doc comment causing issues on https://www.itwinjs.org/reference/core-geometry/cartesiangeometry/transform/multiplytransformtransform/
> fix multiplyTransformTransform doc comment

- common/changes/@itwin/core-backend/imodeljs-native-4.2.11_2023-11-20-15-23.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
addon containing:
https://github.com/iTwin/imodel-native/commit/408d5483c98058fc43e15a302150aace75a65fa5
https://github.com/iTwin/imodel-native/commit/59bc429ce48f2f9b170083407d45a8b4a812fd73
> imodeljs-native@4.2.11

- common/api/presentation-backend.api.md
- common/changes/@itwin/presentation-backend/presentation-multiple-default-formats-for-same-phenomenon_2023-11-21-08-21.json
- full-stack-tests/presentation/src/backend/PresentationManager.test.ts
- presentation/backend/src/presentation-backend/NativePlatform.ts
- presentation/backend/src/presentation-backend/PresentationManager.ts
- presentation/backend/src/presentation-backend/PresentationManagerDetail.ts
- presentation/backend/src/test/PresentationManager.test.ts
imodel-native: https://github.com/iTwin/imodel-native/pull/553
> Presentation: Support multiple unit system formats for the same phenomenon

- common/changes/@itwin/ecsql-common/new-pkg-changelogs_2023-11-22-17-26.json
- core/ecsql/common/CHANGELOG.json
- core/ecsql/common/CHANGELOG.md
```
git checkout release/4.2.x core/ecsql/common/CHANGELOG.md -p 
git checkout release/4.2.x core/ecsql/common/CHANGELOG.json -p 
```
> cherry pick changelog files for new ecsql-common pkg added in 4.2

- docs/ui/appui/content-control.md
- docs/ui/appui/frontstage.md
- docs/ui/leftNav.md
Still need to create the code snippets
> Initial port from Figma document

- common/changes/@itwin/core-frontend/pmc-raster-glyph-transparency_2023-11-29-20-30.json
- core/frontend/src/render/webgl/glsl/Surface.ts
> Multiply glyph alpha with surface alpha

- common/changes/@itwin/presentation-common/presentation-handle-si-and-metric-as-one_2023-12-05-07-58.json
- presentation/common/src/presentation-common/KoqPropertyValueFormatter.ts
- presentation/common/src/test/KoqPropertyValueFormatter.test.ts
Part of https://github.com/iTwin/imodel-native/issues/563.
Related to https://github.com/iTwin/imodel-native/pull/564.
> Presentation: Handle SI and METRIC unit systems as a single unit system

- common/scripts/install-run-rush-pnpm.js
- common/scripts/install-run-rush.js
- common/scripts/install-run-rushx.js
- common/scripts/install-run.js
- rush.json
Rush version 5.112.2 fixes the issue mentioned here: https://github.com/microsoft/rushstack/issues/4445
> Bump rush version to `5.112.2`

- .vscode/settings.json
The November 2023 update to VS Code [changed some settings](https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto) from `boolean` and automatically updates settings.json when opening a workspace.
> Auto-update to settings by VS Code

- common/changes/@itwin/core-backend/imodeljs-native-4.3.6_2023-12-14-17-49.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Addon includes:
https://github.com/iTwin/imodel-native/commit/bb5453e891049dcbc568326952fc4f53e0325bb3
https://github.com/iTwin/imodel-native/commit/47c231c469e7ccc33b202394bd0f36eede54d392
https://github.com/iTwin/imodel-native/commit/ae033352eb2679e676f9709abc50efed93c8ce31
https://github.com/iTwin/imodel-native/commit/f5eca8736b295aa829b60d6b797f467c16de885e
> @bentley/imodeljs-native 4.3.6

- .github/workflows/automation-scripts/update-changelogs.mjs
Successful workflow run on forked repo: https://github.com/anmolshres98/itwinjs-core/actions/runs/7281044979/job/19840735347
Successful update commit to master branch in forked repo: https://github.com/anmolshres98/itwinjs-core/commit/b57377e46ca9763ef415cdfbe62d26baf91a0366#diff-b9d8920a691c4cd4f19daa04048d205203bd51286793080da008e41ba5456983
> Update finalize release to also copy change md files in docs

- full-stack-tests/presentation/src/learning-snippets/customization/InstanceLabelOverride.test.ts
imodel-native: https://github.com/iTwin/imodel-native/pull/642
> Presentation: Fix learning snippets that relied on a bug in the addon

- common/api/core-geometry.api.md
- common/api/summary/core-geometry.exports.csv
- common/changes/@itwin/core-geometry/saeed-torabi-polyface-data_2024-02-14-17-25.json
- common/changes/@itwin/core-geometry/saeed-torabi-polyface-visitor_2024-03-01-18-02.json
- core/geometry/src/Geometry.ts
- core/geometry/src/polyface/IndexedPolyfaceVisitor.ts
- core/geometry/src/polyface/Polyface.ts
- core/geometry/src/polyface/PolyfaceData.ts
- core/geometry/src/test/Checker.ts
- core/geometry/src/test/polyface/Polyface.test.ts
Improved formatting and documentations of IndexedPolyfaceVisitor.ts and related tests.
> Improved IndexedPolyfaceVisitor.ts

- common/changes/@itwin/core-common/rush-update-full_2024-03-11-17-18.json
- common/changes/@itwin/core-geometry/rush-update-full_2024-03-11-17-18.json
- common/changes/@itwin/ecsql-common/rush-update-full_2024-03-11-17-18.json
- common/config/rush/pnpm-lock.yaml
- core/common/package.json
- core/ecsql/common/src/ECSqlAst.ts
- core/geometry/package.json
- missing types/node dep which is used in testing for some pkgs
> `rush update --full`

- common/config/azure-pipelines/valgrind.yaml
The PR contains following changes:
- Moving build to `iModelTechLnxDeb11` and the relevant fixes
- Upgrade node version
> Fix Valgrind Pipeline

- common/api/presentation-common.api.md
- common/api/summary/presentation-common.exports.csv
- common/changes/@itwin/presentation-common/presentation-struct-and-array-member-fields_2024-03-19-09-33.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- docs/presentation/content/PropertySpecification.md
- full-stack-tests/presentation/package.json
- full-stack-tests/presentation/scripts/setup-tests.js
- full-stack-tests/presentation/src/IModelSetupUtils.ts
- full-stack-tests/presentation/src/Utils.ts
- full-stack-tests/presentation/src/frontend/Content.test.ts
- presentation/common/src/presentation-common/LocalizationHelper.ts
- presentation/common/src/presentation-common/PresentationRpcInterface.ts
- presentation/common/src/presentation-common/content/Fields.ts
- presentation/common/src/presentation-common/content/PropertyValueFormatter.ts
- presentation/common/src/test/LocalizationHelper.test.ts
- presentation/common/src/test/_helpers/Content.ts
- presentation/common/src/test/content/Descriptor.test.snap
- presentation/common/src/test/content/Descriptor.test.ts
- presentation/common/src/test/content/Fields.test.snap
- presentation/common/src/test/content/Fields.test.ts
- presentation/common/src/test/content/PropertyFormatter.test.ts
Closes https://github.com/iTwin/imodel-native/issues/656.
imodel-native: https://github.com/iTwin/imodel-native/pull/678
> Presentation: Customization support for struct member and array item fields

- common/changes/@itwin/core-backend/imodeljs-native-4.4.8_2024-03-25-19-53.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
new addon to address https://github.com/iTwin/itwinjs-backlog/issues/1066
> imodeljs-native@4.4.8

- common/config/azure-pipelines/ci.yaml
- common/config/azure-pipelines/integration-client-regression-pr-validation.yaml
- common/config/azure-pipelines/integration-pr-validation.yaml
- common/config/azure-pipelines/integration-validation.yaml
- common/config/azure-pipelines/jobs/fast-ci.yaml
- common/config/azure-pipelines/jobs/version-bump.yaml
- common/config/azure-pipelines/valgrind.yaml
https://github.com/iTwin/itwinjs-backlog/issues/1074 workitem to hopefully ensure we switch back to 20.x
See conversation here: https://github.com/iTwin/itwinjs-core/pull/6547
> change to node 20.11.1 temporarily from 20.x

- common/api/core-geometry.api.md
- common/api/summary/core-geometry.exports.csv
- common/changes/@itwin/core-geometry/da4-export-serializationhelpers_2024-03-26-20-04.json
- core/geometry/src/core-geometry.ts
- core/geometry/src/serialization/SerializationHelpers.ts
- core/geometry/src/test/geometry3d/PolygonOps.test.ts
- core/geometry/src/test/topology/HalfEdgeGraphSearch.test.ts
DGN connector needs this to export periodic B-spline data.
Ref: https://dev.azure.com/bentleycs/iModelTechnologies/_workitems/edit/1400013
> export SerializationHelpers

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/make-api-public_2024-04-08-11-49.json
- core/backend/src/BisCoreSchema.ts
- core/backend/src/ClassRegistry.ts
- core/backend/src/Element.ts
- core/backend/src/Entity.ts
Fixes #6589 plus various related documentation improvements.
> make ClassRegistry.register api public

- common/config/azure-pipelines/templates/core-build.yaml
temporarily disable mobile builds until we are able to release native-android/ios again
> temporarily disable mobile builds

- common/changes/@itwin/certa/master_2024-04-16-07-46.json
- common/changes/@itwin/core-electron/master_2024-04-16-07-46.json
- common/config/rush/pnpm-lock.yaml
- core/electron/package.json
- docs/changehistory/NextVersion.md
- example-code/app/package.json
- full-stack-tests/core/package.json
- full-stack-tests/rpc/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- tools/certa/package.json
- [Electron 30 breaking changes](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-300)
> Add support for Electron 30

- .github/CODEOWNERS
entry for core/ecschema-* missing
> Codeowner update for ecschema-* repos

- docs/learning/InteractiveEditing.md
> Clarify meaning of "local" Txns table

- common/changes/@itwin/core-backend/dan-imodeljs-native-4.6.16_2024-04-19-03-55.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
updating package locally due to error in bash script. Bash script if being fixed in separate PR so it can be backported easily to release branch
> imodeljs-native@4.6.16

- common/changes/@itwin/core-backend/da4-export-element-flatbuffer-test_2024-04-26-22-33.json
- core/backend/src/test/standalone/ExportGraphics.test.ts
Useful for debugging a known element in an iModel
> add test logic to extract fb from iModel

- docs/changehistory/NextVersion.md
- docs/learning/ECSqlReference/Views.md
Latest changes to the addon introduce ECDb profile 4.0.0.5 with a few new features. The changes were exclusively in imodel-native.
This is to mention them in nextversion.md.
> Updated nextversion and docs about new ECDb profile

- common/changes/@itwin/core-backend/samw-turn-down-logging_2024-04-30-17-45.json
- core/backend/src/IModelDb.ts
IModelDb.Elements.getAspects was logging an error upon finding no aspects. That should be an informational message at most.
> Having no asepcts is not an error

- common/config/azure-pipelines/jobs/docs-build.yaml
Fix conversion of task from powershell to bash.
> Fix docs bash script

- common/api/ecschema-editing.api.md
- common/changes/@itwin/ecschema-editing/schema-editing-rename-difference-changes-property_2024-05-22-10-17.json
- core/ecschema-editing/src/Differencing/Errors.ts
- core/ecschema-editing/src/Differencing/SchemaConflicts.ts
- core/ecschema-editing/src/Differencing/SchemaDiagnosticVisitor.ts
- core/ecschema-editing/src/Differencing/SchemaDifference.ts
- core/ecschema-editing/src/Merging/SchemaMerger.ts
- core/ecschema-editing/src/ecschema-editing.ts
- core/ecschema-editing/src/test/Differencing/Difference.test.ts
- core/ecschema-editing/src/test/Merging/ClassMerger.test.ts
- core/ecschema-editing/src/test/Merging/ClassMergerOrder.test.ts
- core/ecschema-editing/src/test/Merging/ConstantMerger.test.ts
- core/ecschema-editing/src/test/Merging/CustomAttributeMerger.test.ts
- core/ecschema-editing/src/test/Merging/EnumerationMerger.test.ts
- core/ecschema-editing/src/test/Merging/KindOfQuantityMerger.test.ts
- core/ecschema-editing/src/test/Merging/PhenomenonMerger.test.ts
- core/ecschema-editing/src/test/Merging/PropertyCategoryMerger.test.ts
- core/ecschema-editing/src/test/Merging/PropertyMerger.test.ts
- core/ecschema-editing/src/test/Merging/RelationshipClassMerger.test.ts
- core/ecschema-editing/src/test/Merging/SchemaMerger.test.ts
- core/ecschema-editing/src/test/Merging/SchemaReferenceMerger.test.ts
- core/ecschema-editing/src/test/Merging/UnitSystemMerger.test.ts
Renamed changes property on SchemaDifferences to differences
> rename difference changes property

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/nick-enable-debuglogging_2024-05-29-18-02.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/backend/src/CloudSqlite.ts
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
imodel-native: https://github.com/iTwin/imodel-native/pull/773
> Give option to enable debug logging for cleanDeletedBlocks

- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ mysql2 vulnerable to Prototype Pollution               │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ mysql2                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <3.9.8                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=3.9.8                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ ../../full-stack-tests/backend > …
```
> Resolve GHSA-pmh2-wpjm-fj45

- common/changes/@itwin/core-backend/Atharva-1063_2024-05-23-11-15.json
- core/backend/src/test/element/NullStructArray.test.ts
imodel-native: https://github.com/iTwin/imodel-native/pull/769
> Added test to confirm null structs in an Struct Array are returned while querying rows

- common/changes/@itwin/core-backend/2024-06-07-02-12.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Update to latest imodeljs native release
> iModeljs-native 4.7.23

- common/changes/@itwin/core-backend/2024-06-10-19-55.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Update to latest imodeljs native release
> iModeljs-native 4.7.25

- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
Updates Braces package to ^3.0.3
https://github.com/advisories/GHSA-grv7-fg5c-xmjg
> Resolve GHSA-grv7-fg5c-xmjg 

- test-apps/display-performance-test-app/src/frontend/TestRunner.ts
Reset selection between tests when reusing test contexts in DPTA
> Reset selection between tests when reusing test contexts in DPTA

- common/changes/@itwin/core-backend/ws-cve-GHSA-3h5v-q93c-6h6q_2024-06-18-17-04.json
- common/changes/@itwin/core-mobile/ws-cve-GHSA-3h5v-q93c-6h6q_2024-06-18-17-04.json
- common/changes/@itwin/ecschema-rpcinterface-tests/ws-cve-GHSA-3h5v-q93c-6h6q_2024-06-18-17-04.json
- common/changes/@itwin/rpcinterface-full-stack-tests/ws-cve-GHSA-3h5v-q93c-6h6q_2024-06-18-17-04.json
- common/config/azure-pipelines/templates/core-build.yaml
- common/config/rush/.pnpmfile.cjs
- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/mobile/package.json
- example-code/app/package.json
- example-code/snippets/package.json
- full-stack-tests/backend/package.json
- full-stack-tests/core/package.json
- full-stack-tests/ecschema-rpc-interface/package.json
- full-stack-tests/rpc-interface/package.json
- test-apps/display-performance-test-app/package.json
resolves [GHSA-3h5v-q93c-6h6q](https://github.com/advisories/GHSA-3h5v-q93c-6h6q)
better fix is in #6853 but theres issues with mobile immediately updating to ws@8
> update ws@7 to latest patch version to resolve GHSA-3h5v-q93c-6h6q

- common/api/core-frontend.api.md
- common/changes/@itwin/core-frontend/pmc-tiled-graphics-provider-near-far-planes_2024-06-19-14-07.json
- core/frontend/src/ViewingSpace.ts
- core/frontend/src/test/tile/TiledGraphicsProvider.test.ts
Fixes #6873.
Awaiting ImageTests results.
> Include extents of TiledGraphicsProviders in ViewingSpace extents.

- common/api/presentation-backend.api.md
- common/changes/@itwin/presentation-backend/presentation-customize-subject-for-ruleset-embedder_2024-06-28-14-20.json
- full-stack-tests/presentation/src/backend/RulesetsEmbedding.test.ts
- presentation/backend/src/presentation-backend/RulesetEmbedder.ts
- presentation/backend/src/test/RulesetEmbedder.test.ts
> Presentation: Add ability to customize subject ID for ruleset embedder

- common/api/core-geometry.api.md
- common/api/summary/core-geometry.exports.csv
- common/changes/@itwin/core-geometry/saeed-torabi-remove-alpha_2024-07-02-14-35.json
- core/geometry/src/Constant.ts
- core/geometry/src/curve/CurveCurve.ts
> Removed alpha from Constant and beta from CurveCurve.intersectionXYZPairs

- .github/workflows/automation-scripts/update-changelogs.mjs
- common/api/core-frontend.api.md
- common/api/summary/core-frontend.exports.csv
- common/changes/@itwin/core-bentley/element-set-tool_2024-07-02-16-43.json
- common/changes/@itwin/core-frontend/element-set-tool_2024-07-02-15-51.json
- core/bentley/src/CompressedId64Set.ts
- core/frontend/src/tools/ElementSetTool.ts
[Evaluate Release Tags](https://github.com/iTwin/itwinjs-backlog/issues/1103)
> Promote ElementSetTool from @alpha to @public for editing applications.

- common/api/core-frontend.api.md
- common/changes/@itwin/core-frontend/app-tooltip-filter_2024-07-04-16-08.json
- core/frontend/src/AccuSnap.ts
- core/frontend/src/public/locales/en/iModelJs.json
- core/frontend/src/tile/map/MapTileTree.ts
- core/frontend/src/tools/ToolAdmin.ts
Also localize strings used for default map layer tooltip.
[Release Tags](https://github.com/iTwin/itwinjs-backlog/issues/1103#issuecomment-2204522281)
> Allow apps to filter tooltip display.

- common/changes/@itwin/ecschema-editing/schema-editing-type-conflicts_2024-07-11-08-55.json
- core/ecschema-editing/src/Differencing/SchemaDiagnosticVisitor.ts
- core/ecschema-editing/src/test/Differencing/Conflicts.test.ts
> Fix property type and primitive type conflicts

- common/changes/@itwin/core-frontend/pmc-never-drawn-overwrite_2024-07-18-17-56.json
- core/frontend/src/render/FeatureSymbology.ts
- core/frontend/src/test/FeatureSymbologyOverrides.test.ts
Order of initialization issue.
> Fix Viewport's never-drawn elements overriding display style's excluded elements

- common/api/core-frontend.api.md
- common/changes/@itwin/core-frontend/accudraw-compass-display-change_2024-07-29-18-47.json
- core/frontend/src/AccuDraw.ts
Added method that is called when AccuDraw compass display changes.
> Support showing AccuDraw input fields in a popup at the cursor.

- common/changes/@itwin/core-frontend/mlemuzic-enable_schedule_script_in_editing_scope_2024-07-30-07-18.json
- core/frontend/src/tile/DynamicIModelTile.ts
- full-stack-tests/core/src/frontend/standalone/GraphicalEditingScope.test.ts
Enable schedule script for elements in edit scope.
> Enable schedule scripts from editing scope

- common/changes/@itwin/core-frontend/accudraw-is-active_2024-07-31-20-39.json
- core/frontend/src/AccuDraw.ts
Copy/paste error with implementation of isActive.
> Fix AccuDrawHintBuilder.isActive.

- common/api/core-frontend.api.md
- common/api/summary/core-frontend.exports.csv
- common/changes/@itwin/core-frontend/accudraw-shortcuts_2024-08-02-14-57.json
- core/frontend/src/public/locales/en/CoreTools.json
- core/frontend/src/tools/AccuDrawTool.ts
- AccuDrawShortcuts.sessionToggle: Disable/Enable AccuDraw for current session
- AccuDrawShortcuts.suspendToggle: Suspend/Unsuspend AccuDraw for current tool
- AccuDrawShortcuts.lockIndex: Disable/Enable indexing for next data point.
> Support editing applications with additional AccuDraw shortcuts.

- common/changes/@itwin/core-backend/rohitptnkr-invalid-property-category-doc_2024-08-08-06-54.json
- core/backend/src/IModelDb.ts
- docs/bis/guide/schema-evolution/schema-versioning-and-generations.md
imodel-native: https://github.com/iTwin/imodel-native/pull/827
> Updated docs for invalid property category check

- common/changes/@itwin/analytical-backend/nam-fix-cve_2024-08-08-17-48.json
- common/changes/@itwin/core-backend/nam-fix-cve_2024-08-08-17-48.json
- common/changes/@itwin/presentation-backend/nam-fix-cve_2024-08-08-17-48.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- domains/analytical/backend/package.json
- full-stack-tests/rpc/package.json
- presentation/backend/package.json
Mergify didn't work :( Manually cherry picked the commit for #7057 into the release branch.
> resolve CVE-2022-25883 (backport #7057) [release/4.8.x]

- full-stack-tests/backend/package.json
- full-stack-tests/backend/src/perftest/ECSqlRow.test.ts
Updating package.json scripts for build pipeline scripts
> Update perftest scripts to include pretest step

- common/changes/@itwin/certa/master_2024-08-20-13-52.json
- common/changes/@itwin/core-electron/master_2024-08-20-13-52.json
- common/config/rush/pnpm-lock.yaml
- core/electron/package.json
- docs/changehistory/NextVersion.md
- example-code/app/package.json
- full-stack-tests/core/package.json
- full-stack-tests/rpc/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- tools/certa/package.json
[Electron 32 breaking changes](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-320)
> Add support for Electron 32

- common/api/ecschema-editing.api.md
- common/changes/@itwin/ecschema-editing/schemaediting-koq-persistenceunit-conflict_2024-08-21-13-43.json
- core/ecschema-editing/src/Differencing/SchemaConflicts.ts
- core/ecschema-editing/src/Differencing/SchemaDiagnosticVisitor.ts
- core/ecschema-editing/src/test/Differencing/Conflicts.test.ts
Added conflict when same kind of quantity has different persistence unit
> Added conflict when same kind of quantity has different persistence unit

- common/changes/@itwin/core-bentley/travis-log-exception-fix_2024-09-12-16-48.json
- core/bentley/src/Logger.ts
- core/bentley/src/test/Logger.test.ts
Fix for https://github.com/iTwin/itwinjs-core/issues/7142.
> Fix Logger.logException when err is undefined or null

- docs/changehistory/NextVersion.md
Update `NextVersion.md` to mention the changes  from https://github.com/iTwin/imodel-native/pull/849, https://github.com/iTwin/itwinjs-core/pull/7127 and https://github.com/iTwin/itwinjs-core/pull/7147.
> Presentation: `NextVersion.md` update

- docs/changehistory/4.9.0.md
- docs/changehistory/index.md
- docs/changehistory/leftNav.md
Backports the missing ChangeHistory from the 4.9.0 release
> 4.9.0 ChangeHistory

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/affank-fix-classid-to-json-rule_2024-10-04-21-19.json
- common/changes/@itwin/core-common/affank-fix-classid-to-json-rule_2024-10-04-21-19.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/backend/src/ECSqlStatement.ts
- core/backend/src/test/ecdb/ECSqlQuery.test.ts
- core/backend/src/test/ecdb/ECSqlStatement.test.ts
- core/common/src/ECSqlReader.ts
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
imodel-native: https://github.com/iTwin/imodel-native/pull/878
> Fix regression caused by ClassId conversion to class name vs hexid

- common/changes/@itwin/core-backend/brep-entity-transform_2024-10-18-23-43.json
- common/changes/@itwin/core-common/brep-entity-transform_2024-10-18-23-43.json
- core/backend/src/test/standalone/GeometryStream.test.ts
- core/common/src/geometry/ElementGeometry.ts
- core/common/src/geometry/GeometryStream.ts
Discovered by code to apply a scale factor to geometry stream entries.
> GeometryStream builder/iterator wasn't applying correct transform to brep.

- common/changes/@itwin/ecschema-rpcinterface-tests/mike-fix-oidc-hang_2024-10-29-22-35.json
- common/changes/@itwin/rpcinterface-full-stack-tests/mike-fix-oidc-hang_2024-10-29-22-35.json
- common/config/azure-pipelines/templates/core-build.yaml
- common/config/rush/pnpm-lock.yaml
- example-code/app/package.json
- example-code/snippets/package.json
- full-stack-tests/backend/package.json
- full-stack-tests/core/package.json
- full-stack-tests/ecschema-rpc-interface/package.json
- full-stack-tests/rpc-interface/package.json
- test-apps/display-performance-test-app/package.json
Update oidc signin tool to latest to fix hanging tests
> Update oidc-signin-tool to 4.3.7

- common/changes/@itwin/ecschema-rpcinterface-common/eschema-rpc-common-esm_2024-11-11-13-55.json
- core/ecschema-rpc/common/package.json
Added ESM build to `@itwin/ecschema-rpcinterface-common` package.
> `@itwin/ecschema-rpcinterface-common`: added ESM build

- common/changes/@itwin/core-backend/floatingPointWordWrapping_2024-11-13-22-20.json
- core/backend/src/TextAnnotationLayout.ts
- core/backend/src/test/annotations/TextAnnotation.test.ts
> Floating point word wrapping

- common/changes/@itwin/core-backend/pmc-container-type-overwritten_2024-11-14-12-30.json
- core/backend/src/CloudSqlite.ts
- example-code/snippets/src/backend/WorkspaceExamples.test.ts
> Fix containerType being overwritten with "property-store"

- common/changes/@itwin/build-tools/gytis-fix-audit-issue_2024-11-18-13-04.json
- common/changes/@itwin/core-electron/gytis-fix-audit-issue_2024-11-18-13-04.json
- common/changes/@itwin/presentation-backend/gytis-fix-audit-issue_2024-11-18-13-04.json
- common/changes/@itwin/presentation-common/gytis-fix-audit-issue_2024-11-18-13-04.json
- common/changes/@itwin/presentation-frontend/gytis-fix-audit-issue_2024-11-18-13-04.json
- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
- core/electron/package.json
- full-stack-tests/presentation/package.json
- presentation/backend/package.json
- presentation/common/package.json
- presentation/frontend/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- tools/build/package.json
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ Regular Expression Denial of Service (ReDoS) in        │
│                     │ cross-spawn                                            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ cross-spawn                                            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <7.0.5                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=7.0.5                                                │
├─────────────────────┼──────────────────────────────────────────── …
```
> Resolve GHSA-3xgq-45jj-v275

- common/changes/@itwin/core-frontend/master_2024-11-20-15-45.json
- core/frontend/src/tile/map/ImageryProviders/BingImageryProvider.ts
Fix regression #7406 introduced by #7233.
> Fix duplicate Bing map attributions.

- .github/workflows/codeql-analysis.yml
- .github/workflows/create-release.yaml
- .github/workflows/extract-api.yaml
- .github/workflows/finalize-release.yaml
- .github/workflows/invalidate-open-prs.yaml
- .github/workflows/invalidate-prs.yaml
- .github/workflows/sanity.yaml
- .github/workflows/status-check-override.yaml
- common/config/azure-pipelines/ci-ios.yaml
- common/config/azure-pipelines/jobs/docs-build.yaml
- common/config/azure-pipelines/jobs/fast-ci.yaml
- common/config/azure-pipelines/jobs/version-bump.yaml
- common/config/azure-pipelines/templates/core-build.yaml
- common/config/azure-pipelines/templates/integration-test-steps.yaml
- common/config/azure-pipelines/valgrind.yaml
upgrade to UseNode because node tool is depricated, update checkout to v4
> Update UseNode and Checkout in yml files

- common/api/core-frontend.api.md
- common/changes/@itwin/core-frontend/accudraw-lock-changed_2024-12-16-14-05.json
- core/frontend/src/AccuDraw.ts
- test-apps/display-test-app/src/frontend/App.ts
- test-apps/display-test-app/src/frontend/DrawingAidTestTool.ts
Added AccuDraw test UI to dta.
> Correct erroneous AccuDraw item field lock change notifications.

- common/changes/@itwin/core-frontend/core-frontend-blank-connection-raise-onopen_2024-12-18-06-20.json
- common/changes/@itwin/presentation-frontend/core-frontend-blank-connection-raise-onopen_2024-12-18-06-20.json
- core/frontend/src/IModelConnection.ts
- core/frontend/src/test/BlankConnection.test.ts
- full-stack-tests/presentation/src/frontend/selection/SelectionManager.test.ts
- presentation/frontend/src/test/selection/SelectionManager.test.ts
Fixes https://github.com/iTwin/itwinjs-core/issues/7498
> Raise `IModelConnection.onChange` when a new `BlankConnection` is created

- common/api/core-common.api.md
- common/api/summary/core-common.exports.csv
- common/changes/@itwin/core-backend/pmc-rm-imodel-encryption-props_2024-12-22-14-09.json
- common/changes/@itwin/core-common/pmc-rm-imodel-encryption-props_2024-12-22-14-09.json
- core/backend/src/IModelDb.ts
- core/common/src/BriefcaseTypes.ts
- core/common/src/IModel.ts
> Remove IModelEncryptionProps

- common/changes/@itwin/core-backend/pmc-redo-string-fix_2025-01-06-12-27.json
- core/backend/src/IpcHost.ts
> Fix IPC redo string

- common/api/core-bentley.api.md
- common/changes/@itwin/core-bentley/mike-remove-deprecated-corebentley_2025-01-16-19-39.json
- core/bentley/src/ByteStream.ts
- core/bentley/src/Id.ts
- docs/changehistory/NextVersion.md
Removes deprecated APIs from core-bentley package
> Remove deprecated 3.x APIs in core-bentley

- common/config/azure-pipelines/jobs/fast-ci.yaml
> Moving to `imodelNative-Win11-VS2022` Pool

- common/changes/@itwin/presentation-frontend/presentation-backport-selection-manager-fix_2025-01-28-05-46.json
- presentation/frontend/src/presentation-frontend/selection/SelectionManager.ts
- presentation/frontend/src/test/selection/SelectionManager.test.ts
Fixes https://github.com/iTwin/itwinjs-core/issues/7496.
Backport part of https://github.com/iTwin/itwinjs-core/pull/7497.
> Presentation: Fix selection changes not being handled when using multiple connections to the same iModel

- docs/presentation/content/index.md
Closes https://github.com/iTwin/itwinjs-core/issues/7257
> Presentation: Update link to a sample

- common/changes/@itwin/core-frontend/fix-txnEntityChanges-typo_2025-02-03-15-04.json
- core/frontend/src/TxnEntityChanges.ts
Fix TxnEntityChanges typo
#7639
> Fix TxnEntityChanges typo

- common/changes/@itwin/appui-abstract/docs-typo-fixes_2025-02-03-14-56.json
- common/changes/@itwin/core-frontend/docs-typo-fixes_2025-02-03-14-56.json
- core/frontend/src/TxnEntityChanges.ts
- ui/appui-abstract/src/appui-abstract/dialogs/DialogItem.ts
Handle a minor reported issue with our documentation.
closes #7516
> Fix a documentation typo

- common/api/presentation-backend.api.md
- common/api/presentation-common.api.md
- common/api/summary/presentation-backend.exports.csv
- common/api/summary/presentation-common.exports.csv
- common/changes/@itwin/presentation-backend/presentation-remove-3x-deprecations-in-backend_2025-02-12-07-10.json
- common/changes/@itwin/presentation-common/presentation-remove-3x-deprecations-in-backend_2025-02-12-07-10.json
- docs/changehistory/NextVersion.md
- full-stack-tests/presentation/src/IntegrationTests.ts
- full-stack-tests/presentation/src/backend/PresentationManager.test.ts
- presentation/backend/src/presentation-backend/PresentationManager.ts
- presentation/backend/src/presentation-backend/PresentationRpcImpl.ts
- presentation/backend/src/presentation-backend/SelectionScopesHelper.ts
- presentation/backend/src/test/PresentationManager.test.ts
- presentation/backend/src/test/PresentationRpcImpl.test.ts
- presentation/backend/src/test/SelectionScopesHelper.test.ts
- presentation/common/src/presentation-common/PresentationManagerOptions.ts
- presentation/common/src/test/PresentationManagerOptions.test.ts
Closes https://github.com/iTwin/itwinjs-backlog/issues/1363
> Presentation: Clean up APIs deprecated in `3.x`

- common/changes/@itwin/presentation-backend/presentation-exclude-ruleset-from-info-logs_2025-02-18-23-35.json
- presentation/backend/src/presentation-backend/PresentationRpcImpl.ts
Closes https://github.com/iTwin/presentation/issues/876
> Presentation: Exclude ruleset from INFO level logs

- common/changes/@itwin/core-geometry/saeed-torabi-createPartialRotationVectorToVector_2025-02-19-15-56.json
- core/geometry/src/geometry3d/Matrix3d.ts
- core/geometry/src/test/geometry3d/Matrix3d.test.ts
It was not returing matrix in result.
> Fixed Matrix3d.createPartialRotationVectorToVector bug

- docs/learning/backend/HandlingUnknownSchemaElements.md
Documentation for changes done in the imodel-native PR https://github.com/iTwin/imodel-native/pull/977
> Documentation to cover unsupported mapping strategies in newer imodels

- common/changes/@itwin/certa/master_2025-03-04-13-36.json
- common/changes/@itwin/core-electron/master_2025-03-04-13-36.json
- common/config/rush/pnpm-lock.yaml
- core/electron/package.json
- docs/changehistory/NextVersion.md
- docs/learning/SupportedPlatforms.md
- example-code/app/package.json
- full-stack-tests/core/package.json
- full-stack-tests/rpc/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- tools/certa/package.json
[Electron 35 breaking changes](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-350)
> Upgrade to Electron 35

- common/changes/@itwin/core-frontend/MichelD-fixArcGisValidate_2025-03-06-19-33.json
- core/frontend/src/internal/tile/map/ArcGisUtilities.ts
- core/frontend/src/test/tile/map/ArcGisUtilities.test.ts
Fix [#7801](https://github.com/iTwin/itwinjs-core/issues/7801)
> Fix issue validating ArcGIS service URL

- docs/bis/guide/intro/modeling-with-bis.md
> Rewrite how aspect can be used in relationships to be less confusing

- common/api/core-backend.api.md
- common/api/core-common.api.md
- common/api/summary/core-common.exports.csv
- common/changes/@itwin/core-backend/pmc-drawing-scale-factor_2025-04-03-13-40.json
- common/changes/@itwin/core-common/pmc-drawing-scale-factor_2025-04-03-13-40.json
- common/changes/@itwin/core-extension/pmc-drawing-scale-factor_2025-04-03-14-22.json
- core/backend/src/Element.ts
- core/backend/src/test/standalone/Drawing.test.ts
- core/common/src/ElementProps.ts
- core/extension/index.d.ts
Update API for the [introduction](https://github.com/iTwin/bis-schemas/pull/458) of this property in BisCore 1.18.0.
> Add Drawing.scaleFactor

- common/api/analytical-backend.api.md
- common/api/ecschema-metadata.api.md
- common/api/linear-referencing-backend.api.md
- common/api/physical-material-backend.api.md
- common/changes/@itwin/analytical-backend/fix-domains_2025-04-03-16-40.json
- common/changes/@itwin/linear-referencing-backend/fix-domains_2025-04-03-16-40.json
- common/changes/@itwin/linear-referencing-common/fix-domains_2025-04-03-18-25.json
- common/changes/@itwin/physical-material-backend/fix-domains_2025-04-03-16-40.json
- common/config/rush/pnpm-lock.yaml
- domains/analytical/backend/.mocharc.jsonc
- domains/analytical/backend/package.json
- domains/analytical/backend/src/AnalyticalSchema.ts
- domains/analytical/backend/src/test/AnalyticalSchema.test.ts
- domains/linear-referencing/backend/.mocharc.jsonc
- domains/linear-referencing/backend/package.json
- domains/linear-referencing/backend/src/LinearReferencingSchema.ts
- domains/linear-referencing/backend/src/test/LinearReferencingSchema.test.ts
- domains/linear-referencing/common/package.json
- domains/physical-material/backend/.mocharc.jsonc
- domains/physical-material/backend/package.json
- domains/physical-material/backend/src/PhysicalMaterialSchema.ts
- domains/physical-material/backend/src/test/PhysicalMaterialSchema.test.ts
https://github.com/iTwin/itwinjs-core/pull/7892 incorrectly tried to override the mocharc config; re-dd the rest of those settings
> try to fix domains, mocharc not complete

- common/api/core-frontend.api.md
- common/changes/@itwin/core-frontend/one-shot-view-tools_2025-04-08-13-51.json
- core/frontend/src/tools/ViewTool.ts
> Don't leave a one shot, drag only view tool active after the mouseover event and no longer dragging.

- common/config/azure-pipelines/jobs/docs-build.yaml
Update BeMetalsmith in docs build to 6.0. Notable improvements:
- mermaid chart support
- typedoc 0.28 compatibility
- sass-free
- jquery-free
- ESM + Many dev quality of life issues.
> bemetalsmith@6.x

- common/config/azure-pipelines/templates/gather-docs.yaml
Due to error in changelog script this didn't get updated. Waiting on fix for changelog script, but correcting now before first patch release
> 4.11 gather docs

- common/changes/@itwin/core-backend/mike-reduce-cache-size_2025-05-01-19-28.json
- core/backend/src/IModelDb.ts
Reduces the element cache to 50 elements and the model cache to 10 models.
> Reduce Element and Model Cache Size

- common/changes/@itwin/core-frontend/webpack-magic-comment_2025-05-13-17-35.json
- core/frontend/src/extension/providers/ExtensionLoadScript.ts
for bundlers based like webpack and rspack
> add webpack magic comment to suppress csp

- common/changes/@itwin/core-backend/pmc-fix-text-width-factor_2025-05-14-20-58.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/backend/src/test/annotations/TextAnnotation.test.ts
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Fixes #8086.
imodel-native: https://github.com/iTwin/imodel-native/pull/1113
> Fix text width factor

- common/changes/@itwin/presentation-common/JonasD-exported-ruleset-schema_2025-05-15-07-59.json
- presentation/common/package.json
> Export Ruleset.schema.json through exports field

- common/changes/@itwin/certa/master_2025-05-19-12-24.json
- common/changes/@itwin/core-electron/master_2025-05-19-12-24.json
- common/config/rush/pnpm-lock.yaml
- core/electron/package.json
- docs/changehistory/NextVersion.md
- example-code/app/package.json
- full-stack-tests/core/package.json
- full-stack-tests/rpc/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- tools/certa/package.json
[Electron 36 breaking changes](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-360)
> Add support for Electron 36

- common/changes/@itwin/core-frontend/locate-failure-tooltip_2025-06-09-15-07.json
- core/frontend/src/AccuSnap.ts
> Allow ToolAdmin.wantToolTip to decide whether the locate failure message is displayed.

- docs/changehistory/leftNav.md
update left nav to have 4.11.0
> 4.11.0.md in left nav

- common/config/azure-pipelines/jobs/docs-build.yaml
- common/config/azure-pipelines/jobs/docs-ci.yaml
Archives the v4 docs to release/4.11.x.
> Archive docs v4

- common/changes/@itwin/core-quantity/nam-bearing-flexibility_2025-06-16-15-37.json
- core/quantity/src/Parser.ts
- core/quantity/src/test/BearingAzimuth.test.ts
- core/quantity/src/test/Parsing.test.ts
> Expand parsing flexibility for Bearing input strings.

- common/changes/@itwin/core-backend/arbrumbaugh-fix-recipe-init_2025-06-24-16-05.json
- core/backend/src/Element.ts
Initialize the recipe property from the supplied value in props.
Addresses #8274
> Fix recipe initialization in TypeDefinitionElement

- common/changes/@itwin/map-layers-formats/bipin-export-package-json_2025-07-02-19-05.json
- extensions/map-layers-formats/package.json
Issue: https://github.com/iTwin/itwinjs-backlog/issues/1544
>  package.json added to exports - @itwin/map-layers-formats 

- common/changes/@itwin/certa/gytis-electron-37_2025-07-10-08-32.json
- common/changes/@itwin/core-electron/gytis-electron-37_2025-07-10-08-32.json
- common/config/rush/pnpm-lock.yaml
- core/electron/package.json
- docs/changehistory/NextVersion.md
- example-code/app/package.json
- full-stack-tests/core/package.json
- full-stack-tests/rpc/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- tools/certa/package.json
[Electron 37 breaking changes](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-370)
> Add support for Electron 37

- common/changes/@itwin/core-backend/nam-cve-GHSA-fjxv-7rqg-78g4_2025-07-21-21-58.json
- common/changes/@itwin/core-electron/nam-cve-GHSA-fjxv-7rqg-78g4_2025-07-21-21-58.json
- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/electron/package.json
> Address CVE GHSA-fjxv-7rqg-78g4

- docs/learning/SupportedPlatforms.md
Also update required glibc/glibcxx versions.
> Fix supp'd plats to be x64-only for win/lin and update redist link

- CONTRIBUTING.md
- common/changes/@itwin/core-backend/nam-update-documentations_2025-08-25-15-45.json
- core/backend/src/workspace/Workspace.ts
- test-apps/display-test-app/README.md
Closes https://github.com/iTwin/itwinjs-core/issues/8450
- Found a typo in workspace documentation
> Improve documentation on backports and setting up repo

- common/changes/@itwin/certa/gytis-electron-28_2025-09-22-07-12.json
- common/changes/@itwin/core-electron/gytis-electron-28_2025-09-22-07-12.json
- common/config/rush/pnpm-lock.yaml
- core/electron/package.json
- docs/changehistory/NextVersion.md
- example-code/app/package.json
- full-stack-tests/core/package.json
- full-stack-tests/rpc/package.json
- test-apps/display-performance-test-app/package.json
- test-apps/display-test-app/package.json
- tools/certa/package.json
[Electron 38 breaking changes](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-380)
> Add support for Electron 38

- common/api/core-backend.api.md
- common/changes/@itwin/core-backend/tcobbs-bcv-stats-fix_2025-09-29-22-24.json
- common/config/rush/pnpm-lock.yaml
- core/backend/package.json
- core/backend/src/CloudSqlite.ts
- full-stack-tests/backend/src/integration/Checkpoints.test.ts
- full-stack-tests/backend/src/integration/CloudSqlite.test.ts
- test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle
- test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj
- tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
imodel-native: https://github.com/iTwin/imodel-native/pull/1220
> Update unit tests bcv stats API change

- common/changes/@itwin/core-backend/dan-revert-deprecation-dates_2025-10-01-19-07.json
- common/changes/@itwin/presentation-backend/dan-revert-deprecation-dates_2025-10-01-19-07.json
- common/changes/@itwin/presentation-common/dan-revert-deprecation-dates_2025-10-01-19-07.json
- common/changes/@itwin/presentation-frontend/dan-revert-deprecation-dates_2025-10-01-19-07.json
- core/backend/src/BriefcaseManager.ts
- presentation/backend/src/presentation-backend/PresentationManager.ts
- presentation/common/src/presentation-common/KeySet.ts
- presentation/common/src/presentation-common/PresentationManagerOptions.ts
- presentation/common/src/presentation-common/PresentationRpcInterface.ts
- presentation/common/src/presentation-common/Update.ts
- presentation/common/src/presentation-common/hierarchy/HierarchyLevel.ts
- presentation/common/src/presentation-common/hierarchy/Key.ts
- presentation/common/src/presentation-common/hierarchy/Node.ts
- presentation/common/src/presentation-common/hierarchy/NodePathElement.ts
- presentation/common/src/presentation-common/rules/customization/GroupingRule.ts
- presentation/common/src/presentation-common/rules/hierarchy/ChildNodeRule.ts
- presentation/common/src/presentation-common/rules/hierarchy/ChildNodeSpecification.ts
- presentation/common/src/presentation-common/rules/hierarchy/CustomNodeSpecification.ts
- presentation/common/src/presentation-common/rules/hierarchy/CustomQueryInstanceNodesSpecification.ts
- presentation/common/src/presentation-common/rules/hierarchy/InstanceNodesOfSpecificClassesSpecification.ts
- presentation/common/src/presentation-common/rules/hierarchy/NavigationRule.ts
- presentation/common/src/presentation-common/rules/hierarchy/NodeArtifactsRule.ts
- presentation/common/src/presentation-common/rules/hierarchy/RelatedInstanceNodesSpecification.ts
- presentation/common/src/presentation-common/rules/hierarchy/RootNodeRule.ts
- presentation/common/src/presentation-common/rules/hierarchy/SubCondition.ts
- presentation/frontend/src/presentation-frontend/PresentationManager.ts
This reverts commit 7617f4341b78c3e33a190ae51be73cbb6a0498f0.
> Revert "Apply deprecation date rule"
