iTwin/itwinjs-core

common/changes/@itwin/appui-layout-react/fix-resize-issue_2022-09-15-13-36.json, ui/appui-layout-react/src/appui-layout-react/state/internal/NineZoneStateHelpers.ts, ui/appui-layout-react/src/appui-layout-react/state/internal/WidgetStateHelpers.ts
This PR fixes a floating widget resize interaction.
The culprit of the problem was introduction of [non-immerable](https://immerjs.github.io/immer/complex-objects/) object - instance of `Rectangle` class was used for `bounds` property of a `FloatingWidgetState`.
=> Fix a floating widget resize issue

common/api/presentation-components.api.md, common/changes/@itwin/presentation-components/presentation-tree-node-loader-props_2022-09-02-15-59.json, presentation/components/src/presentation-components/tree/controlled/TreeHooks.ts
We are announcing addition of `seedTreeModel` property in `NextVersion.md`, thus this property should be at least in `@beta` phase.
We also do not want users to be combining `enableHierarchyAutoUpdate` and `seedTreeModel` properties.
=> Presentation: Improve seedTreeModel documentation.

.github/CODEOWNERS
Make the Core UI team the codeowners for appui-test-app .
=> Update CODEOWNERS for appui-test-app

common/api/core-geometry.api.md, common/changes/@itwin/core-geometry/pmc-fix-boxprops-api-change_2022-09-24-18-58.json, core/backend/src/GeometrySummary.ts, core/backend/src/test/element/ElementRoundTrip.test.ts, core/geometry/src/serialization/IModelJsonSchema.ts, core/geometry/src/solid/Box.ts, core/geometry/src/test/serialization/IModelJson.test.ts, docs/changehistory/NextVersion.md, docs/learning/geometry/IModelJsonGeometrySchema.md
Fixes #4350
Retain `origin` as  the documented, required way to specify the origin of the box's base rectangle.
Add `baseOrigin` as an optional, deprecated, undocumented property with the same meaning as `origin`.
Output both when serializing.
When deserializing, if `origin` is not present, try to use `baseOrigin` instead.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/281508).
TODO: test, lint, extract-api, etc.
=> Fix BoxProps breaking API change

common/changes/@itwin/components-react/raplemie-removeSkippedUITests_2022-09-26-20-55.json, common/changes/@itwin/imodel-components-react/raplemie-removeSkippedUITests_2022-09-26-20-55.json, ui/components-react/src/test/editors/EnumEditor.test.tsx, ui/components-react/src/test/table/columnfiltering/TableFilterDescriptor.test.ts, ui/components-react/src/test/table/component/Table.test.tsx, ui/components-react/src/test/table/component/TableCell.test.tsx, ui/imodel-components-react/src/test/navigationaids/CubeNavigationAid.test.tsx
When this was done for other packages, I asked UI to be left away because of the ongoing Enzyme stuff, however these packages will not be touched by the enzyme removal short term, so I remove /fix the tests.
I'll try to run the CI a couple of times to see if the remaining tests are flaky.
Follow up of  iTwin/itwinjs-backlog#386
=> UI: Remove skipped tests

common/changes/@itwin/core-electron/gytis-ElectronHost-tests_2022-09-16-11-55.json, core/electron/src/backend/ElectronHost.ts, core/electron/src/test/backend/ElectronHost.test.ts
Adds 5 new tests to existing `ElectronHost` test suite.
Any suggestions for future Electron testing are welcome.
=> Add new `ElectronHost` tests

common/changes/@itwin/core-i18n/build-and-webpack_2022-09-27-16-12.json, core/i18n/package.json
Changes made based on the following comment:
> Please make sure either the `build` or the `test` script does the webpacking. `rush build:ci` followed by `rush cover` should suffice to run all tests.
_Originally posted by @pmconne in https://github.com/iTwin/itwinjs-core/issues/4323#issuecomment-1259592991_
=> Add `webpack:test` to `build:ci` script 

common/changes/@itwin/core-common/TileRpcVerBump_2022-09-28-21-25.json, core/common/src/rpc/IModelTileRpcInterface.ts
[See changes](https://github.com/iTwin/itwinjs-core/blob/b1e1582b462a099242114fce5c9a4bf9c8f608a0/core/common/src/rpc/IModelTileRpcInterface.ts)
=> bump tile rpc version after object storage pr

common/changes/@itwin/core-backend/fix-tilerpc_2022-09-29-16-09.json, common/changes/@itwin/core-common/fix-tilerpc_2022-09-29-16-09.json, common/changes/@itwin/core-frontend/fix-tilerpc_2022-09-29-16-09.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/TileStorage.ts, core/common/package.json, core/frontend/package.json, full-stack-tests/core/package.json, test-apps/display-test-app/package.json
The object-storage packages were missing a header that was needed for requesting tiles. That fix was in this PR, https://github.com/iTwin/object-storage/pull/65, and is pulled in via the 1.4.0 release of those packages.
=> add missing header to TileStorage.uploadTile

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-render-material-docs_2022-10-04-19-20.json, core/frontend/src/render/RenderMaterial.ts, docs/learning/frontend/Views.md
Replace inline interface definitions with named, publicly documented interfaces.
Noticed the problem, illustrated below, when linking to documentation in response to a [question](https://github.com/iTwin/itwinjs-core/discussions/4423#discussioncomment-3797261).
```
interface Thing {
prop: {
/** This documentation is not published and therefore useless. */
innerProp: boolean;
};
}
```
Also add [camera visualization sample](https://www.itwinjs.org/sandboxes/iTwinPlatform/Camera%20Visualizer) to Views.md.
=> Material and view documentation

common/api/appui-layout-react.api.md, common/api/summary/appui-layout-react.exports.csv, common/changes/@itwin/appui-layout-react/auto-hide-fixes_2022-10-05-10-29.json, common/changes/@itwin/appui-react/auto-hide-fixes_2022-10-05-10-29.json, ui/appui-layout-react/src/appui-layout-react/base/NineZone.tsx, ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.scss, ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.tsx, ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidgets.tsx, ui/appui-layout-react/src/appui-layout-react/widget/Widget.tsx, ui/appui-layout-react/src/test/widget/FloatingWidget.test.tsx, ui/appui-layout-react/src/test/widget/TabBar.test.tsx, ui/appui-react/src/appui-react/widget-panels/FloatingWidget.tsx, ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
This PR fixes auto-hide UI related issues.
1. Hovering a hidden floating widget consumes the pointer event w/o showing the UI (content area/viewport doesn't receive pointer events).
2. UI (with floating widgets) is hidden when mouse is hovering over a floating widget.
=> Fix auto-hide UI issues

common/changes/@bentley/imodeljs-editor-frontend/pmc-transform-elements-2.19.x_2022-10-06-11-36.json, editor/frontend/src/TransformElementsTool.ts
Fixes #4404.
Is really a band-aid because we're limited in what we can change in 2.19.x.
Fix properly in 3.x.
=> Prevent distorted graphics when transforming elements far from the origin

common/changes/@itwin/appui-layout-react/raplemie-panelHandlePriority_2022-10-06-16-15.json, ui/appui-layout-react/src/appui-layout-react/widget-panels/Panel.scss
This brings the handle on top of the splitter so the full handle area is usable even if the spliter occupy the same space.
Fixes iTwin/itwinjs-backlog#457
=> UI: Priorize panel handles over panel splitters

common/api/appui-react.api.md, common/api/summary/appui-react.exports.csv, common/changes/@itwin/appui-react/restore-frontstages_2022-10-10-13-17.json, ui/appui-react/public/locales/en/UiFramework.json, ui/appui-react/src/appui-react/frontstage/FrontstageManager.ts, ui/appui-react/src/appui-react/tools/RestoreLayoutTool.ts
This PR adds a `RestoreFrontstagesLayoutTool` that restores layout of all frontstages.
The tool can be invoked via `restore frontstages layout` key-in, which supplements existing `restore frontstage layout {frontstageId}` (which is used to restore currently active OR specific frontstage by providing optional frontstageId).
=> Add restore frontstages tool

common/changes/@itwin/core-backend/da4-eg-add-rejected-mesh-test_2022-10-10-21-14.json, core/backend/src/test/standalone/ExportGraphics.test.ts
Add exportGraphics test for fixed-block meshes.
* This tests the native fix for https://github.com/iTwin/itwinjs-core/issues/4368 from 2 weeks ago.
* This is not needed for 3.4.
=> exportGraphics: add test for fixed-block mesh

common/scripts/gather_packages.py
Dist tag was being hardcoded to "previous", but new releases of 2.x packages should be "latest" because they do not overlap with the 3.x package names.
=> Fix incorrect dist tag for 2.x releases

common/changes/@itwin/presentation-backend/presentation-fix-rpc-impl-cancelling-requests-by-mistake_2022-10-11-12-05.json, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/462.
Turns out the `CloudCache`-related crash with app verifier enabled was a false alarm (probably). That was a continuable stop related to freeing an active critical section.
The actual problem was that we didn't account for zero requests timeout, which should mean "no timeouts" in our RPC code. That means we cancelled the requests after 10 seconds and it seems on slower machines we may sometimes exceed that. When the request is cancelled, the backend returns an error response with "cancelled" status and our frontend code "eats" the error and returns some default value - `0`, `[]`, etc. Filed an issue https://github.com/iTwin/itwinjs-core/issues/4467 to look into that.
=> Presentation: Fix `PresentationRpcImpl` cancelling requests when it's configured to not use request timeout

common/changes/@itwin/core-frontend/pmc-fix-point-cloud-shader-assertion_2022-10-12-21-12.json, core/frontend/src/render/webgl/glsl/PointCloud.ts
#4466 removed assignment of frag color. Would have been caught by assertion, but tests don't run with assertions enabled (why?). It appears we have no ImageTests views that cover classified, hilited point clouds.
=> Fix point cloud classified hiliter

common/api/appui-layout-react.api.md, common/api/summary/appui-layout-react.exports.csv, common/changes/@itwin/appui-layout-react/close-widget-overflow_2022-10-14-10-17.json, ui/appui-layout-react/src/appui-layout-react/base/DragManager.tsx, ui/appui-layout-react/src/appui-layout-react/widget-panels/AppContent.tsx, ui/appui-layout-react/src/appui-layout-react/widget-panels/Panel.tsx, ui/appui-layout-react/src/appui-layout-react/widget/Overflow.tsx, ui/appui-layout-react/src/test/base/DragManager.test.tsx, ui/appui-layout-react/src/test/widget-panels/AppContent.test.tsx, ui/appui-layout-react/src/test/widget-panels/Panel.test.tsx
This PR fixes an issue where widget overflow popup is not closed when a panel is collapsed (when `AutoCollapseUnpinnedPanelsContext` is set to `true`).
Additionally panels will auto-collapse when the app content is hovered instead of when the mouse leaves the panel (since popups are usually rendered outside of panel element tree, resulting in auto-collapse when i.e. a widget overflow popup is hovered).
=> Close widget overflow when panel is collapsed

common/api/appui-react.api.md, common/api/summary/appui-react.exports.csv, common/changes/@itwin/appui-react/rename-restore-frontstages_2022-10-17-11-54.json, ui/appui-react/public/locales/en/UiFramework.json, ui/appui-react/src/appui-react/tools/RestoreLayoutTool.ts
This PR renames `RestoreFrontstagesLayoutTool` to `RestoreAllFrontstagesTool`.
=> Rename RestoreFrontstagesLayoutTool to RestoreAllFrontstagesTool

common/api/core-backend.api.md, common/changes/@itwin/core-backend/pmc-tile-cache-cleanup_2022-10-15-14-21.json, core/backend/src/IModelHost.ts, core/backend/src/test/IModelHost.test.ts
Adds `IModelHostOptions.maxTileCacheDbSize`.
[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/286803).
=> Allow applications to configure max tile cache size

common/changes/@itwin/core-backend/getElementProps-exception_2022-10-18-17-24.json, core/backend/src/IModelDb.ts, core/backend/src/test/standalone/TxnManager.test.ts
Fixes Issue #4505 
in 3.4.0, it was throwing `Error`, which is different than older versions and the documentation.
=> IModelDb.elements.getElementProps should throw IModelError

common/changes/@itwin/core-backend/pmc-pending-viewstate-request_2022-10-20-17-54.json, core/backend/src/PromiseMemoizer.ts, core/backend/src/rpc-impl/IModelReadRpcImpl.ts, core/backend/src/rpc-impl/IModelTileRpcImpl.ts
Fixes #4517
There are no existing tests for `getCustomViewState3dData`, and the new memoization bit would be quite tricky to test.
=> Memoize getCustomViewState3dData rpc requests

common/changes/@itwin/core-frontend/pmc-remove-terrain-lighting_2022-10-24-19-50.json, core/frontend/src/render/primitives/SurfaceParams.ts, core/frontend/src/render/primitives/VertexTable.ts, core/frontend/src/render/primitives/VertexTableSplitter.ts, core/frontend/src/render/primitives/mesh/MeshPrimitives.ts, core/frontend/src/render/webgl/MeshData.ts, core/frontend/src/render/webgl/MeshGeometry.ts, core/frontend/src/render/webgl/RenderFlags.ts, core/frontend/src/render/webgl/SurfaceGeometry.ts, core/frontend/src/render/webgl/glsl/Lighting.ts, core/frontend/src/render/webgl/glsl/Surface.ts, core/frontend/src/tile/ImdlReader.ts
`SurfaceFlags.NoFaceFront` was set only if `SurfaceParams.hasFixedNormals`, which is always false.
It was introduced to enable applying lighting to terrain, but applying lighting to terrain was silly so we disabled that.
@MarcNeely intends to replace this flag with one that indicates the surface uses a normal map.
=> Remove obsolete terrain lighting code

common/api/core-frontend.api.md, common/changes/@itwin/core-electron/ipc-function-proxy_2022-10-26-12-47.json, common/changes/@itwin/core-frontend/ipc-function-proxy_2022-10-26-12-47.json, common/changes/@itwin/editor-frontend/ipc-function-proxy_2022-10-26-12-47.json, core/electron/src/frontend/ElectronApp.ts, core/frontend/src/IpcApp.ts, editor/frontend/src/EditToolIpc.ts, test-apps/ui-test-app/src/frontend/tools/editing/PlaceBlockTool.ts
#4533 broke the Electron.Dialog ipc.
Adds `IpcApp.makeIpcFunctionProxy` which is also useful for edit tools.
=> Fix Electron dialog ipc

.github/workflows/status-check-override.yaml
The tj-actions glob that matches for changelog files that was introduced in https://github.com/iTwin/itwinjs-core/pull/4547, was wrong. This fixes it.
Tested here: https://github.com/mattbjordan/itwinjs-core-mattbjordan/pull/10
This was noticed in https://github.com/iTwin/itwinjs-core/pull/4563 where the extract-api build was skipped, but not faked as successful.
=> Fix changelogs glob

common/config/azure-pipelines/jobs/ci-core.yaml, common/config/azure-pipelines/templates/publish.yaml
Currently, to determine whether to publish a new set of itwinjs packages, we check npmjs to see if the local package versions have already been published. Generally, when we commit a new version bump as part of our release procedures, the new packages are picked up and published from that commit. 
If the CI build for a version bump commit fails due to some transient issue (flaky tests), it is possible for a new CI build triggered after the version bump to be picked up as the new release. This PR adds additional validation so that we can only trigger the release of a new iTwin.js version from the CI build of a version bump.
=> Only publish packages from version bumps

common/changes/@itwin/core-frontend/pmc-fix-sse-assert_2022-11-01-19-34.json, core/frontend/src/tile/RealityModelTileTree.ts
#4572 introduced `RealityTileLoader.maximumScreenSpaceError`, with an assertion that a `RealityModelTileTree.Reference` always refers to a `RealityTileTree`. In the case of an Orbit point cloud, that's not true and we produce an exception trying to access the property of the non-existent loader.
=> Fix faulty assertion

docs/changehistory/index.md
Adding the missing pound before `improved-link-table-selection` in the table of contents to avoid getting a 404 when clicking on it.
=> Missing pound '#' before link causing a 404

common/api/presentation-backend.api.md, common/api/summary/presentation-backend.exports.csv, common/changes/@itwin/presentation-backend/presentation-deprecate_manager_mode_2022-11-11-13-15.json, common/changes/@itwin/presentation-testing/presentation-deprecate_manager_mode_2022-11-11-13-15.json, docs/changehistory/NextVersion.md, full-stack-tests/presentation/src/backend/NativePlatform.test.ts, full-stack-tests/presentation/src/backend/RulesetsRoundtrip.test.ts, presentation/backend/src/presentation-backend/NativePlatform.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/presentation-backend/PresentationManagerDetail.ts, presentation/backend/src/test/NativePlatform.test.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/testing/src/presentation-testing/Helpers.ts, test-apps/presentation-test-app/src/backend/main.ts
Deprecate PresentationManager mode because there is no difference in performance between PresentationManager working in `ReadOnly` or `ReadWrite` mode. Previously we were used to collect additional data for updates after iModel changes in `ReadWrite` mode but this is not the case after update handling was changed.
Closes #4587
Native changes: https://github.com/iTwin/imodel-native/pull/29
=> Presentation: deprecate manager mode

full-stack-tests/core/src/frontend/standalone/BriefcaseConnection.test.ts
Test "_should cancel pulling changes after abort signal_" keeps failing on pipeline runs with inconsistent frequency (test doesn't fail locally). Most likely cause: download gets completed before cancel is fired. Increasing number of changesets and cancelling sooner should fix test flakiness.
=> Fix flaky `BriefcaseConnection` test

tools/internal/scripts/rush/audit.js
https://github.com/advisories/GHSA-3rfm-jhwj-7488
And now also https://github.com/advisories/GHSA-hhq3-ff78-jv3g
Should we really be auditing our dev dependencies?
=> Ignore another loader-utils 'vulnerability'

common/changes/@itwin/appui-react/raplemie-flacky-uishowhidemanager_2022-11-15-21-16.json, ui/appui-react/src/appui-react/utils/UiShowHideManager.ts
Resolves iTwin/itwinjs-backlog#517
The hide timer sometime reach it's limit before being cancelled, which causes the UiShowHideManager to stay in a Hidden state because the `terminate` is canceling the timeout, but did not reset the values to their defaults (like other terminate would usually do)
This wasnt a concern for real applications, but as this is a static, tests would hence depend on the last value and expect it to be the default when the test start, which was not always the case.
=> UI: Reset UiShowHideManager fields on `terminate`

docs/bis/guide/fundamentals/element-fundamentals.md
Small typo I noticed while reading the documentation.
=> Fix typo in class name in BIS guide

common/changes/@itwin/appui-react/hidden-location_2022-11-16-20-45.json, full-stack-tests/ui/tests/Utils.ts, full-stack-tests/ui/tests/widget-state.test.ts, ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
This PR fixes an issue where a hidden widget panel location is restored to a default value after a frontstage is changed.
This caused a widget to move to a left start panel section in this scenario:
1. Hide a widget **W** (widget must be docked to a panel)
2. Change the frontstage
3. Navigate to a previously active frontstage
4. Show a widget **W**
=> Fix restore of hidden widget panel location

common/config/rush/pnpm-config.json, common/scripts/install-run-rush.js, common/scripts/install-run.js, rush.json
Update rush to 5.83.1
- https://github.com/microsoft/rushstack/blob/main/apps/rush/CHANGELOG.md#5833
- [5.79.0](https://github.com/microsoft/rushstack/blob/main/apps/rush/CHANGELOG.md#5790) added support for setting pnpm config options
Update pnpm to 6.35.1
- https://github.com/pnpm/pnpm/blob/v6.35.1/packages/pnpm/CHANGELOG.md
- [6.26.0](https://pnpm.io/6.x/package_json#pnpmpeerdependencyrulesignoremissing) added support for surpressing missing peer deps
This should significantly cleanup the garbage output during `rush install` and `rush update`
=> update rush and pnpm versions

test-apps/appui-test-app/connected/src/frontend/index.tsx, test-apps/ui-test-app/src/frontend/index.tsx
Update the rpcParams in the UI test apps to make them work with the General Purpose backend again.
=> Fix rpcParams in UI test apps

common/api/presentation-backend.api.md, common/api/presentation-common.api.md, common/api/summary/presentation-common.exports.csv, common/changes/@itwin/presentation-backend/presentation-esm-compatibility_2022-11-22-12-26.json, common/changes/@itwin/presentation-common/presentation-esm-compatibility_2022-11-22-12-11.json, presentation/backend/src/presentation-backend/Constants.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/presentation-backend/PresentationManagerDetail.ts, presentation/common/src/presentation-common/Utils.ts
`__dirname` is replaced with `import.meta.url` in ESM contexts, but we must keep this module as CJS for now.
This change fixes one failure point when users try to build their iTwin.js app with Vite.
=> Improve presentation-common compatibility with ESM

common/changes/@itwin/core-react/ui-dialog-backstop_2022-11-23-16-33.json, test-apps/appui-test-app/appui-test-providers/src/ui/dialogs/SampleModelessDialog.tsx, ui/core-react/src/core-react/dialog/Dialog.scss
Using an iTwinUI component that has a popup (e.g., Select) does not work with AppUi modeless dialogs because of the way AppUi hides the dialog backstop. Changed the core-dialog-hidden class to make it compatible with the Tippy package used by iTwinUI.
=> Update Dialog.scss for iTwinUI

common/api/editor-frontend.api.md, common/api/summary/editor-frontend.exports.csv, common/changes/@itwin/core-frontend/master_2022-12-02-15-58.json, common/changes/@itwin/editor-frontend/master_2022-12-02-15-58.json, core/frontend/src/GraphicalEditingScope.ts, core/frontend/src/SelectionSet.ts, editor/frontend/src/EditTool.ts, editor/frontend/src/ModifyCurveTools.ts, editor/frontend/src/ModifyElementTool.ts, editor/frontend/src/public/locales/en/Editor.json
Incidental changes:
- Make GraphicalEditingScope.notifyGeometryChanged notify of all deleted elements in one call instead of one call per element. Otherwise Selection/HiliteSet events get produced for every deleted element present in those sets.
- Only invoke onSelectionSetChanged from HiliteSet.setHilite if the hilite set actually changed.
=> Added RegionBooleanTool to unite, subtract, or intersect planar regions.

common/config/azure-pipelines/jobs/docs-build.yaml
External repositories with pipelines trying to use the docs build template would fail due to the "checkout: self" step, which will always check out the repository which is hosting the pipeline's YAML file. This is fine in the itwinjs-core repo, but other repositories using this template must supply a repository alias in order to check out this repo (and not themselves) when using the docs build template.
This parameter allows for external pipelines to supply this alias while defaulting to "self" if no alias is specified.
=> Support external docs builds

common/changes/@itwin/appui-react/circular-ui-dep-2_2022-12-05-15-08.json, ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
This PR fixes a run-time circular dependency issue in `appui-react`.
=> Fix a circular dependency issue in appui-react

common/changes/@itwin/appui-layout-react/raplemie-newGrips_2022-12-07-16-49.json, ui/appui-layout-react/src/appui-layout-react/widget-panels/Grip.scss, ui/appui-layout-react/src/appui-layout-react/widget-panels/Grip.tsx, ui/appui-layout-react/src/appui-layout-react/widget-panels/Panel.scss, ui/appui-layout-react/src/test/widget-panels/Grip.test.snap, ui/appui-layout-react/src/test/widget-panels/Panel.test.snap, ui/appui-layout-react/src/test/widget-panels/Panels.test.snap
This is changing the look and behavior of the AppUI panel grips:
1. When the panel are open, only the blue bar will show on hover, the full panel side is interactive.
2. When the panel are collapsed, the handle will be larger and look like a pull tab, the full panel side is interactive.
3. When the handle is hovered, it will morph into the blue full width bar indicating that the full panel side is interactive.
=> UI: New side panel grips

common/changes/@itwin/appui-layout-react/maint-rmUuid_2022-12-08-17-44.json, common/changes/@itwin/certa/maint-rmUuid_2022-12-08-17-44.json, common/config/rush/pnpm-lock.yaml, tools/certa/package.json, tools/certa/src/utils/CoverageUtils.ts, ui/appui-layout-react/package.json, ui/appui-layout-react/src/appui-layout-react/base/NineZone.tsx
as mentioned in scrum today, no need for this dep.
ideally will replace usage with the standard api (available on both node and web), `crypto.randomUUID` but this would be breaking since we still support node12. see https://github.com/iTwin/itwinjs-core/issues/4777
=> maint: remove dep on uuid

common/api/core-bentley.api.md, common/api/core-frontend.api.md, common/api/summary/core-bentley.exports.csv, common/changes/@itwin/core-bentley/pmc-32-bit-reality-mesh_2022-12-12-18-38.json, common/changes/@itwin/core-frontend/pmc-32-bit-reality-mesh_2022-12-12-18-38.json, core/bentley/src/TypedArrayBuilder.ts, core/bentley/src/test/TypedArrayBuilder.test.ts, core/frontend/src/render/RealityMeshParams.ts, core/frontend/src/render/webgl/RealityMesh.ts
Fixes #4460.
Added `UintArrayBuilder` which allocates a Uint8/16/32Array based on the largest value put into the typed array.
Updated RealityMeshParamsBuilder to use it.
The meshes produced by the ellipsoid terrain provider and some of those produced by CesiumTerrainProvider contain fewer than 256 vertices. We now allocate 8-bit indices for those meshes.
TODO:
=> Support 8- and 32-bit reality mesh indices

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, test-apps/display-test-app/README.md, test-apps/display-test-app/package.json, test-apps/display-test-app/public/locales/en/SVTTools.json, test-apps/display-test-app/src/frontend/App.ts, test-apps/display-test-app/src/frontend/SectionTools.ts, test-apps/display-test-app/src/frontend/ViewClipByElementGeometryTool.ts
Fixes #3883.
Select one or more elements. The backend produces polyfaces from their geometry. We create a ClipVector from those polyfaces and apply it to the view.
TODO:
=> Example tool to clip view based on element geometry

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/pmc-viewport-resize_2022-12-14-16-49.json, core/frontend/src/ViewManager.ts, core/frontend/src/Viewport.ts, docs/changehistory/NextVersion.md
When the div containing a viewport changes size, we want to redraw the viewport's contents based on the new size. However, at the inception of iTwin.js, some popular browsers lacked support for `ResizeObserver`; the alternative was to manually check for size changes in `requestAnimationFrame`. We did not want to do this every frame out of concern for people's laptop battery life, so we defaulted to polling once per second.
The result is that after resizing a viewport there is up to a 1 second delay during which its contents appear stretched or squished until we realize we need to redraw them.
Now that `ResizeObserver` is supported everywhere, we can use it to immediately request a redraw after a resize occurs. The contents of the viewport will smoothly adjust during a resize operation. …
=> Smoother viewport resizing

common/changes/@itwin/core-frontend/fix-rmCjsImportCoreFrontend_2022-12-09-17-46.json, core/frontend/src/render/webgl/UniformHandle.ts
fix what we can from the core side, just rm the erroneous cjs import
rest will require updates to angular webpack config or consumption of esm ver of the pkgs
=> rm cjs import causing warnings for optimizated angular builds

common/changes/@itwin/components-react/ui-fix_filtering_input_placeholder_2022-12-13-15-00.json, ui/components-react/src/components-react/filtering/FilteringInput.tsx
Invalid localized string key is passed to `translate` function with causes key to be shown in component.
=> UI: Fix filtering input placeholder

common/scripts/run_rush_change.py
Modify rush change to not default to master branch when currBranch == targetBranch
Also change if stmts for readability.
Related to PR validation issue
https://github.com/iTwin/itwinjs-core/issues/4086
also a good test for PR validation pipeline
=> Modify if stmts in run_rush_change.py

common/scripts/run_rush_change.py
Change logic from
targetBranch == currentBranch
to
targetBranch == "imodel02"
when Running rush change -b
Issue was caused by a previous change that changed logic when current branch == target branch
Previous change: https://github.com/iTwin/itwinjs-core/pull/4819
=> run rush change -b if targetBranch equal imodel02

common/api/core-bentley.api.md, common/api/core-common.api.md, common/api/summary/core-bentley.exports.csv, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-backend/pmc-error-types_2022-12-21-16-48.json, common/changes/@itwin/core-bentley/pmc-error-types_2022-12-21-16-48.json, common/changes/@itwin/core-common/pmc-error-types_2022-12-21-16-48.json, core/backend/src/CloudSqlite.ts, core/bentley/src/BentleyError.ts, core/common/src/IModelError.ts
`IModelError` (`@public`) in core-common uses a bunch of `enum`s (many not `@public`) from core-bentley.
api-extractor doesn't enforce release tags across package boundaries.
Clean them up and add some documentation as part of broader effort to stabilize our APIs (many of which have languished in `@beta` or `@alpha` far too long) in preparation for 4.0.
=> Clean up error types

test-apps/display-test-app/src/backend/SetToStandalone.ts
When converting an existing file to be a Standalone iModel, enable WAL mode too. Extends #4853
=> enable WAL mode in SetToStandalone

common/api/core-backend.api.md, common/changes/@itwin/core-backend/get-origin-property2_2023-01-03-10-29.json, core/backend/src/ECSqlStatement.ts, core/backend/src/test/ecdb/ECSqlStatement.test.ts
Method allows getting the backing property name, if any. It's different from getPropertyName as it does still return the property name even if an alias is used for the column.
Native addon changes are already live and included in the latest build that we consume.
=> Added getOriginPropertyName() method to column info

common/changes/@bentley/build-tools/fix-2.19-audit_2023-01-04-18-23.json, common/changes/@bentley/config-loader/fix-2.19-audit_2023-01-04-18-23.json, common/config/rush/pnpm-lock.yaml, tools/build/scripts/rush/audit.js, tools/config-loader/package.json
[Prototype Pollution in JSON5 via Parse Method](https://github.com/advisories/GHSA-9c47-m6qq-7p4h)
@bentley/backend-application-insights-client>webpack>loader-utils>json5, @bentley/geonames-extension>svg-sprite-loader>html-webpack-plugin>loader-utils>json5, @bentley/ecschema-editing>i18next-node-fs-backend>json5
Update json5 in config loader package, suppress audit failure for other packages we don't have control of.
=> suppress rush audit failure

docs/learning/faq.md, docs/learning/index.md, docs/learning/leftNav.md
It contained one lonely, probably-not-actually-very-frequently-asked question about presentation.
@grigasp agreed.
I want to more fundamentally reorganize this corner of the docs - grab bags of assorted "helpful links" are not all that helpful to users - but that's for a separate PR.
=> Remove FAQ

test-apps/display-test-app/android/imodeljs-test-app/app/src/main/java/com/bentley/imodeljs_test_app/MainActivity.kt
Adapt to changes made in the add-on's java API.
Re-enabled the onResume/onPause handlers as they are working again.
=> Use WebView instead of MobileFrontend since it has been removed

.github/CODEOWNERS
@diegoalexdiaz likes to solicit feedback from BIS working group members before finalizing changes to BIS docs. Require approval from him and/or @ColinKerr.
=> Code owners for BIS docs.

common/changes/@itwin/appui-react/raplemie-detailedMessageNewLine_2023-01-09-21-15.json, ui/appui-react/src/appui-react/messages/MessageManager.tsx
Put back the detailed message on a new line in outputMessage toast messages.
Fixes https://github.com/iTwin/itwinjs-backlog/issues/604
=> Put detailed message on a new line in toast

common/config/azure-pipelines/jobs/docs-ci.yaml
The ci build for docs relies upon a published artifact produced by the last run of the same build on master. However, we cannot select the last run _which produces an artifact_ (without using ADO's REST api) and so the build fails anytime the docs ci was run manually. This changes the build to produce artifacts any time it is run off master or release.
=> allow docs ci build to publish artifacts on manual trigger

common/config/azure-pipelines/templates/gather-docs.yaml
This is a quick-fix to get docs builds working again: Hard coding the last successful build with published artifacts so the next run off master will succeed. Following that, we can revert this change and rethink this workflow.
=> hard code last docs build with published artifacts

docs/learning/guidelines/release-tags-guidelines.md
Standardize on `@deprecated in <Version>. <What to use instead>`.
=> update release tag guidelines for deprecated APIs.

common/api/core-backend.api.md, common/changes/@itwin/core-transformer/checkpoint-WAL_2023-01-11-12-29.json, core/backend/src/IModelDb.ts, core/backend/src/LocalHub.ts, core/backend/src/test/standalone/ServerBasedLocks.test.ts, core/transformer/src/test/standalone/IModelTransformerHub.test.ts, core/transformer/src/test/standalone/IModelTransformerResumption.test.ts, example-code/snippets/src/backend/IModelBranchingOperations.test.ts
Tests that copy an IModel while it is opened for write must call `IModelDb.performCheckpoint`.
=> Fix tests that broke due to WAL mode

common/api/core-mobile.api.md, common/changes/@itwin/core-mobile/mobile-lifecycle-forwarding_2023-01-20-16-14.json, core/mobile/src/backend/MobileHost.ts, core/mobile/src/common/MobileAppProps.ts, core/mobile/src/frontend/MobileApp.ts
TS side of fix.
Mobile lifecycle events (suspend and resume) are now properly received on the frontend.
My initial approach (attempting to use the websocket) proved unreliable for suspend. Too much is happening in the app during the suspend/resume sequence to guarantee that the message will be transmitted before the socket goes away.
This approach directly calls the JS event handlers in the frontend webivew from platform-specific code.
=> fix Mobile lifecycle events (frontend)

common/changes/@itwin/presentation-components/presentation-filter_to_execpression_conversion_2023-01-25-12-49.json, presentation/components/src/presentation-components/instance-filter-builder/InstanceFilterConverter.ts, presentation/components/src/test/instance-filter-builder/InstanceFilterConverter.test.ts, presentation/components/src/test/tree/DataProvider.test.ts
Fixed coversion to not use `IS` operator as it is not supported by ECExpressions.
Closes https://github.com/iTwin/itwinjs-core/issues/4972
=> Presentation: Fix filter to ECExpression conversion

common/changes/@itwin/map-layers/gytis-update-map-widget-state-dynamically_2023-01-25-11-52.json, extensions/map-layers/src/ui/widget/MapLayerManager.tsx, extensions/map-layers/src/ui/widget/MapLayersWidget.tsx
Map Layers widget isn't updated after an iModel is geolocated or `backgroundMap` flag is changed. 
Listen to certain events and update widget state when needed.
=> Fix Map Layers widget not updating after an iModel gets geolocated

common/changes/@itwin/appui-layout-react/raplemie-gripWebpackFix_2023-01-25-22-19.json, ui/appui-layout-react/src/appui-layout-react/widget-panels/Grip.scss
Sass variables were incorrectly used in css `calc` calls for webpack (requires use of `#{$variable}`)
fixes itwin/itwinjs-backlog#621
=> UI: Fix grip calc usage.

common/changes/@itwin/appui-layout-react/appui-layout-react-fix-tests-dev-env_2023-01-30-12-51.json, ui/appui-layout-react/src/appui-layout-react/target/useAllowedWidgetTarget.tsx, ui/appui-layout-react/src/test/target/PanelTargets.test.tsx, ui/appui-layout-react/src/test/target/SectionTargets.test.tsx, ui/appui-layout-react/src/test/target/TabTarget.test.tsx, ui/appui-layout-react/src/test/target/TitleBarTarget.test.tsx, ui/appui-layout-react/src/test/widget/MenuTab.test.tsx
This PR fixes tests that are failing when running in development environment.
Assertions are only failing when running in development environment. Since we do not run tests in development env by default a couple of tests were affected by missing context providers.
=> Fix tests of appui-layout-react when running in development environment

common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-common/undeprecate-rpc-pending_2023-01-31-16-54.json, core/common/src/rpc/core/RpcControl.ts
These classes fall into the same category as RpcInterface and RpcManager for now (there is a common usage and we don't have anything to offer as a replacement at this point).
They should not have been deprecated in my initial PR (which evolved to only deprecated classes that should become internal going forward).
=> Undeprecate RpcPendingResponse and RpcNotFoundResponse

common/changes/@itwin/appui-react/ui-fix-missing-icon_2023-02-09-08-27.json, common/changes/@itwin/components-react/ui-fix-missing-icon_2023-02-09-08-27.json, common/changes/@itwin/presentation-components/ui-fix-missing-icon_2023-02-09-08-27.json, common/config/rush/pnpm-lock.yaml, presentation/components/package.json, test-apps/appui-test-app/appui-test-providers/package.json, test-apps/appui-test-app/connected/package.json, test-apps/appui-test-app/standalone/package.json, test-apps/ui-items-providers-test/package.json, test-apps/ui-test-app/package.json, ui/appui-react/package.json, ui/components-react/package.json
`ToolAssistanceField` in `appui-react` uses `SvgPinHollow` that was only added to `@itwin/itwinui-icons-react` in version `1.15.0`: https://github.com/iTwin/iTwinUI-icons/pull/46. Update the dependency version.
=> UI: Fix missing icon

ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
fixes iTwin/itwinjs-backlog#638
When the content is written to the popout, update the title regardless of the url used.
=> Fix Popout Widget window title for about:blank

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-promotions-for-presentation_2023-02-10-12-55.json, core/frontend/src/NoRenderApp.ts, core/frontend/src/SelectionSet.ts
To address [usage of `internal` APIs](https://github.com/iTwin/presentation/pull/60#issuecomment-1425265546) in presentation packages.
=> core-frontend API promotions for presentation

common/changes/@itwin/presentation-components/presentation-fix-merged-categorized-nested-content-building-on-3.6_2023-02-14-09-03.json, presentation/components/src/presentation-components/common/ContentBuilder.ts, presentation/components/src/presentation-components/propertygrid/DataProvider.ts, presentation/components/src/test/propertygrid/DataProvider.test.snap, presentation/components/src/test/propertygrid/DataProvider.test.ts
Fixes https://github.com/iTwin/itwinjs-core/issues/5063.
Also, changes how we display child properties when parent field is merged - see below.
**Before merge:**
**After merge before this PR:**
**After merge with changes in this PR:**
=> Presentation: Fix merged categorized nested content building

common/changes/@itwin/build-tools/fix_add_source_dir_script_2023-02-14-13-42.json, tools/build/scripts/utils/addSourceDir.js
Previous implementation to find relative path from root to package source folder was very sensitive to folder layout. It was depending on that root folder name matches `name` value in root package.json file and that path up to root folder does not contain it.
Before changes `packageRoot` was resolved to:
`D:\itwinjs-core\itwin-1\itwinjs-core\core\backend\src` -> `itwin-1\itwinjs-core\core\backend\src`
After changes it is resolved correctly:
`D:\itwinjs-core\itwin-1\itwinjs-core\core\backend\src` -> `core\backend\src`
=> Fix `betools docs` to find correct relative path from root to package source

common/config/azure-pipelines/jobs/version-bump.yaml
It is possible that between the latest commit on a branch, and when the version bump commit is created, a CVE could have been introduced causing the version bump CI build to fail. This PR updates the pipeline to run `rush audit` before creating a version bump commit as a validation step to avoid this.
=> Run rush audit before bumping version

ui/appui-react/src/appui-react/messages/MessageManager.tsx
This validates that if a reactNode is present, it should be used as the `briefMessage` rather than being put directly in the output (which was throwing an error)
Also changed the additional `<br/>` that was added in #4895 for a solution closer to the previous behavior (`display: "block"` instead of a new line, as this have a bigger impact when the briefMessage is a react node.
Fixes #5081
=> UI: Fix React BriefMessage breaking toast display.

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-ellipsoid-terrain-meshes_2023-02-16-20-56.json, core/frontend/src/IModelApp.ts, core/frontend/src/render/RealityMeshParams.ts, core/frontend/src/tile/RealityTile.ts, core/frontend/src/tile/RealityTileTree.ts, core/frontend/src/tile/map/EllipsoidTerrainProvider.ts, core/frontend/src/tile/map/MapCartoRectangle.ts, core/frontend/src/tile/map/MapTile.ts, core/frontend/src/tile/map/MapTileTree.ts, core/frontend/src/tile/map/MapTilingScheme.ts, core/frontend/src/tile/map/QuadId.ts, core/frontend/src/tile/map/TerrainMeshProvider.ts, core/frontend/src/tile/map/TerrainProvider.ts
Some implementations of `TerrainMeshProvider` only have terrain data available for specific parts of the globe (e.g., within the region their terrain service supports). But (as now documented) a terrain provider is required to provide terrain meshes for the entire globe. Make it easy to fall back to producing smooth meshes for areas with no data by promoting `EllipsoidTerrainProvider` to public. Also, promote from beta to public the various APIs required to implement a terrain provider.
=> Promote terrain provider-related APIs to public

common/changes/@itwin/core-frontend/pmc-gltf-default-material_2023-02-21-15-34.json, core/frontend/src/tile/GltfReader.ts
Per [the spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes-overview).
=> Use default material if none specified in glTF

common/api/core-geometry.api.md, common/changes/@itwin/core-geometry/da4-parity-region-polyface-builder_2023-02-22-23-46.json, core/geometry/src/polyface/PolyfaceBuilder.ts, core/geometry/src/test/polyface/Polyface.test.ts
An oversight left unfinished the final step in the double dispatch implementation for `Loops` and `ParityRegions` in `PolyfaceBuilder.addGeometryQuery`. This won't work for `UnionRegions`.
Now you can facet such planar regions with e.g., `builder.addGeometryQuery(loop)`. The builder's stroke options (and reversed flag) will control the triangulation.
In support of #5108.
=> implement PolyfaceBuilder.addGeometryQuery for Loops and ParityRegions

common/config/azure-pipelines/templates/core-build.yaml
Related to https://github.com/iTwin/imodel-native-internal/pull/76.
Audit stage now skips when source branch is not master or release
=> Skip audit Stage During PR Val

common/changes/@itwin/core-backend/nick-disable-sqlite-category_2023-03-10-17-02.json, core/backend/src/CheckpointManager.ts
Applications are outputting noisy log messages when in this function 'updateToRequestedVersion', even if they don't have to applyChangesets. Some of these logs appear to occur just when opening the database for write. Affan says  applyChangesets handles a lot of these errors under the hood so they just clutter logs and confuse people who read the logs.
=> Disable native SQLite logger category when calling 'updateToRequestedVersion'

common/changes/@itwin/presentation-opentelemetry/presentation-lock-down-opentelemetry-dependencies_2023-03-14-15-08.json, common/config/rush/pnpm-lock.yaml, presentation/opentelemetry/package.json
Looks like there're issues building with the latest `1.10` version - lock down to `1.5` which we know is fine. 
Filed https://github.com/iTwin/presentation/issues/100 to look into upgrading to `1.10`.
=> Presentation: Lock down `@opentelemetry` dependency versions to `~1.5`

common/changes/@itwin/appui-layout-react/release-3.7.x_2023-03-15-20-52.json, ui/appui-layout-react/src/appui-layout-react/base/PointerCaptor.tsx, ui/appui-layout-react/src/appui-layout-react/widget/Tab.tsx, ui/appui-layout-react/src/test/widget-panels/Panel.test.snap, ui/appui-layout-react/src/test/widget-panels/Panels.test.snap, ui/appui-layout-react/src/test/widget/FloatingWidget.test.snap, ui/appui-layout-react/src/test/widget/FloatingWidgets.test.snap, ui/appui-layout-react/src/test/widget/PanelWidget.test.snap, ui/appui-layout-react/src/test/widget/Tab.test.snap, ui/appui-layout-react/src/test/widget/Tab.test.tsx, ui/appui-layout-react/src/test/widget/Tabs.test.snap
When clicking on a tab, the focus will now be moved to the tab, and keyboard navigation is now enabled on tab, press `Space` or `Enter` to open the widget.
close https://github.com/iTwin/appui/issues/195
=> UI: Allow focus on widget tabs and keyboard navigation

common/api/core-geometry.api.md, common/api/summary/core-geometry.exports.csv, common/changes/@itwin/core-geometry/da4-geometry-promotions_2023-03-20-22-17.json, core/geometry/src/curve/ChainCollectorContext.ts, core/geometry/src/curve/CurveChainWithDistanceIndex.ts, core/geometry/src/curve/CurvePrimitive.ts, core/geometry/src/curve/LineString3d.ts, core/geometry/src/curve/Loop.ts, core/geometry/src/curve/Query/CurveSplitContext.ts, core/geometry/src/curve/RegionOps.ts, core/geometry/src/curve/internalContexts/MultiChainCollector.ts, core/geometry/src/geometry3d/PolygonOps.ts, core/geometry/src/geometry4d/PlaneByOriginAndVectors4d.ts, core/geometry/src/numerics/Polynomials.ts, core/geometry/src/serialization/DeepCompare.ts, core/geometry/src/test/topology/ChainCollector.test.ts, core/geometry/src/test/topology/RegionOps.test.ts
Promote classes to published API for #4851:
* `DeepCompare` from `@internal` to `@public`
* `RegionOps` from `@beta` to `@public`
API changes:
* Narrow the value type of the map member `DeepCompare.propertyCounts` from `any` to `number`.
* In `RegionOps`, prefer `AnyCurve` to `GeometryQuery` when only handling curves.
* Substitute `AnyCurve` for `CurveCollection | CurvePrimitive` as they are the same type.
* New method names `RegionOps.cloneCurvesWithXYSplits` and `RegionOps.splitToPathsBetweenBreaks` to remove outdated references to `CurveLocationDetail` markup as "flags".
Plus documentation clarifications.
=> promote DeepCompare, RegionOps

common/changes/@itwin/frontend-tiles/pmc-clipped-tiles_2023-03-22-19-44.json, extensions/frontend-tiles/src/BatchedTile.ts, extensions/frontend-tiles/src/BatchedTileTree.ts, extensions/frontend-tiles/src/BatchedTileTreeReference.ts
Pretty much identical to the approach used by IModelTile.
We can tweak it further later, especially after tile tree restructuring is completed, but it's an improvement over the current jank.
Also increase concurrency from 6 to 20 to match the ThreeJs demo.
=> Improve batched tile selection

.github/CODEOWNERS, common/changes/@itwin/frontend-tiles/pmc-frontend-tiles-fixes_2023-03-23-14-22.json, extensions/frontend-tiles/README.md
As pointed out and fixed in #5269 on release/3.7.x.
=> Fix frontend-tiles package references

common/changes/@itwin/frontend-tiles/pmc-fix-proxy-iterator_2023-03-24-15-58.json, extensions/frontend-tiles/src/BatchedSpatialTileTreeRefs.ts
If you opened to a non-spatial view, then a spatial view, no tiles would display. If you then opened a different spatial view, the tiles would display.
=> Fix iterator for ProxySpatialTileTreeReferences

common/api/frontend-tiles.api.md, common/api/summary/frontend-tiles.exports.csv, common/changes/@itwin/frontend-tiles/pmc-config-tile-skip_2023-03-24-19-18.json, extensions/frontend-tiles/src/BatchedTile.ts, extensions/frontend-tiles/src/FrontendTiles.ts
[Restructuring of tile tree](https://dev.azure.com/bentleycs/iModelTechnologies/_git/graphics-exporter-services/pullrequest/323662?iteration=10&base=9) leads BatchedTile to load many more intermediate tiles when refining the view.
Add an option to indicate how many intermediate tiles to skip, and default it to 4.
=> Configure max tiles to skip for batched tile trees

common/changes/@itwin/core-frontend/pmc-batched-tile-model-ranges_2023-03-27-19-46.json, common/changes/@itwin/frontend-tiles/pmc-batched-tile-model-ranges_2023-03-27-19-46.json, core/frontend/src/IModelConnection.ts, extensions/frontend-tiles/src/BatchedTileTreeReference.ts
Previously fitting the view always fit the the extents of the entire tileset - i.e., all of the spatial models.
Instead, fit only to the union of the extents of those models that are currently in the model selector.
=> Batched tiles: fit to viewed models

common/api/appui-abstract.api.md, common/api/presentation-common.api.md, common/changes/@itwin/appui-abstract/presentation-api-promotions_2023-03-28-11-39.json, common/changes/@itwin/presentation-common/presentation-api-promotions_2023-03-28-11-39.json, presentation/common/src/presentation-common/EC.ts, ui/appui-abstract/src/appui-abstract/properties/Description.ts
Based on https://github.com/iTwin/itwinjs-core/issues/4851.
**Promoted in this PR:**
```
presentation / quantity ALPHA: property "PropertyInfo.kindOfQuantity"
presentation ALPHA: property "PropertyDescription.hideCompositePropertyLabel"
```
**Couldn't find usage of this anywhere:**
```
presentation INTERNAL: method "RulesetVariablesManager.getAllVariables"
```
**Promoted in https://github.com/iTwin/itwinjs-core/pull/4954:**
```
presentation ALPHA: property "NestedContentField.actualPrimaryClassIds"
presentation ALPHA: property "NestedContentField.relationshipMeaning"
```  
**Made `@public` in https://github.com/iTwin/itwinjs-core/pull/5064 and https://github.com/iTwin/itwinjs-core/pull/5054:**
```
presentation INTERNAL: method "NestedContentField.rebuildParentship"
presentation INTERNAL: …
```
=> Presentation: Promote some `@alpha` apis to `@public`

common/api/presentation-backend.api.md, common/api/presentation-common.api.md, common/api/presentation-frontend.api.md, common/api/summary/presentation-common.exports.csv, common/api/summary/presentation-frontend.exports.csv, common/changes/@itwin/presentation-backend/presentation-values_formatting_2023-03-28-11-21.json, common/changes/@itwin/presentation-common/presentation-values_formatting_2023-03-28-11-21.json, common/changes/@itwin/presentation-frontend/presentation-values_formatting_2023-03-28-11-21.json, common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, docs/changehistory/NextVersion.md, presentation/backend/package.json, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/test/PresentationManager.test.snap, presentation/backend/src/test/PresentationManager.test.ts, presentation/common/assets/locales/en/Presentation.json, presentation/common/src/presentation-common.ts, presentation/common/src/presentation-common/KoqPropertyValueFormatter.ts, presentation/common/src/presentation-common/LocalizationHelper.ts, presentation/common/src/presentation-common/PresentationManagerOptions.ts, presentation/common/src/presentation-common/content/PropertyValueFormatter.ts, presentation/common/src/presentation-common/content/Value.ts, presentation/common/src/test/KoqPropertyValueFormatter.test.ts, presentation/common/src/test/LocalizationHelper.test.ts, presentation/common/src/test/content/PropertyFormatter.test.ts, presentation/frontend/package.json, presentation/frontend/src/presentation-frontend/PresentationManager.ts, presentation/frontend/src/test/PresentationManager.test.ts
Added `ContentPropertyValuesFormatter` for getting display values for different type raw values in content. This is necessary for supporting Content formatting on the frontend.
Added ability to request Content without formatted values and format them on the frontend. 
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/values_formatting_rework
Native changes: https://github.com/iTwin/imodel-native/pull/220
Part of https://github.com/iTwin/itwinjs-core/issues/5029
=> Presentation: Values formatting on frontend

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/pmc-view-creator-all-subcategories_2023-03-29-11-55.json, core/frontend/src/DisplayStyleState.ts, core/frontend/src/SubCategoriesCache.ts, core/frontend/src/ViewCreator3d.ts, core/frontend/src/Viewport.ts, full-stack-tests/core/src/frontend/standalone/ViewCreator3d.test.ts
Fixes #5153.
As usual, the hard part is writing a test.
Incidentally, cleaned up `ViewCreator3dOptions` documentation.
=> Add a ViewCreator3d option to make all subcategories visible

common/api/core-markup.api.md, common/changes/@itwin/core-markup/markup-api-promotions_2023-03-30-16-59.json, core/markup/src/Markup.ts
Markup.undo to support undo/redo commands.
Markup.selected for writing tools or making changes to the selected markup elements.
Part of #4851
=> Make Markup.selected and Markup.undo public.

docs/config/docSites.json
To help docs link to release notes, we need to know if a repository keeps its packages in lockstep.
=> update docsites metadata with repo versioning info

docs/changehistory/NextVersion.md
Document the source location for the appui packages that have been moved out of itwinjs-core in the 4.0 release
=> Add new appui packages location to NextVersion.md #5330

common/changes/@itwin/core-common/markschlosser-fix-frustum-planes-front-too-small_2023-03-31-14-13.json, core/common/src/geometry/FrustumPlanes.ts, core/common/src/test/FrustumPlanes.test.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/670
In the case of the above bug, the front rect of a scaled-down frustum for readPixels() can become rather tiny because the source view frustum was already rather small. Deriving the front plane's normals from a small rect resulted in a near-zero plane normal, causing computeFrustumPlanes() to return an empty array of planes. This caused the rendering system to eventually assert.
To fix the problem, we now derive the front plane from the rear plane.
We also generally hardened the code in computeFrustumPlanes() by ensuring that the normals are only ever calculated from points of the frustum box that yield a 90 degree angle (this was not done previously).  We did this by reordering the point used for the cross product function. This …
=> Harden computeFrustumPlanes() in FrustumPlanes.ts

tools/internal/scripts/rush/audit.js
Revert when #5373 is complete.
=> Temporarily ignore xml2js CVE until @azure/storage-blob is updated

common/changes/@itwin/presentation-backend/presentation-report-diagnostics-with-error-responses_2023-04-11-13-00.json, full-stack-tests/presentation/src/backend/Diagnostics.test.ts, presentation/backend/src/presentation-backend/NativePlatform.ts, presentation/backend/src/presentation-backend/PresentationManagerDetail.ts, presentation/backend/src/test/NativePlatform.test.ts, presentation/backend/src/test/PresentationManager.test.ts
imodel-native PR: https://github.com/iTwin/imodel-native/pull/234
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/include-diagnostics-in-error-responses
=> Presentation: Include diagnostics in error responses

full-stack-tests/presentation/src/learning-snippets/content/customization/PropertySpecification.test.ts
Updating test
Closes https://github.com/iTwin/imodel-native/issues/206
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/ruleset-variables-not-included-in-cache-key
=> Presentation: Ruleset variables not included in content cache key

docs/changehistory/2.18.0.md, docs/changehistory/2.9.0.md, docs/changehistory/3.0.0.md, docs/learning/ui/appui-react/ChildWindows.md, docs/learning/ui/appui-react/Dialogs.md, docs/learning/ui/appui-react/ModalFrontstage.md, docs/learning/ui/appui-react/NestedFrontstage.md, docs/learning/ui/imodel-components/Viewport.md
AppUI 4.0 removes classes and interfaces that were deprecated in 3.x and earlier. Update the learning docs and release notes to removed links to the removed code.
=> Update markdown files

common/api/core-common.api.md, common/api/core-frontend.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-common/pmc-preserve-tile-leafness_2023-04-25-15-09.json, common/changes/@itwin/core-frontend/pmc-preserve-tile-leafness_2023-04-25-15-09.json, common/changes/@itwin/frontend-tiles/pmc-preserve-tile-leafness_2023-04-25-15-09.json, core/common/src/tile/TileMetadata.ts, core/frontend/src/tile/ImdlReader.ts, core/frontend/src/tile/RealityTileTree.ts, core/frontend/src/tile/TileAdmin.ts, core/frontend/src/tile/TileDrawArgs.ts, core/frontend/src/tile/TileTree.ts, extensions/frontend-tiles/src/BatchedTile.ts, extensions/frontend-tiles/src/BatchedTileTree.ts, test-apps/display-test-app/README.md, test-apps/display-test-app/src/common/DtaConfiguration.ts, test-apps/display-test-app/src/frontend/DisplayTestApp.ts
Users of the new @itwin/frontend-tiles package report that tiles sometimes disappear from the view, often failing to reload appropriately. This is particularly evident when setting a low GPU memory limit and using the look-and-move tool.
When a GPU memory limit is set, content for any tiles that are not considered "in use" are disposed of in LRU order until the total amount of GPU memory consumed (an estimate) is below the limit, or no unused tiles remain. This PR adds a config variable to display-test-app to specify the limit, to ease testing.
The reason unloaded tile contents were not reliably being reloaded: `Tile.setContent` was overriding the "is leaf" flag. Batched tiles know ahead of time whether or not they are leaves (have no children), but we were recomputing this from …
=> Address tile content disposal issues

common/changes/@itwin/core-backend/container-ispublic_2023-05-03-09-39.json, core/backend/src/CloudSqlite.ts
Necessary to implement token refresh.
imodel-native: https://github.com/iTwin/imodel-native/tree/cloudsqlite-public-containers
=> add `isPublic` member to `CloudContainer`

common/api/core-backend.api.md, common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-backend/getlatestchangeset_2023-05-04-12-27.json, common/changes/@itwin/core-common/getlatestchangeset_2023-05-04-12-27.json, core/backend/src/BriefcaseManager.ts, core/backend/src/LocalHub.ts, core/backend/src/test/changesets/ChangeMerging.test.ts, core/backend/src/test/standalone/HubMock.test.ts, core/common/src/ChangesetProps.ts
These public methods wrap the internal `BackendHubAccess` interface methods.
=> Add public methods to BriefcaseManager to query changesets

common/changes/@itwin/core-mobile/mobile-rpc-server-pending_2023-05-03-22-13.json, core/mobile/src/backend/MobileRpcServer.ts
This fixes a problem encountered when cancelling authentication in the Mobile SDK Android app. The native callback would happen before the RPC server had reconnected and the message would be lost.
Note: this was tested in the release/3.7.x branch as we're not able to run mobile on master yet.
=> Mobile RPC queue up pending messages until reconnected in foreground

common/changes/@itwin/core-common/jake-common-remove-semver-depend_2023-05-04-19-51.json, common/config/rush/pnpm-lock.yaml, core/common/package.json, core/common/src/RpcInterface.ts, core/common/src/test/VersionCompatible.test.ts
Removing semver dependency by implementing own way to compare versions. This is to help resolve an issue introduced when upgrading to semver@7.5.0 that caused failures when installing dependencies for the viewers. Removing our dependency on this should solve that issue.
=> [@itwin/core-common] Removing dependency on semver

common/changes/@itwin/core-frontend/fix-tiles-on-vite_2023-05-10-16-58.json, core/frontend/src/tile/TileAdmin.ts
There are long outstanding issues with [Vite](https://vitejs.dev/), [see](https://github.com/vitejs/vite/issues/5499), where dynamic imports behave differently between development and production builds.
See our users reporting issues: https://github.com/iTwin/itwinjs-core/discussions/5185
=> Fix for dynamic imports in Vite apps so tiles render

docs/learning/SupportedPlatforms.md
Update minimum support to debian 11
- based on this min glibc ver will be 2.31, [see](https://en.wikipedia.org/wiki/Glibc)
- glibcxx ver obtained from https://github.com/nodejs/node/blob/4eec3626f2c2898ec00734e4b0ab70de8c24704c/BUILDING.md?plain=1#L180
=> [docs] update min glibc ver

common/changes/@itwin/core-frontend/accusnap-still-required_2023-05-15-12-56.json, core/frontend/src/AccuSnap.ts
For example, a primitive tool with AccuSnap enabled gets suspended by a viewing tool started from a drag event. Need to ignore snaps that are resolved after the view tool is started.
=> Check that current tool still wants snap after promise is resolved.

common/changes/@itwin/presentation-backend/presentation-accept-buffer-responses-from-addon_2023-05-17-09-01.json, presentation/backend/src/presentation-backend/NativePlatform.ts, presentation/backend/src/test/NativePlatform.test.ts
imodel-native PR: https://github.com/iTwin/imodel-native/pull/283
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/avoid-native-string-copy-to-napi-string
=> Presentation: Accept `Buffer` responses from addon

common/api/core-common.api.md, common/changes/@itwin/core-common/master_2023-05-24-10-32.json, core/common/src/ChangedElements.ts
After upgrading to TypeScript 5.0, users who have code like
```TypeScript
const changeType: TypeOfChange = 0; // Element contains no changes because it was deleted
```
will receive a type error: `Type '0' is not assignable to type 'TypeOfChange'.` because [all enums are now union enums](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#all-enums-are-union-enums).
With the change this PR makes, the code above no longer produces an error. [TypeScript playground](https://www.typescriptlang.org/play?#code/KYOwrgtgBAKgngB2AeQGYGEAWBDEBzYKAbwCgooB6CqAOQHstcCBnKAXigAYAaMqABQBOdJIIAucdlwBGARl7kA4sDoRgYwZI6c5PPvwA22AMbA1IMVJ2zOe8gEkQAEwCWg4McvbdthVAASLk5OoFY+vvrY7hZhNrYRAL4kJMAAHgh04lDGdCDMlsY4+MCy8EgAXLCIKBhFBFYA3CnpmQW5+dl1wABMZcCVfWiMxVKDtUzAAHRCIsDikgA+VUhDXZPKquqaDUA).
=> Add `NoChange` member to `TypeOfChange` flag enum for better support for TypeScript 5.x

common/changes/@itwin/core-frontend/pmc-mime-type-jpg_2023-05-31-11-49.json, core/frontend/src/common/ImageUtil.ts
The standard is `image/jpeg` but it's an easy mistake to make and real data sets make it.
=> Handle non-standard mimeType 'image/jpg'

common/changes/@itwin/map-layers-formats/geo-fix_maplayersformats_test_leak_2023-05-31-19-36.json, core/frontend/src/tile/map/ImageryProviders/ArcGISImageryProvider.ts, extensions/map-layers-formats/src/test/ArcGisFeature/ArcGisFeatureProvider.test.ts
@Jake-Screen was finally able to reproduce locally and we got:
So I made sure the tests never reach 'fetch'
=> Fix leaks in map-layers-formats tests

common/changes/@itwin/core-frontend/geo-fixImageryTileTreeSupplier_2023-06-03-01-29.json, core/frontend/src/test/tile/map/ImageryTileTree.test.ts, core/frontend/src/tile/map/ImageryTileTree.ts
Two map layers instance having two different set of sub-layers, such as:
```
{ formatId: "ArcGIS", url: "https://server.com", name: "Layer1", subLayers: [{name: "sub_layer1", visible: true}]};
{ formatId: "ArcGIS", url: "https://server.com", name: "Layer1", subLayers: [{name: "sub_layer2", visible: true}]};
```
should not share the same tile tree since it define different datasets.
Also I think the same apply for two map-layers having two differents formatId, but same URL, although unlikely:
```
{ formatId: "ArcGIS", url: "https://server.com", name: "Layer1",};
{ formatId: "WMS", url: "https://server.com", name: "Layer2"};
```
=> Two map-layers instances having different formatId or subLayers set should not share the same tile tree.

common/scripts/create_release.py
Solution for https://github.com/iTwin/itwinjs-core/issues/5554. Since Release notes are now stored on GitHub releases, the previous pre-processing that used to occur does not anymore. This has resulted in broken links due to relative links being used. This PR fixes the TOC and image links. Will be working on a lint rule that flags relative links in nextVersion.md soon.
Tested it out on a fork here: https://github.com/yashincontrol/itwinjs-core/releases/tag/release%2F4.0.0
=> Fix TOC and Image links in release notes

common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml, full-stack-tests/backend/package.json
Resolves previously-ignored CVE in xml2js.
Does not resolve [new dottie CVE](https://github.com/advisories/GHSA-4gxf-g5gf-22h4). sequelize is patched, azurite is not.
@aruniverse
=> Azurite 3.24.0

.github/workflows/extract-api.yaml, common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-view-creator-fit_2023-06-12-19-31.json, core/frontend/src/SpatialViewState.ts, core/frontend/src/ViewCreator3d.ts, core/frontend/src/test/SpatialViewState.test.ts
Fixes #5619.
The `ViewCreator3d` knows the union of the extents of all of the models, but it calls `SpatialViewState.computeFitRange` which tries to (re-)compute it from the ranges of the models' tile trees, which are not yet loaded; therefore it would fall back to using the project extents.
Added an optional `baseExtents` to that method to permit it to provide its precomputed minimal extents.
=> ViewCreator3d fits to the viewed models' extents

common/changes/@itwin/core-frontend/pmc-batched-tile-render-timeline_2023-06-13-17-13.json, core/frontend/src/DisplayStyleState.ts
If timeline is being applied on the frontend (i.e., `TileAdmin.enableFrontendScheduleScripts` is `true`), the element Ids need to be included.
This was the case for scripts stored in the display style's JSON properties, but not for those stored on RenderTimeline elements - they were always unconditionally omitted.
=> Ensure Ids are included in render timeline if needed

common/changes/@itwin/presentation-backend/presentation-fix-source-element-id-invalid-category_2023-06-14-13-38.json, full-stack-tests/presentation/src/backend/DefaultSupplementalRules.test.ts, presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
This is a quick fix to get past the regression [test failures](https://github.com/iTwin/presentation/actions/runs/5265017713/jobs/9517083564?pr=160#step:8:180) in [presentation](https://github.com/iTwin/presentation) repo:
```
ERR!   1) PropertyDataProvider
ERR!        with flat property categories
ERR!          finds nested property record keys:
ERR!      AssertionError: expected undefined not to be undefined
ERR!       at /home/runner/work/presentation/presentation/packages/full-stack-tests/src/components/properties/PropertyPaneDataProvider.test.ts:246:37
ERR! 
ERR!   2) PropertyDataProvider
ERR!        with nested property categories
ERR!          finds nested property record keys:
ERR!      TypeError: Cannot read properties of undefined (reading 'find')
ERR!       at …
```
=> Presentation: Fix 'Source Element ID' property being assigned a wrong category

common/config/azure-pipelines/jobs/docs-build.yaml, common/config/azure-pipelines/templates/copy-docs-artifact.yaml, common/config/azure-pipelines/templates/gather-docs.yaml
- use hasDocs tag when gathering from presentation
- name docsBuild job so imodel-transformer builds can tag appropriately. After changes are made in transformer repo, will double back and add hasDocs for transformer once again.
=> add hasDocs tag; name docsBuild job

full-stack-tests/presentation/package.json
The first run causes `core-frontend` to copy some `.js` files to `/lib/public/scripts`. Then on the second run mocha attempted to load them and failed...
=> Presentation: Fix mocha attempting to load irrelevant .js files

common/api/core-geometry.api.md, common/api/summary/core-geometry.exports.csv, common/changes/@itwin/core-geometry/da4-export-multichaincollector-expedient_2023-06-15-17-20.json, core/geometry/src/core-geometry.ts, core/geometry/src/curve/internalContexts/MultiChainCollector.ts
So as to not hold up iTwin Studio project.
When new API exposing this class's functionality is created for #5505, this temporary export will be reverted.
=> temporarily export internal class MultiChainCollector

common/changes/@itwin/presentation-backend/presentation-fix-diagnostic-errors_2023-06-19-11-09.json, docs/presentation/content/ContentModifier.md, presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
Closes: https://github.com/iTwin/imodel-native/issues/318
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/fix-diagnostic-errors
=> Presentation: Diagnostic errors logged when using ContentModifier without a class attribute

common/changes/@itwin/core-frontend/pmc-fix-gltf-assert_2023-06-29-00-02.json, core/frontend/src/tile/GltfReader.ts
Introduced in #4679. Reported by @Ellord207.
`DisplayParams` will assert if the material has a texture mapping and a separate texture mapping is also displayed.
With assertions disabled, the glTF would display just fine regardless. Now it doesn't assert.
=> Fix assertion for glTF containing a normal map.

common/api/core-common.api.md, common/changes/@itwin/core-backend/concurrent-query-retry_2023-07-11-07-14.json, common/changes/@itwin/core-common/concurrent-query-retry_2023-07-11-07-14.json, core/backend/src/test/ecdb/ECSqlQuery.test.ts, core/common/src/ECSqlReader.ts
If a timeout occurs during the execution of a concurrent query, the data returned in the response remains undefined.
The current code wasn't validating this and was trying to read the length of the data array returned, which ended up causing a typerror "Cannot read properties of undefined".
I've added a check to continue with the retries if the timeout scenario occurs.
=> Retry concurrent query if timeout occurs

common/changes/@itwin/build-tools/nick-build-tools-change_2023-07-11-19-43.json, common/changes/@itwin/build-tools/nick-build-tools-change_2023-07-11-19-45.json, common/changes/@itwin/core-frontend/nick-build-tools-change_2023-07-11-19-43.json, core/frontend/src/tile/map/ImageryProviders/ArcGISImageryProvider.ts, tools/build/src/mocha-reporter/index.ts
Also removes unnecessary double clone from map-layers-format extension.
=> With DEBUG_LEAKS on: Print the initialize callstack of active async resources which may be preventing node from shutting down 

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/master_2023-07-14-17-42.json, core/frontend/src/tile/GltfReader.ts, core/frontend/src/tile/RealityTileLoader.ts, core/frontend/src/tile/TileContent.ts
#5737 overlooked the need to set `RealityTileLoader.containsPointClouds`, so that we will select the correct classification shaders.
Incidentally, move special case for b3dm reality tiles that don't conform to 3D tiles spec for default wrap mode to only apply to b3dm tilesets.
=> Fix classification for glTF point clouds.

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/deco-propagate-mouse-motion_2023-07-18-14-42.json, core/frontend/src/render/CanvasDecoration.ts, core/frontend/src/tools/ToolAdmin.ts
Part of iTwin/itwinjs-backlog#782. See that issue's description for details.
=> Allow pickable CanvasDecoration to forward motion event to active tool.

full-stack-tests/presentation/src/frontend/Hierarchies.test.snap
imodel-native PR: https://github.com/iTwin/imodel-native/pull/365
imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/hierarchy-filtering-perf-on-master
=> Presentation: Update snapshot - filtered hierarchies don't support filtering on top

common/changes/@itwin/core-frontend/nam-dta-electron-fix_2023-07-26-19-35.json, common/config/rush/pnpm-lock.yaml, core/frontend/src/IModelApp.ts, test-apps/display-test-app/package.json, test-apps/display-test-app/vite.config.ts
When `npm run start:electron` is run by itself in `test-apps/display-test-app`, the frontend would raise errors in the console, stating `require is not defined`. This comes from Vite, by default, not properly transforming `require` statements used in CommonJS into `import` used by ES6.
`vite.config.js` was edited to explicitly transform files that use `require`, such as that found in `core-frontend`.
In addition, `process.env` is used in many places in DTA, but wasn't being picked up within vite's build process, raising a `process is not defined` at DTA's runtime. To address that, we inject `process.env`.
Steps to reproduce and test:
Run `rushx build`, then run `npm run start:electron`. If you get a localhost:3000 - CONNECTION REFUSED error, it means `NODE_ENV` was set to `development`. …
=> Fix Display Test App's production electron build

common/changes/@itwin/core-common/bp-3.7.x-1b51f57c785c76dbb77068af253dc9295659af4f_2023-07-27-18-38.json, common/changes/@itwin/core-frontend/bp-3.7.x-1b51f57c785c76dbb77068af253dc9295659af4f_2023-07-27-18-38.json, core/common/src/tile/GltfTileIO.ts, core/frontend/src/tile/GltfReader.ts
Backport https://github.com/iTwin/itwinjs-core/pull/5737/commits/1b51f57c785c76dbb77068af253dc9295659af4f for reality data viewer.
=> Handle trailing bytes after binary glTF chunk

common/changes/@itwin/core-backend/mattbjordan-update-blobs-in-tests_2023-08-02-15-04.json, core/backend/src/test/ecdb/ECSqlStatement.test.ts, full-stack-tests/core/src/frontend/standalone/ECSqlQuery.test.ts
(Try 2 to fix rush change annoyances from original PR: https://github.com/iTwin/itwinjs-core/pull/5810)
Fixes: https://github.com/iTwin/itwinjs-backlog/issues/702
Native-side PR: https://github.com/iTwin/imodel-native/pull/386
imodel-native: https://github.com/iTwin/imodel-native/tree/mattbjordan/blob-return-format
=> Update abbreviated blobs in tests to new format

common/api/core-backend.api.md, core/backend/src/IModelDb.ts, core/backend/src/test/imodel/IModel.test.ts
Replaces this one https://github.com/iTwin/itwinjs-core/pull/5840 that originally also merged master. Description copied verbatim:
native PR: https://github.com/iTwin/imodel-native/pull/404
Description copied verbatim:
In https://github.com/iTwin/imodel-native/pull/180 we started unicode-aware (previously ascii) trimming of code values. Before that, several production iModels stored code values containing non-ascii whitespace. A couple transformer library users that are trying to move up to 4.x have reported failures when transforming these iModels since the codes are not preserved during db loads/stores.
Since the transformer wants to preserve the code values as they are stored in the Db, this PR introduces a per-dgndb `DgnCodeValue::Behavior m_codeValueBehavior`, and makes …
=> Code trim behaviors

.vscode/launch.json, full-stack-tests/core/package.json
I took the opportunity to do some light cleanup of the launch.json, including:
- Dropped the [deprecated](https://github.com/microsoft/vscode-js-debug/commit/f314b55c8035fa535c42411c522714124df2dce5) `pwa-` prefix from config types.
- Removed references to deleted directories in `outFiles`
- Replace broken "UI Core Tests" launch config with "AppUI Abstract Tests"
FWIW, I believe that VSCode's sourcemap resolution has improved to the point where we don't need to specify `outFiles` explicitly anymore.  As much as I'd like to go thru and remove all those, we should probably do some more extensive testing first...
=> Fix full-stack-tests/core debugging config and clean up launch.json

common/changes/@itwin/core-backend/aks-native-platform-for-schema-utility_2023-08-18-06-38.json, core/backend/src/SchemaUtils.ts, core/backend/src/test/SchemaUtils.test.ts
This fixes a bug in SchemaUtils that was causing a call to a native SchemaUtility API to fail with an error message `Cannot read properties of undefined (reading 'SchemaUtility')`
=> Fixes a bug while calling native `SchemaUtility` APIs

docs/presentation/content/index.md
Remove the broken link as the sample is now gone and I couldn't find anything similar to what it used to contain.
=> Presentation: Remove a link to a missing sample

common/changes/@itwin/core-backend/nick-numPrefetchesOnDatabase_2023-08-23-14-03.json, core/backend/src/CheckpointManager.ts, core/backend/src/CloudSqlite.ts, full-stack-tests/backend/src/integration/Checkpoints.test.ts
imodel-native: https://github.com/iTwin/imodel-native/tree/nick/prefetch-client-counts
=> Don't prefetch v2 checkpoints twice, check first if one is already ongoing.

docs/learning/ui/components/Toolbar.md
Simple quick change to address itwin/appui#474
(Full learning docs still need to be reviewed as per itwin/appui#248)
=> Fix AppUI Learning toolbar documentation

.github/workflows/automation-scripts/update-changelogs.mjs, .github/workflows/finalize-release.yaml
Fixes error with push command by including `origin` in cmd.
Fixes the removal of extra newline characters to be more readable.
Upgrades to action/checkoutV3
Add authtoken to checkout step. From testing in a dummy repo, this token also appears to be what authorizes the push later in the pipeline. Also tested pushing to a protected branch with an authorized user and it worked correctly.
Changes trigger from tag to on commits to branches with release/* and updates to files with the path **/CHANGELOG.md, this is because when the workflow is triggered by a tag, the default branch that gets checkout is in a detached head state, and checking out to a new branch doesn't correct this. I believe using git switch might work, however this is easier because I use the branch name to detect what the …
=> fix finalize release 4.1.x

common/api/core-backend.api.md, common/api/core-frontend.api.md, common/changes/@itwin/core-backend/pmc-default-view-doc_2023-09-07-01-02.json, common/changes/@itwin/core-frontend/pmc-default-view-doc_2023-09-07-00-18.json, core/backend/src/IModelDb.ts, core/frontend/src/IModelConnection.ts, core/frontend/src/ViewCreator3d.ts, test-apps/display-test-app/src/frontend/ViewPicker.ts
This property was intended to provide a reasonable default view for an iModel, but in practice each viewing application will have its own definition of "reasonable" and most existing iModels' default views are far from reasonable choices for most applications. Besides, we expect future connectors to avoid embedding views in iModels at all.
=> Deprecate default view Id

test-apps/display-test-app/vite.config.ts
Fixes a couple of issues in the vite config file for the display-test-app that were causing the debugger to not display correctly. First, the `build.sourcemap` value has been updated so that changed files can be seen in the debugger source. Second, the `optimizeDeps.force` value has been set, so that changes to those files are properly displayed in the debugger. Note that setting the force value is not a perfect solution, as this change causes the vite cache to be rebuilt entirely on each rebuild, which has a negative effect on performance. However, there is a known issue with vite where `optimizeDeps.include` does not work as intended on monorepos, [here](https://github.com/vitejs/vite/issues/14099). As a result, this is our best solution for known. Once the issue in vite is resolved, we …
=> Fixes issues with debuggers on display-test-app

common/api/core-backend.api.md, common/changes/@itwin/core-backend/pmc-stabilize-watch-for-changes_2023-09-08-18-32.json, common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/IModelDb.ts, core/backend/src/TxnManager.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/845 (the geometry synchronization problem, not the project extents synchronization problem).
Previously, a reader process would watch sqlite's WAL file to detect when a writer process modified the briefcase.
This is unreliable - we may be notified of the change to the file before the changes can be read.
Instead:
- When opening a read-only briefcase /path/to/my.bim with `watchForChanges=true`, create /path/to/my.bim-watch if it does not exist, and watch it for changes. I call this the briefcase's "watch file".
- After committing to a briefcase, modify the timestamp on my.bim-watch if it exists, to signal that the changes are ready to be read by a reader process.
I could delete the watch file when closing the read-only briefcase, but …
=> Stabilize watchForChanges

common/api/core-backend.api.md, common/changes/@itwin/core-backend/rohitptnkr-use-instance-queries-getAspects_2023-09-11-12-17.json, core/backend/src/IModelDb.ts, core/backend/src/test/element/ElementAspect.test.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/813.
There was a performance issue when calling getAspects() on an abstract class.
The function has been modified to use instance queries in order to get all aspects in a single go.
imodel-native: https://github.com/iTwin/imodel-native/tree/affank/custom-instance-json
=> Use instance query to get aspects for abstract classes

common/changes/@itwin/certa/gytis-Electron-26-support_2023-09-11-10-31.json, common/changes/@itwin/core-electron/gytis-Electron-26-support_2023-09-11-10-31.json, common/config/rush/pnpm-lock.yaml, core/electron/package.json, docs/changehistory/NextVersion.md, example-code/app/package.json, full-stack-tests/core/package.json, full-stack-tests/rpc/package.json, test-apps/display-performance-test-app/package.json, test-apps/display-test-app/package.json, tools/certa/package.json
- Extend supported Electron version range with Electron 26.
- Increase Electron dev dependency version to `^26.0.0`.
No code changes required since core doesn't use [APIs changed in 26](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-260).
=> Add support for Electron 26

common/config/azure-pipelines/templates/gather-docs.yaml
For some reason, master is still gathering docs from AppUI's release/4.0.x branch. Switch this to the 'hasDocs' tag.
=> use latest appui docs with hasDocs tag

common/changes/@itwin/backend-webpack-tools/BenPusey-FixDTABuildBackendWebpack_2023-09-12-20-41.json, common/config/rush/pnpm-lock.yaml, tools/backend-webpack/package.json
Found this issue working with `display-test-app`, where the `npm run build:backend-webpack` command would fail with a module not found exception. This prevented devs from building the backend needed to run the `npm run start:electron-webpack` command. Probably caused issues for other backend webpack build commands as well.
=> Fixes Webpack Backend Build Dependencies

common/api/core-backend.api.md, common/changes/@itwin/core-backend/pmc-more-fun-with-file-watching_2023-09-13-18-20.json, core/backend/src/IModelDb.ts, core/backend/src/TxnManager.ts, full-stack-tests/core/src/backend/backend.ts, full-stack-tests/core/src/common/FullStackTestIpc.ts, full-stack-tests/core/src/frontend/standalone/BriefcaseTxns.test.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/845 (again).
- Before closing the db, you must close all open statements, or you will get BUSY error.
- After reopening the db, you must restore the native object's pointer to the JS IModelDb. It is reset to null when closing the db. If you don't restore it, native TxnManager won't be able to invoke functions on JS TxnManager, preventing events from being received in JS.
=> Fix BriefcaseDb.closeAndReopen

common/changes/@itwin/core-backend/rohitptnkr-update-tests-instance-query-getAspects_2023-09-13-08-49.json, core/backend/src/IModelDb.ts, core/backend/src/test/ecdb/ECSqlAst.test.ts, core/backend/src/test/element/ElementAspect.test.ts, full-stack-tests/core/src/frontend/standalone/ECSqlAst.test.ts
Updated getAspects() to cache all derived classes of an abstract class irrespective of whether they are instantiated at runtime.
getAspects now logs an error message when no aspects exists for the element Id and aspect class name supplied.
Updated tests to check the data and format of the aspects returned by getAspects() which is now using instance queries.
As instance access is no longer experimental, updated getAspects() and relevant tests to remove ENABLE_EXPERIMENTAL_FEATURES option for instance queries.
imodel-native: https://github.com/iTwin/imodel-native/tree/rohitptnkr/remove-instance-access-from-experimental-features
=> Updated getAspects to use instance queries

common/changes/@itwin/core-backend/ImVeryLost-handle-db-busy_2023-09-18-10-25.json, core/backend/src/IModelDb.ts
Follow up to #5980 
Previously, if db was locked, we ended up in corrupted state were `nativeDb` was closed, and any attempt to access it would kill the backend.
As such:
1. Move `closeAndReopen` into the try/finally block, to ensure briefcase is always reopened in read-only mode.
2. Move out the `const fileName = this.pathName;` line, as not to access `nativeDb` when its closed ( `pathName` is a wrapper around`this.nativeDb.getFilePath()`, which crashes the backend if `nativeDb` is closed.
=> Update executeWritable to handle db busy errors

common/changes/@itwin/certa/bump-electron-26.2.1_2023-09-18-20-40.json, common/changes/@itwin/core-electron/bump-electron-26.2.1_2023-09-18-20-40.json, common/config/rush/pnpm-lock.yaml, core/electron/package.json, example-code/app/package.json, full-stack-tests/core/package.json, full-stack-tests/rpc/package.json, test-apps/display-performance-test-app/package.json, test-apps/display-test-app/package.json, tools/certa/package.json
Mitigate https://github.com/advisories/GHSA-j7hp-h8jx-5ppr by bumping electron to first patched version (26.2.1)
=> CVE-2023-4863 - bump electron to 26.2.1

common/changes/@itwin/build-tools/FlakyTestFix_2023-09-18-20-14.json, tools/build/src/mocha-reporter/index.ts
- Increasing the timeout duration when detecting hangs in mocha-reporter index.ts to fix the handle leaks errors. 
- Most of the time, the browser only takes anywhere from 0.2s to a few seconds to close. However, sometimes, it can take the browser up to around 12s (based on some of the testing I've ran so far) to close successfully. Thus, having the timeout being only 5 seconds interrupts this process and forcefully kill the process, so the browser couldn't be cleaned up properly. Bumping this timeout duration to 30s would make sure that the browser have enough time to be closed gracefully by Playwright.
(Logs generated with DEBUG=pw:browser*)
With 5s of timeout: (gracefully close started but didn't end)
With 30s of timeout:
Related issues/discussion from playwright: …
=> Increase timeout duration in mocha-reporter to fix flaky tests

common/api/ecschema-locaters.api.md, common/api/summary/ecschema-locaters.exports.csv, common/changes/@itwin/ecschema-locaters/export-file-utility_2023-09-07-18-34.json, core/ecschema-locaters/src/ecschema-locaters.ts
The SchemaFileUtility class allows writing in memory schemas to an xml file. It was requested to expose this class so that users can leverage this function.
=> export SchemaFileUtility

common/api/frontend-tiles.api.md, common/api/summary/frontend-tiles.exports.csv, common/changes/@itwin/frontend-tiles/pmc-opt-in-batched-tile-edges_2023-09-22-11-23.json, extensions/frontend-tiles/src/BatchedTile.ts, extensions/frontend-tiles/src/BatchedTileTree.ts, extensions/frontend-tiles/src/FrontendTiles.ts, test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts, test-apps/display-test-app/src/frontend/DisplayTestApp.ts
Amend #6022 to make the new behavior opt-in.
The currently deployed mesh export service does not produce edges. Users know this, but it's better to prevent any confusion by continuing to disallow turning on visible edges or wireframe when rendering those tiles, until the exporter is updated to support it.
display-test-app and display-performance-test-app opt in to the new behavior.
=> Opt-in for batched tile edges

common/changes/@itwin/core-frontend/arun-rm-frontend-require_2023-09-25-15-16.json, core/frontend/src/IModelApp.ts, test-apps/display-performance-test-app/vite.config.ts, test-apps/display-test-app/vite.config.ts
Remove `require` call in core-frontend preventing pure esm usage of the pkg
Like we do with the cjs require, in esm we import a file (package.json) at runtime which doesnt exist at compile time, so we suppress the ts compiler error.
If we import the file where it actually is, it will copy the json file into the lib folder, and the paths of our output will be different (lib/esm/src instead of just lib/esm)
ToDo later:
investigate what other libraries are doing to expose the version
possibilities:
=> rm require in core-frontend

common/changes/@itwin/core-backend/master_2023-09-27-20-33.json, core/backend/src/test/KnownTestLocations.ts, tools/internal/ios/core-test-runner/core-test-runner/ViewController.swift
Otherwise the tests file due to a write attempt in a read-only directory tree
=> Backend unit tests: copy mobile assets to tmp

common/changes/@itwin/core-backend/travis-unit-tests-mobile-dirs_2023-09-28-16-50.json, core/backend/src/test/IModelHost.test.ts, core/backend/src/test/PropertyDb.test.ts, core/backend/src/test/TestUtils.ts, core/backend/src/test/standalone/TileCache.test.ts, core/backend/src/test/standalone/ViewDefinition.test.ts, core/backend/src/test/standalone/ViewStoreDb.test.ts
Tests were failing because they were trying to write files to paths relative to `__dirname`, which does not work on mobile.
=> Fix unit test output dirs to be writable on mobile

common/changes/@itwin/core-frontend/fix-webpack-core-ver-import_2023-10-02-17-32.json, core/frontend/src/IModelApp.ts, core/frontend/tsconfig.json
Fixes the above webpack issue by enabling  [allowSyntheticDefaultImports](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports) and switching from named to default import
thx @simnorm for reporting the issue
=> fix webpack import of named core version

full-stack-tests/core/src/frontend/standalone/RealityDataAccess.test.ts, test-apps/display-performance-test-app/src/frontend/TestRunner.ts, test-apps/display-test-app/src/frontend/App.ts, test-apps/display-test-app/src/frontend/ClassificationsPanel.ts
Fixes #6079.
If `process.env.WHATEVER` is not defined, it stringifies to `undefined`, not empty string.
Introduced in #6073.
=> Fix url prefix in reality data client base URL

docs/learning/tutorials/development-prerequisites.md
Debugger for Chrome is deprecated. The extension page has this message: This extension has been deprecated as Visual Studio Code now has a bundled JavaScript Debugger that covers the same functionality.
=> Update recommended tools list

common/changes/@itwin/certa/gytis-Electron-27-support_2023-10-13-10-54.json, common/changes/@itwin/core-electron/gytis-Electron-27-support_2023-10-13-10-54.json, common/config/rush/pnpm-lock.yaml, core/electron/package.json, core/electron/src/common/ElectronPush.ts, core/electron/src/common/ElectronRpcManager.ts, core/electron/src/common/ElectronRpcProtocol.ts, core/electron/src/common/ElectronRpcRequest.ts, core/electron/src/test/backend/ElectronHost.test.ts, core/electron/src/test/frontend/ElectronApp.test.ts, docs/changehistory/NextVersion.md, example-code/app/package.json, full-stack-tests/core/package.json, full-stack-tests/rpc/package.json, test-apps/display-performance-test-app/package.json, test-apps/display-test-app/package.json, tools/certa/package.json
- Extend supported Electron version range with Electron 27.
- Increase Electron dev dependency version to `^27.0.0`.
No code changes required since core doesn't use [APIs changed in 27](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-270).
=> Add support for Electron 27

docs/learning/ui/appui-react/Frontstages.md, docs/learning/ui/appui-react/Widgets.md
This PR backports #5040
Removed a workaround to avoid code deprecation with multiple code snippets, related PR https://github.com/iTwin/appui/pull/529
Replaced inline code snippet with an extracted one for `setWidgetState` example.
=> Update Frontstage docs (bp #5040)

common/changes/@itwin/core-backend/travis-ios-unit-tests-assets-fix_2023-10-13-22-47.json, core/backend/package.json, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, tools/internal/ios/core-test-runner/core-test-runner/Info.plist, tools/internal/ios/core-test-runner/core-test-runner/ViewController.swift
Fix assets copy for iOS backend unit tests
iOS test runner:
* Store results xmls in Documents
* Enable file sharing to extract results xmls
* Delete all but the most recent 10 results xmls
=> Fixes for iOS backend unit tests

common/changes/@itwin/core-backend/remove_reserved_keywords_from_tests_2023-10-16-07-34.json, core/backend/src/test/ecdb/ECSqlStatement.test.ts, example-code/snippets/src/backend/ECSQL-queries.test.ts
Some of the tests use reserved SQLite keywords, so those tests will fail when [ECSql starts using some of the reserved keywords that were not used before.](https://github.com/iTwin/imodel-native/pull/515)
=> Remove reserved SQLite keywords from tests

.github/workflows/automation-scripts/update-changelogs.mjs
fix the commit msg syntax error that occurs when a patch come from our previous Major version. This will need to get a bp to release/4.2.x
=> check for commit substring

common/config/azure-pipelines/jobs/fast-ci.yaml
We never switched back our node version to be 18.x. Assuming we want to revert back to this.
=> set nodeVersion back to 18.x

common/changes/@itwin/core-frontend/pmc-batched-tiles-reality-models_2023-10-19-16-58.json, common/changes/@itwin/frontend-tiles/pmc-batched-tiles-reality-models_2023-10-19-16-58.json, core/frontend/src/ModelState.ts, extensions/frontend-tiles/src/BatchedModels.ts, extensions/frontend-tiles/src/BatchedSpatialTileTreeRefs.ts
Previously we assumed the geometry for all spatial models was included in the single batched tileset, but persistent reality models obtain their tiles from elsewhere, as specified in their JSON properties.
Tested locally with the big point cloud that wasn't showing up in ImageTests - it displays now.
Incidentally, compute the viewed extents only when they change, not every time `unionFitRange` is called.
Incidentally, fix a bug where `SpatialModelState.isRealityModel` was returning false incorrectly. It only checked for a `tilesetUrl` property, but the reality data can alternatively be specified by an `orbitGtBlob` or `rdSourceKey` property.
TODO:
=> Make persistent reality models display with batched tiles

tools/internal/ios/core-test-runner/core-test-runner-xcuitest/CoreTestRunnerXCUITest.swift, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Without this change, the backend unit tests were run in portrait and landscape in both light and dark mode, so they ran 4 times for no reason.
I don't know why the test runner project doesn't have the correct add-on version; I suspect that it is missing from the version update release instructions.
=> Only run iOS unit test once & update add-on

core/backend/src/test/assets/TestSchema.ecschema.json, core/backend/src/test/schema/ClassRegistry.test.ts
CoreCustomAttributes v01.00.04, an EC3.2 schema, is about to be released. To ensure that PR build pipelines can work with the latest schema, some tests and test data need to be modified. This PR introduces the required test changes.
imodel-native: https://github.com/iTwin/imodel-native/pull/522
=> Update tests to release CoreCustomAttributes EC3.2 schema

common/changes/@itwin/core-frontend/pmc-rm-reality-tile-max-depth_2023-10-30-13-33.json, core/frontend/src/tile/RealityModelTileTree.ts
Fixes https://github.com/iTwin/itwinjs-backlog/issues/901
Reverts "temporary" [five-year-old workaround](https://github.com/iTwin/itwinjs-core/commit/f85f06fb5f6f1499dc458a2edc992889cce66137).
=> Remove max depth for reality tiles.

common/api/core-backend.api.md, common/changes/@itwin/core-backend/nick-removelistener_2023-11-01-20-07.json, core/backend/src/IModelHost.ts, core/backend/src/test/IModelHost.test.ts
removelistener can't find the listener to remove if an anonymous function is passed. 
Thanks to Carole for reporting this.
(node:22416) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 beforeExit listeners added to [process]. Use emitter.setMaxListeners() to increase limit 
Is seen in logs when running tests without this change.
=> Pass IModelHost.shutdown as the listener function instead of a lambda function 

common/changes/@itwin/ecsql-common/fix-ecsql-common-docs-location_2023-11-02-13-14.json, core/ecsql/common/package.json
The `docs` script for `ecsql-common` outputs to an incorrect location. This fixes that so the generated docs sit alongside other packages' generated docs in the repo.
=> move ecsql/common generated-docs up one folder level

common/changes/@itwin/core-backend/affanK-fix-test-sensitive-to-order_2023-11-03-19-45.json, core/backend/src/test/ecdb/CTE.test.ts
_This test broke due to change execution plan in updated SQLite version._
imodel-native: https://github.com/iTwin/imodel-native/pull/542
=> Fix test sensitive to order which is dependent on SQLite execution plan.

test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts, test-apps/display-performance-test-app/src/frontend/TestRunner.ts
Display-performance-test-app traps and logs exceptions during tests, and by default keeps going to the next test (can be overridden by config).  However, certain exceptions cause DPTA to hang and are not recoverable, such as context loss.
Added test for known exceptions that are not recoverable and terminate DPTA on those.
=> Enhance error termination for display-performance-test-app

common/changes/@itwin/core-backend/rohitptnkr-removed-breaking-change-from-getAspects_2023-11-16-10-01.json, core/backend/src/IModelDb.ts, core/backend/src/test/element/ElementAspect.test.ts, docs/bis/ec/ec-format.md
In the change made in the PR #5966, the function getAspects was modified to use instance queries.
As part of the change in which we are checking if the input class is abstract, I had assumed the input aspect class full name to only ever be colon-separated (as per the unit tests present at the time).
This constitutes a breaking change as we used to accept class full names that were dot-separated as well as colon-separated before the PR #5966 
This PR fixes the change to handle both inputs and makes the change made in #5966 non-breaking.
Fixes iTwin/itwinjs-backlog/issues/981
=> Modified getAspects to handle dot separator in full classname

common/changes/@itwin/core-frontend/fix_maplayers_identify_2023-11-17-21-03.json, core/frontend/src/test/tile/map/ArcGISMapLayerImageryProvider.test.ts, core/frontend/src/tile/map/ImageryProviders/ArcGISMapLayerImageryProvider.ts
Very small fix to correctly set the spatial reference id in the 'Identify' query parameters.  
Also use the default 'top' mode instead of all `visible` layers.
=> Fix Map Feature Info for ArcGIS map services when reprojection is needed

common/changes/@itwin/core-frontend/pmc-fix-unquantized-feature-id-extraction_2023-11-21-19-46.json, core/frontend/src/common/render/primitives/VertexTableSplitter.ts
#6220 fixed extraction of feature index from unquantized vertex tables but it was extracting 4 bytes. The 4th byte is the material index, not part of the feature index. If it is non-zero (i.e., the vertex table uses a material atlas), the extracted feature index will be incorrect.
=> Fix unquantized feature index extraction

common/changes/@itwin/presentation-backend/presentation-fix_multi_element_properties_request_2023-11-21-13-57.json, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/test/PresentationManager.test.ts
Fixed bug uncovered by https://github.com/iTwin/imodel-native/pull/550
imodel-native: https://github.com/iTwin/imodel-native/pull/550
=> Presentation: Pass correct content options when loading multiple element properties

common/api/presentation-frontend.api.md, common/changes/@itwin/presentation-frontend/presentation-hilite_set_iterator_2023-11-21-11-41.json, common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, presentation/frontend/package.json, presentation/frontend/src/presentation-frontend/selection/HiliteSetProvider.ts, presentation/frontend/src/presentation-frontend/selection/SelectionManager.ts, presentation/frontend/src/test/selection/HiliteSetProvider.test.ts, presentation/frontend/src/test/selection/SelectionManager.test.ts
Part of https://github.com/iTwin/presentation/issues/329
Added `getHiliteSetIterator` method to `HiliteSetProvider`. This allows to handle hilite set in batches instead of waiting for whole set to be loaded. It also makes to possible to cancel hilite set loading if selection changes.
=> Presentation: Add hilite set iterator

common/changes/@itwin/map-layers-formats/missing_peer_dep_2023-11-24-07-53.json, extensions/map-layers-formats/package.json
`@itwin/map-layers-formats` package exposes types from `core-frontend` but does not have it as peer dependency.
https://github.com/iTwin/itwinjs-core/blob/ce0577203cc5ac67767871025e756566f937c933/common/api/map-layers-formats.api.md?plain=1#L62
https://github.com/iTwin/itwinjs-core/blob/ce0577203cc5ac67767871025e756566f937c933/common/api/map-layers-formats.api.md?plain=1#L94
This might lead to build failures in packages consuming `@itwin/map-layers-formats` if different `core-frontend` is resolved by package manager.
=> `@itwin/map-layers-formats`: Add missing `core-frontend` peer dep

common/changes/@itwin/core-frontend/pmc-ignore-subcategory-for-decorations_2023-11-28-21-11.json, core/frontend/src/render/webgl/BranchState.ts, core/frontend/src/render/webgl/Graphic.ts, core/frontend/src/test/TestDecorators.ts, core/frontend/src/test/render/webgl/DecorationFeatures.test.ts
Fixes #5876.
Non-scene graphics ignore the view's symbology overrides. That means no subcategories are visible, so only geometry that has an invalid subcategory gets displayed.
@Rock2000 is creating world decorations/overlays from element geometry, which contains valid subcategory Ids.
I changed it so that geometry of all subcategories is displayed for non-scene decorations, since disabling display of every subcategory is not useful.
In future, someone might want to create non-scene decorations that observe the symbology overrides applied to the view (e.g., subcategory visibility/appearance). If so we will need to provide a mechanism for that. For now, this is a sufficient improvement.
The third `test` in the "world decorations" and "world overlays" tests failed prior to my changes.
=> Enable display of all subcategories for non-scene decorations

common/api/core-backend.api.md, common/changes/@itwin/core-backend/aks-save-changes-on-IModelDb-close_2023-11-29-08-12.json, core/backend/src/BriefcaseManager.ts, core/backend/src/CheckpointManager.ts, core/backend/src/IModelDb.ts, core/backend/src/LocalHub.ts, core/backend/src/test/SchemaUtils.test.ts, core/backend/src/test/element/ElementDependencyGraph.test.ts, core/backend/src/test/imodel/IModel.test.ts, core/backend/src/test/standalone/TxnManager.test.ts, full-stack-tests/backend/src/HubUtility.ts, full-stack-tests/backend/src/integration/ApplyChangeSets.test.ts, full-stack-tests/backend/src/integration/ChangedElements.test.ts, test-apps/display-test-app/src/backend/SetToStandalone.ts
With this pull request, changes made to the iModel will now be automatically saved before closing.
imodel-native: https://github.com/iTwin/imodel-native/pull/558
=> Save changes before closing ReadWrite IModels

common/config/azure-pipelines/templates/gather-docs.yaml
Looks like we never properly switched this to the correct branch on 3.7.0, so this was still labeled as master.
Once first patch for 3.8.0 is out we will set this to 3.8.x. 
Don't know if its worth changing 3.7.x branch since it will no longer be in use after next week. Thoughts @ben-polinsky @aruniverse ? It is a simple change, so for continuity purpose might as well right?
=> Update gather-docs.yaml for 3.8.0 release

test-apps/display-performance-test-app/README.md, test-apps/display-performance-test-app/src/frontend/TestRunner.ts
Enhance the .csv output of timings tests in display-performance-test-app so that when the 'renderCmdStats' flag is set to true it will output columns for the number of Primitives, Batches, and Branches used by the command lists to render the scene.
I also added this new option and comumns explanations to the README file and added information for some comumns which were missing from the README file.
=> Enhance display-performance-test-app output.

docs/bis/ec/ec-format.md, docs/bis/ec/kindofquantity.md
Updated ec format and kindof quantity markdown files.
Added lines and examples explaining how format definitions and overrides handle unit labels which are null or empty strings.
=> Updated ec conceptual docs for format overrides

common/changes/@itwin/certa/gytis-support-Electron-28_2023-12-05-08-14.json, common/changes/@itwin/core-electron/gytis-support-Electron-28_2023-12-05-08-14.json, common/config/rush/pnpm-lock.yaml, core/electron/package.json, docs/changehistory/NextVersion.md, example-code/app/package.json, full-stack-tests/core/package.json, full-stack-tests/rpc/package.json, test-apps/display-performance-test-app/package.json, test-apps/display-test-app/package.json, tools/certa/package.json
- Extend range of supported Electron versions with Electron 28.
- Increase Electron dev dependency version to `^28.0.0`.
No code changes required since core doesn't use [APIs changed in 28](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-280).
=> Add support for Electron 28

common/changes/@itwin/core-backend/nick-disableschemachecktrue_2023-12-05-18-03.json, core/backend/src/ChangesetECAdaptor.ts
-1 is truthy, so when classFullName contains a : and not a ., it still splits on "." and then parts is an array of length 1.
=> Fix bug in changesetECAdaptor

common/scripts/install-run.js, rush.json
Rationale for this change is same as this PR: https://github.com/iTwin/itwinjs-core/pull/5824
New issue opened for this in rushstack's repo: https://github.com/microsoft/rushstack/issues/4445
=> Downgrade rush to v5.99.0 since higher versions don't support `preminor` version bump type

common/api/core-mobile.api.md, common/changes/@itwin/core-mobile/travis-mobile-connect-event_2023-12-12-00-07.json, core/mobile/src/backend/MobileHost.ts, core/mobile/src/backend/MobileRpcServer.ts
This is a complement to a future PR that will cause IpcHost.send to throw an exception when the backend and frontend are not connected. (Right now it crashes the mobile app.) Any code that catches that exception can then record the fact somewhere and add an onConnect handler.
=> Raise an event when mobile backend connects to frontend

docs/changehistory/leftNav.md
Adds the missing 4.3.0 changelogs to our change history. We should also consider a eslint rule for formatting `leftNav.md` files as extra spaces cause paragraphs to be inserted which breaks the nav.
=> add 4.3.0 changelogs to left nav

common/api/core-common.api.md, common/changes/@itwin/core-common/travis-send-to-frontend-not-async_2023-12-12-22-54.json, common/changes/@itwin/core-electron/travis-send-to-frontend-not-async_2023-12-12-23-30.json, common/changes/@itwin/core-mobile/travis-send-to-frontend-not-async_2023-12-12-22-54.json, core/common/src/rpc/core/RpcInvocation.ts, core/common/src/rpc/core/RpcMarshaling.ts, core/common/src/rpc/core/RpcProtocol.ts, core/electron/src/common/ElectronPush.ts, core/mobile/src/backend/MobileHost.ts, core/mobile/src/backend/MobileRpcServer.ts, core/mobile/src/common/MobileIpc.ts, core/mobile/src/common/MobilePush.ts
The main fix is to make MobileIpc.sendToFrontend not be async so that if an error happens it does not crash the whole app. This required RpcMarshaling.serialize to also not be async.
=> Fix mobile backend to frontend communication

.vscode/settings.json, common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-backend/jf-glyph_2023-12-13-15-06.json, common/changes/@itwin/core-common/jf-glyph_2023-12-13-15-06.json, core/backend/src/test/standalone/GeometryStream.test.ts, core/common/src/geometry/ElementGeometry.ts, core/common/src/geometry/TextString.ts
There is the ability to include text layout data in the flatbuffer of TextString rather than computing them at display time. Batch connector (in C++) uses this to preserve visual fidelity between MicroStation and IModels. This PR adds the same data in the TypeScript library so that the live sync connector can do this as well.
=> Add glyph data to TextString

common/changes/@itwin/core-backend/clear-geometry-stream-2_2023-12-20-14-45.json, common/changes/@itwin/core-common/clear-geometry-stream-2_2023-12-20-14-45.json, core/backend/src/test/standalone/GeometryStream.test.ts, core/common/src/geometry/ElementGeometry.ts
imodel-native: https://github.com/iTwin/imodel-native/pull/580
=> Support civil use case that requires update be able to clear the geometry stream.

common/api/core-backend.api.md, common/changes/@itwin/core-backend/affanK-fix-change-iterator-api_2023-12-20-21-59.json, core/backend/src/ChangesetECAdaptor.ts, core/backend/src/test/standalone/ChangesetReader.test.ts
This change include two fixes reported by developers
1. Make `$meta.ClassName` compatible with other APIs (classFullName).
2. Change unifier failed with update change was processed as the update does not have ECClassId. Now the check is more flexible and Api fallback to root class for the table and does not fail.
=> Update ChangesetReader API and relaxing requirement for ECClassId in update change 

common/api/presentation-backend.api.md, common/api/presentation-common.api.md, common/api/summary/presentation-common.exports.csv, common/changes/@itwin/presentation-backend/presentation-optimizations-for-full-imodel-read_2023-12-22-09-43.json, common/changes/@itwin/presentation-common/presentation-optimizations-for-full-imodel-read_2023-12-22-09-43.json, common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, full-stack-tests/presentation/src/performance/GetElementProperties.test.ts, presentation/backend/package.json, presentation/backend/src/presentation-backend/ElementPropertiesHelper.ts, presentation/backend/src/presentation-backend/NativePlatform.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/presentation-backend/PresentationManagerDetail.ts, presentation/backend/src/test/ElementPropertiesHelper.test.ts, presentation/backend/src/test/Helpers.ts, presentation/backend/src/test/PresentationManager.test.snap, presentation/backend/src/test/PresentationManager.test.ts, presentation/common/src/presentation-common/LocalizationHelper.ts, presentation/common/src/presentation-common/PresentationManagerOptions.ts, presentation/common/src/presentation-common/content/Item.ts, presentation/common/src/presentation-common/content/PropertyValueFormatter.ts, presentation/common/src/test/content/Item.test.snap, presentation/common/src/test/content/Item.test.ts
Closes https://github.com/iTwin/itwinjs-backlog/issues/976.
imodel-native: https://github.com/iTwin/imodel-native/pull/582
Performance of reading all `bis.GeometricElement` elements' properties:
| iModel | Before the change | After the change |
| --- | --- | --- |
| https://construction.bentley.com/22845570-a681-423c-b107-d9d3445a77ec/4d132ce6-df69-441c-ac39-5edef761e42d/imodel-progress | > 4 hours | ~1:30 h |
| https://qa-connect-imodelhubwebsite.bentley.com/Context/892aa2c9-5be8-4865-9f37-7d4c7e75ebbf/iModel/90b6fa70-c130-40c0-8a76-969f57eaaea4 | ~190 s. | ~105 s. |
Also improved the `PresentationManager.getElementProperties` API for the multiple elements case to accept a custom content parser, in case the caller wants to get results in a format other than the simplified …
=> Presentation: Optimizations for full iModel read

common/api/core-common.api.md, common/changes/@itwin/core-frontend/pmc-v1-magnify-float_2023-12-28-20-20.json, core/common/src/tile/IModelTileIO.ts, core/frontend/src/render/webgl/InstancedGeometry.ts
imodel-native-internal: https://github.com/iTwin/imodel-native-internal/pull/327
This PR just bumps tile format version to match native.
Older frontends will request an older tile format version; the mitigation is only applied for the new (v33) version.
This prevents older frontends from receiving unquantized tiles that they may not properly handle.
Also fixed `InstancedGeometry` failing to override `usesQuantizedPositions`, causing floating-point vertex tables to display incorrectly (jumbled into a plane).
=> Mitigate quantization error for magnified tiles

common/changes/@itwin/core-backend/affanK-FixFlakyTest_2024-01-02-17-08.json, core/backend/src/ChangesetECAdaptor.ts, core/backend/src/test/standalone/ChangesetReader.test.ts
The fix is to choose the derived class id & name in meta data when the change is of type update and fallback classid is present for both changes.
=> Fix flaky test that depended on order of changes in a changeset

common/changes/@itwin/ecschema-editing/julio-fixComparisonOfSchemasWithSameNameVersion_2023-12-21-21-09.json, core/ecschema-editing/src/Validation/SchemaCompareResultDelegate.ts, core/ecschema-editing/src/test/Validation/SchemaComparisonSameNameVersion.test.ts
This PR removes the keyMismatch comparison when comparing two schemas, this will allow the API to create two reports every time regardless of the schema names and version.
=> Fix comparison of schemas with same name version

common/changes/@itwin/core-backend/nick-changesetecadaptor-fixmaybe_2024-01-04-21-23.json, core/backend/src/ChangesetECAdaptor.ts
Without this change I get a ChangedECInstance which has no ECClassId or fallbackClassId
With the change a classId is present:
=> classIdPresentInChange should be true when ecClassId is present

common/api/core-backend.api.md, common/api/core-common.api.md, common/changes/@itwin/core-backend/fix-clone-materials_2024-01-10-19-10.json, common/changes/@itwin/core-common/fix-clone-materials_2024-01-10-19-10.json, core/backend/src/Material.ts, core/backend/src/test/standalone/RenderMaterialElement.test.ts, core/common/src/MaterialProps.ts
Transformations can lose data or cause strange behavior if they do not remap ids in json properties, and the ids are attempted to be reused by another application. In this case, transformations can just lose textured materials.
- fix not remapping texture ids in `RenderMaterial` json properties
- add a test over a mock clone context
- move some test utilities up in the file to reuse in a new `describe` test block
- add optional types for possible maps in iModel data, see below for questions
I am seeking review of the documentation I added for possible maps as observed in the house model sample. I see a potential list of really supported maps [here in the native code](https://github.com/iTwin/imodel-native/blob/116fc61ff5d19c08c0d5296295b44a71c5e2cf71/iModelCore/iModelPlatform/PublicAPI/Dgn …
=> Fix `RenderMaterialElement.onCloned` not remapping map texture ids

common/changes/@itwin/core-geometry/master_2024-01-11-23-07.json, core/geometry/src/geometry3d/Angle.ts, core/geometry/src/geometry3d/YawPitchRollAngles.ts, core/geometry/src/test/geometry3d/ViewBox.test.ts, core/geometry/src/test/geometry3d/YawPitchRollAngles.test.ts
Now if a near-rigid matrix is passed to Matrix3d.createRigidFromMatrix3d, the function does not return undefined.
=> Loosen tolerance of Matrix3d.createRigidFromMatrix3d to allow near-rigid matrices

common/changes/@itwin/frontend-tiles/pmc-include-model-ranges_2024-01-11-18-41.json, extensions/frontend-tiles/package.json, extensions/frontend-tiles/src/BatchedModels.ts, extensions/frontend-tiles/src/BatchedSpatialTileTreeRefs.ts, extensions/frontend-tiles/src/BatchedTileTree.ts, extensions/frontend-tiles/src/BatchedTilesetReader.ts
In reaction to https://github.com/iTwin/imodel-native-internal/pull/351.
Prerequisite for #6354.
The BENTLEY_BatchedTileset extension is now required, and must contain the parallel arrays of model Ids and model extents. Tilesets published prior to this change to tileset.json will fail to load. I do not want to have to maintain multiple alternate code paths to support pre-release versions of the tileset schema.
=> Include model ranges in batched tilesets

test-apps/display-test-app/src/common/DtaConfiguration.ts, test-apps/display-test-app/src/frontend/App.ts
- Change default client id for electron renderer auth to a more appropriately named client id (electron client ids should follow `native-XX`)
- Fixes `dta signin` callback hanging after successful log in on the electron DTA, when `npm run start` script is used. Specifically, a different redirect url has to be used in this case, because the default, localhost:3000 is already used by the webserver. Added an if statement in DtaConfiguration to allow redirect urls to branch depending on the process.
=> Change config handling for display test app

common/config/rush/.pnpmfile.cjs, common/config/rush/pnpm-lock.yaml
After running rush update --full in the release branch a couple of days ago and a failing docs build: https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2612229&view=logs&j=bf01bec3-f6e2-5983-bdff-93019feebaa1&t=8d110379-66a4-5f89-b46c-1a9b11ce4c18
I decided to debug into typedoc/typescript code and poke around. In a broken docs build (after running rush update --full), we were missing some exports from RpcManager. This was due to RpcManager now resolving to a path like `"D:/itwinjs-core2/common/temp/node_modules/.pnpm/@itwin+corecommon@4.3.3_67wltvhdskk2oee2c3z2o4tfly/node_modules/@itwin/core-common/lib/cjs/RpcManager.d.ts"` instead of `"D:/itwinjs-core/core/common/lib/cjs/RpcManager.d.ts"`. 
When running typedoc we intentionally exclude paths with node_modules (by …
=> Add core-common to the list of packages for electron-auth and browser-auth to be marked as workspace:*

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, test-apps/display-performance-test-app/package.json, test-apps/display-test-app/package.json
The `display-test-app` and `display-performance-test-app` packages haver `eslint.config.js` files that have `require("@typescript-eslint/parser")` statements. No such package dependency existed on either packages leading to a `module not found error` on ESLint VS Code intellisense. This PR fixes that issue
=> Add `@typescript-eslint/parser` dev dependency

common/changes/@itwin/core-quantity/nam-parse-quantity-fix_2024-01-25-19-48.json, core/quantity/src/Parser.ts, core/quantity/src/test/Parsing.test.ts
Addresses #6362 
Adds logic, plus test cases to core quantity's Parser, which supports parsing numeric strings that have decimal separators that don't use a period.
=> Add different decimal separator support to core-quantity's Parser

common/api/presentation-common.api.md, common/changes/@itwin/presentation-backend/presentation-fix-missing-localization_2024-01-29-12-21.json, common/changes/@itwin/presentation-common/presentation-fix-missing-localization_2024-01-29-12-21.json, common/changes/@itwin/presentation-frontend/presentation-fix-missing-localization_2024-01-29-12-21.json, docs/presentation/advanced/Localization.md, full-stack-tests/presentation/src/frontend/Localization.test.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts, presentation/common/src/presentation-common/LocalizationHelper.ts, presentation/common/src/test/LocalizationHelper.test.ts, presentation/frontend/src/presentation-frontend/PresentationManager.ts, presentation/frontend/src/test/PresentationManager.test.ts
This is a proper fix for an issue that's worked around in https://github.com/iTwin/viewer-components-react/pull/745.
Add tests, missing calls to our localization handler, clarify docs.
=> Presentation: Fix descriptor, node path and distinct value responses not being localized

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-query-batch-table_2024-01-27-01-05.json, common/changes/@itwin/core-frontend/pmc-query-batch-table_2024-01-27-02-16.json, core/frontend/src/ContextRealityModelState.ts, core/frontend/src/DisplayStyleState.ts, core/frontend/src/tile/BatchedTileIdMap.ts, core/frontend/src/tile/RealityModelTileTree.ts, core/frontend/src/tile/RealityTileTree.ts, docs/changehistory/NextVersion.md, example-code/snippets/src/frontend/BatchTableProperties.ts
See NextVersion.md and example code in BatchTableProperties.ts.
I don't have a good way to automate testing of this.
I didn't want to make this API front-and-center because it's strictly relevant to a subset of 3D Tiles 1.0 tilesets. 3D Tiles 1.1 completely replaces the way per-feature properties are done, and we're also planning to migrate to viewer APIs based on "scene objects" instead of "tile trees".
=> Batch table property access

docs/reference/index.md, docs/reference/leftNav.md
This PR removes documentation referencing the internal package `@itwin/appui-layout-react`.
=> Remove docs reference to internal package

common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-common/add_generic_instance_filter_definition_2024-02-07-15-45.json, core/common/src/GenericInstanceFilter.ts, core/common/src/core-common.ts, core/common/src/test/GenericInstanceFilter.test.ts
Moved `GenericInstanceFilter` definition from `presentation-components` to `core-common`. It was introduced as an intermediate format when converting `PresentationInstanceFilter` into other formats (e.g. ECSQL) and does not depend on `presentation`. Having it in `core-common` allows to use it without having dependency on `presentation-components` and on `AppUI` as a result.
=> Add `GenericInstanceFilter` definition

common/changes/@itwin/ecsql-common/as-add-missing-dep_2024-02-17-20-37.json, common/config/rush/pnpm-lock.yaml, core/ecsql/common/package.json
Dependency is not specified even though the https://github.com/iTwin/itwinjs-core/blob/master/core/ecsql/common/eslint.config.js file has a `require("@itwin/eslint-plugin")` statement
Intellisense does not work without this dependency specified
=> Add missing `@itwin/eslint-plugin` devDependency to `@itwin/ecsql-common`

common/config/azure-pipelines/jobs/fast-ci.yaml
Post success was running on all runs of iTwin.js pipeline. Its only needed for PRs. Will give errors otherwise.
=> only run post success on PRs

common/changes/@itwin/core-backend/TileStorage-init-409_2024-02-21-16-02.json, core/backend/src/TileStorage.ts
A race condition can occur when multiple people try to open the same iModel at the same time. Since `@itwin/object-storage` doesn't have good error handling, this PR simply ignores 409 errors that come from Azure blob storage.
=> Ignore 409 errors when initializing tile storage

common/api/frontend-tiles.api.md, common/api/summary/frontend-tiles.exports.csv, common/changes/@itwin/frontend-tiles/diborra-new-options-for-mesh-export-service_2024-02-22-15-26.json, extensions/frontend-tiles/src/FrontendTiles.ts, extensions/frontend-tiles/src/test/FrontendTiles.test.ts
- Add the following parameters to the mesh-export/get-exports query:
- version: filters the exports by version, to support multiple versions
- cdn: activates the CDN (context delivery network) to make tile downloads faster
=> Add CDN and version parameters to mesh-export/get-exports query

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/djs-chg-desktop-GPUMemLimit_2024-02-23-20-43.json, core/frontend/src/test/tile/TileAdmin.test.ts, core/frontend/src/tile/TileAdmin.ts
For non-mobile devices, the gpuMemoryLimit used a setting of "none" (no limit) when it was not defined.  This changes that setting to TileAdmin.nonMobileUndefinedGpuMemoryLimit (6,000 MB) instead.
Some very large reality data sets and imodels could on occasion cause a WebGL context loss with no limit imposed, so this attempts to set a generous limit that should prevent most of these problems for the common case of the gpuMemoryLimit being undefined.  If desired, the limit can still be set to "none".
See https://github.com/iTwin/itwinjs-backlog/issues/1047
=> Change gpuMemoryLimit setting used when undefined

common/changes/@itwin/core-frontend/nam-mem-leak-resolution_2024-02-28-21-45.json, core/frontend/src/ViewManager.ts, core/frontend/src/test/ViewManager.test.ts
When ImodelApp.shutdown() is called, ViewManager's onShutdown() is called. Problem is, the  viewports that are a part of IModelApp do not have their dispose() functions called, which holds up WebGL resources. This results in a memory leak even after shutdown() is called: thousands of featureAppearance overrides are being retained every refresh, which are coming from ScreenViewport's OnScreenTarget.
Solution is to drop all viewports in IModelApp's viewManager when shutdown is called.
=> Address memory leak regarding markers and decorators

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-batch-table-iterator_2024-03-05-15-37.json, core/frontend/src/tile/BatchedTileIdMap.ts, core/frontend/src/tile/RealityTileTree.ts
=> Add an iterator over the entries of BatchTableProperties

common/config/azure-pipelines/jobs/fast-ci.yaml
always build even if a native PR is linked. Just to be safe probably best to require builds before merging an itwinjs-core PR. If we decide to skip this part in the future it can easily be added back. This will also mean we don't need to change the requirements on any of our status checks. Also by doing this I would like to not build itwinjs-core during a the release process. 
Pros:
This doesn't necessarily save us time since other builds take longer. However, this reduces the chance for flaky tests failing during itwinjs-core builds and cause releases to be delayed. I just have a feeling people are more likely to not notice if Release builds fail, and cause longer delays in the release. If their PR fails they will definitely notice.
Cons:
Doing this we only verify that master and the new …
=> Do Not Skip PR builds when native change is linked

common/changes/@itwin/frontend-tiles/pmc-clamp-batched-models-extents_2024-03-07-14-29.json, extensions/frontend-tiles/src/BatchedModels.ts
The iModel's project extents are supposed to clamp the range of viewable geometry. The tileset publisher enforces this. However, at display time we compute the volume of the displayed viewable models by taking the union of the bounding boxes of each model, which may extend (sometimes very far!) outside of the project extents. This can arbitrarily expand the viewed volume so that when you fit the view, it zooms way out; and can negatively affect depth buffer precision, producing visual artifacts.
Add project extents clamping when computing viewed extents in BatchedModels.
Needs to be backported to 4.4.x ASAP. Running ImageTests first.
=> Clamp batched tile fit volume to project extents.

common/changes/@itwin/core-frontend/man-fix-gpu-timings_2024-03-11-19-45.json, core/frontend/src/render/webgl/GLTimer.ts
This fixes a problem that started occurring with our GPU timing code which happened when a new chrome (and then later electron) were pushed.  We were depending on some un-documented behavior for querying the gpu timings and its behavior changed.  We implement a stack of timers so that we can time sub-processes of the render and were re-starting a timer query which used to add the results of both querries for you.  The behavior of this instead now resets the timer so we only get the time for the last time.  To fix this the code now starts a new timer instead and adds the results of all of the timers for the parent timing together when it is finished.
=> Fix GPU timings

common/changes/@itwin/core-backend/aks-queryreader-crash-fix_2024-03-08-09-55.json, common/changes/@itwin/core-common/aks-queryreader-crash-fix_2024-03-08-09-55.json, core/backend/src/test/ecdb/ECSqlReader.test.ts, core/common/src/ECSqlReader.ts
This Pull Request addresses a critical bug causing the `ECSqlReader.toRow()` method to crash when the `QueryRowFormat` is set to `UseECSqlPropertyNames` or `UseECSqlPropertyIndexes` and duplicate property names are selected.
Resolved the crash issue by updating the row formatting logic to prevent the use of the same property name multiple times.
Closes #6343
=> Bug Fix: Resolve `ECSqlReader.toRow()` crash while duplicate property names are selected

common/api/core-backend.api.md, common/changes/@itwin/core-backend/AlfonsoM-potentialSectionDrawingInsertBug_2024-03-13-15-56.json, core/backend/src/Element.ts, core/backend/src/test/standalone/SectionDrawing.test.ts
It was creating the supertype `DrawingModel` instead.
Fixes #6511.
=> SectionDrawing.insert should insert a SectionDrawingModel

common/changes/@itwin/core-frontend/pmc-fix-gltf-instance-transform_2024-03-18-16-47.json, core/frontend/src/tile/GltfReader.ts
Fixes https://github.com/iTwin/itwin-graphics-backlog/issues/124.
Rotation and scale were being multiplied in the opposite of the order mandated by the [specification](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing/README.md#transformation-order).
=> Fix glTF instance transform

common/changes/@itwin/core-frontend/man-cut-plane-graphics-for-batched-tiles_2024-03-14-14-07.json, common/changes/@itwin/frontend-devtools/man-cut-plane-graphics-for-batched-tiles_2024-03-15-14-44.json, core/frontend-devtools/README.md, core/frontend-devtools/src/tools/ClipTools.ts, core/frontend/src/tile/PrimaryTileTree.ts
This modification allows cut plane graphics to be generated for batched tiles.
It also enhances the fdt test clip style key-in command so that you can optionally specify a CutStyleProps to use for the cut plane geometry instead of the hard-coded one.
=> Cut Plane Graphics for Batched Tiles

common/changes/@itwin/core-backend/master_2024-03-21-12-51.json, core/backend/src/IModelDb.ts
I cannot open a ViewStore from my test frontend application. It turns out `accessViewStore` function isn't forwarding user token to `CloudSqlite.requestToken` invocation when `ContainerProps` are not supplied.
=> `IModelDb`: Fix `IModelDb.views.accessViewStore` ignoring supplied `userToken` and `accessLevel` values

common/changes/@itwin/core-common/like-operator-note_2024-03-29-07-55.json, core/common/src/GenericInstanceFilter.ts
Added note to `GenericInstanceFilterRuleOperator` that `like` operator should be handled as a `contains` operator as discussed in [496](https://github.com/iTwin/presentation/pull/496).
=> Add note to GenericInstanceFilterRuleOperator

docs/changehistory/4.5.0.md, docs/changehistory/leftNav.md
This step has been automated here: https://github.com/iTwin/itwinjs-core/blob/17656436e63ba98e1d413acd251676f18caf4002/.github/workflows/automation-scripts/update-changelogs.mjs#L131
However, this automation is done when the finalize release script runs after a minor release. The scripts checks for the most recent commit message to verify it is a minor release then does this change. During this minor release, this check failed because when the finalize release step ran, there was already a commit made after the minor release commit. Hence, the part of the script that does this edit also did not run and now needs to be done manually for this minor.
Minors releases in the future shouldn't need this
=> Update leftNav.md after minor release

common/config/azure-pipelines/templates/gather-docs.yaml
This step has been automated here: https://github.com/iTwin/itwinjs-core/blob/17656436e63ba98e1d413acd251676f18caf4002/.github/workflows/automation-scripts/update-changelogs.mjs#L96C1-L96C36
However, this automation is done when the finalize release script runs after a minor release. The scripts checks for the most recent commit message to verify it is a minor release then does this change. During this minor release, this check failed because when the finalize release step ran, there was already a commit made after the minor release commit. Hence, the part of the script that does this edit also did not run and now needs to be done manually for this minor. 
Minors releases in the future shouldn't need this
=> Update gather-docs yaml to correct branch name

common/api/core-backend.api.md, common/api/core-bentley.api.md, common/api/summary/core-bentley.exports.csv, common/changes/@itwin/core-backend/affanK-improve-ts-changeset-api_2024-04-01-13-35.json, common/changes/@itwin/core-bentley/affanK-improve-ts-changeset-api_2024-04-01-13-35.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/IModelDb.ts, core/backend/src/SqliteChangesetReader.ts, core/backend/src/test/standalone/ChangeConflictHandler.test.ts, core/bentley/src/BeSQLite.ts, test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Added the following methods to `ChangesetConflictArgs` to allow it access changed column and its values. A similar improvement is done to `SqliteChangeSetReader`  to allow it to access strong-type individual column values.
```ts
getPrimaryKeyColumns: () => number[];
getValueType: (columnIndex: number, stage: DbChangeStage) => DbValueType | undefined;
getValueBinary: (columnIndex: number, stage: DbChangeStage) => Uint8Array | undefined;
getValueId: (columnIndex: number, stage: DbChangeStage) => Id64String | undefined;
getValueText: (columnIndex: number, stage: DbChangeStage) => string | undefined;
getValueInteger: (columnIndex: number, stage: DbChangeStage) => number | undefined;
getValueDouble: (columnIndex: number, stage: DbChangeStage) => number | undefined;
isValueNull: (columnIndex: …
```
=> Improve ChangesetConflictArgs & SqliteChangeSetReader API

common/changes/@itwin/core-backend/otel-internal-span_2024-04-15-10-20.json, core/backend/src/rpc/tracing.ts
There should be only one "server" span for each "client" span and it should be in a direct parent-child relationship. The way it was set up, you couldn't insert any spans before this one without breaking the rule. This was problematic especially with HTTP auto-instrumentation, which is otherwise very useful.
If this happens to be the root span (there's no client, proxy etc. with tracing enabled), "internal" is the most suitable option. If it's not the root span, users will probably want to use a transport layer instrumentation library to enable context propagation anyway, and that will add a "server" span above this RPC span.
=> Change RPC SpanKind to internal

common/config/azure-pipelines/ci.yaml, common/config/azure-pipelines/jobs/docs-build.yaml, common/config/azure-pipelines/jobs/fast-ci.yaml, common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml, common/scripts/install-run-rush-pnpm.js, common/scripts/install-run-rush.js, common/scripts/install-run-rushx.js, common/scripts/install-run.js, rush.json
Use latest version of Rush to fix security issue we had previously worked-around.
[Node security issue](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2#command-injection-via-args-parameter-of-child_processspawn-without-shell-option-enabled-on-windows-cve-2024-27980---high)
[Rush change](https://github.com/microsoft/rushstack/pull/4637)
=> update rush - permanent fix for cve-2024-27980 (node security patch)

common/changes/@itwin/core-backend/lock-perf_2024-04-18-17-47.json, core/backend/src/Element.ts, core/backend/src/ServerBasedLocks.ts
Changes as requested by @abeesh after seeing a 20x slow down with local synchronizations compared to batch connectors.
=> Don't save to lock-database when inserting elements if their Model is locked

common/scripts/update-imodeljs-native-version.sh
#FIX [Error](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2820026&view=logs&j=f2f89327-8de0-5593-ba24-f02f308318c4&t=68df82d3-6497-5825-5355-16706c9e3b52) in Release Pipeline 
- Description: rush change accepts arguments in format remote/branch, not branch
- Solution: add origin/ before branch name when passing to rush change
- Affected File(s): update-imodeljs-native-version.sh
=> Fix arguments format passed to rush change

common/api/core-backend.api.md, common/changes/@itwin/core-backend/push-changes-writeable_2024-04-22-12-28.json, core/backend/src/IModelDb.ts, core/backend/src/test/standalone/IModelWrite.test.ts
Use `BriefcaseDb.executeWriteable` and make that function open the `ServerBasedLocks` lock control.
=> Allow pushing changes from a BriefcaseDb opened readonly

common/changes/@itwin/ecschema-editing/schema-editing-default-changes-array_2024-04-25-08-44.json, core/ecschema-editing/src/Differencing/SchemaDifference.ts, core/ecschema-editing/src/test/Differencing/Difference.test.ts, core/ecschema-editing/src/test/Merging/SchemaMerger.test.ts
SchemaDifferences has a readonly array-property _changes_ that contain all differences between two compared schemas. At the moment, the changes array kept undefined if no changes were found, this however limits the ability for a consumer to add manually or apply pre-saved changes.
=> Change SchemaDifference.changes to be not undefined

common/changes/@itwin/core-frontend/pmc-fix-2d-dynamic-graphics-clip_2024-05-01-11-11.json, core/frontend/src/tile/DynamicIModelTile.ts
=> Don't clip 2d dynamic element graphics to project extents.

common/api/core-common.api.md, common/changes/@itwin/core-backend/pmc-fix-text-anchor_2024-05-03-11-44.json, common/changes/@itwin/core-common/pmc-fix-text-anchor_2024-05-03-11-44.json, core/backend/src/TextAnnotationGeometry.ts, core/backend/src/test/annotations/TextAnnotation.test.ts, core/common/src/annotation/TextAnnotation.ts, test-apps/display-test-app/src/frontend/TextDecoration.ts
Fixes #6688.
Added key-ins to display-test-app:
- `dta text rotation <degrees>`
- `dta text anchor <left|center|right|top|middle|bottom>`
Removed `TextAnnotation.origin`. It was not adding anything useful.
Clarified documentation of `TextAnnotationAnchor`.
Fixed inverted addition and subtraction in `TextAnnotation.computeDocumentTransform`, copied from rarely-if-ever-used C++ version.
Made `computeDocumentTransform` rotate about the fixed anchor point.
The results are *almost* correct.
=> Fix text rotation around anchor point 

common/changes/@itwin/core-backend/2024-05-07-16-09.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Backport [imodeljs-native 4.6.31](https://github.com/iTwin/itwinjs-core/commit/f995d7fe75a5ca2b3998ed1ce23aad7d8a31d136) for 4.6 release.
=> @bentley/imodeljs-native 4.6.31

common/changes/@itwin/core-backend/gytis-brotli-compression-for-rpc_2024-05-13-14-51.json, common/changes/@itwin/core-common/gytis-brotli-compression-for-rpc_2024-05-13-14-51.json, common/changes/@itwin/ecschema-rpcinterface-common/gytis-brotli-compression-for-rpc_2024-05-13-14-51.json, common/changes/@itwin/presentation-common/gytis-brotli-compression-for-rpc_2024-05-13-14-51.json, core/backend/src/rpc/web/response.ts, core/backend/src/test/rpc/response.test.ts, core/common/src/rpc/core/RpcInvocation.ts, core/common/src/rpc/core/RpcMarshaling.ts, core/common/src/rpc/core/RpcOperation.ts, core/common/src/rpc/core/RpcProtocol.ts, core/ecschema-rpc/common/src/ECSchemaRpcInterface.ts, presentation/common/src/presentation-common/PresentationRpcInterface.ts
Enabling compression for RPC response bodies have show to significantly drop size of data which needs to be downloaded by the frontend. Right now, only certain RPC requests have Gzip compression enabled.
Also, Brotli compression have shown to have better compression ratio for our RPC requests without additional compressing time.
- Make Brotli main compression instead of Gzip (if Brotli not supported by the browser, will fallback to Gzip).
- Enable compression for all RPC responses by default (to disable compression for specific RPC request, add following line above definition: `@RpcOperation.setPolicy({ allowResponseCompression: false })`.
=> Enable Brotli compression for RPC requests by default

common/changes/@itwin/core-geometry/saeed-torabi-polyface-query-reorder_2024-05-22-13-28.json, core/geometry/src/polyface/PolyfaceQuery.ts, core/geometry/src/test/serialization/crossPlatform.test.ts
Also fixed a couple lint issues
=> Move a few of PolyfaceQuery functions around to make the code more readable

common/changes/@itwin/core-frontend/nam-subcategories-increase_2024-05-28-20-57.json, core/frontend/src/SubCategoriesCache.ts
The maximum number of categories passed into the function is changed to 2500, to address performance issues with the querySubCategories workflow for large iModels.
=> Increase maximum number of categories passed into querySubCategories.

full-stack-tests/core/src/frontend/standalone/RealityDataAccess.test.ts
Re enabled "should get RealityDataSource for reality data attachment in iModel" test.
More test user rights had to be fixed.
=> Re-enabled RealityDataSource test

common/api/core-geometry.api.md, common/changes/@itwin/core-geometry/da4-top-facet-subset-visitor_2024-05-29-22-20.json, core/geometry/src/polyface/IndexedPolyfaceVisitor.ts, core/geometry/src/polyface/Polyface.ts, core/geometry/src/polyface/PolyfaceQuery.ts, core/geometry/src/test/polyface/Polyface.test.ts
New method `IndexedPolyfaceSubsetVisitor.createNormalComparison` makes it easy to iterate facets of a mesh that satisfy a normal condition, e.g., the "top" facets of a DTM while avoiding "side" or "skirt" facets. In particular, many `Polyface` API methods take a mesh or a visitor, so passing in this visitor allows for operations on filtered facets.
Motivated by conversations with Map and Booster teams.
Also:
* Refactored and tested this visitor, which was not tested previously.
* Preserve readIndex in `PolyfaceQuery.visitorClientPointCount` and `PolyfaceQuery.visitorClientFacetCount`
* New optional `PolyfaceVisitor.getVisitableFacetCount` interface method allowing visitors to return facet count more efficiently.
=> Add `IndexedPolyfaceSubsetVisitor` constructor to iterate "top" facets of a mesh

common/changes/@itwin/core-backend/master_2024-05-27-13-55.json, core/backend/src/NativeAppStorage.ts, core/backend/src/test/standalone/NativeAppStorage.test.ts
This should prevent storage files from being created outside storage cache directory.
Alternative solution would be to not allow any sort of path elements in the storage name. However, this would break apps which use storage names likes `my-app/common-settings` (if such apps exist).
=> Increase restrictions on native app storage name

test-apps/display-performance-test-app/src/backend/WebMain.ts, test-apps/display-performance-test-app/src/frontend/TestRunner.ts
Also add a new flag to enable EGL for creating headless GL context on chrome / linux.
This is required to run image tests on headless linux virtual machines, e.g., that do not have a display.
=> Add GL headless support on linux chrome

common/changes/@itwin/core-frontend/undo-redo-restart-active-tool_2024-06-06-18-23.json, common/changes/@itwin/editor-frontend/undo-redo-restart-active-tool_2024-06-06-18-23.json, core/frontend/src/BriefcaseConnection.ts, core/frontend/src/tools/ToolAdmin.ts, editor/frontend/src/UndoRedoTool.ts
Required to avoid a potentially stale tool state.
Hopefully it's fine adding this directly to BriefcaseConnection...seemed like the most sensible place to me.
=> Handle restart of the active tool in onAfterUndoRedo txn event.

common/changes/@itwin/build-tools/pmc-api-extractor-7.47_2024-06-11-22-32.json, common/config/rush/pnpm-lock.yaml, tools/build/package.json
We're 4 months out of date (7.40.x) and the [latest version](https://github.com/microsoft/rushstack/blob/main/apps/api-extractor/CHANGELOG.md#minor-changes) introduces [support](https://github.com/microsoft/rushstack/pull/4698) for `export * as whatever`, which I want to use [here](https://github.com/iTwin/itwinjs-core/pull/6828).
The new version produces identical .api.md files.
=> Update api-extractor to 7.47

common/changes/@itwin/core-geometry/da4-linestring-frenet-bug_2024-06-12-13-28.json, core/geometry/src/curve/LineString3d.ts, core/geometry/src/test/GeometryCoreTestIO.ts, core/geometry/src/test/curve/LineString3d.test.ts
When the input global fraction refers to the midpoint of an interior segment coplanar with its two neighbors, and they have opposite concavity with respect to the segment, the accumulated normal computed by `accumulateGoodUnitPerpendicular` vanished, resulting incorrectly in the default output (identity).
Applied fix: if the accumulated normal vanishes, we revert to its previous value.
=> `LineString3d.fractionToFrenetFrame` incorrect output

common/changes/@itwin/core-backend/pmc-anchor-pt-at-origin_2024-06-12-16-37.json, common/changes/@itwin/core-common/pmc-anchor-pt-at-origin_2024-06-12-16-37.json, core/backend/src/TextAnnotationGeometry.ts, core/common/src/annotation/TextAnnotation.ts, core/common/src/test/annotations/TextAnnotation.test.ts
This way the anchor point always coincides with the element's placement origin.
=> Align text annotation anchor point with origin

common/changes/@itwin/core-backend/jiarui-doNotThrowErrorWhenSourcemapUndefined_2024-06-12-16-07.json, common/changes/@itwin/core-backend/jiarui-doNotThrowErrorWhenSourcemapUndefined_2024-06-12-19-22.json, core/backend/src/Material.ts, core/backend/src/test/standalone/RenderMaterialElement.test.ts
fix iTwin/itwinjs-backlog#1123
sourceMap could be undefined/null in some cases. ignore it instead of throwing an error
=> Don't throw an error if sourceMap is null/undefined

common/changes/@itwin/ecschema-editing/schema-editing-ca-properties-comparison-fix_2024-06-14-13-33.json, core/ecschema-editing/src/Validation/SchemaComparer.ts, core/ecschema-editing/src/test/Validation/SchemaComparer.test.ts
SchemaComparer reported a delta if the properties on a CustomAttribute were not in the same order.
Changed the comparer to use keys instead of indices.
=> Custom Attribute comparison fix when lookup properties

.vscode/cSpell.json, common/changes/@itwin/core-geometry/da4-linestring-fraction-mapper-bug_2024-06-14-16-05.json, core/geometry/src/curve/LineString3d.ts, core/geometry/src/test/curve/LineString3d.test.ts, test-apps/display-performance-test-app/src/frontend/TestRunner.ts
Global fraction 1.0 resulted in invalid segment index.
Addresses https://github.com/iTwin/itwinjs-backlog/issues/1143
=> `LineString3d.globalFractionToSegmentIndexAndLocalFraction` bug fix

common/config/azure-pipelines/templates/core-build.yaml, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, tools/internal/ios/core-test-runner/core-test-runner/ViewController.swift
These were failing during CI but not failing for me locally, so there is a decent chance they will still fail now that they are reenabled, so I added a small amount of extra output printing during the run.
=> Reenable iOS backend unit tests

common/changes/@itwin/core-backend/nick-changesummariestoken_2024-06-26-15-42.json, core/backend/src/ChangeSummaryManager.ts
This is so potentially long running operations like pullChanges will refresh their token when downloadingChangesets because hubAccess methods call IModelHost.authorizationClient.getAccessToken if we don't pass a token.
=> Within changeSummaryManager, try to rely on having an authClient defined where possible.

common/changes/@itwin/frontend-tiles/andremig-version-tracking_2024-06-26-17-48.json, extensions/frontend-tiles/src/GraphicsProvider/GraphicRepresentationProvider.ts
Add iTwinJS Version and Tile Version as query params in the Graphic Representation query url for tracking purposes.
Export Type was also updated in the query url to reflect the actual export type, and not be hardcoded to "IMODEL".
=> Add iTwinJS and Tile Version Tracking to Graphics Service Requests

common/changes/@itwin/ecschema-metadata/pmc-ecschema-metadata-clean_2024-07-01-09-38.json, core/ecschema-metadata/package.json
Removed in #6900. @williamkbentley I presume this was unintentional.
Causes `rush clean` to fail.
=> Reinstate ecschema-metadata clean script

common/changes/@itwin/core-geometry/nick-add-public_2024-07-03-13-55.json, core/geometry/src/Constant.ts
Without this, I get 
Analysis will use the bundled TypeScript version 5.4.2
Error: src/Constant.ts:13:1 - (ae-missing-release-tag) "Constant" is part of the package's API, but it is missing a release tag (@alpha, @beta, @public, or @internal)
API Extractor completed with errors
locally. 
As well as in my pipeline https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2997999&view=logs&jobId=98bcb9af-6780-51c4-01f3-7d41d7c82e74&j=98bcb9af-6780-51c4-01f3-7d41d7c82e74&t=93a643e6-ba20-5515-aad8-b904d25149fa
=> Add public to constant.ts

common/config/rush/pnpm-lock.yaml, full-stack-tests/core/package.json, full-stack-tests/core/src/backend/backend.ts, full-stack-tests/core/src/certa/certaBackend.ts, full-stack-tests/core/src/frontend/TestUtility.ts, full-stack-tests/core/tsconfig.json, test-apps/display-performance-test-app/package.json, test-apps/display-performance-test-app/src/backend/backend.ts, test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts, test-apps/display-performance-test-app/tsconfig.backend.json, test-apps/display-test-app/package.json, test-apps/display-test-app/src/backend/Backend.ts, test-apps/display-test-app/src/frontend/App.ts, test-apps/display-test-app/src/frontend/signIn.ts, test-apps/display-test-app/tsconfig.backend.json
- Use @itwin/electron-authorization `0.19.5` in our test apps and core full stack tests.
- Use the export maps exposed in @itwin/electron-authorization `package.json`.
- Modify the tsconfig.json of the 3 packages above with the following justifications:
-  `resolvePackageJsonExports` to use libraries' `exports` field when importing those libraries, else `tsc` will complain it couldn't find the declaration files or the library itself.
- To use a library's `exports` field, we also need to use a `moduleResolution` of `NodeNext` or `Bundler`, but the latter will enforce the files you use to strictly ESM. The former supports CJS files, which is what the 3 packages above use.
=> Use export maps from electron-auth, update build config

common/api/presentation-common.api.md, common/changes/@itwin/presentation-common/nested-content-value-label_2024-07-08-08-17.json, presentation/common/src/presentation-common/content/ContentTraverser.ts, presentation/common/src/presentation-common/content/Value.ts, presentation/common/src/test/content/ContentTraverser.test.ts
Part of https://github.com/iTwin/presentation/issues/654
Will be consumed in `presentation-components` in https://github.com/iTwin/presentation/pull/664
=> Presentation: Add `NestedContentValue.label` property which is passed to `IContentVisitor.startStruct`

common/changes/@itwin/ecschema-rpcinterface-common/enable-response-caching-by-default-schema-rpc_2024-07-10-10-47.json, core/ecschema-rpc/common/src/ECSchemaRpcInterface.ts, docs/changehistory/NextVersion.md
This enables RPC caching as well
=> Make getSchemaKeys and getSchemaJSON schema rpc methods GETs by default

common/api/core-backend.api.md, common/changes/@itwin/core-backend/affanK-schema-sync-fix_2024-07-10-17-30.json, core/backend/src/SchemaSync.ts
Fixes
* `SchemaSync.pull()` should not obtain write-lock on container. Its a read-only container operation.
*  Set timeout to `1 sec` & `30 retries`. The default was `100 ms` & `20 retries` which is too small for `SchemaSync` operation that may take at least 1 sec or more.
The overall algorithm for retry need to be improved. This issue was reported on internal backlog by local sync.
=> SchemaSync.pull() should not obtain write-lock on container

common/changes/@itwin/core-backend/affanK-changeset-reader-fix_2024-07-11-13-09.json, core/backend/src/ChangesetECAdaptor.ts, core/backend/src/test/standalone/ChangesetReader.test.ts
The issue can be reproduced as follows: It is unclear why the user dataset contains `NULL` for `ExclusiveRootClassId`.
1. Import a schema with a class that spans an overflow table.
2. Insert an element for the class.
3. Push the changes to the hub.
4. Update the element.
5. Push the changes to the hub again.
6. Delete the element.
7. Set ExclusiveRootClassId to NULL for the overflow table to simulate the issue.
8. The ECChangesetAdaptor should be able to read changeset 2, in which the element is updated, against the latest iModel where the element is deleted.
Fixes: https://github.com/iTwin/itwinjs-backlog/issues/1168
=> Fix issue where ECChangesetAdaptor fails when ExclusiveRootClassId is NULL for overflow table

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/geo-fixArcGisError403_2024-07-11-16-32.json, common/changes/@itwin/map-layers-formats/geo-fixArcGisError403_2024-07-11-16-32.json, core/frontend/src/tile/map/ArcGisUtilities.ts, core/frontend/src/tile/map/ImageryProviders/ArcGISImageryProvider.ts, core/frontend/src/tile/map/ImageryProviders/ArcGISMapLayerImageryProvider.ts, extensions/map-layers-formats/src/ArcGisFeature/ArcGisFeatureProvider.ts
Some ArcGIS service will throw an error 403 (You do not have permissions to access this resource or perform this operation),
when an OAuth token is required ( instead of the typical 499 error - TokenRequired).
So we now check for error 403 before triggering the Oauth2 login process.
=> Fix missing login dialog for some ArcGIS services

common/changes/@itwin/core-markup/markup-tool-cleanup_2024-07-15-18-12.json, core/markup/src/Markup.ts
The markup text tool will accept the current editor contents when it exits.
[Issue](https://github.com/iTwin/itwinjs-backlog/issues/1110)
=> Terminate active markup tool before stopping session.

common/changes/@itwin/core-frontend/travis-double-tap-fix_2024-07-16-22-12.json, core/frontend/src/tools/ToolAdmin.ts
Fix for: https://github.com/iTwin/itwinjs-core/issues/6976
The double tap code had an `await` call when waiting for the double tap timeout. Unfortunately, that meant that it was impossible for the second tap to be registered until the first tap's timeout had already expired, thus preventing double taps from ever being registered. Changing `await` to `void` fixed the problem.
=> Double tap fix

common/api/core-backend.api.md, common/api/summary/core-backend.exports.csv, common/changes/@itwin/core-backend/pmc-release-all-locks_2024-07-17-18-42.json, core/backend/src/IModelDb.ts, core/backend/src/LockControl.ts, core/backend/src/core-backend.ts, core/backend/src/internal/NoLocks.ts, core/backend/src/internal/ServerBasedLocks.ts, core/backend/src/test/standalone/ServerBasedLocks.test.ts
This was removed from public API because documentation asserted it should never be used outside of core-backend. Connector framework was using it in [two cases](https://github.com/iTwin/connector-framework/blob/f1bdc691eda469e725d1123ffd18af3ad30dbbb3/src/ConnectorRunner.ts#L279):
1. They want to abandon their entire briefcase's local changes in response to an error, and relinquish all of their locks.
2. They sometimes call `pushChanges` when the briefcase does not actually contain any local changes, in which case `pushChanges` silently retains all locks.
Add `LockControl.releaseAllLocks`. It throws if the briefcase contains local changes. Also make `pushChanges` always release all locks unless `retainLocks` is specified.
Also, export LockControl from the core-backend barrel. It's pretty …
=> LockControl.releaseAllLocks

common/api/core-backend.api.md, common/api/summary/core-backend.exports.csv, common/changes/@itwin/core-backend/samw-delete-layered-definitions_2024-07-23-12-43.json, core/backend/src/ElementTreeWalker.ts, core/backend/src/test/standalone/GeometryStream.test.ts
To handle layered dependencies, deleteElementTree must make multiple passes. In each pass, it creates and uses a new ElementTreeDeleter, which detects and classifies the remaining elements and calls IModelDb.deleteDefinitionElements on the remaining definition elements that it finds. 
Note that deleteDefinitionElements will delete only definition elements that are not "used" (as defined by NativeDb usage calculator).
Scenario: A LineStyle refers to a GeometryPart (which captures a LS symbol). The GeometryStreams and SubCategories that refer to the LineStyle must be deleted first. Then the LS symbol GeometryPart can be deleted. 
That's just one example. There can be further layers of dependencies.
=> delete layered definitions

common/changes/@itwin/core-frontend/elementsettool-select-assembly_2024-07-25-18-19.json, core/frontend/src/tools/ElementSetTool.ts
As getGroupIds was originally written with assemblies created from dgn cells in mind, and since the geometric element created to represent the cell header doesn't have a geometry stream (not locatable), selecting the parent wasn't tested.
=> Picking assembly parent wasn't selecting members.

common/changes/@itwin/presentation-frontend/presentation-selection-fix_2024-07-25-12-28.json, presentation/frontend/src/presentation-frontend/selection/SelectionManager.ts, presentation/frontend/src/test/selection/SelectionManager.test.ts
Fixed `selectionChange` event not being emitted for `BlankConnection`. This fixes element highlighting in unified selection viewport.
=> Presentation: Fix `Presentation.selection.selectionChange` event not being emitted for `BlankConnection`

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-public-viewport-constructor_2024-08-01-18-00.json, core/frontend/src/NoRenderApp.ts, core/frontend/src/Viewport.ts, core/frontend/src/render/MockRender.ts, core/frontend/src/render/RenderTarget.ts, core/frontend/src/render/webgl/Target.ts
Part of https://github.com/iTwin/itwinjs-backlog/issues/1103.
They both take a `RenderTarget`. Promote `RenderTarget` to public as an opaque type that `Viewport` subclasses can forward to `super`.
=> Promote ScreenViewport and OnScreenViewport constructors

common/changes/@itwin/core-frontend/marcB-CheckCRSValidityBeforeUsingForOCP_2024-08-01-17-58.json, core/frontend/src/tile/OPCFormatInterpreter.ts, test-apps/imodel-from-orbitgt/src/OrbitGtContextModelCreator.ts
Found out that the CRS 9300 is not defined in the CRS registry database, so we cannot use CRSManager: https://ogtcrsregistry.blob.core.windows.net/registry/crs/9300.prj We will check for isGeographicCRS and isProjectedCRS and both are going to return false in that case and we will fallback to use un-georeferenced code path.
=> Synch this code from @bentley/reality-data package.

common/changes/@itwin/core-common/pmc-fix-black-text-line_2024-08-08-12-48.json, core/common/src/geometry/GeometryStream.ts
Black = 0 = falsy.
Fixes #7048.
=> Fix incorrect geometry for black text

common/changes/@itwin/analytical-backend/nam-fix-cve_2024-08-08-17-48.json, common/changes/@itwin/core-backend/nam-fix-cve_2024-08-08-17-48.json, common/changes/@itwin/presentation-backend/nam-fix-cve_2024-08-08-17-48.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, domains/analytical/backend/package.json, full-stack-tests/rpc/package.json, presentation/backend/package.json
Bump `semver` to `4.5.2` to address new high [CVE](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw)
=> resolve CVE-2022-25883

docs/presentation/advanced/Localization.md
Reverts iTwin/itwinjs-core#6999 until we allow `$` links in md files in Bemetalsmith
=> Revert "[docs] Fix link to frontend localization"

common/changes/@itwin/core-backend/rush-update-full_2024-08-09-18-54.json, common/changes/@itwin/core-common/rush-update-full_2024-08-09-18-54.json, common/changes/@itwin/core-frontend/rush-update-full_2024-08-09-18-54.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/common/package.json, core/frontend/package.json, example-code/snippets/package.json, full-stack-tests/backend/package.json, full-stack-tests/core/package.json, full-stack-tests/core/webpack.config.js, test-apps/display-test-app/package.json
ran `rush update --full`, update storage-blob deps as that prevented a successful build
pr with changes from storage dep changes: https://github.com/iTwin/object-storage/pull/114
- basically unpin all versions of third party deps
=> `rush update --full`

common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml
temporarily suppress https://github.com/advisories/GHSA-8hc4-vh64-cxmj 
remove old global override for a cve that we resolved
=> suppress GHSA-8hc4-vh64-cxmj

common/changes/@itwin/core-frontend/MathieuM-asyncWorker_2024-08-15-19-04.json, core/frontend/src/test/worker/WorkerProxy.test.ts, core/frontend/src/test/worker/test-worker.ts, core/frontend/src/workers/RegisterWorker.ts
Adding async support to enable worker proxy so we can run async operation like fetch().  In my case, it is a large geojson stream that would like to avoid moving from the the main thread to the worker thread.
=> Allow async methods on worker proxy

common/api/ecsql-common.api.md, common/changes/@itwin/core-backend/Soham-test_changes_2024-08-20-15-22.json, common/changes/@itwin/ecsql-common/Soham-test_changes_2024-08-20-15-22.json, core/backend/src/test/ecdb/ECSqlAst.test.ts, core/ecsql/common/src/ECSqlAst.ts
This is a following PR for the imodel-native PR https://github.com/iTwin/imodel-native/pull/836
=> Added support for CTE in subquery for the command "PRAGMA parseTree"

common/changes/@itwin/core-backend/master_2024-08-23-11-20.json, core/backend/src/rpc/web/response.ts
At some point, the value of the `error` metadata property is being overwritten to `true`, and as a result, the original value is not available in telemetry.
=> Fix `error` metadata being overwritten in logs

common/changes/@itwin/core-frontend/pmc-fix-graphic-description-batch-range_2024-09-05-16-35.json, core/frontend/src/common/internal/render/GraphicDescriptionBuilderImpl.ts, core/frontend/src/test/render/GraphicDescription.test.ts
Fixes #7117 for @matmarchand.
The batch's range needs to be in local coordinates (sans translation applied to the branch).
Incidentally remove a "TODO" about instancing that is addressed in #7091.
=> Fix GraphicDescription bounding box

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/wm-supportsmapfeatureinfo-beta_2024-09-09-12-49.json, core/frontend/src/tile/map/MapLayerImageryProvider.ts
This getter is needed in @itwin/map-layers package of viewer-components-react to show the map feature info tool only when a provider is registered to support it.
=> Change MapLayerImageryProvider.supportsMapFeatureInfo from alpha to public

common/api/core-backend.api.md, common/changes/@itwin/core-backend/update-tokenProps-interface_2024-09-09-17-51.json, common/changes/@itwin/core-backend/update-tokenProps-interface_2024-09-09-19-26.json, core/backend/src/BlobContainerService.ts, example-code/snippets/src/backend/AzuriteTest.ts, full-stack-tests/backend/src/integration/AzuriteTest.ts, full-stack-tests/core/src/backend/AzuriteTest.ts
ContainerService.requestToken() returns TokenProps, inside the TokenProps, base uri seems to be missing. 
base uri points to the location where the actual workspace container lives, it is required for every operation. Internal api (storage-container) also return base uri, we just need to expose it through interface and add it to response.
=> Update BlobContainer.TokenProps interface

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/accudraw-rotate-perpendicular_2024-09-13-13-54.json, core/frontend/src/public/locales/en/CoreTools.json, core/frontend/src/tools/AccuDrawTool.ts
[Addresses:](https://dev.azure.com/bentleycs/Civil-iTwin/_workitems/edit/1377994?src=WorkItemMention&src-action=artifact_link)
Rework AccuDrawShortcutsTool base class to address issues with shortcuts no longer working correctly when run with an active Tentative or AccuSnap.
=> New AccuDraw shortcut to rotate compass to closest point on an element (perpendicular).

common/api/appui-abstract.api.md, common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/appui-abstract/rounding_errors_2024-09-16-10-01.json, common/changes/@itwin/core-common/rounding_errors_2024-09-16-10-01.json, core/common/src/GenericInstanceFilter.ts, ui/appui-abstract/src/appui-abstract/properties/Value.ts
Type changes required for https://github.com/iTwin/appui/issues/990
=> Add `roundingError` to `GenericInstanceFilterRuleValue` and `PrimitiveValue`

common/api/core-backend.api.md, common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-backend/backend-geometry-cache_2024-09-18-15-30.json, common/changes/@itwin/core-common/backend-geometry-cache_2024-09-18-15-30.json, core/backend/src/IModelDb.ts, core/common/src/geometry/ElementGeometry.ts
requiring backend native libraries to perform their operation.
Replacement for using internal/deprecated nativeDb directly in EditCommand in editing package.
=> Add IModelDb methods needed for solid modeling tools

common/config/rush/pnpm-lock.yaml
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ DOM Clobbering Gadget found in rollup bundled scripts  │
│                     │ that leads to XSS                                      │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ rollup                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=4.0.0 <4.22.4                                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=4.22.4                                               │
├─────────────────────┼──────────────────────────────────────────── …
```
=> Resolve GHSA-gcx4-mw62-g8wm

common/config/rush/pnpm-lock.yaml
The previous mergify PR. was merged in without any files changed, the cherry-pick failed, forgot to manually resolve it.
=> Fix Cherry-pick: Resolve GHSA-gcx4-mw62-g8wm (backport #7189) [release/4.9.x] 

common/changes/@itwin/core-backend/revert-7150-Soham-booleanExpsInSelect_2024-09-25-06-10.json, core/backend/src/test/ecdb/ECSqlAst.test.ts
Reverts iTwin/itwinjs-core#7150
imodel-native: https://github.com/iTwin/imodel-native/pull/868
=> Revert "Added test cases to test support for boolean exps in select statements"

docs/changehistory/NextVersion.md
Fixed invalid link in NextVersion.md
@DanRod1999 @aruniverse Do you have any idea why Docs pipeline does not fail on invalid link? You can check latest run on master. It's successful but warning is logged. In Presentation repo validate docs job fails for that invalid link.
=> Fix link in NextVersion.md

common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-backend/gytis-deprecate-WipRpcInterface_2024-09-27-12-22.json, common/changes/@itwin/core-common/gytis-deprecate-WipRpcInterface_2024-09-27-12-22.json, core/backend/src/ChangedElementsManager.ts, core/backend/src/IModelHost.ts, core/backend/src/rpc-impl/WipRpcImpl.ts, core/common/src/rpc/WipRpcInterface.ts, full-stack-tests/backend/src/integration/ChangedElements.test.ts, full-stack-tests/core/src/common/RpcInterfaces.ts
`WipRpcInterface` is internal and has no usage in core. With our intent of moving away from RPC, this is a no-brainer for removal.
While the interface is internal, this doesn’t guarantee that no one is using it. For this reason, I propose deprecating it now and removing it in 5.0.
=> Deprecate `WipRpcInterface`

common/changes/@itwin/frontend-tiles/diborra-reduce-get-export-return-list_2024-10-02-11-48.json, extensions/frontend-tiles/src/GraphicsProvider/GraphicRepresentationProvider.ts
We can reduce the response times of querying exports (mesh export service), by limiting the number of exports we want to receive. That reduces the size of the response and the time to generate the information for each export.
=> Limit the number of returned exports to 5

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/sheetVS-computeFitRange-raise_2024-10-02-16-04.json, core/frontend/src/SheetViewState.ts
Removes internal tag from `SheetViewState.computeFitRange`.
Resolves issue #7222
=> SheetViewState.computeFitRange removed internal tag

common/api/core-geometry.api.md, common/changes/@itwin/core-geometry/saeed-torabi-arcArcIntersection_2024-10-02-16-09.json, core/geometry/internaldocs/unitCircleEllipseIntersection.md, core/geometry/src/curve/Arc3d.ts, core/geometry/src/curve/internalContexts/CurveCurveIntersectXY.ts, core/geometry/src/geometry3d/Matrix3d.ts, core/geometry/src/geometry3d/Point3dVector3d.ts, core/geometry/src/numerics/Polynomials.ts, core/geometry/src/test/curve/CurveCurveIntersectXY.test.ts, core/geometry/src/test/curve/CurveCurveIntersectXYZ.test.ts, core/geometry/src/test/curve/RegionBoolean.test.ts
Code was returning imaginary roots for one of the quadratics derived from the quartic by way of the resolvent cubic. Now no roots are returned for this case. This was apparently a fat-finger from the native port.
=> Fixed issue with arc-arc intersection returning invalid intersections

common/changes/@itwin/core-bentley/nam-vitest-v8-coverage_2024-10-09-19-51.json, common/changes/@itwin/core-common/nam-vitest-v8-coverage_2024-10-09-19-51.json, common/changes/@itwin/core-geometry/nam-vitest-v8-coverage_2024-10-09-19-51.json, common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, core/bentley/package.json, core/bentley/vitest.config.mts, core/common/package.json, core/common/vitest.config.mts, core/geometry/package.json, core/geometry/vitest.config.mts
We're seeing an increase in running times for rush cover in our CI builds, in particular the subdirectories that have moved to vitest might not exit cleanly at the end of the test run, and hang. This PR aims to reduce flakiness of rush cover by switching to a more performant coverage provider for vitest. The reported coverage statistics are different - we see 10-15% improvement to coverage statistics when switching from istanbul to v8...
Locally, on an M1 Mac, comparing times from istanbul to v8 across the 3 packages that are using vitest right now, averaged across 5 runs:
- core-geometry: 108s -> 25s
- core-bentley: 2.8s -> 1.8s
- core-common: 8.6s -> 5.3s
Diving deeper into the times for core-geometry, the time vitest spent transforming and setting up the tests were significantly lower …
=> Switch from istanbul to v8 for vitest coverage provider

common/changes/@itwin/core-backend/affanK-regression_classid_2024-10-18-19-55.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/test/ecdb/ECSqlQuery.test.ts, core/backend/src/test/ecdb/ECSqlStatement.test.ts, test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
1. CTE query returning classid switch from className to classId in `4.9.x`. This broke a user. 
2. [PR 7235](https://github.com/iTwin/itwinjs-core/pull/7238) Fix CTE, but this requires properly handling extendType information. This result in another break in behavior where aliased classid property was return as className. In 4.8.x/ 4.9.0 it used to return Id not class name. This break only happens for Concurrent Query for ECSqlStatement was fine as it set a flag called `DoNotConvertClassIdsToClassNamesWhenAliased` to reproduce previous behavior.
3. This PR also set `DoNotConvertClassIdsToClassNamesWhenAliased` for concurrent query to reproduce behavior of classId returning class name when aliased to be compilable with 4.8.x
First query that broke user is following 
```sql
SELECT …
```
=> Regression 4.9.2 where aliased ECClassId switch from returning classId to className

common/changes/@itwin/build-tools/extract-api-dir_2024-10-22-09-50.json, tools/build/scripts/extract-api.js
This PR updates the `extract-api` script to allow the specification of a relative directory for the `entry` argument.
This might be useful for packages that do not deliver `cjs` modules or have a different module structure. 
I.e. extract the API from the `lib` directory: `betools extract-api --entry=./lib/core-frontend`.
Current usage is not affected by this change - if the `entry` argument specifies only a file name w/o a directory name, the `./lib/cjs` directory is used. I.e. `betools extract-api --entry=core-frontend` continues to extract the API from `lib/cjs` directory.
=> Update `extract-api` to support custom `entry` paths

test-apps/display-test-app/src/frontend/EditingTools.ts, test-apps/display-test-app/src/frontend/FeatureOverrides.ts
Two tiny tweaks for two upcoming demos:
- Allow `dta place line string` tool to be used in read-only iModels, for testing AccuSnap, dynamics, etc. It will fail if you try to persist the result.
- Fix logic that governs enabled/checked state of the color/transparency overrides.
=> display-test-app tweaks

.github/CODEOWNERS
Our CODEOWNERS file attempts to keep simple version updates from requiring all reviewers, but since `rush change` adds changelog JSON files in `common/changes`, those folks wind up being required reviewers anyway.
=> Exclude rush change artifacts from CODEOWNERS

common/changes/@itwin/map-layers-formats/geo-fixFeatureFormatCase_2024-10-25-19-20.json, extensions/map-layers-formats/src/ArcGisFeature/ArcGisFeatureProvider.ts, extensions/map-layers-formats/src/ArcGisFeature/ArcGisFeatureQuery.ts, extensions/map-layers-formats/src/ArcGisFeature/ArcGisFeatureResponse.ts, extensions/map-layers-formats/src/test/ArcGisFeature/ArcGisFeatureProvider.test.ts, extensions/map-layers-formats/src/test/ArcGisFeature/ArcGisFeatureQuery.test.ts, extensions/map-layers-formats/src/test/ArcGisFeature/ArcGisFeatureResponse.test.ts
This PR solves 2 issues:
1. Capabilities parsing issue of the `supportedQueryFormats`:
Typically, the capabilities response contains the following:
`"supportedQueryFormats": "JSON, PBF",`
Turns out some server, do no include a whitespace after the comma separator, like this:
`"supportedQueryFormats": "JSON,PBF",`
3. The `f` (i.e. format) query parameter, must have its value set in lower case, even though the `supportedQueryFormats` capability indicates the formats in upper case.
This is confirmed by the [ArcGIS documentation](https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer/):
=> Fix ArcGIS Feature request failures on specific server

common/changes/@itwin/core-backend/travis-ios-tests-fix_2024-10-30-17-54.json, common/config/azure-pipelines/templates/core-build.yaml, core/backend/scripts/runUnitTestsIosSimulator.mjs, test-apps/display-test-app/scripts/runIosSimulator.mjs, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, tools/internal/ios/core-test-runner/core-test-runner/ViewController.swift
iOS tests fix:
* Reenable iOS backend unit tests in CI
* Copy test output XML instead of extracting from console log
* Show error output if present when running display-test-app
Hopefully this will fix the CI test failures for the backend unit tests. Unfortunately, I have no idea what was causing the failures, but I no longer execute the code that appeared to be failing, so hopefully that fixes the problem. (Specifically, instead of printing the XML file contents to the console during execution, this now prints the XML filename, and that file is then copied to the appropriate place by the script running the iOS Simulator.)
=> iOS tests fix

common/changes/@itwin/core-frontend/man-khr-mesh-compression-fix_2024-10-31-14-07.json, core/frontend/src/tile/GltfReader.ts
Fixes the reading of KHR compressed meshes.  This makes it possible to read in the meshes that we export with the cesium option which were in many cases not scaling properly when attached back into the original iModel.
Partially fixes issue [#420](https://github.com/iTwin/itwin-graphics-backlog/issues/420)
=> Fix reading of KHR compressed meshes

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/pmc-core-frontend-internal-apis_2024-11-04-14-33.json, core/frontend/src/BriefcaseConnection.ts, core/frontend/src/DrawingViewState.ts, core/frontend/src/ModelState.ts, core/frontend/src/SheetViewState.ts, core/frontend/src/SpatialViewState.ts
At one point we decided that when a derived type overrides a field/method from the super type and requires no further documentation, we should mark it as `@internal` to avoid cluttering the API docs.
That was misguided. One side effect is that apps get flagged for using "internal" APIs when they use the derived type's accessor.
Removed that tag from a bunch of such occurrences in core-frontend.
=> Trivial core-frontend API promotions.

common/config/rush/version-policies.json
Manually modify `version-policies.json` to version `5.0.0-dev`.
When the nightly version bump runs, itll increment version to `5.0.0-dev.x`
=> point master to 5.0.0-dev

common/api/presentation-frontend.api.md, common/api/summary/presentation-frontend.exports.csv, common/changes/@itwin/presentation-common/bump_unified_selection_2024-11-06-14-52.json, common/changes/@itwin/presentation-frontend/bump_unified_selection_2024-11-06-14-52.json, common/config/rush/pnpm-lock.yaml, presentation/common/src/presentation-common/KeySet.ts, presentation/common/src/test/KeySet.test.ts, presentation/frontend/package.json, presentation/frontend/src/presentation-frontend/PresentationManager.ts, presentation/frontend/src/presentation-frontend/selection/HiliteSetProvider.ts, presentation/frontend/src/presentation-frontend/selection/SelectionManager.ts, presentation/frontend/src/test/PresentationManager.test.ts, presentation/frontend/src/test/selection/HiliteSetProvider.test.ts, presentation/frontend/src/test/selection/SelectionManager.test.ts
Bumped `@itwin/unified-selection` version.
Updated `KeySet` to always store instance key class names in `Schema:Class` format.
=> Presentation: Bump `@itwin/unified-selection` version

full-stack-tests/core/src/frontend/standalone/BriefcaseTxns.test.ts
Over the last 14 days this test has failed the most times than any other test at 13 times. Adding logging in hopes that it might give some clarity. I also considered doing a log message before and after each expectEvents call, but wasn't sure if that would be too much.
=> try to add logging for flaky test "briefcasetxns writable connection receives events from TxnManager"

common/api/core-electron.api.md, common/changes/@itwin/core-electron/gytis-remove-deprecated-electron-apis_2024-11-11-13-17.json, core/electron/src/backend/ElectronHost.ts, core/electron/src/frontend/ElectronApp.ts, docs/changehistory/NextVersion.md
Both methods are in beta, have been deprecated since 3.x and have 1:1 replacement.
Also, fixed `ElectronHostWindowOptions.webPreferences` type. We override values of some of the properties in `webPreferences` before passing it to the Electron. New `Omit<WebPreferences, "preload" | ...>` type omits those properties as to not confuse API callers.
=> Remove `ElectronHost.getWindowSizeSetting` and `ElectronApp.callDialog`

common/changes/@itwin/build-tools/build-tools-bump-typedoc-plugin-merge-modules_2024-11-14-06-58.json, common/config/rush/pnpm-lock.yaml, tools/build/package.json
Should've been part of https://github.com/iTwin/itwinjs-core/pull/7353
=> Build tools: Bump `typedoc-plugin-merge-modules` to a version that supports `typedoc@0.26`

common/changes/@itwin/core-common/docs-isInUseLocksError-link-fix_2024-11-18-19-36.json, core/common/src/ITwinError.ts
Links to namespace children must be prefaced by namespace name, even when inside of the namespace. Docs link validation failed to catch this error due an oversight in easing the upgrade to TypeScript 5.3/TypeDoc 0.24.x.
=> documentation: fix link to isInUseLocksError

common/changes/@itwin/build-tools/build-tools-provide-full-path-to-typedoc-plugin_2024-11-20-07-32.json, tools/build/scripts/docs.js
The `typedoc` version that we recently started using [changed the way plugins are loaded](https://github.com/TypeStrong/typedoc/commit/f06401f51ad119da3d01b4dc5d5568a86e1f0a02#diff-cd82c66603e6129d6e4b251f231c7d7d2350784573ed9bd58221f999bfa20a90R21). Previously, it used `require(path)`, now it uses `await import(path)`. One of the differences between the two is that [`import` doesn't respect `NODE_PATH`](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#432-removal-of-non-local-dependencies), which was one way to resolve the path to the plugin. With that gone, the only way for `typedoc` to find the plugin by name is when the plugin is [hoisted](https://pnpm.io/npmrc#dependency-hoisting-settings), since the plugin is not a dependency of `typedoc`. But hoisting is a bad …
=> Build tools: Fix `typedoc` not finding `typedoc-plugin-merge-modules` plugin when hoisting is disabled

.github/workflows/automation-scripts/update-changelogs.mjs
Add function that finds the newest release branch. Old method sorted branches alphabetically which broke when minors or majors reached double digits.
=> Fix Logic For Changelog automation

.github/CODEOWNERS, .github/workflows/extract-api.yaml, .github/workflows/finalize-release.yaml
Add setup node step to pipeline. Otherwise we run the risk of a vm not using a supported version of node.
This caused an error in another pipeline, so we should use node setup or nodeTool whenever possible to avoid this problem
=> add setup node to finalize-release.yaml

common/changes/@itwin/core-mobile/travis-ios-17_2024-11-25-23-29.json, core/mobile/src/test/ios/imodeljs-backend-test-app/imodeljs-backend-test-app.xcodeproj/project.pbxproj, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
Since iTwin 5 requires iOS 17, configure the build to reflect that.
=> Set iOS deployment target to 17

common/api/presentation-common.api.md, common/api/summary/presentation-common.exports.csv, common/changes/@itwin/presentation-backend/presentation-getElementProperties-with-elementIds_2024-11-27-12-05.json, common/changes/@itwin/presentation-common/presentation-getElementProperties-with-elementIds_2024-11-27-12-05.json, full-stack-tests/presentation/src/backend/PresentationManager.test.snap, full-stack-tests/presentation/src/backend/PresentationManager.test.ts, full-stack-tests/presentation/src/performance/GetElementProperties.test.ts, presentation/backend/src/presentation-backend/ElementPropertiesHelper.ts, presentation/backend/src/presentation-backend/PresentationManager.ts, presentation/backend/src/test/ElementPropertiesHelper.test.ts, presentation/backend/src/test/Helpers.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/common/src/presentation-common/PresentationManagerOptions.ts
Closes https://github.com/iTwin/itwinjs-core/issues/7403.
Performance numbers on a specific test iModel with 688452 geometric elements (ran each test 3 times on my local box):
```
Loaded 688452 elements properties in 94.01 s
Loaded 688452 elements properties in 99.85 s
Loaded 688452 elements properties in 93.98 s
Loaded 688452 elements properties in 81.74 s
Loaded 688452 elements properties in 84.52 s
Loaded 688452 elements properties in 85.40 s
Loaded 688452 elements properties in 79.83 s
Loaded 688452 elements properties in 70.09 s
Loaded 688452 elements properties in 73.82 s
```
=> Presentation: Add `getElementProperties` overload for specifying elements by id

common/changes/@itwin/core-backend/nick-updatecrscount_2024-12-04-20-14.json, core/backend/src/test/misc/GeoServices.test.ts
Arun mentioned that gcs workspace was deployed to prod yesterday.
=> Change expected number of CRS to 11975 in GeoServices.test.ts

common/changes/@itwin/core-backend/simi-mkdir-race_2024-12-05-22-02.json, core/backend/src/IModelJsFs.ts
Addresses issue: Race condition in iModelHost.startup #7452 
Ignore when a folder was already created between the existence check and the attempt to create it.
This would typically only happen if the folder was created out-of-process or in a multi-threaded environment.
=> Ignore 'file already exists' errors when recursively making directories

common/changes/@itwin/core-frontend/frontend-fetch-stubs_2024-12-09-15-57.json, core/frontend/src/test/tile/map/ArcGISImageryProvider.test.ts, core/frontend/src/test/tile/map/ArcGISMapLayerImageryProvider.test.ts, core/frontend/src/test/tile/map/ArcGisUtilities.test.ts
should resolve the following for those on node 22.12.0
```
==[ FAILURE: 1 operation ]=====================================================
--[ FAILURE: @itwin/core-frontend ]--------------------------[ 9.48 seconds ]--
src/test/tile/map/ArcGISImageryProvider.test.ts(36,103): error TS2694: Namespace 'NodeJS' has no exported member 'fetch'.
src/test/tile/map/ArcGISMapLayerImageryProvider.test.ts(202,103): error TS2694: Namespace 'NodeJS' has no exported member 'fetch'.
src/test/tile/map/ArcGisUtilities.test.ts(114,103): error TS2694: Namespace 'NodeJS' has no exported member 'fetch'.
Returned error code: 2
Operations failed.
```
=> fix core-frontend tests using fetch stub on node 22

common/changes/@itwin/build-tools/docs-residual-typedoc0.26-issues_2024-12-09-20-45.json, common/config/azure-pipelines/jobs/docs-build.yaml, tools/build/scripts/docs.js
TypeDoc 0.26 introduced a [defect](https://github.com/TypeStrong/typedoc/issues/2802) which caused modifier tags (`@alpha`, `@beta`, etc...) to be absent in certain type reflections - causing various issues with linking. While the bug has been identified and fixed, we need to update our docs build system to ESM (in progress) to consume the new version of TypeDoc. In the meantime, a workaround for the issue is to override the default `cascadedModifierTags`.
=> Docs: workaround for typedoc issue #2802

common/config/azure-pipelines/templates/core-build.yaml
These are failing with the Node 22-based addon. Until that can be fixed, disable them to allow other PRs to succeed.
=> Disable iOS Simulator backend unit tests

common/changes/@itwin/core-frontend/element-set-tool-preferred-source_2024-12-12-13-53.json, core/frontend/src/tools/ElementSetTool.ts
Missed the early return here when reviewing #7478.
=> ElementSetTool still needs to support option to clear an unsupported selection when it's models and/or sub-categories.

common/config/azure-pipelines/templates/core-build.yaml
The problems that caused them to fail have been fixed in the native add-on.
=> Reenable iOS backend unit tests for CI jobs

common/changes/@itwin/core-backend/travis-ios-tests-crash-fix_2024-12-18-20-41.json, common/config/azure-pipelines/templates/core-build.yaml, core/backend/scripts/runUnitTestsIosSimulator.mjs, tools/internal/ios/ios.webpack.config.js
1. Do not include ECSqlTestParser.js or ECSqlTestRunner.test.js in unit tests webpack for iOS. The former includes marked, which has at least one hard-coded regex that crashes the mobile Node due to the lack of ICU support. The latter depends on the former.
2. Update iOS simulator test runner script to show stderr output if present.
3. Reenabled iOS simulator backend unit tests in CI job.
=> Fix iOS backend unit test crash

common/changes/@itwin/core-backend/affanK-flaky-test_2024-12-23-13-44.json, core/backend/src/test/standalone/MergeConflict.test.ts
Disabling test for now.
```
2024-12-06T18:13:02.5772150Z   1) Merge conflict & locking
2024-12-06T18:13:02.5772330Z        pull/merge causing update conflict - update causing local changes (with no lock):
2024-12-06T18:13:02.5772520Z      Error: Failed to throw error with message: "UPDATE/DELETE before value do not match with one in db or CASCADE action was triggered."
2024-12-06T18:13:02.5772730Z       at assertThrowsAsync (src/test/standalone/MergeConflict.test.ts:49:9)
2024-12-06T18:13:02.5772900Z       at async Context.<anonymous> (src/test/standalone/MergeConflict.test.ts:229:5)
```
=> Disable a flaky test

common/api/core-backend.api.md, common/api/summary/core-backend.exports.csv, common/changes/@itwin/core-backend/pmc-native-db-internal-only_2024-12-23-16-54.json, common/changes/@itwin/core-backend/pmc-native-db-internal-only_2024-12-23-21-26.json, common/changes/@itwin/core-backend/pmc-native-db-internal-only_2024-12-23-21-43.json, common/changes/@itwin/core-backend/pmc-native-db-internal-only_2024-12-24-14-54.json, common/changes/@itwin/core-backend/pmc-native-db-internal-only_2024-12-24-15-28.json, common/changes/@itwin/core-backend/pmc-native-db-internal-only_2024-12-24-15-36.json, common/changes/@itwin/core-backend/pmc-native-db-internal-only_2024-12-24-15-48.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/ECDb.ts, core/backend/src/IModelDb.ts, core/backend/src/IModelHost.ts, core/backend/src/SQLiteDb.ts, core/backend/src/TxnManager.ts, docs/changehistory/NextVersion.md, example-code/snippets/src/backend/IModelBranchingOperations.test.ts, example-code/snippets/src/backend/IModelExporter.test.ts, test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
imodel-native: https://github.com/iTwin/imodel-native/pull/945
These were always @internal, always dangerous to use outside of core-backend, and deprecated in 4.x to give people fair warning that they would be removed.
Add new APIs for functionality needed by external packages.
- code-service
- `cloudContainer` and `getLastInsertRowId` to `SQLiteDb`.
- imodel-transform
- `StandaloneDb.convertToStandalone` - so many copies of this function floating around.
- `IModelDb.insertElement` now takes the same options as the `NativeDgnDb` method, allowing transformer to optionally preserve element Ids during filtering transformations.
- `IModelDb.exportSchema(s)`.
- `IModelDb.inlineGeometryParts`.
- `IModelDb.simplifyGeometry`.
- `IModelDb.getLastError`.
- `TxnManager.getChangeTrackingMemoryUsed`. …
=> Remove nativeDb and IModelHost.platform

.github/CODEOWNERS, .github/workflows/sanity.yaml
I added this line in #7292 with the hopes of not requiring reviews from everyone for package.json-only updates.  An unintentional side-effect of this has been that now @iTwin/itwinjs-core is required to review every single PR, even when a smaller set of codeowners would otherwise be sufficient, leading to a lot of notification noise.
Since changelog files are never expected to be added on their own, let's just not require anyone as a reviewer for those.
=> Remove @iTwin/itwinjs-core team as owner for all changelog files.

common/config/azure-pipelines/jobs/fast-ci.yaml
PR validation pipelines (fast-ci.yml) currently ignore all .md files, so we don't build and test code just for docs changes.
ECSQL uses md files for tests, so "**.md" was too broad of a filter iTwin.js pipeline.
These two filters should still skip CI for all relevant md files, but now include CI for ECSQL md tests
example pr where we currently skip CI, but should not
https://github.com/iTwin/itwinjs-core/pull/7522
=> [ci] fix filter to run ECSQL tests in markdown

common/changes/@itwin/core-backend/rob-manual-column-fix-backport_2025-01-13-14-43.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/test/ecdb/ECSqlReader.test.ts, core/backend/src/test/standalone/DisplayStyle.test.ts, test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
imodel-native: https://github.com/iTwin/imodel-native/pull/965
backport from PR https://github.com/iTwin/imodel-native/pull/965
The automatic backport would do too much as this fix was bundled with the new ECSql test suite which we do not want to backport.
So this includes only the test adjustments that are needed with the fix.
=> Manual backport 2 fixes from master (Column Infos)

common/changes/@itwin/core-backend/mike-update-baseUri_2025-01-15-19-02.json, core/backend/src/BlobContainerService.ts, full-stack-tests/backend/src/integration/AzuriteTest.ts
Updates the baseURI comment in BlobContainerService to correctly reflect what should be returned by the service. 
The baseURI does not contain the containerId, only the url of the storage account hosting the container. 
Updates AzuriteTest to correctly reflect this behavior as well.
=> Update BaseURI Comment and Test

common/changes/@itwin/presentation-backend/presentation-fix-backend-returning-error-details_2025-01-16-09-38.json, full-stack-tests/presentation/src/frontend/content/Infrastructure.test.ts, presentation/backend/src/presentation-backend/PresentationManagerDetail.ts, presentation/backend/src/presentation-backend/PresentationRpcImpl.ts, presentation/backend/src/test/PresentationManager.test.ts, presentation/backend/src/test/PresentationRpcImpl.test.ts
For security reasons we don't want the backend's error response to contain any details about the error. The RPC implementation was converting all errors to a 200 response containing the error message. Now we only do that for `PresentationError` errors, which contain errors that we want to return (e.g. "invalid element id", or "unknown presentation rule", etc.). The generic `Error` errors are just re-thrown to the RPC system, where they can be handled in a generic way.
=> Presentation: Fix Presentation RPC returning details contained within thrown errors

full-stack-tests/presentation/package.json, full-stack-tests/presentation/scripts/setup-tests.js, full-stack-tests/presentation/src/IntegrationTests.ts
Should reduce test flakiness related to tests attempting to overwrite files that aren't yet released by the OS.
=> Presentation Set up test assets once for the whole test suite rather than for each test

common/changes/@itwin/presentation-backend/presentation-dont-include-undefined-in-json_2025-01-16-18-04.json, common/changes/@itwin/presentation-common/presentation-dont-include-undefined-in-json_2025-01-16-18-04.json, presentation/backend/src/test/PresentationManager.test.snap, presentation/common/src/presentation-common.ts, presentation/common/src/presentation-common/Utils.ts, presentation/common/src/presentation-common/content/Descriptor.ts, presentation/common/src/presentation-common/content/Fields.ts, presentation/common/src/presentation-common/content/Item.ts, presentation/common/src/test/_helpers/Content.ts, presentation/common/src/test/content/Descriptor.test.snap, presentation/common/src/test/content/Fields.test.snap, presentation/common/src/test/content/Fields.test.ts, presentation/common/src/test/content/Item.test.snap, presentation/common/src/test/content/Item.test.ts
https://github.com/iTwin/itwinjs-core/pull/7563 highlighted that we're unnecessarily including `undefined` values to our JSONs, making our responses larger than needed.
=> Presentation: Don't include undefined in json

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/accudraw-appui-focus-one-home_2025-01-22-13-17.json, core/frontend/src/tools/AccuDrawViewportUI.ts, docs/learning/frontend/AccuDrawUI.md
Actually overriding the problematic method is much better than having a protected method on AccuDraw. Once FrameworkToolAdmin is fixed the app override can just be removed.
=> More sensible work around for appui keyboard shortcuts only working on Home.

test-apps/display-performance-test-app/vite.config.mts, test-apps/display-test-app/vite.config.mts
Looks like #7309 broke display-test-app because Vite was not configured to polyfill `using` statements in dev mode.
CC: @pmconne
=> Fix display-test-app not polyfilling `using` statements

common/changes/@itwin/core-frontend/man-fix-mapmask-crash_2025-01-24-20-08.json, core/frontend/src/render/webgl/PlanarClassifier.ts
Fixes issue [#559](https://github.com/iTwin/itwin-graphics-backlog/issues/559)
Model masking was crashing on a specific data set.  The cause turned out to be the way the draw command list was being created and the use of some syntax which, though is faster to process, is known to stack overflow for large arrays.
An alternative way of appending one array to another is now used if the array being appended is too large.
=> Fix crash of bg map model masking.

common/config/azure-pipelines/templates/core-build.yaml
I think I know why the test is now failing, but fixing it is going to take some time. In the meantime, disable the test so that other PRs can pass.
=> Temporarily disable Android integration test

common/changes/@itwin/core-bentley/master_2025-01-31-18-34.json, core/bentley/src/test/OneAtATime.test.ts
Closes #7200 
Handling of vitest where:
1. We expect an error to be thrown
2. We expect those errors to be thrown as promise rejections (i.e run as non awaited promises) 
Can cause wonky behaviors, with vitest's runner identifying those errors to be 'uncaught'. We can listen to these uncaught exception events raised to suppress that behavior.
=> re enable oneAtATime test

common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-common/mike-fix-extract_2025-02-07-16-14.json, core/common/src/internal/BackendTypes.ts
In https://github.com/iTwin/itwinjs-core/pull/7572#issuecomment-2642292035 BackendTypes referenced by `HttpServerRequest` were converted to internal. These types need to remain public to match `HttpServerRequest`.
Both the BackendTypes and `HttpServerRequest` function are deprecated, and should be removed by the upcoming RPC refactor.
=> Revert BackendTypes to Public

common/api/presentation-frontend.api.md, common/api/summary/presentation-frontend.exports.csv, common/changes/@itwin/presentation-common/presentation-remove-3x-deprecations-in-frontend_2025-02-12-12-08.json, common/changes/@itwin/presentation-frontend/presentation-remove-3x-deprecations-in-frontend_2025-02-12-11-47.json, docs/changehistory/NextVersion.md, presentation/common/src/presentation-common/hierarchy/Node.ts, presentation/frontend/src/presentation-frontend/selection/SelectionScopesManager.ts
Closes https://github.com/iTwin/itwinjs-backlog/issues/1365
=> Presentation: Remove 3x deprecations in frontend

docs/presentation/advanced/ECExpressions.md
Based on a consumer's question on how to use "like" operator in presentation rules.
`"My name is Peter" ~ "% name is %"` ==> `True`
=> Presentation: Add docs for `~` (like) operator

common/api/ecschema-metadata.api.md, common/changes/@itwin/ecschema-editing/stefan-schema-getItems-method_2025-02-13-14-13.json, common/changes/@itwin/ecschema-metadata/stefan-schema-getItems-method_2025-02-13-14-13.json, core/ecschema-editing/src/test/Editing/mvp.test.ts, core/ecschema-metadata/src/Metadata/Schema.ts, core/ecschema-metadata/src/test/Metadata/Schema.test.ts
**What**
After changing the signature of getItem and lookup item in a previous issue (#7577), the getItems method still had the old signature with a generic that could not verify the items type before returning them.
This changes the method signature to be consistent with the other calls. It also ensures the returned items are all of the requested type, items of other types will be ignored and not returned.
```ts
schema.getItems() // Return iterable of Schema Items
schema.getItems(EntityClass) // Returns iterable of EntityClasses
schema.getItems(ECClass) // Returns iterable of all class items in this schema (Entities, Structs, Mixins,...)
```
=> Change Schemas getItems method to be consistent with other item calls

common/changes/@itwin/core-geometry/saeed-torabi-ray3d-flaky-test_2025-02-14-15-52.json, core/geometry/src/geometry3d/Ray3d.ts, core/geometry/src/test/geometry3d/Ray3d.test.ts
Ray3d.intersectionWithTriangle was not finding intersection of a Ray3d into a triangle if ray origin was on the triangle.
=> Fixed Ray3d flaky test

common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml
Address https://github.com/advisories/GHSA-vjh7-7g9h-fjfh
full-stack-core tests still needs `crypto-browserify` to build and run tests, so can't drop. No new version of the dep has been published since, so have to override the subdeps that's the root of the audit issue.
Will manually cherry-pick to my existing bp PRs.
=> add elliptic to pnpm globalOverrides, address GHSA-vjh7-7g9h-fjfh

common/changes/@itwin/core-geometry/saeed-torabi-EllipseSamplerFlakyTest_2025-02-19-19-11.json, core/geometry/src/test/curve/Arc3d.test.ts
Moved a test case to long tests to reduce the test run time from around 6 sec to around 3 sec
=> Reduced the run time of EllipseSampler test

common/api/core-bentley.api.md, common/api/core-common.api.md, common/changes/@itwin/core-bentley/master_2025-02-19-14-14.json, common/changes/@itwin/core-common/master_2025-02-19-14-14.json, core/bentley/src/BentleyError.ts, core/bentley/src/StatusCategory.ts, core/common/src/GeoCoordinateServices.ts
`GeoCoordStatus` and `GeoServiceStatus` seem to be only used to indicate coordinate conversion status. After going through the code it doesn't seem like `Pending` will be ever returned (last usage in core was removed in https://github.com/iTwin/itwinjs-core/pull/5098 and [`ReprojectStatus`](https://github.com/iTwin/imodel-native/blob/daa66a0a45de96f8e8153d4265edc7c153d8f5e1/iModelCore/GeomLibs/PublicAPI/Geom/GeoPoint.h#L49) in native does not contain `Pending` type either).
=> Deprecate `GeoServiceStatus.Pending` and `GeoCoordStatus.Pending`

common/changes/@itwin/core-frontend/accudraw-bearing-mode_2025-02-20-23-48.json, core/frontend/src/AccuDraw.ts
When the "angle" input field is being used with a bearing direction formatter/parser, update the logic that adjusts the angle (which is measured from the AccuDraw compass X axis) for the current bearing format conventions. Now design X wants 90 for "N90E" instead of 0, and design Y wants 0 for "N0E" instead of 90, which was the old convention.
=> Account for changes for bearing format conventions

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/accudraw-force-2d-layout_2025-02-22-15-02.json, core/frontend/src/AccuDraw.ts, core/frontend/src/tools/AccuDrawTool.ts, core/frontend/src/tools/AccuDrawViewportUI.ts
Added is3dCompass for SiteOps to use 2d UI in 3d. [Issue](https://github.com/iTwin/itwinjs-core/issues/7757)
=> Fix for ACS plane snap lock.

common/changes/@itwin/core-electron/gytis-fix-core-electron-build_2025-03-03-11-39.json, common/config/rush/pnpm-lock.yaml, core/electron/src/backend/ElectronHost.ts
Electron changed their type in minor version and it breaks core-electron build with newer versions. 
Issue: https://github.com/iTwin/itwinjs-core/issues/7575
This was fixed in master with https://github.com/iTwin/itwinjs-core/pull/7574
=> Fix core-electron build with newer Electron 33 versions

common/api/ecschema-locaters.api.md, common/api/ecschema-metadata.api.md, common/api/ecschema-rpcinterface-common.api.md, common/changes/@itwin/ecschema-editing/stefan-readonly-schemakey-change_2025-03-06-09-23.json, common/changes/@itwin/ecschema-locaters/stefan-readonly-schemakey-change_2025-03-06-09-23.json, common/changes/@itwin/ecschema-metadata/stefan-readonly-schemakey-change_2025-03-06-09-23.json, common/changes/@itwin/ecschema-rpcinterface-common/stefan-readonly-schemakey-change_2025-03-06-09-23.json, common/changes/@itwin/ecschema2ts/stefan-readonly-schemakey-change_2025-03-06-09-23.json, core/ecschema-editing/src/Merging/SchemaMerger.ts, core/ecschema-editing/src/test/TestUtils/DeserializationHelpers.ts, core/ecschema-locaters/src/SchemaFileLocater.ts, core/ecschema-locaters/src/SchemaStringLocater.ts, core/ecschema-metadata/src/Context.ts, core/ecschema-metadata/src/Deserialization/Helper.ts, core/ecschema-metadata/src/Interfaces.ts, core/ecschema-metadata/src/SchemaJsonLocater.ts, core/ecschema-metadata/src/SchemaKey.ts, core/ecschema-metadata/src/test/TestUtils/DeserializationHelpers.ts, core/ecschema-metadata/src/test/TestUtils/FormatTestHelper.ts, core/ecschema-metadata/src/test/UnitProvider/UnitProvider.test.ts, core/ecschema-metadata/src/utils/SchemaGraph.ts, core/ecschema-rpc/common/src/ECSchemaRpcLocater.ts, full-stack-tests/presentation/src/backend/PresentationManager.test.ts, tools/ecschema2ts/src/ecschema2ts_io.ts
Since the properties on SchemaKey are already readonly, wrapping the type in a Readonly Utility-Type is not necessary. 
Changed the locater method argument from Readonly<SchemaKey> to SchemaKey and applied the change to all callers and implementations.
=> readonly schemakey change

common/changes/@itwin/core-backend/docs-7841-subject-link_2025-03-14-01-59.json, core/backend/src/Element.ts
[Remove unnecessary link to learning](https://www.itwinjs.org/reference/core-backend/elements/subject/), only to go back to reference.
fixes #7841
=> Subject: remove circular link

full-stack-tests/backend/src/integration/BriefcaseManager.test.ts
temporarily skip failing test blocking all pipeline runs to investigate further
=> temporarily skip BriefcaseManager should reuse checkpoints

common/changes/@itwin/ecschema-metadata/rohitptnkr-add-minimum-ecspecversion-check_2025-03-27-08-13.json, core/ecschema-metadata/src/Metadata/Schema.ts, core/ecschema-metadata/src/test/Metadata/Schema.test.ts
Backported from PR https://github.com/iTwin/itwinjs-core/pull/7884
=> Metadata: Add a minimum ECSpecVersion check in Schema (backport #7884) [release/4.10.x]

CONTRIBUTING.md
Adds:
"Branch names should be all lowercase to avoid potential issues with non-case-sensitive systems and words should be separated by a dash. Eg: `my-itwin-changes`"
This is in response to potential issues that can arise when multiple branches have similar prefixes such as `mikes` and `mikeS` on non-case-sensitive systems.
=> Addition to Branch Naming Policy

common/api/core-electron.api.md, common/changes/@itwin/core-electron/gytis-deprecate-unused-electron-type_2025-04-08-13-43.json, core/electron/src/backend/ElectronHost.ts, core/electron/src/common/ElectronIpcInterface.ts
All methods using this were deprecated in https://github.com/iTwin/itwinjs-core/pull/4533 and removed recently.
=> Deprecate `DialogModuleMethod` in core-electron

common/api/core-frontend.api.md, common/api/summary/core-frontend.exports.csv, common/changes/@itwin/core-frontend/pmc-fix-extract-api_2025-04-08-19-39.json, core/frontend/src/tile/PntsReader.ts
#7924 exported this function; extract-api failed yet the PR auto-merged anyway. Fix the extract-api error by marking the function @internal. On master, this function is not exported from the barrel, so no release tag was needed. We seem to be missing a check on extract-api for PRs targeting release branch.
=> Mark readPntsColors @internal

common/changes/@itwin/core-frontend/accudraw-snap-rotation_2025-04-09-20-21.json, core/frontend/src/AccuDraw.ts, core/frontend/src/tools/AccuDrawViewportUI.ts
Addresses: #7914 
Remove preventDefault for unhandled qualifiers in AccuDraw UI key event, couldn't use ctrl+shift+i when AccuDraw item field had focus.
=> Don't use AxisOrder.XZY in AccuDraw.getSnapRotation as it's a left-handed matrix.

common/config/azure-pipelines/integration-pr-validation.yaml, common/config/azure-pipelines/integration-validation.yaml
Node 22 Windows and Linux were incorrectly run on MacOS machines.
=> Fix image names in integration-validation.yaml

test-apps/display-test-app/scripts/runAndroidEmulator.py
=> Don't fail test when Android emulator output includes invalid UTF-8

full-stack-tests/core/src/frontend/map/PlanarClipMask.test.ts
This PR doubles the planar clip mask test timeout from the default 240,000 ms to 480,000 ms to reolve this issue: https://github.com/iTwin/itwinjs-core/issues/7972
=> Change Planar Clip Mask test time out

common/config/azure-pipelines/jobs/regression-testing.yaml, docs/learning/SupportedPlatforms.md, rush.json
Closes #8009 
- Updates node 20 version used in regression tests.
- Update documented minimum supported node version from 20.9.0 to 20.11.0 to accomodate [some new features used](https://github.com/iTwin/itwinjs-core/issues/8009#issuecomment-2834064116).
Update NextVersion.md in backport PR later
=> Update minimum supported Node 20 to 20.11.0

common/changes/@itwin/frontend-devtools/pmc-contour-tooltip_2025-04-29-19-23.json, core/frontend-devtools/src/tools/ToolTipProvider.ts
#7986 added contour line information to the tooltips produced by `fdt tooltips` keyin. Slightly tweak the formatting and include the group name, for demo purposes.
=> Tweak contour tooltip

common/api/ecschema-metadata.api.md, common/api/ecschema-rpc-interface.api.md, common/changes/@itwin/ecschema-rpcinterface-common/deprecate-getSchemaSync-Rpc-Locater_2025-05-05-06-38.json, core/ecschema-rpc/common/src/ECSchemaRpcLocater.ts, full-stack-tests/core/src/frontend/standalone/SchemaLocator.test.ts
**What’s Changed:**
- Deprecated the `getSchemaSync` method in `ECSchemaRpcLocater`.
- Updated its implementation to always throw an error, clearly stating that synchronous schema loading over RPC is not supported.
**New Behavior:**
Calling `getSchemaSync` will now immediately throw:
```typescript
Error: getSchemaSync is not supported. Use the asynchronous getSchema method instead.
```
=> Deprecate `getSchemaSync` method in `ECSchemaRpcLocater` and enforce async usage

common/changes/@itwin/core-frontend/markschlosser-fix-add-contour-render-tests_2025-05-02-14-07.json, core/frontend/src/test/render/Contours.test.ts
The contour display rendering test introduced in https://github.com/iTwin/itwinjs-core/pull/7986 which checks for expected color values was intentionally skipped because it did not handle alpha blending. For example, with a blue contour line rendered, the scene could contain bluish hues at places instead of only pure blue.
This PR fixes that test by introducing a fuzzier approach to checking for all the expected colors in the scene.  This is similar to the approach done by the thematic display tests.
This PR also adds a bunch more tests which render and check for expected color values in a variety of contour line combinations.
=> Fix and add more contour display rendering tests

common/api/core-backend.api.md, common/changes/@itwin/core-backend/benpo-return-world-crs_2025-05-02-20-06.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/GeographicCRSServices.ts, core/backend/src/test/misc/GeoServices.test.ts, test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
imodel-native: https://github.com/iTwin/imodel-native/pull/1103
There are a number of critical "world" CRS ("EPSG:4326" for example) which are not available from [getAvailableCoordinateReferenceSystems](https://github.com/iTwin/itwinjs-core/blob/06313ff2dc8671959008c377d92437e3bbe2f57a/core/backend/src/GeographicCRSServices.ts#L48). This is because [GeoServicesInterop::GetListOfGCS](https://github.com/iTwin/imodel-native/blob/644642cf7a86d9926c7c64aee51f4491045cca97/iModelJsNodeAddon/GeoServicesInterop.cpp#L75) filters out CRS without extents or those with extents spanning the globe.
This PR exposes an optional includeWorld argument to circumvent the above check.
=> Optionally return world CRS

common/changes/@itwin/core-geometry/saeed-torabi-parity-union-centroid_2025-05-06-19-47.json, core/geometry/src/bspline/BSplineSurface.ts, core/geometry/src/curve/RegionMomentsXY.ts, core/geometry/src/curve/RegionOps.ts, core/geometry/src/curve/RegionOpsClassificationSweeps.ts, core/geometry/src/curve/internalContexts/TransferWithSplitArcs.ts, core/geometry/src/test/curve/RegionBoolean.test.ts, core/geometry/src/test/topology/RegionOps.test.ts
Also resolved another related issue where a region with a hole was missing its hole after merge via below call:
RegionOps.regionBooleanXY(region, undefined, RegionBinaryOpType.Union)
=> Calculate correct area and centroid for union and parity regions

common/changes/@itwin/build-tools/tcobbs-handle-leak-30-seconds_2025-05-08-21-00.json, tools/build/src/mocha-reporter/index.ts
I decreased it to 10 after moving where it executed from. While that worked on my local machine and solved the test failures, it isn't working on the CI Macs.
=> Increase Chrome handle leak timeout back to 30 seconds

common/changes/@itwin/core-backend/snapshot-set-ecef-geolocation_2025-05-09-13-12.json, core/backend/src/IModelDb.ts, core/backend/src/test/imodel/IModel.test.ts
Both `SnapshotDb.createBlank` and `StandaloneDb.createBlank` accept `geographicCoordinateSystem` and `ecefLocation` as options, but do not set the properties on the db. 
Fixes #7877
=> Snapshot/StandaloneDb.createBlank - set ecefLocation and gcs

common/changes/@itwin/core-backend/tcobbs-handle-leak-fixes_2025-05-12-18-00.json, common/changes/@itwin/core-frontend/tcobbs-handle-leak-fixes_2025-05-12-18-00.json, core/backend/src/CloudSqlite.ts, core/frontend/src/IpcApp.ts
* Call `unref` on long-running CloudSqlite token refresh timeout.
* Remove registered IpcAppNotifyHandler in `IpcApp.shutdown`.
Hopefully this will fix the handle leaks that are occurring on the Mac CI pipeline.
=> Handle leak fixes

full-stack-tests/core/src/frontend/standalone/BriefcaseTxns.test.ts
* Show the exact point that an error happens by adding a label to ExpectEvents
* Fail immediately if events don't come in in the expected order
* Hard fail after 30 seconds
* Run `wait` in a loop to avoid possible stack overflow The first change was made so that we can track down what was being done at the point of failure in the event of future failures.
=> Tweaks to BriefcaseTxns tests

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/pmc-background-map-tile-tree-reference_2025-05-14-15-33.json, core/frontend/src/Viewport.ts
`backgroundMap` is @internal and returns `MapTileTreeReference` which is @internal.
=> Add Viewport.backgroundMapTileTreeReference

common/changes/@itwin/map-layers-formats/MichelD-GoogleMapsApiKeyFix_2025-05-15-19-07.json, extensions/map-layers-formats/src/GoogleMaps/GoogleMapsImageryProvider.ts
The session manager should be used, no matter if an API key is set or not in the map layer format registry.
=> Bug fix: Google Maps would only use the supplied session manager if an API key was also configured.

common/changes/@itwin/core-geometry/da4-flaky-test-announce-boundary-edges_2025-06-11-00-41.json, core/geometry/src/test/polyface/PolyfaceQuery.test.ts
Timing for this test can be off by as much as 5-13x in a CI build.  Never happens on a dev box.
Just disable the check for CI builds.
=> disable flaky test

common/config/azure-pipelines/templates/core-build.yaml
remove extract api check in native builds because it does not break addon, and extract api is checked during the core PR validation as a GH workflow
=> remove extract api from native builds

common/api/core-common.api.md, common/api/summary/core-common.exports.csv, common/changes/@itwin/core-backend/affank-concurrent-query_2025-06-18-14-14.json, common/changes/@itwin/core-common/affank-concurrent-query_2025-06-18-14-14.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/test/ecdb/ConcurrentQuery.test.ts, core/backend/src/test/ecdb/ConcurrentQueryLoad.test.ts, core/backend/src/test/ecdb/ECSqlQuery.test.ts, core/common/src/ConcurrentQuery.ts, test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
imodel-native: https://github.com/iTwin/imodel-native/pull/1156
his PR addresses a stability issue reported by users involving concurrent queries, where `SQLITE_INTERRUPT` is returned and the backend enters a failure loop, causing all subsequent queries to fail with the same error. This typically occurs with large, long-running queries.
**Why switch API:**
- `sqlite3_interrupt()` must be called from a separate thread. It interrupts the currently executing statement, but the exact timing is unpredictable. This can lead to unintended behavior, such as interrupting a different statement than the one originally targeted.
- On the other hand, `sqlite3_progress_handler()` allows cancellation from within the same thread. Its timing can be precisely controlled within the scope of the specific …
=> replace sqlite3_interrupt() with sqlite3_progress_handler() to cancel query

common/config/rush/pnpm-lock.yaml, full-stack-tests/core/package.json, full-stack-tests/core/webpack.config.js
Crypto-browserify is no longer needed (please correct me if I am wrong): It's used to polyfil crypto for browsers which do not have support. We only consume the package from core-full-stack-tests - any browser we launch should have support for crypto.
Fixes: https://github.com/advisories/GHSA-h7cp-r72f-jxh6
=> remove crypto-browserify 

common/changes/@itwin/core-backend/affank-check-changeset-id_2025-06-25-13-18.json, core/backend/src/BriefcaseManager.ts
Introduce a validation step to verify the changeset ID before pushing, ensuring the consistency and accuracy of the changeset data.
This update addresses a customer-reported issue where the changeset ID sent to the hub was not the actual SHA1 hash of the changeset file. Although the issue could not be reproduced, this safeguard helps prevent similar inconsistencies in the future.
=> Add changeset ID verification before pushing

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/pmc-EXT_mesh_primitive_restart_2025-07-10-14-31.json, core/frontend/package.json, core/frontend/src/common/gltf/GltfSchema.ts, core/frontend/src/test/tile/GltfReader.test.ts, core/frontend/src/tile/GltfReader.ts
Implement the EXT_mesh_primitive_restart extension described by the specification in https://github.com/KhronosGroup/glTF/pull/2478.
iTwin.js did not previously support line strips. Now it does, with or without the extension.
It still lacks support for line loops, triangle fans, and triangle strips, so no changes were made to support the extension for those.
[Example glb model](https://github.com/user-attachments/files/21167811/primitive-restart.zip) encoding line strings using primitive restart.
=> EXT_mesh_primitive_restart

full-stack-tests/core/src/frontend/map/PlanarClipMask.test.ts
Backport PlanarClipMaskTest.ts to avoid flaky test in release/5.0x
https://github.com/iTwin/itwinjs-backlog/issues/1551
=> Backport planar clip mask test

common/changes/@itwin/presentation-backend/master_2025-07-22-13-17.json, common/changes/@itwin/presentation-common/master_2025-07-22-13-17.json, common/changes/@itwin/presentation-frontend/master_2025-07-22-13-17.json, common/config/rush/pnpm-lock.yaml, full-stack-tests/presentation/package.json, presentation/backend/package.json, presentation/common/package.json, presentation/frontend/package.json
eslint-config-prettier was [hacked](https://www.endorlabs.com/learn/cve-2025-54313-eslint-config-prettier-compromise----high-severity-but-windows-only)
More: https://github.com/prettier/eslint-config-prettier/issues/339
=> bump eslint-config-prettier versions CVE-2025-54313

common/changes/@itwin/core-bentley/nam-test_2025-07-29-20-28.json, core/bentley/src/test/OneAtATime.test.ts
From a recent CI [build](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=4166644&view=logs&j=8673a5cb-f235-5320-c755-005ead49efbb&t=ae0ee70f-cf19-52a3-7a8c-c857212779af&l=2802),
Vitest doesn't like hanging assertions, so rewrote OneAtATime.test.ts to avoid using 'void' during promise rejection assertions.
Proven CI [build](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=4169765&view=logs&j=607f17b7-2b33-5225-6b64-00ff0e2e25e4&t=89ec18ca-7724-51ff-9cd4-fafaa006e1ca&l=7553) that no longer displays warning
=> Address vitest hanging assertions in core-bentley

common/changes/@itwin/core-backend/pmc-material-transparency-override_2025-07-31-11-32.json, common/changes/@itwin/core-common/pmc-material-transparency-override_2025-07-31-11-32.json, core/backend/src/Material.ts, core/backend/src/test/standalone/RenderMaterialElement.test.ts, core/common/src/MaterialProps.ts
Updates docs for how material transparency behaves to be consistent with https://github.com/iTwin/imodel-native/pull/1182.
=> Permit a material to not override element transparency.

common/api/core-frontend.api.md, common/changes/@itwin/core-frontend/pmc-silhouette-normal-encoding_2025-08-12-12-42.json, core/frontend/src/tile/GltfReader.ts
Based on [feedback](https://github.com/KhronosGroup/glTF/pull/2479#discussion_r2254518315) the specification no longer calls for oct-encoded normals; instead it expects float or signed byte components.
This incidentally fixes failure to read vertex normals compressed by meshopt (we previously didn't support signed byte normal components).
=> Update silhouette edge decoding

common/api/ecschema-rpc-impl.api.md, common/api/ecschema-rpc-interface.api.md, common/changes/@itwin/ecschema-rpcinterface-common/catch-getschemajson-notfound_2025-08-14-15-36.json, common/changes/@itwin/ecschema-rpcinterface-impl/catch-getschemajson-notfound_2025-08-14-15-36.json, common/changes/@itwin/ecschema-rpcinterface-tests/catch-getschemajson-notfound_2025-08-14-15-36.json, core/ecschema-rpc/common/src/ECSchemaRpcInterface.ts, core/ecschema-rpc/common/src/ECSchemaRpcLocater.ts, core/ecschema-rpc/impl/src/ECSchemaRpcImpl.ts, full-stack-tests/ecschema-rpc-interface/src/frontend/SchemaRpcInterface.test.ts
Moved exception handling of 'schema not found' from ECSchemaRpcLocater to backend implementation ECSchemaRpcImpl.getSchemaJson to avoid RPC error logging when bentley Logger is initialized.
=> Move exception handling from ECSchemaRpcLocater to backend implementation. 

common/changes/@itwin/core-frontend/pmc-fix-map-tile-availability_2025-08-20-16-50.json, core/frontend/src/internal/tile/map/MapTileAvailability.ts
Whenever I opened a view with terrain enabled and sufficiently zoomed in, I'd get this:
Regression introduced in #8391.
The non-null assertions were erroneous. It is fine and expected for `node.parent` to be `undefined`.
=> Fix map tile availability

common/config/rush/pnpm-lock.yaml, full-stack-tests/presentation/package.json
Fixes this during `rush install`:
```
../../full-stack-tests/presentation
└─┬ global-jsdom 25.0.0
└── ✕ unmet peer jsdom@">=25 <26": found 26.0.0
```
=> Presentation: Fix `global-jsdom` and `jsdom` version mismatch

common/changes/@itwin/ecschema-metadata/navigationproperty-override-fix_2025-08-28-10-50.json, core/ecschema-metadata/src/Metadata/EntityClass.ts
**Description**
When a class overrides a property with a navigation property an error like this was thrown.
```
An ECProperty with the name <PROPERTYNAME> already exists in the class <CLASSNAME>.
```
This issue only occurred during sync deserialization. The reason for this, is that the check is supposed to check the local properties only, when creating a NavigationProperty synchronously, it's check is not restricted to local properties and so overriding a property fails.
Code has been changed to work as it's async method.
=> NavigationProperty override fix

common/changes/@itwin/presentation-common/fix-content-formatting_2025-09-03-08-41.json, presentation/common/src/presentation-common/content/PropertyValueFormatter.ts, presentation/common/src/test/content/PropertyFormatter.test.ts
Content formatter was assuming that all struct members have values. If one of them does not have value it was crashing. Added additional check and tests.
=> [presentation]: Fix content formatting

common/changes/@itwin/core-common/pmc-fix-feature-appearance-assertions_2025-09-09-16-04.json, core/common/src/FeatureSymbology.ts, core/common/src/test/FeatureSymbology.test.ts
Fixes #8503. The assertions were never correct, but would only produce exceptions if assertions were enabled.
=> Remove spurious assertions

example-code/snippets/src/backend/ExampleCode.test.ts
Update `Snippets.extractGeometryFromBimFile` example function and "export elements from local bim file" test with a new option to export the geometry as JSON instead of in FlatBuffers format.
=> export JSON from .bim file

common/changes/@itwin/core-geometry/da4-offset-curve-chain-anomaly_2025-09-15-21-44.json, core/geometry/src/curve/internalContexts/PolygonOffsetContext.ts, core/geometry/src/test/topology/RegionOps.test.ts
A `Loop` with a last line segment much smaller than the interior offset distance now correctly vanishes in the offset curve.
We were not handling the seam correctly, nor were we trying to excise swallowed primitives.
Existing polygon offset code came in handy here, and this too was cleaned up.
=> `RegionOps.constructCurveXYOffset` failed to offset at seam of Loop

common/api/core-backend.api.md, common/changes/@itwin/core-backend/affank-allow-reading-in-mem-changes_2025-09-23-18-18.json, common/config/rush/pnpm-lock.yaml, core/backend/package.json, core/backend/src/SqliteChangesetReader.ts, core/backend/src/test/standalone/ChangesetReader.test.ts, test-apps/display-test-app/android/imodeljs-test-app/app/build.gradle, test-apps/display-test-app/ios/imodeljs-test-app/imodeljs-test-app.xcodeproj/project.pbxproj, tools/internal/ios/core-test-runner/core-test-runner.xcodeproj/project.pbxproj
imodel-native: https://github.com/iTwin/imodel-native/pull/1217
This has been added to help developer debug problem by looking into changes before calling `saveChanges()`.
=> Add SqliteChangesetReader.openInMemory() to allow read unsaved changes
